namespace FruitBox
{
	// Token: 0x0200010B RID: 267
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Safi_Sardkhane : global::System.Windows.Forms.Form
	{
		// Token: 0x060025DE RID: 9694 RVA: 0x001CA068 File Offset: 0x001C8268
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060025DF RID: 9695 RVA: 0x001CA0B8 File Offset: 0x001C82B8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Safi_Sardkhane));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Grid_rizFurush = new global::FruitBox.DataEntryGrid(this.components);
			this.UiRadioButton3 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.UiRadioButton2 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.UiRadioButton1 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.txt_tozih = new global::FruitBox.EditBox(this.components);
			this.MetroStatusBar1 = new global::DevComponents.DotNetBar.Metro.MetroStatusBar();
			this.LabelItem2 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem1 = new global::DevComponents.DotNetBar.LabelItem();
			this.txt_num = new global::FruitBox.NumericBox(this.components);
			this.lbl_vurudbar = new global::System.Windows.Forms.Label();
			this.lbl_tedadkol = new global::System.Windows.Forms.Label();
			this.lbl_baskulmabda = new global::System.Windows.Forms.Label();
			this.lbl_baskul = new global::System.Windows.Forms.Label();
			this.lbl_shmashin = new global::System.Windows.Forms.Label();
			this.lbl_sh_barname = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.WarningBox1 = new global::DevComponents.DotNetBar.Controls.WarningBox();
			this.Grid_RizBar = new global::FruitBox.DataEntryGrid(this.components);
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_darsad = new global::FruitBox.NumericBox(this.components);
			this.txt_saat = new global::Janus.Windows.GridEX.EditControls.MaskedEditBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txt_tarikh = new global::Janus.Windows.GridEX.EditControls.MaskedEditBox();
			this.txt_karmozd = new global::FruitBox.CurrencyBox(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txt_hezar2 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_hezar1 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_mande = new global::FruitBox.CurrencyBox(this.components);
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txt_sayer = new global::FruitBox.CurrencyBox(this.components);
			this.Label21 = new global::System.Windows.Forms.Label();
			this.txt_takhlie = new global::FruitBox.CurrencyBox(this.components);
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txt_jamFurush = new global::FruitBox.CurrencyBox(this.components);
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txt_keraye = new global::FruitBox.CurrencyBox(this.components);
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_rizFurush).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.Grid_rizFurush);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton3);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton2);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton1);
			this.UiGroupBox1.Controls.Add(this.txt_tozih);
			this.UiGroupBox1.Controls.Add(this.MetroStatusBar1);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.lbl_vurudbar);
			this.UiGroupBox1.Controls.Add(this.lbl_tedadkol);
			this.UiGroupBox1.Controls.Add(this.lbl_baskulmabda);
			this.UiGroupBox1.Controls.Add(this.lbl_baskul);
			this.UiGroupBox1.Controls.Add(this.lbl_shmashin);
			this.UiGroupBox1.Controls.Add(this.lbl_sh_barname);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.WarningBox1);
			this.UiGroupBox1.Controls.Add(this.Grid_RizBar);
			this.UiGroupBox1.Controls.Add(this.Label20);
			this.UiGroupBox1.Controls.Add(this.Label17);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_618_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_618_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Silver;
			global::System.Windows.Forms.Control arg_656_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(986, 619);
			arg_656_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Grid_rizFurush.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_rizFurush.AlternatingColors = true;
			this.Grid_rizFurush.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("Grid_rizFurush_DesignTimeLayout.LayoutString");
			this.Grid_rizFurush.DesignTimeLayout = gridEXLayout;
			this.Grid_rizFurush.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_rizFurush.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_rizFurush.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.Grid_rizFurush.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_rizFurush.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_726_0 = this.Grid_rizFurush;
			location = new global::System.Drawing.Point(266, 232);
			arg_726_0.Location = location;
			this.Grid_rizFurush.Name = "Grid_rizFurush";
			this.Grid_rizFurush.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_rizFurush.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_771_0 = this.Grid_rizFurush;
			size = new global::System.Drawing.Size(720, 275);
			arg_771_0.Size = size;
			this.Grid_rizFurush.TabIndex = 33;
			this.Grid_rizFurush.TabStop = false;
			this.Grid_rizFurush.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_rizFurush.Visible = false;
			this.Grid_rizFurush.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiRadioButton3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton3.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton3.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_814_0 = this.UiRadioButton3;
			location = new global::System.Drawing.Point(539, 199);
			arg_814_0.Location = location;
			this.UiRadioButton3.Name = "UiRadioButton3";
			global::System.Windows.Forms.Control arg_83F_0 = this.UiRadioButton3;
			size = new global::System.Drawing.Size(85, 23);
			arg_83F_0.Size = size;
			this.UiRadioButton3.TabIndex = 32;
			this.UiRadioButton3.Text = "ریز فروش";
			this.UiRadioButton3.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiRadioButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton2.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton2.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_8CC_0 = this.UiRadioButton2;
			location = new global::System.Drawing.Point(653, 198);
			arg_8CC_0.Location = location;
			this.UiRadioButton2.Name = "UiRadioButton2";
			global::System.Windows.Forms.Control arg_8F7_0 = this.UiRadioButton2;
			size = new global::System.Drawing.Size(85, 23);
			arg_8F7_0.Size = size;
			this.UiRadioButton2.TabIndex = 32;
			this.UiRadioButton2.Text = "نوع جنس";
			this.UiRadioButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiRadioButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton1.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton1.Checked = true;
			this.UiRadioButton1.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_991_0 = this.UiRadioButton1;
			location = new global::System.Drawing.Point(779, 199);
			arg_991_0.Location = location;
			this.UiRadioButton1.Name = "UiRadioButton1";
			global::System.Windows.Forms.Control arg_9BC_0 = this.UiRadioButton1;
			size = new global::System.Drawing.Size(104, 23);
			arg_9BC_0.Size = size;
			this.UiRadioButton1.TabIndex = 32;
			this.UiRadioButton1.TabStop = true;
			this.UiRadioButton1.Text = "قیمت میانگین";
			this.UiRadioButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_tozih.AcceptEnter = true;
			this.txt_tozih.AllowEdit = true;
			this.txt_tozih.AllowNew = true;
			this.txt_tozih.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tozih.FocusColor = true;
			this.txt_tozih.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A79_0 = this.txt_tozih;
			location = new global::System.Drawing.Point(266, 157);
			arg_A79_0.Location = location;
			this.txt_tozih.Name = "txt_tozih";
			this.txt_tozih.Nullable = true;
			this.txt_tozih.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tozih.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_AD2_0 = this.txt_tozih;
			size = new global::System.Drawing.Size(617, 36);
			arg_AD2_0.Size = size;
			this.txt_tozih.TabIndex = 2;
			this.txt_tozih.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.MetroStatusBar1.BackColor = global::System.Drawing.Color.White;
			this.MetroStatusBar1.BackgroundStyle.BackColor = global::System.Drawing.Color.FromArgb(0, 122, 204);
			this.MetroStatusBar1.BackgroundStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.MetroStatusBar1.ContainerControlProcessDialogKey = true;
			this.MetroStatusBar1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.MetroStatusBar1.DragDropSupport = true;
			this.MetroStatusBar1.Font = new global::System.Drawing.Font("Segoe UI", 10.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MetroStatusBar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.LabelItem2,
				this.LabelItem1
			});
			global::System.Windows.Forms.Control arg_BBF_0 = this.MetroStatusBar1;
			location = new global::System.Drawing.Point(0, 594);
			arg_BBF_0.Location = location;
			this.MetroStatusBar1.Name = "MetroStatusBar1";
			this.MetroStatusBar1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_BFA_0 = this.MetroStatusBar1;
			size = new global::System.Drawing.Size(986, 25);
			arg_BFA_0.Size = size;
			this.MetroStatusBar1.TabIndex = 30;
			this.MetroStatusBar1.Text = "MetroStatusBar1";
			this.LabelItem2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem2.ForeColor = global::System.Drawing.Color.Black;
			this.LabelItem2.Name = "LabelItem2";
			this.LabelItem2.Text = "صافی مانده به حروف :";
			this.LabelItem1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem1.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem1.Name = "LabelItem1";
			this.txt_num.AcceptEnter = true;
			this.txt_num.AllowEdit = true;
			this.txt_num.AllowNew = true;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_num.ButtonText = "...";
			this.txt_num.FocusColor = true;
			this.txt_num.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D51_0 = this.txt_num;
			location = new global::System.Drawing.Point(758, 51);
			arg_D51_0.Location = location;
			this.txt_num.Name = "txt_num";
			this.txt_num.Nullable = true;
			this.txt_num.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_num.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_DA7_0 = this.txt_num;
			size = new global::System.Drawing.Size(125, 36);
			arg_DA7_0.Size = size;
			this.txt_num.TabIndex = 0;
			this.txt_num.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_num.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_vurudbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_vurudbar.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_vurudbar.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_vurudbar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E39_0 = this.lbl_vurudbar;
			location = new global::System.Drawing.Point(758, 95);
			arg_E39_0.Location = location;
			this.lbl_vurudbar.Name = "lbl_vurudbar";
			global::System.Windows.Forms.Control arg_E64_0 = this.lbl_vurudbar;
			size = new global::System.Drawing.Size(125, 23);
			arg_E64_0.Size = size;
			this.lbl_vurudbar.TabIndex = 28;
			this.lbl_vurudbar.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_tedadkol.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tedadkol.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tedadkol.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tedadkol.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_EEB_0 = this.lbl_tedadkol;
			location = new global::System.Drawing.Point(266, 126);
			arg_EEB_0.Location = location;
			this.lbl_tedadkol.Name = "lbl_tedadkol";
			global::System.Windows.Forms.Control arg_F19_0 = this.lbl_tedadkol;
			size = new global::System.Drawing.Size(140, 23);
			arg_F19_0.Size = size;
			this.lbl_tedadkol.TabIndex = 28;
			this.lbl_tedadkol.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_baskulmabda.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_baskulmabda.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_baskulmabda.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_baskulmabda.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_FA0_0 = this.lbl_baskulmabda;
			location = new global::System.Drawing.Point(494, 126);
			arg_FA0_0.Location = location;
			this.lbl_baskulmabda.Name = "lbl_baskulmabda";
			global::System.Windows.Forms.Control arg_FCE_0 = this.lbl_baskulmabda;
			size = new global::System.Drawing.Size(165, 23);
			arg_FCE_0.Size = size;
			this.lbl_baskulmabda.TabIndex = 28;
			this.lbl_baskulmabda.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_baskul.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_baskul.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_baskul.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_baskul.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1055_0 = this.lbl_baskul;
			location = new global::System.Drawing.Point(758, 126);
			arg_1055_0.Location = location;
			this.lbl_baskul.Name = "lbl_baskul";
			global::System.Windows.Forms.Control arg_1080_0 = this.lbl_baskul;
			size = new global::System.Drawing.Size(125, 23);
			arg_1080_0.Size = size;
			this.lbl_baskul.TabIndex = 28;
			this.lbl_baskul.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_shmashin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_shmashin.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_shmashin.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_shmashin.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1107_0 = this.lbl_shmashin;
			location = new global::System.Drawing.Point(494, 95);
			arg_1107_0.Location = location;
			this.lbl_shmashin.Name = "lbl_shmashin";
			global::System.Windows.Forms.Control arg_1135_0 = this.lbl_shmashin;
			size = new global::System.Drawing.Size(163, 23);
			arg_1135_0.Size = size;
			this.lbl_shmashin.TabIndex = 28;
			this.lbl_shmashin.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_sh_barname.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sh_barname.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_sh_barname.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_sh_barname.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11BC_0 = this.lbl_sh_barname;
			location = new global::System.Drawing.Point(266, 95);
			arg_11BC_0.Location = location;
			this.lbl_sh_barname.Name = "lbl_sh_barname";
			global::System.Windows.Forms.Control arg_11EA_0 = this.lbl_sh_barname;
			size = new global::System.Drawing.Size(140, 23);
			arg_11EA_0.Size = size;
			this.lbl_sh_barname.TabIndex = 28;
			this.lbl_sh_barname.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1271_0 = this.Label8;
			location = new global::System.Drawing.Point(662, 127);
			arg_1271_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_129C_0 = this.Label8;
			size = new global::System.Drawing.Size(79, 17);
			arg_129C_0.Size = size;
			this.Label8.TabIndex = 25;
			this.Label8.Text = "باسکول مبدا";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1329_0 = this.Label13;
			location = new global::System.Drawing.Point(886, 129);
			arg_1329_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_1354_0 = this.Label13;
			size = new global::System.Drawing.Size(52, 17);
			arg_1354_0.Size = size;
			this.Label13.TabIndex = 26;
			this.Label13.Text = "باسکول";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_13E1_0 = this.Label14;
			location = new global::System.Drawing.Point(409, 129);
			arg_13E1_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_140C_0 = this.Label14;
			size = new global::System.Drawing.Size(58, 17);
			arg_140C_0.Size = size;
			this.Label14.TabIndex = 27;
			this.Label14.Text = "تعداد کل";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1496_0 = this.Label11;
			location = new global::System.Drawing.Point(885, 97);
			arg_1496_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_14C1_0 = this.Label11;
			size = new global::System.Drawing.Size(80, 17);
			arg_14C1_0.Size = size;
			this.Label11.TabIndex = 21;
			this.Label11.Text = "تاریخ ورود بار";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_154B_0 = this.Label10;
			location = new global::System.Drawing.Point(408, 96);
			arg_154B_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_1576_0 = this.Label10;
			size = new global::System.Drawing.Size(87, 17);
			arg_1576_0.Size = size;
			this.Label10.TabIndex = 22;
			this.Label10.Text = "شماره بارنامه";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1600_0 = this.Label9;
			location = new global::System.Drawing.Point(660, 97);
			arg_1600_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_162B_0 = this.Label9;
			size = new global::System.Drawing.Size(92, 17);
			arg_162B_0.Size = size;
			this.Label9.TabIndex = 23;
			this.Label9.Text = "شماره ماشین";
			this.WarningBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.WarningBox1.BackColor = global::System.Drawing.Color.FromArgb(255, 230, 159);
			this.WarningBox1.CloseButtonVisible = false;
			this.WarningBox1.ColorScheme = global::DevComponents.DotNetBar.Controls.eWarningBoxColorScheme.Yellow;
			this.WarningBox1.ForeColor = global::System.Drawing.Color.Black;
			this.WarningBox1.Image = global::FruitBox.My.Resources.Resources.clipboard_error;
			global::System.Windows.Forms.Control arg_16D4_0 = this.WarningBox1;
			location = new global::System.Drawing.Point(266, 511);
			arg_16D4_0.Location = location;
			this.WarningBox1.Name = "WarningBox1";
			this.WarningBox1.OptionsButtonVisible = false;
			global::System.Windows.Forms.Control arg_170F_0 = this.WarningBox1;
			size = new global::System.Drawing.Size(720, 77);
			arg_170F_0.Size = size;
			this.WarningBox1.TabIndex = 20;
			this.WarningBox1.Visible = false;
			this.Grid_RizBar.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_RizBar.AlternatingColors = true;
			this.Grid_RizBar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout2.LayoutString = componentResourceManager.GetString("Grid_RizBar_DesignTimeLayout.LayoutString");
			this.Grid_RizBar.DesignTimeLayout = gridEXLayout2;
			this.Grid_RizBar.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_RizBar.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_RizBar.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.Grid_RizBar.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_RizBar.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_17E0_0 = this.Grid_RizBar;
			location = new global::System.Drawing.Point(266, 231);
			arg_17E0_0.Location = location;
			this.Grid_RizBar.Name = "Grid_RizBar";
			this.Grid_RizBar.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_RizBar.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_182B_0 = this.Grid_RizBar;
			size = new global::System.Drawing.Size(720, 274);
			arg_182B_0.Size = size;
			this.Grid_RizBar.TabIndex = 2;
			this.Grid_RizBar.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_RizBar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label20.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label20.AutoSize = true;
			this.Label20.BackColor = global::System.Drawing.Color.Transparent;
			this.Label20.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_18C0_0 = this.Label20;
			location = new global::System.Drawing.Point(882, 204);
			arg_18C0_0.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control arg_18EB_0 = this.Label20;
			size = new global::System.Drawing.Size(99, 17);
			arg_18EB_0.Size = size;
			this.Label20.TabIndex = 17;
			this.Label20.Text = "صافی بر اساس";
			this.Label17.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1978_0 = this.Label17;
			location = new global::System.Drawing.Point(889, 168);
			arg_1978_0.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control arg_19A3_0 = this.Label17;
			size = new global::System.Drawing.Size(59, 17);
			arg_19A3_0.Size = size;
			this.Label17.TabIndex = 17;
			this.Label17.Text = "توضیحات";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A2D_0 = this.Label6;
			location = new global::System.Drawing.Point(885, 61);
			arg_1A2D_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_1A58_0 = this.Label6;
			size = new global::System.Drawing.Size(78, 17);
			arg_1A58_0.Size = size;
			this.Label6.TabIndex = 17;
			this.Label6.Text = "شماره سند";
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.txt_darsad);
			this.UiGroupBox2.Controls.Add(this.txt_saat);
			this.UiGroupBox2.Controls.Add(this.Label3);
			this.UiGroupBox2.Controls.Add(this.txt_tarikh);
			this.UiGroupBox2.Controls.Add(this.txt_karmozd);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.txt_hezar2);
			this.UiGroupBox2.Controls.Add(this.txt_hezar1);
			this.UiGroupBox2.Controls.Add(this.txt_mande);
			this.UiGroupBox2.Controls.Add(this.Label22);
			this.UiGroupBox2.Controls.Add(this.Label23);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.txt_sayer);
			this.UiGroupBox2.Controls.Add(this.Label21);
			this.UiGroupBox2.Controls.Add(this.txt_takhlie);
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.txt_jamFurush);
			this.UiGroupBox2.Controls.Add(this.Label16);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.Label24);
			this.UiGroupBox2.Controls.Add(this.Label18);
			this.UiGroupBox2.Controls.Add(this.Label15);
			this.UiGroupBox2.Controls.Add(this.txt_keraye);
			this.UiGroupBox2.Controls.Add(this.Label1);
			global::System.Windows.Forms.Control arg_1CD2_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 40);
			arg_1CD2_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_1D03_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(260, 548);
			arg_1D03_0.Size = size;
			this.UiGroupBox2.TabIndex = 0;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_darsad.AcceptEnter = true;
			this.txt_darsad.AllowEdit = true;
			this.txt_darsad.AllowNew = true;
			this.txt_darsad.AllowZero = true;
			this.txt_darsad.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_darsad.DecimalDigits = 2;
			this.txt_darsad.FixLength = 2;
			this.txt_darsad.FocusColor = true;
			this.txt_darsad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1DD6_0 = this.txt_darsad;
			location = new global::System.Drawing.Point(12, 62);
			arg_1DD6_0.Location = location;
			this.txt_darsad.MaxLength = 5;
			this.txt_darsad.Name = "txt_darsad";
			this.txt_darsad.Nullable = true;
			this.txt_darsad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_darsad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1E3C_0 = this.txt_darsad;
			size = new global::System.Drawing.Size(135, 36);
			arg_1E3C_0.Size = size;
			this.txt_darsad.TabIndex = 0;
			this.txt_darsad.Text = "0";
			this.txt_darsad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_darsad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_saat.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			global::System.Windows.Forms.Control arg_1E9E_0 = this.txt_saat;
			location = new global::System.Drawing.Point(14, 519);
			arg_1E9E_0.Location = location;
			this.txt_saat.Mask = "00:00";
			this.txt_saat.Name = "txt_saat";
			this.txt_saat.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_1EE7_0 = this.txt_saat;
			size = new global::System.Drawing.Size(91, 21);
			arg_1EE7_0.Size = size;
			this.txt_saat.TabIndex = 4;
			this.txt_saat.TabStop = false;
			this.txt_saat.Visible = false;
			this.txt_saat.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.VS2010;
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1F78_0 = this.Label3;
			location = new global::System.Drawing.Point(149, 113);
			arg_1F78_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1FA3_0 = this.Label3;
			size = new global::System.Drawing.Size(50, 19);
			arg_1FA3_0.Size = size;
			this.Label3.TabIndex = 15;
			this.Label3.Text = "کارمزد";
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			global::System.Windows.Forms.Control arg_1FEC_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(14, 492);
			arg_1FEC_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_2035_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(91, 21);
			arg_2035_0.Size = size;
			this.txt_tarikh.TabIndex = 3;
			this.txt_tarikh.TabStop = false;
			this.txt_tarikh.Visible = false;
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.VS2010;
			this.txt_karmozd.AcceptEnter = false;
			this.txt_karmozd.AllowEdit = true;
			this.txt_karmozd.AllowNegative = true;
			this.txt_karmozd.AllowNew = true;
			this.txt_karmozd.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_karmozd.FixLength = 15;
			this.txt_karmozd.FocusColor = true;
			this.txt_karmozd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2116_0 = this.txt_karmozd;
			location = new global::System.Drawing.Point(12, 103);
			arg_2116_0.Location = location;
			this.txt_karmozd.MaxLength = 15;
			this.txt_karmozd.Name = "txt_karmozd";
			this.txt_karmozd.Nullable = false;
			this.txt_karmozd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_karmozd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_217D_0 = this.txt_karmozd;
			size = new global::System.Drawing.Size(135, 36);
			arg_217D_0.Size = size;
			this.txt_karmozd.TabIndex = 1;
			this.txt_karmozd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_karmozd.Value = value;
			this.txt_karmozd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_220F_0 = this.Label2;
			location = new global::System.Drawing.Point(149, 73);
			arg_220F_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_223A_0 = this.Label2;
			size = new global::System.Drawing.Size(89, 19);
			arg_223A_0.Size = size;
			this.Label2.TabIndex = 15;
			this.Label2.Text = "درصد کارمزد";
			this.txt_hezar2.AcceptEnter = true;
			this.txt_hezar2.AllowEdit = false;
			this.txt_hezar2.AllowNew = true;
			this.txt_hezar2.FocusColor = true;
			this.txt_hezar2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_22CC_0 = this.txt_hezar2;
			location = new global::System.Drawing.Point(14, 450);
			arg_22CC_0.Location = location;
			this.txt_hezar2.MaxLength = 10;
			this.txt_hezar2.Name = "txt_hezar2";
			this.txt_hezar2.Nullable = true;
			this.txt_hezar2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hezar2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2333_0 = this.txt_hezar2;
			size = new global::System.Drawing.Size(135, 36);
			arg_2333_0.Size = size;
			this.txt_hezar2.TabIndex = 5;
			this.txt_hezar2.TabStop = false;
			this.txt_hezar2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hezar2.Value = value;
			this.txt_hezar2.Visible = false;
			this.txt_hezar2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hezar1.AcceptEnter = true;
			this.txt_hezar1.AllowEdit = false;
			this.txt_hezar1.AllowNew = true;
			this.txt_hezar1.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_hezar1.FocusColor = true;
			this.txt_hezar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2417_0 = this.txt_hezar1;
			location = new global::System.Drawing.Point(12, 314);
			arg_2417_0.Location = location;
			this.txt_hezar1.MaxLength = 10;
			this.txt_hezar1.Name = "txt_hezar1";
			this.txt_hezar1.Nullable = true;
			this.txt_hezar1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hezar1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_247E_0 = this.txt_hezar1;
			size = new global::System.Drawing.Size(135, 36);
			arg_247E_0.Size = size;
			this.txt_hezar1.TabIndex = 5;
			this.txt_hezar1.TabStop = false;
			this.txt_hezar1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hezar1.Value = value;
			this.txt_hezar1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_mande.AcceptEnter = true;
			this.txt_mande.AllowEdit = true;
			this.txt_mande.AllowNew = true;
			this.txt_mande.FocusColor = true;
			this.txt_mande.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2533_0 = this.txt_mande;
			location = new global::System.Drawing.Point(12, 272);
			arg_2533_0.Location = location;
			this.txt_mande.MaxLength = 10;
			this.txt_mande.Name = "txt_mande";
			this.txt_mande.Nullable = true;
			this.txt_mande.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mande.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_259A_0 = this.txt_mande;
			size = new global::System.Drawing.Size(135, 36);
			arg_259A_0.Size = size;
			this.txt_mande.TabIndex = 2;
			this.txt_mande.TabStop = false;
			this.txt_mande.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_mande.Value = value;
			this.txt_mande.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label22.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label22.AutoSize = true;
			this.Label22.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2624_0 = this.Label22;
			location = new global::System.Drawing.Point(113, 527);
			arg_2624_0.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control arg_264F_0 = this.Label22;
			size = new global::System.Drawing.Size(118, 13);
			arg_264F_0.Size = size;
			this.Label22.TabIndex = 15;
			this.Label22.Text = "ساعت اعلام به مشتری";
			this.Label22.Visible = false;
			this.Label23.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label23.AutoSize = true;
			this.Label23.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_26C3_0 = this.Label23;
			location = new global::System.Drawing.Point(117, 500);
			arg_26C3_0.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control arg_26EE_0 = this.Label23;
			size = new global::System.Drawing.Size(108, 13);
			arg_26EE_0.Size = size;
			this.Label23.TabIndex = 15;
			this.Label23.Text = "تاریخ اعلام به مشتری";
			this.Label23.Visible = false;
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_277A_0 = this.Label7;
			location = new global::System.Drawing.Point(149, 281);
			arg_277A_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_27A5_0 = this.Label7;
			size = new global::System.Drawing.Size(88, 19);
			arg_27A5_0.Size = size;
			this.Label7.TabIndex = 15;
			this.Label7.Text = "صافی مانده";
			this.txt_sayer.AcceptEnter = true;
			this.txt_sayer.AllowEdit = false;
			this.txt_sayer.AllowNew = true;
			this.txt_sayer.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_sayer.FocusColor = true;
			this.txt_sayer.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2859_0 = this.txt_sayer;
			location = new global::System.Drawing.Point(12, 230);
			arg_2859_0.Location = location;
			this.txt_sayer.MaxLength = 10;
			this.txt_sayer.Name = "txt_sayer";
			this.txt_sayer.Nullable = true;
			this.txt_sayer.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sayer.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_28C0_0 = this.txt_sayer;
			size = new global::System.Drawing.Size(135, 36);
			arg_28C0_0.Size = size;
			this.txt_sayer.TabIndex = 4;
			this.txt_sayer.TabStop = false;
			this.txt_sayer.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sayer.Value = value;
			this.txt_sayer.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label21.AutoSize = true;
			this.Label21.BackColor = global::System.Drawing.Color.Transparent;
			this.Label21.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2962_0 = this.Label21;
			location = new global::System.Drawing.Point(149, 241);
			arg_2962_0.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control arg_298D_0 = this.Label21;
			size = new global::System.Drawing.Size(104, 19);
			arg_298D_0.Size = size;
			this.Label21.TabIndex = 15;
			this.Label21.Text = "سایر هزینه ها";
			this.txt_takhlie.AcceptEnter = true;
			this.txt_takhlie.AllowEdit = false;
			this.txt_takhlie.AllowNew = true;
			this.txt_takhlie.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_takhlie.FocusColor = true;
			this.txt_takhlie.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2A41_0 = this.txt_takhlie;
			location = new global::System.Drawing.Point(12, 188);
			arg_2A41_0.Location = location;
			this.txt_takhlie.MaxLength = 10;
			this.txt_takhlie.Name = "txt_takhlie";
			this.txt_takhlie.Nullable = true;
			this.txt_takhlie.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_takhlie.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2AA8_0 = this.txt_takhlie;
			size = new global::System.Drawing.Size(135, 36);
			arg_2AA8_0.Size = size;
			this.txt_takhlie.TabIndex = 4;
			this.txt_takhlie.TabStop = false;
			this.txt_takhlie.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_takhlie.Value = value;
			this.txt_takhlie.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2B4A_0 = this.Label5;
			location = new global::System.Drawing.Point(149, 197);
			arg_2B4A_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_2B75_0 = this.Label5;
			size = new global::System.Drawing.Size(45, 19);
			arg_2B75_0.Size = size;
			this.Label5.TabIndex = 15;
			this.Label5.Text = "تخلیه";
			this.txt_jamFurush.AcceptEnter = true;
			this.txt_jamFurush.AllowEdit = false;
			this.txt_jamFurush.AllowNew = true;
			this.txt_jamFurush.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_jamFurush.FocusColor = true;
			this.txt_jamFurush.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2C26_0 = this.txt_jamFurush;
			location = new global::System.Drawing.Point(12, 20);
			arg_2C26_0.Location = location;
			this.txt_jamFurush.Name = "txt_jamFurush";
			this.txt_jamFurush.Nullable = true;
			this.txt_jamFurush.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jamFurush.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2C7F_0 = this.txt_jamFurush;
			size = new global::System.Drawing.Size(135, 36);
			arg_2C7F_0.Size = size;
			this.txt_jamFurush.TabIndex = 0;
			this.txt_jamFurush.TabStop = false;
			this.txt_jamFurush.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jamFurush.Value = value;
			this.txt_jamFurush.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2D21_0 = this.Label16;
			location = new global::System.Drawing.Point(151, 460);
			arg_2D21_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_2D4C_0 = this.Label16;
			size = new global::System.Drawing.Size(101, 17);
			arg_2D4C_0.Size = size;
			this.Label16.TabIndex = 15;
			this.Label16.Text = "افزایش هزار ریال";
			this.Label16.Visible = false;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2DD8_0 = this.Label4;
			location = new global::System.Drawing.Point(150, 154);
			arg_2DD8_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_2E03_0 = this.Label4;
			size = new global::System.Drawing.Size(41, 19);
			arg_2E03_0.Size = size;
			this.Label4.TabIndex = 15;
			this.Label4.Text = "کرایه";
			this.Label24.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label24.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Label24.Font = new global::System.Drawing.Font("Tahoma", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2E83_0 = this.Label24;
			location = new global::System.Drawing.Point(148, 361);
			arg_2E83_0.Location = location;
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control arg_2EAE_0 = this.Label24;
			size = new global::System.Drawing.Size(106, 37);
			arg_2EAE_0.Size = size;
			this.Label24.TabIndex = 27;
			this.Label24.Text = "صافی کل";
			this.Label24.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label18.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label18.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Label18.Font = new global::System.Drawing.Font("Mitra", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2F39_0 = this.Label18;
			location = new global::System.Drawing.Point(12, 361);
			arg_2F39_0.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control arg_2F67_0 = this.Label18;
			size = new global::System.Drawing.Size(137, 37);
			arg_2F67_0.Size = size;
			this.Label18.TabIndex = 27;
			this.Label18.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2FE3_0 = this.Label15;
			location = new global::System.Drawing.Point(149, 325);
			arg_2FE3_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_300E_0 = this.Label15;
			size = new global::System.Drawing.Size(104, 19);
			arg_300E_0.Size = size;
			this.Label15.TabIndex = 15;
			this.Label15.Text = "کسر هزار ریال";
			this.txt_keraye.AcceptEnter = true;
			this.txt_keraye.AllowEdit = false;
			this.txt_keraye.AllowNew = true;
			this.txt_keraye.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_keraye.FocusColor = true;
			this.txt_keraye.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_30C2_0 = this.txt_keraye;
			location = new global::System.Drawing.Point(12, 145);
			arg_30C2_0.Location = location;
			this.txt_keraye.MaxLength = 10;
			this.txt_keraye.Name = "txt_keraye";
			this.txt_keraye.Nullable = true;
			this.txt_keraye.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_keraye.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3129_0 = this.txt_keraye;
			size = new global::System.Drawing.Size(135, 36);
			arg_3129_0.Size = size;
			this.txt_keraye.TabIndex = 3;
			this.txt_keraye.TabStop = false;
			this.txt_keraye.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_keraye.Value = value;
			this.txt_keraye.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_31C8_0 = this.Label1;
			location = new global::System.Drawing.Point(148, 25);
			arg_31C8_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_31F3_0 = this.Label1;
			size = new global::System.Drawing.Size(84, 19);
			arg_31F3_0.Size = size;
			this.Label1.TabIndex = 15;
			this.Label1.Text = "جمع فروش";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3,
				this.ButtonItem4,
				this.ButtonItem5
			});
			global::DevComponents.DotNetBar.Bar arg_32C1_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_32C1_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_32EF_0 = this.Bar1;
			size = new global::System.Drawing.Size(986, 41);
			arg_32EF_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 13;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.page;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem1.Visible = false;
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف (F5)";
			this.ButtonItem3.Visible = false;
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "چاپ (F4)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.customers_coins;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "درصد مشارکت";
			this.ButtonItem5.Visible = false;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(986, 619);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Safi_Sardkhane";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "ثبت صافی فروش از سردخانه";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_rizFurush).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000EC4 RID: 3780
		private global::System.ComponentModel.IContainer components;
	}
}
