namespace FruitBox
{
	// Token: 0x020000D1 RID: 209
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Moshtari : global::System.Windows.Forms.Form
	{
		// Token: 0x060011CB RID: 4555 RVA: 0x000C087C File Offset: 0x000BEA7C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060011CC RID: 4556 RVA: 0x000C08CC File Offset: 0x000BEACC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem2 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem3 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.group__albagi = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox3 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txt_mablagh = new global::FruitBox.CurrencyBox(this.components);
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.txt_tarikh = new global::FruitBox.DateBox2(this.components);
			this.cmb_avaldore = new global::FruitBox.ComboBox(this.components);
			this.group_mahale_faaliyat = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox4 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Txt_Grouh_Moshtari = new global::FruitBox.SelectItem(this.components);
			this.txt_grouhmoshtari2 = new global::FruitBox.SelectItem(this.components);
			this.txt_name = new global::FruitBox.EditBox(this.components);
			this.txt_karmozd = new global::FruitBox.NumericBox(this.components);
			this.txt_moshtari_kind = new global::FruitBox.SelectItem(this.components);
			this.lbl_code = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.UiTab1 = new global::Janus.Windows.UI.Tab.UITab();
			this.UiTabPage2 = new global::Janus.Windows.UI.Tab.UITabPage();
			this.UiButton6 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton7 = new global::Janus.Windows.EditControls.UIButton();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.UiTabPage1 = new global::Janus.Windows.UI.Tab.UITabPage();
			this.UiButton4 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton3 = new global::Janus.Windows.EditControls.UIButton();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.txt_codeegtesadi = new global::FruitBox.NumericBox(this.components);
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.txt_tel2 = new global::FruitBox.EditBox(this.components);
			this.txt_family = new global::FruitBox.EditBox(this.components);
			this.Label23 = new global::System.Windows.Forms.Label();
			this.txt_code_moshtari = new global::FruitBox.NumericBox(this.components);
			this.group_contact_info = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_address2 = new global::FruitBox.EditBox(this.components);
			this.Label8 = new global::System.Windows.Forms.Label();
			this.moaref_kind = new global::FruitBox.SelectItem(this.components);
			this.txt_address = new global::FruitBox.EditBox(this.components);
			this.Label17 = new global::System.Windows.Forms.Label();
			this.txt_tel1 = new global::FruitBox.EditBox(this.components);
			this.txt_Moaref = new global::FruitBox.EditBox(this.components);
			this.txt_codemelli = new global::FruitBox.NumericBox(this.components);
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_shsh = new global::FruitBox.NumericBox(this.components);
			this.txt_tel3 = new global::FruitBox.EditBox(this.components);
			this.txt_tel4 = new global::FruitBox.EditBox(this.components);
			this.txt_fax = new global::FruitBox.EditBox(this.components);
			this.txt_codeposti = new global::FruitBox.EditBox(this.components);
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.OpenFileDialog2 = new global::System.Windows.Forms.OpenFileDialog();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group__albagi).BeginInit();
			this.group__albagi.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.group_mahale_faaliyat).BeginInit();
			this.group_mahale_faaliyat.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiTab1).BeginInit();
			this.UiTab1.SuspendLayout();
			this.UiTabPage2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.UiTabPage1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.group_contact_info).BeginInit();
			this.group_contact_info.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.SuspendLayout();
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label2.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_559_0 = this.Label2;
			global::System.Drawing.Point location = new global::System.Drawing.Point(982, 104);
			arg_559_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_584_0 = this.Label2;
			global::System.Drawing.Size size = new global::System.Drawing.Size(24, 17);
			arg_584_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "نام";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label3.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_61E_0 = this.Label3;
			location = new global::System.Drawing.Point(723, 105);
			arg_61E_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_649_0 = this.Label3;
			size = new global::System.Drawing.Size(82, 17);
			arg_649_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "نام خانوادگی";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label4.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_6E6_0 = this.Label4;
			location = new global::System.Drawing.Point(703, 130);
			arg_6E6_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_711_0 = this.Label4;
			size = new global::System.Drawing.Size(53, 17);
			arg_711_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "کد ملی";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label5.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_7AE_0 = this.Label5;
			location = new global::System.Drawing.Point(447, 132);
			arg_7AE_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_7D9_0 = this.Label5;
			size = new global::System.Drawing.Size(46, 17);
			arg_7D9_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "ش.ش";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label6.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_873_0 = this.Label6;
			location = new global::System.Drawing.Point(703, 48);
			arg_873_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_89E_0 = this.Label6;
			size = new global::System.Drawing.Size(64, 17);
			arg_89E_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "تلفن ثابت";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label7.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_938_0 = this.Label7;
			location = new global::System.Drawing.Point(443, 105);
			arg_938_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_963_0 = this.Label7;
			size = new global::System.Drawing.Size(39, 16);
			arg_963_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "همراه";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label10.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_9FD_0 = this.Label10;
			location = new global::System.Drawing.Point(167, 90);
			arg_9FD_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_A28_0 = this.Label10;
			size = new global::System.Drawing.Size(37, 16);
			arg_A28_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "فکس";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label12.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_AC5_0 = this.Label12;
			location = new global::System.Drawing.Point(162, 485);
			arg_AC5_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_AF0_0 = this.Label12;
			size = new global::System.Drawing.Size(75, 17);
			arg_AF0_0.Size = size;
			this.Label12.TabIndex = 0;
			this.Label12.Text = "کد اقتصادی";
			this.Label12.Visible = false;
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label13.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_B9A_0 = this.Label13;
			location = new global::System.Drawing.Point(667, 176);
			arg_B9A_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_BC5_0 = this.Label13;
			size = new global::System.Drawing.Size(91, 17);
			arg_BC5_0.Size = size;
			this.Label13.TabIndex = 0;
			this.Label13.Text = "آدرس محل کار";
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.group__albagi);
			this.UiGroupBox1.Controls.Add(this.group_mahale_faaliyat);
			this.UiGroupBox1.Controls.Add(this.txt_name);
			this.UiGroupBox1.Controls.Add(this.txt_karmozd);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari_kind);
			this.UiGroupBox1.Controls.Add(this.lbl_code);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.UiTab1);
			this.UiGroupBox1.Controls.Add(this.txt_codeegtesadi);
			this.UiGroupBox1.Controls.Add(this.Label21);
			this.UiGroupBox1.Controls.Add(this.Label20);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.txt_tel2);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.txt_family);
			this.UiGroupBox1.Controls.Add(this.Label23);
			this.UiGroupBox1.Controls.Add(this.txt_code_moshtari);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.group_contact_info);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox1.ForeColor = global::System.Drawing.Color.Black;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_E21_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_E21_0.Location = location;
			global::System.Windows.Forms.Control arg_E38_0 = this.UiGroupBox1;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(0);
			arg_E38_0.Margin = margin;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_E76_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(1054, 518);
			arg_E76_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.group__albagi.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.group__albagi.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.group__albagi.Controls.Add(this.UiGroupBox3);
			this.group__albagi.Controls.Add(this.Label15);
			this.group__albagi.Controls.Add(this.txt_mablagh);
			this.group__albagi.Controls.Add(this.Label14);
			this.group__albagi.Controls.Add(this.Label16);
			this.group__albagi.Controls.Add(this.txt_tarikh);
			this.group__albagi.Controls.Add(this.cmb_avaldore);
			this.group__albagi.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_F79_0 = this.group__albagi;
			location = new global::System.Drawing.Point(284, 133);
			arg_F79_0.Location = location;
			this.group__albagi.Name = "group__albagi";
			global::System.Windows.Forms.Control arg_FA7_0 = this.group__albagi;
			size = new global::System.Drawing.Size(764, 74);
			arg_FA7_0.Size = size;
			this.group__albagi.TabIndex = 104;
			this.group__albagi.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox3.BackColor = global::System.Drawing.Color.Transparent;
			this.UiGroupBox3.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox3.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_1029_0 = this.UiGroupBox3;
			location = new global::System.Drawing.Point(7, 11);
			arg_1029_0.Location = location;
			this.UiGroupBox3.Name = "UiGroupBox3";
			global::System.Windows.Forms.Control arg_1057_0 = this.UiGroupBox3;
			size = new global::System.Drawing.Size(768, 20);
			arg_1057_0.Size = size;
			this.UiGroupBox3.TabIndex = 6;
			this.UiGroupBox3.Text = "الباقی حساب";
			this.UiGroupBox3.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label15.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_10FE_0 = this.Label15;
			location = new global::System.Drawing.Point(699, 47);
			arg_10FE_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_1129_0 = this.Label15;
			size = new global::System.Drawing.Size(58, 16);
			arg_1129_0.Size = size;
			this.Label15.TabIndex = 0;
			this.Label15.Text = "نوع مانده";
			this.txt_mablagh.AcceptEnter = true;
			this.txt_mablagh.AllowEdit = true;
			this.txt_mablagh.AllowNew = true;
			this.txt_mablagh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mablagh.FocusColor = true;
			this.txt_mablagh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11C8_0 = this.txt_mablagh;
			location = new global::System.Drawing.Point(278, 33);
			arg_11C8_0.Location = location;
			this.txt_mablagh.Name = "txt_mablagh";
			this.txt_mablagh.Nullable = true;
			this.txt_mablagh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1221_0 = this.txt_mablagh;
			size = new global::System.Drawing.Size(159, 36);
			arg_1221_0.Size = size;
			this.txt_mablagh.TabIndex = 7;
			this.txt_mablagh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_mablagh.Value = value;
			this.txt_mablagh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label14.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_12D2_0 = this.Label14;
			location = new global::System.Drawing.Point(439, 46);
			arg_12D2_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_12FD_0 = this.Label14;
			size = new global::System.Drawing.Size(33, 16);
			arg_12FD_0.Size = size;
			this.Label14.TabIndex = 21;
			this.Label14.Text = "مبلغ";
			this.Label16.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label16.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1398_0 = this.Label16;
			location = new global::System.Drawing.Point(161, 44);
			arg_1398_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_13C3_0 = this.Label16;
			size = new global::System.Drawing.Size(78, 16);
			arg_13C3_0.Size = size;
			this.Label16.TabIndex = 21;
			this.Label16.Text = "مانده از تاریخ";
			this.txt_tarikh.AcceptEnter = true;
			this.txt_tarikh.AllowEdit = true;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh.ButtonEnable = false;
			this.txt_tarikh.FocusDatePart = 2;
			this.txt_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_145F_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(0, 33);
			arg_145F_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_14AB_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(159, 36);
			arg_14AB_0.Size = size;
			this.txt_tarikh.TabIndex = 8;
			this.txt_tarikh.Text = "1392/08/02";
			this.txt_tarikh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Center;
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.cmb_avaldore.AllowNew = true;
			this.cmb_avaldore.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.cmb_avaldore.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.cmb_avaldore.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem.FormatStyle.Alpha = 0;
			uIComboBoxItem.IsSeparator = false;
			uIComboBoxItem.Text = "بیحساب";
			uIComboBoxItem.Value = "0";
			uIComboBoxItem2.FormatStyle.Alpha = 0;
			uIComboBoxItem2.IsSeparator = false;
			uIComboBoxItem2.Text = "بدهکار";
			uIComboBoxItem2.Value = "1";
			uIComboBoxItem3.FormatStyle.Alpha = 0;
			uIComboBoxItem3.IsSeparator = false;
			uIComboBoxItem3.Text = "بستانکار";
			uIComboBoxItem3.Value = "2";
			this.cmb_avaldore.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem,
				uIComboBoxItem2,
				uIComboBoxItem3
			});
			global::System.Windows.Forms.Control arg_1608_0 = this.cmb_avaldore;
			location = new global::System.Drawing.Point(536, 34);
			arg_1608_0.Location = location;
			this.cmb_avaldore.Name = "cmb_avaldore";
			this.cmb_avaldore.Nullable = true;
			this.cmb_avaldore.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			global::System.Windows.Forms.Control arg_1654_0 = this.cmb_avaldore;
			size = new global::System.Drawing.Size(161, 36);
			arg_1654_0.Size = size;
			this.cmb_avaldore.TabIndex = 6;
			this.cmb_avaldore.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2007;
			this.group_mahale_faaliyat.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.group_mahale_faaliyat.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.group_mahale_faaliyat.Controls.Add(this.UiGroupBox4);
			this.group_mahale_faaliyat.Controls.Add(this.Label19);
			this.group_mahale_faaliyat.Controls.Add(this.Label1);
			this.group_mahale_faaliyat.Controls.Add(this.Txt_Grouh_Moshtari);
			this.group_mahale_faaliyat.Controls.Add(this.txt_grouhmoshtari2);
			this.group_mahale_faaliyat.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_1729_0 = this.group_mahale_faaliyat;
			location = new global::System.Drawing.Point(279, 213);
			arg_1729_0.Location = location;
			this.group_mahale_faaliyat.Name = "group_mahale_faaliyat";
			global::System.Windows.Forms.Control arg_1757_0 = this.group_mahale_faaliyat;
			size = new global::System.Drawing.Size(769, 49);
			arg_1757_0.Size = size;
			this.group_mahale_faaliyat.TabIndex = 103;
			this.group_mahale_faaliyat.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox4.BackColor = global::System.Drawing.Color.Transparent;
			this.UiGroupBox4.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox4.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_17DD_0 = this.UiGroupBox4;
			location = new global::System.Drawing.Point(505, 16);
			arg_17DD_0.Location = location;
			this.UiGroupBox4.Name = "UiGroupBox4";
			global::System.Windows.Forms.Control arg_180B_0 = this.UiGroupBox4;
			size = new global::System.Drawing.Size(261, 23);
			arg_180B_0.Size = size;
			this.UiGroupBox4.TabIndex = 101;
			this.UiGroupBox4.Text = "محل فعالیت";
			this.UiGroupBox4.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label19.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label19.AutoSize = true;
			this.Label19.BackColor = global::System.Drawing.Color.Transparent;
			this.Label19.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label19.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_18B3_0 = this.Label19;
			location = new global::System.Drawing.Point(454, 15);
			arg_18B3_0.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control arg_18DE_0 = this.Label19;
			size = new global::System.Drawing.Size(45, 17);
			arg_18DE_0.Size = size;
			this.Label19.TabIndex = 0;
			this.Label19.Text = "منطقه";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label1.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1978_0 = this.Label1;
			location = new global::System.Drawing.Point(176, 15);
			arg_1978_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_19A3_0 = this.Label1;
			size = new global::System.Drawing.Size(68, 17);
			arg_19A3_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "شهرستان";
			this.Txt_Grouh_Moshtari.AcceptEnter = true;
			this.Txt_Grouh_Moshtari.AddNewForm = null;
			this.Txt_Grouh_Moshtari.AllowEdit = true;
			this.Txt_Grouh_Moshtari.AllowNew = true;
			this.Txt_Grouh_Moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Txt_Grouh_Moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.Txt_Grouh_Moshtari.ButtonText = "...";
			this.Txt_Grouh_Moshtari.CanEdit = false;
			this.Txt_Grouh_Moshtari.DisplayMember = "Name";
			this.Txt_Grouh_Moshtari.Edit_Frm = null;
			this.Txt_Grouh_Moshtari.ExtraData = 0L;
			this.Txt_Grouh_Moshtari.FocusColor = true;
			this.Txt_Grouh_Moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "گروه مشتریان";
			column.Name = "Name";
			column.Size = 100;
			this.Txt_Grouh_Moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column
			});
			global::System.Windows.Forms.Control arg_1AE7_0 = this.Txt_Grouh_Moshtari;
			location = new global::System.Drawing.Point(283, 0);
			arg_1AE7_0.Location = location;
			this.Txt_Grouh_Moshtari.Name = "Txt_Grouh_Moshtari";
			this.Txt_Grouh_Moshtari.Nullable = true;
			this.Txt_Grouh_Moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.Txt_Grouh_Moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.Txt_Grouh_Moshtari.SelectCommand = "select * from grouh_Moshtari";
			this.Txt_Grouh_Moshtari.SelectedRow = null;
			this.Txt_Grouh_Moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1B6B_0 = this.Txt_Grouh_Moshtari;
			size = new global::System.Drawing.Size(159, 36);
			arg_1B6B_0.Size = size;
			this.Txt_Grouh_Moshtari.TabIndex = 4;
			this.Txt_Grouh_Moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.Txt_Grouh_Moshtari.Value = null;
			this.Txt_Grouh_Moshtari.ValueMember = "ID";
			this.Txt_Grouh_Moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_grouhmoshtari2.AcceptEnter = true;
			this.txt_grouhmoshtari2.AddNewForm = null;
			this.txt_grouhmoshtari2.AllowEdit = true;
			this.txt_grouhmoshtari2.AllowNew = true;
			this.txt_grouhmoshtari2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_grouhmoshtari2.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_grouhmoshtari2.ButtonText = "...";
			this.txt_grouhmoshtari2.CanEdit = false;
			this.txt_grouhmoshtari2.DisplayMember = "Name";
			this.txt_grouhmoshtari2.Edit_Frm = null;
			this.txt_grouhmoshtari2.ExtraData = 0L;
			this.txt_grouhmoshtari2.FocusColor = true;
			this.txt_grouhmoshtari2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column2.Caption = "گروه مشتریان";
			column2.Name = "Name";
			column2.Size = 100;
			this.txt_grouhmoshtari2.Items.AddRange(new global::FruitBox.Column[]
			{
				column2
			});
			global::System.Windows.Forms.Control arg_1CD2_0 = this.txt_grouhmoshtari2;
			location = new global::System.Drawing.Point(5, 2);
			arg_1CD2_0.Location = location;
			this.txt_grouhmoshtari2.Name = "txt_grouhmoshtari2";
			this.txt_grouhmoshtari2.Nullable = true;
			this.txt_grouhmoshtari2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_grouhmoshtari2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_grouhmoshtari2.SelectCommand = "select * from grouh_Moshtari2";
			this.txt_grouhmoshtari2.SelectedRow = null;
			this.txt_grouhmoshtari2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1D56_0 = this.txt_grouhmoshtari2;
			size = new global::System.Drawing.Size(159, 36);
			arg_1D56_0.Size = size;
			this.txt_grouhmoshtari2.TabIndex = 5;
			this.txt_grouhmoshtari2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_grouhmoshtari2.Value = null;
			this.txt_grouhmoshtari2.ValueMember = "ID";
			this.txt_grouhmoshtari2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_name.AcceptEnter = true;
			this.txt_name.AllowEdit = true;
			this.txt_name.AllowNew = true;
			this.txt_name.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_name.FocusColor = true;
			this.txt_name.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1E1C_0 = this.txt_name;
			location = new global::System.Drawing.Point(820, 93);
			arg_1E1C_0.Location = location;
			this.txt_name.Name = "txt_name";
			this.txt_name.Nullable = false;
			this.txt_name.NullToolTipText = "لطفا نام مشتری را وارد نمائید";
			this.txt_name.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1E75_0 = this.txt_name;
			size = new global::System.Drawing.Size(159, 36);
			arg_1E75_0.Size = size;
			this.txt_name.TabIndex = 1;
			this.txt_name.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_karmozd.AcceptEnter = true;
			this.txt_karmozd.AllowEdit = true;
			this.txt_karmozd.AllowNew = true;
			this.txt_karmozd.AllowZero = true;
			this.txt_karmozd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_karmozd.DecimalDigits = 2;
			this.txt_karmozd.FixLength = 2;
			this.txt_karmozd.FocusColor = true;
			this.txt_karmozd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1F37_0 = this.txt_karmozd;
			location = new global::System.Drawing.Point(283, 49);
			arg_1F37_0.Location = location;
			this.txt_karmozd.MaxLength = 5;
			this.txt_karmozd.Name = "txt_karmozd";
			this.txt_karmozd.Nullable = true;
			this.txt_karmozd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_karmozd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1F9D_0 = this.txt_karmozd;
			size = new global::System.Drawing.Size(159, 36);
			arg_1F9D_0.Size = size;
			this.txt_karmozd.TabIndex = 27;
			this.txt_karmozd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_karmozd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari_kind.AcceptEnter = true;
			this.txt_moshtari_kind.AddNewForm = null;
			this.txt_moshtari_kind.AllowEdit = true;
			this.txt_moshtari_kind.AllowNew = true;
			this.txt_moshtari_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari_kind.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari_kind.ButtonText = "...";
			this.txt_moshtari_kind.CanEdit = false;
			this.txt_moshtari_kind.DisplayMember = "name";
			this.txt_moshtari_kind.Edit_Frm = null;
			this.txt_moshtari_kind.ExtraData = 0L;
			this.txt_moshtari_kind.FocusColor = true;
			this.txt_moshtari_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column3.Caption = "عنوان";
			column3.Name = "Name";
			column3.Size = 100;
			this.txt_moshtari_kind.Items.AddRange(new global::FruitBox.Column[]
			{
				column3
			});
			global::System.Windows.Forms.Control arg_20EC_0 = this.txt_moshtari_kind;
			location = new global::System.Drawing.Point(562, 49);
			arg_20EC_0.Location = location;
			this.txt_moshtari_kind.Name = "txt_moshtari_kind";
			this.txt_moshtari_kind.Nullable = false;
			this.txt_moshtari_kind.NullToolTipText = "نوع مشتری را وارد نمائید";
			this.txt_moshtari_kind.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_moshtari_kind.SelectCommand = "select * from moshtari_kind";
			this.txt_moshtari_kind.SelectedRow = null;
			this.txt_moshtari_kind.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2170_0 = this.txt_moshtari_kind;
			size = new global::System.Drawing.Size(159, 36);
			arg_2170_0.Size = size;
			this.txt_moshtari_kind.TabIndex = 0;
			this.txt_moshtari_kind.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari_kind.Value = null;
			this.txt_moshtari_kind.ValueMember = "id";
			this.txt_moshtari_kind.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_code.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_code.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_code.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_220F_0 = this.lbl_code;
			location = new global::System.Drawing.Point(820, 51);
			arg_220F_0.Location = location;
			this.lbl_code.Name = "lbl_code";
			global::System.Windows.Forms.Control arg_223D_0 = this.lbl_code;
			size = new global::System.Drawing.Size(159, 36);
			arg_223D_0.Size = size;
			this.lbl_code.TabIndex = 25;
			this.lbl_code.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3,
				this.ButtonItem4
			});
			global::DevComponents.DotNetBar.Bar arg_22FD_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_22FD_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_232B_0 = this.Bar1;
			size = new global::System.Drawing.Size(1054, 41);
			arg_232B_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 24;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف (F5)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.bank_customer;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "حساب های بانکی (F7)";
			this.UiTab1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiTab1.FirstTabOffset = 58;
			global::System.Windows.Forms.Control arg_24A6_0 = this.UiTab1;
			location = new global::System.Drawing.Point(8, 49);
			arg_24A6_0.Location = location;
			this.UiTab1.Name = "UiTab1";
			this.UiTab1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiTab1.OfficeCustomColor = global::System.Drawing.Color.SkyBlue;
			this.UiTab1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_2502_0 = this.UiTab1;
			size = new global::System.Drawing.Size(269, 215);
			arg_2502_0.Size = size;
			this.UiTab1.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.UiTab1.TabDisplay = global::Janus.Windows.UI.Tab.TabDisplay.Text;
			this.UiTab1.TabIndex = 23;
			this.UiTab1.TabPages.AddRange(new global::Janus.Windows.UI.Tab.UITabPage[]
			{
				this.UiTabPage2,
				this.UiTabPage1
			});
			this.UiTab1.TabStop = false;
			this.UiTab1.VisualStyle = global::Janus.Windows.UI.Tab.TabVisualStyle.Office2010;
			this.UiTabPage2.Controls.Add(this.UiButton6);
			this.UiTabPage2.Controls.Add(this.UiButton7);
			this.UiTabPage2.Controls.Add(this.PictureBox2);
			global::System.Windows.Forms.Control arg_25D3_0 = this.UiTabPage2;
			location = new global::System.Drawing.Point(1, 24);
			arg_25D3_0.Location = location;
			this.UiTabPage2.Name = "UiTabPage2";
			this.UiTabPage2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_2611_0 = this.UiTabPage2;
			size = new global::System.Drawing.Size(267, 190);
			arg_2611_0.Size = size;
			this.UiTabPage2.TabStop = true;
			this.UiTabPage2.Text = "نمونه امضا";
			global::System.Windows.Forms.Control arg_264C_0 = this.UiButton6;
			location = new global::System.Drawing.Point(21, 135);
			arg_264C_0.Location = location;
			this.UiButton6.Name = "UiButton6";
			global::System.Windows.Forms.Control arg_2677_0 = this.UiButton6;
			size = new global::System.Drawing.Size(75, 23);
			arg_2677_0.Size = size;
			this.UiButton6.TabIndex = 1;
			this.UiButton6.Text = "حذف";
			this.UiButton6.TextHorizontalAlignment = global::Janus.Windows.EditControls.TextAlignment.Empty;
			global::System.Windows.Forms.Control arg_26BF_0 = this.UiButton7;
			location = new global::System.Drawing.Point(102, 135);
			arg_26BF_0.Location = location;
			this.UiButton7.Name = "UiButton7";
			global::System.Windows.Forms.Control arg_26EA_0 = this.UiButton7;
			size = new global::System.Drawing.Size(75, 23);
			arg_26EA_0.Size = size;
			this.UiButton7.TabIndex = 0;
			this.UiButton7.Text = "بارگذاری";
			this.PictureBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox2.Dock = global::System.Windows.Forms.DockStyle.Top;
			global::System.Windows.Forms.Control arg_273E_0 = this.PictureBox2;
			location = new global::System.Drawing.Point(0, 0);
			arg_273E_0.Location = location;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control arg_276F_0 = this.PictureBox2;
			size = new global::System.Drawing.Size(267, 129);
			arg_276F_0.Size = size;
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 1;
			this.PictureBox2.TabStop = false;
			this.UiTabPage1.Controls.Add(this.UiButton4);
			this.UiTabPage1.Controls.Add(this.UiButton3);
			this.UiTabPage1.Controls.Add(this.PictureBox1);
			global::System.Windows.Forms.Control arg_27F4_0 = this.UiTabPage1;
			location = new global::System.Drawing.Point(1, 24);
			arg_27F4_0.Location = location;
			this.UiTabPage1.Name = "UiTabPage1";
			global::System.Windows.Forms.Control arg_2825_0 = this.UiTabPage1;
			size = new global::System.Drawing.Size(267, 190);
			arg_2825_0.Size = size;
			this.UiTabPage1.TabStop = true;
			this.UiTabPage1.Text = "تصویر";
			global::System.Windows.Forms.Control arg_2860_0 = this.UiButton4;
			location = new global::System.Drawing.Point(50, 141);
			arg_2860_0.Location = location;
			this.UiButton4.Name = "UiButton4";
			global::System.Windows.Forms.Control arg_288B_0 = this.UiButton4;
			size = new global::System.Drawing.Size(75, 23);
			arg_288B_0.Size = size;
			this.UiButton4.TabIndex = 1;
			this.UiButton4.Text = "حذف";
			this.UiButton4.TextHorizontalAlignment = global::Janus.Windows.EditControls.TextAlignment.Empty;
			global::System.Windows.Forms.Control arg_28D6_0 = this.UiButton3;
			location = new global::System.Drawing.Point(131, 141);
			arg_28D6_0.Location = location;
			this.UiButton3.Name = "UiButton3";
			global::System.Windows.Forms.Control arg_2901_0 = this.UiButton3;
			size = new global::System.Drawing.Size(75, 23);
			arg_2901_0.Size = size;
			this.UiButton3.TabIndex = 1;
			this.UiButton3.Text = "بارگذاری";
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.Dock = global::System.Windows.Forms.DockStyle.Top;
			global::System.Windows.Forms.Control arg_2955_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_2955_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_2986_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(267, 129);
			arg_2986_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 0;
			this.PictureBox1.TabStop = false;
			this.txt_codeegtesadi.AcceptEnter = true;
			this.txt_codeegtesadi.AllowEdit = true;
			this.txt_codeegtesadi.AllowNew = true;
			this.txt_codeegtesadi.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_codeegtesadi.FocusColor = true;
			this.txt_codeegtesadi.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2A2D_0 = this.txt_codeegtesadi;
			location = new global::System.Drawing.Point(8, 473);
			arg_2A2D_0.Location = location;
			this.txt_codeegtesadi.Name = "txt_codeegtesadi";
			this.txt_codeegtesadi.Nullable = true;
			this.txt_codeegtesadi.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_codeegtesadi.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2A86_0 = this.txt_codeegtesadi;
			size = new global::System.Drawing.Size(153, 36);
			arg_2A86_0.Size = size;
			this.txt_codeegtesadi.TabIndex = 8;
			this.txt_codeegtesadi.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_codeegtesadi.Visible = false;
			this.txt_codeegtesadi.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label21.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label21.AutoSize = true;
			this.Label21.BackColor = global::System.Drawing.Color.Transparent;
			this.Label21.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label21.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_2B36_0 = this.Label21;
			location = new global::System.Drawing.Point(723, 59);
			arg_2B36_0.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control arg_2B61_0 = this.Label21;
			size = new global::System.Drawing.Size(75, 17);
			arg_2B61_0.Size = size;
			this.Label21.TabIndex = 0;
			this.Label21.Text = "نوع مشتری";
			this.Label20.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label20.AutoSize = true;
			this.Label20.BackColor = global::System.Drawing.Color.Transparent;
			this.Label20.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label20.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_2BFB_0 = this.Label20;
			location = new global::System.Drawing.Point(981, 62);
			arg_2BFB_0.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control arg_2C26_0 = this.Label20;
			size = new global::System.Drawing.Size(72, 17);
			arg_2C26_0.Size = size;
			this.Label20.TabIndex = 0;
			this.Label20.Text = "کد مشتری";
			this.txt_tel2.AcceptEnter = true;
			this.txt_tel2.AllowEdit = true;
			this.txt_tel2.AllowNew = true;
			this.txt_tel2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tel2.FocusColor = true;
			this.txt_tel2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2CC5_0 = this.txt_tel2;
			location = new global::System.Drawing.Point(283, 91);
			arg_2CC5_0.Location = location;
			this.txt_tel2.Name = "txt_tel2";
			this.txt_tel2.Nullable = true;
			this.txt_tel2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tel2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2D1E_0 = this.txt_tel2;
			size = new global::System.Drawing.Size(159, 36);
			arg_2D1E_0.Size = size;
			this.txt_tel2.TabIndex = 3;
			this.txt_tel2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_family.AcceptEnter = true;
			this.txt_family.AllowEdit = true;
			this.txt_family.AllowNew = true;
			this.txt_family.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_family.FocusColor = true;
			this.txt_family.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2DB9_0 = this.txt_family;
			location = new global::System.Drawing.Point(562, 91);
			arg_2DB9_0.Location = location;
			this.txt_family.Name = "txt_family";
			this.txt_family.Nullable = false;
			this.txt_family.NullToolTipText = "لطفا نام خانوادگی مشتری را وارد نمائید";
			this.txt_family.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2E12_0 = this.txt_family;
			size = new global::System.Drawing.Size(159, 36);
			arg_2E12_0.Size = size;
			this.txt_family.TabIndex = 2;
			this.txt_family.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label23.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label23.AutoSize = true;
			this.Label23.BackColor = global::System.Drawing.Color.Transparent;
			this.Label23.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label23.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_2EA8_0 = this.Label23;
			location = new global::System.Drawing.Point(444, 58);
			arg_2EA8_0.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control arg_2ED3_0 = this.Label23;
			size = new global::System.Drawing.Size(44, 17);
			arg_2ED3_0.Size = size;
			this.Label23.TabIndex = 0;
			this.Label23.Text = "کارمزد";
			this.txt_code_moshtari.AcceptEnter = true;
			this.txt_code_moshtari.AllowEdit = true;
			this.txt_code_moshtari.AllowNew = true;
			this.txt_code_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_code_moshtari.FocusColor = true;
			this.txt_code_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2F72_0 = this.txt_code_moshtari;
			location = new global::System.Drawing.Point(820, 51);
			arg_2F72_0.Location = location;
			this.txt_code_moshtari.MaxLength = 10;
			this.txt_code_moshtari.Name = "txt_code_moshtari";
			this.txt_code_moshtari.Nullable = true;
			this.txt_code_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_code_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2FD9_0 = this.txt_code_moshtari;
			size = new global::System.Drawing.Size(157, 36);
			arg_2FD9_0.Size = size;
			this.txt_code_moshtari.TabIndex = 100;
			this.txt_code_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_code_moshtari.Visible = false;
			this.txt_code_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.group_contact_info.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.group_contact_info.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.group_contact_info.Controls.Add(this.txt_address2);
			this.group_contact_info.Controls.Add(this.Label8);
			this.group_contact_info.Controls.Add(this.Label13);
			this.group_contact_info.Controls.Add(this.moaref_kind);
			this.group_contact_info.Controls.Add(this.txt_address);
			this.group_contact_info.Controls.Add(this.Label4);
			this.group_contact_info.Controls.Add(this.Label17);
			this.group_contact_info.Controls.Add(this.Label6);
			this.group_contact_info.Controls.Add(this.txt_tel1);
			this.group_contact_info.Controls.Add(this.txt_Moaref);
			this.group_contact_info.Controls.Add(this.txt_codemelli);
			this.group_contact_info.Controls.Add(this.Label18);
			this.group_contact_info.Controls.Add(this.Label22);
			this.group_contact_info.Controls.Add(this.Label5);
			this.group_contact_info.Controls.Add(this.UiGroupBox2);
			this.group_contact_info.Controls.Add(this.txt_shsh);
			this.group_contact_info.Controls.Add(this.txt_tel3);
			this.group_contact_info.Controls.Add(this.txt_tel4);
			this.group_contact_info.Controls.Add(this.txt_fax);
			this.group_contact_info.Controls.Add(this.txt_codeposti);
			this.group_contact_info.Controls.Add(this.Label11);
			this.group_contact_info.Controls.Add(this.Label10);
			this.group_contact_info.Controls.Add(this.Label9);
			this.group_contact_info.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_3267_0 = this.group_contact_info;
			location = new global::System.Drawing.Point(276, 256);
			arg_3267_0.Location = location;
			this.group_contact_info.Name = "group_contact_info";
			this.group_contact_info.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_32A5_0 = this.group_contact_info;
			size = new global::System.Drawing.Size(775, 259);
			arg_32A5_0.Size = size;
			this.group_contact_info.TabIndex = 102;
			this.group_contact_info.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_address2.AcceptEnter = true;
			this.txt_address2.AllowEdit = true;
			this.txt_address2.AllowNew = true;
			this.txt_address2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_address2.FocusColor = true;
			this.txt_address2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3340_0 = this.txt_address2;
			location = new global::System.Drawing.Point(5, 210);
			arg_3340_0.Location = location;
			this.txt_address2.Name = "txt_address2";
			this.txt_address2.Nullable = true;
			this.txt_address2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_address2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3399_0 = this.txt_address2;
			size = new global::System.Drawing.Size(645, 36);
			arg_3399_0.Size = size;
			this.txt_address2.TabIndex = 19;
			this.txt_address2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label8.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_3433_0 = this.Label8;
			location = new global::System.Drawing.Point(653, 219);
			arg_3433_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_345E_0 = this.Label8;
			size = new global::System.Drawing.Size(119, 17);
			arg_345E_0.Size = size;
			this.Label8.TabIndex = 0;
			this.Label8.Text = "آدرس محل سکونت";
			this.moaref_kind.AcceptEnter = true;
			this.moaref_kind.AddNewForm = null;
			this.moaref_kind.AllowEdit = true;
			this.moaref_kind.AllowNew = true;
			this.moaref_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.moaref_kind.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.moaref_kind.ButtonText = "...";
			this.moaref_kind.CanEdit = false;
			this.moaref_kind.DisplayMember = null;
			this.moaref_kind.Edit_Frm = null;
			this.moaref_kind.ExtraData = 0L;
			this.moaref_kind.FocusColor = true;
			this.moaref_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_355D_0 = this.moaref_kind;
			location = new global::System.Drawing.Point(286, 79);
			arg_355D_0.Location = location;
			this.moaref_kind.Name = "moaref_kind";
			this.moaref_kind.Nullable = true;
			this.moaref_kind.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.moaref_kind.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.moaref_kind.SelectCommand = null;
			this.moaref_kind.SelectedRow = null;
			this.moaref_kind.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_35DD_0 = this.moaref_kind;
			size = new global::System.Drawing.Size(159, 36);
			arg_35DD_0.Size = size;
			this.moaref_kind.TabIndex = 13;
			this.moaref_kind.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.moaref_kind.Value = null;
			this.moaref_kind.ValueMember = null;
			this.moaref_kind.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_address.AcceptEnter = true;
			this.txt_address.AllowEdit = true;
			this.txt_address.AllowNew = true;
			this.txt_address.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_address.FocusColor = true;
			this.txt_address.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_369F_0 = this.txt_address;
			location = new global::System.Drawing.Point(5, 164);
			arg_369F_0.Location = location;
			this.txt_address.Name = "txt_address";
			this.txt_address.Nullable = true;
			this.txt_address.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_address.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_36F8_0 = this.txt_address;
			size = new global::System.Drawing.Size(644, 36);
			arg_36F8_0.Size = size;
			this.txt_address.TabIndex = 18;
			this.txt_address.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label17.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label17.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_378F_0 = this.Label17;
			location = new global::System.Drawing.Point(703, 89);
			arg_378F_0.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control arg_37BA_0 = this.Label17;
			size = new global::System.Drawing.Size(40, 17);
			arg_37BA_0.Size = size;
			this.Label17.TabIndex = 0;
			this.Label17.Text = "معرف";
			this.txt_tel1.AcceptEnter = true;
			this.txt_tel1.AllowEdit = true;
			this.txt_tel1.AllowNew = true;
			this.txt_tel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tel1.FocusColor = true;
			this.txt_tel1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3859_0 = this.txt_tel1;
			location = new global::System.Drawing.Point(542, 37);
			arg_3859_0.Location = location;
			this.txt_tel1.Name = "txt_tel1";
			this.txt_tel1.Nullable = true;
			this.txt_tel1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tel1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_38B2_0 = this.txt_tel1;
			size = new global::System.Drawing.Size(159, 36);
			arg_38B2_0.Size = size;
			this.txt_tel1.TabIndex = 9;
			this.txt_tel1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_Moaref.AcceptEnter = true;
			this.txt_Moaref.AllowEdit = true;
			this.txt_Moaref.AllowNew = true;
			this.txt_Moaref.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_Moaref.FocusColor = true;
			this.txt_Moaref.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_394E_0 = this.txt_Moaref;
			location = new global::System.Drawing.Point(542, 79);
			arg_394E_0.Location = location;
			this.txt_Moaref.Name = "txt_Moaref";
			this.txt_Moaref.Nullable = true;
			this.txt_Moaref.NullToolTipText = "لطفا نام خانوادگی مشتری را وارد نمائید";
			this.txt_Moaref.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_39A7_0 = this.txt_Moaref;
			size = new global::System.Drawing.Size(159, 36);
			arg_39A7_0.Size = size;
			this.txt_Moaref.TabIndex = 12;
			this.txt_Moaref.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_codemelli.AcceptEnter = true;
			this.txt_codemelli.AllowEdit = true;
			this.txt_codemelli.AllowNew = true;
			this.txt_codemelli.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_codemelli.FocusColor = true;
			this.txt_codemelli.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3A43_0 = this.txt_codemelli;
			location = new global::System.Drawing.Point(542, 121);
			arg_3A43_0.Location = location;
			this.txt_codemelli.MaxLength = 10;
			this.txt_codemelli.Name = "txt_codemelli";
			this.txt_codemelli.Nullable = true;
			this.txt_codemelli.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_codemelli.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3AAA_0 = this.txt_codemelli;
			size = new global::System.Drawing.Size(159, 36);
			arg_3AAA_0.Size = size;
			this.txt_codemelli.TabIndex = 15;
			this.txt_codemelli.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_codemelli.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label18.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label18.AutoSize = true;
			this.Label18.BackColor = global::System.Drawing.Color.Transparent;
			this.Label18.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label18.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_3B4E_0 = this.Label18;
			location = new global::System.Drawing.Point(447, 48);
			arg_3B4E_0.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control arg_3B79_0 = this.Label18;
			size = new global::System.Drawing.Size(91, 17);
			arg_3B79_0.Size = size;
			this.Label18.TabIndex = 0;
			this.Label18.Text = "تلفن ضروری 1";
			this.Label22.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label22.AutoSize = true;
			this.Label22.BackColor = global::System.Drawing.Color.Transparent;
			this.Label22.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label22.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_3C13_0 = this.Label22;
			location = new global::System.Drawing.Point(447, 90);
			arg_3C13_0.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control arg_3C3E_0 = this.Label22;
			size = new global::System.Drawing.Size(62, 17);
			arg_3C3E_0.Size = size;
			this.Label22.TabIndex = 0;
			this.Label22.Text = "نوع معرف";
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.UiGroupBox2.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_3CC3_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(7, 12);
			arg_3CC3_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_3CF1_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(760, 19);
			arg_3CF1_0.Size = size;
			this.UiGroupBox2.TabIndex = 6;
			this.UiGroupBox2.Text = "اطلاعات تماس";
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_shsh.AcceptEnter = true;
			this.txt_shsh.AllowEdit = true;
			this.txt_shsh.AllowNew = true;
			this.txt_shsh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shsh.FocusColor = true;
			this.txt_shsh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3D9D_0 = this.txt_shsh;
			location = new global::System.Drawing.Point(286, 121);
			arg_3D9D_0.Location = location;
			this.txt_shsh.Name = "txt_shsh";
			this.txt_shsh.Nullable = true;
			this.txt_shsh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shsh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3DF6_0 = this.txt_shsh;
			size = new global::System.Drawing.Size(159, 36);
			arg_3DF6_0.Size = size;
			this.txt_shsh.TabIndex = 16;
			this.txt_shsh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_shsh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tel3.AcceptEnter = true;
			this.txt_tel3.AllowEdit = true;
			this.txt_tel3.AllowNew = true;
			this.txt_tel3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tel3.FocusColor = true;
			this.txt_tel3.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3E9F_0 = this.txt_tel3;
			location = new global::System.Drawing.Point(286, 37);
			arg_3E9F_0.Location = location;
			this.txt_tel3.Name = "txt_tel3";
			this.txt_tel3.Nullable = true;
			this.txt_tel3.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tel3.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3EF8_0 = this.txt_tel3;
			size = new global::System.Drawing.Size(159, 36);
			arg_3EF8_0.Size = size;
			this.txt_tel3.TabIndex = 10;
			this.txt_tel3.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tel4.AcceptEnter = true;
			this.txt_tel4.AllowEdit = true;
			this.txt_tel4.AllowNew = true;
			this.txt_tel4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tel4.FocusColor = true;
			this.txt_tel4.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3F90_0 = this.txt_tel4;
			location = new global::System.Drawing.Point(6, 37);
			arg_3F90_0.Location = location;
			this.txt_tel4.Name = "txt_tel4";
			this.txt_tel4.Nullable = true;
			this.txt_tel4.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tel4.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3FE9_0 = this.txt_tel4;
			size = new global::System.Drawing.Size(159, 36);
			arg_3FE9_0.Size = size;
			this.txt_tel4.TabIndex = 11;
			this.txt_tel4.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fax.AcceptEnter = true;
			this.txt_fax.AllowEdit = true;
			this.txt_fax.AllowNew = true;
			this.txt_fax.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fax.FocusColor = true;
			this.txt_fax.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_4081_0 = this.txt_fax;
			location = new global::System.Drawing.Point(5, 79);
			arg_4081_0.Location = location;
			this.txt_fax.Name = "txt_fax";
			this.txt_fax.Nullable = true;
			this.txt_fax.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fax.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_40DA_0 = this.txt_fax;
			size = new global::System.Drawing.Size(160, 36);
			arg_40DA_0.Size = size;
			this.txt_fax.TabIndex = 14;
			this.txt_fax.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_codeposti.AcceptEnter = true;
			this.txt_codeposti.AllowEdit = true;
			this.txt_codeposti.AllowNew = true;
			this.txt_codeposti.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_codeposti.FocusColor = true;
			this.txt_codeposti.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_4172_0 = this.txt_codeposti;
			location = new global::System.Drawing.Point(5, 121);
			arg_4172_0.Location = location;
			this.txt_codeposti.Name = "txt_codeposti";
			this.txt_codeposti.Nullable = true;
			this.txt_codeposti.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_codeposti.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_41CB_0 = this.txt_codeposti;
			size = new global::System.Drawing.Size(160, 36);
			arg_41CB_0.Size = size;
			this.txt_codeposti.TabIndex = 17;
			this.txt_codeposti.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label11.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_4265_0 = this.Label11;
			location = new global::System.Drawing.Point(167, 132);
			arg_4265_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_4290_0 = this.Label11;
			size = new global::System.Drawing.Size(61, 16);
			arg_4290_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "کد پستی";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label9.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_432A_0 = this.Label9;
			location = new global::System.Drawing.Point(167, 49);
			arg_432A_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_4355_0 = this.Label9;
			size = new global::System.Drawing.Size(81, 16);
			arg_4355_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "تلفن ضروری2";
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this.OpenFileDialog1.RestoreDirectory = true;
			this.OpenFileDialog1.Title = "انتخاب تصویر";
			this.OpenFileDialog2.FileName = "OpenFileDialog1";
			this.OpenFileDialog2.RestoreDirectory = true;
			this.OpenFileDialog2.Title = "انتخاب تصویر";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1054, 518);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Moshtari";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "تعریف مشتریان";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group__albagi).EndInit();
			this.group__albagi.ResumeLayout(false);
			this.group__albagi.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.group_mahale_faaliyat).EndInit();
			this.group_mahale_faaliyat.ResumeLayout(false);
			this.group_mahale_faaliyat.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiTab1).EndInit();
			this.UiTab1.ResumeLayout(false);
			this.UiTabPage2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.UiTabPage1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.group_contact_info).EndInit();
			this.group_contact_info.ResumeLayout(false);
			this.group_contact_info.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040006D0 RID: 1744
		private global::System.ComponentModel.IContainer components;
	}
}
