namespace FruitBox
{
	// Token: 0x02000124 RID: 292
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_rpt_bedehkaran : global::System.Windows.Forms.Form
	{
		// Token: 0x06002A4F RID: 10831 RVA: 0x001FCCF0 File Offset: 0x001FAEF0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002A50 RID: 10832 RVA: 0x001FCD40 File Offset: 0x001FAF40
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_rpt_bedehkaran));
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem2 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem3 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			this.GridEX1 = new global::Janus.Windows.GridEX.GridEX();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiCheckBox3 = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_ta_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_az_tarikh = new global::FruitBox.DateBox2(this.components);
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txt_noe_moshtari = new global::FruitBox.SelectItem(this.components);
			this.UiCheckBox2 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox1 = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_tedadruz = new global::FruitBox.EditBox(this.components);
			this.txt_search = new global::FruitBox.EditBox(this.components);
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			this.UiComboBox1 = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.UiProgressBar1 = new global::Janus.Windows.EditControls.UIProgressBar();
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.GridEX1.AcceptsEscape = false;
			this.GridEX1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutomaticSort = false;
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_2CB_0 = this.GridEX1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 134);
			arg_2CB_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			global::System.Windows.Forms.Control arg_309_0 = this.GridEX1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1189, 410);
			arg_309_0.Size = size;
			this.GridEX1.TabIndex = 1;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.UiCheckBox3);
			this.UiGroupBox1.Controls.Add(this.txt_ta_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_az_tarikh);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.txt_noe_moshtari);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox2);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox1);
			this.UiGroupBox1.Controls.Add(this.txt_tedadruz);
			this.UiGroupBox1.Controls.Add(this.txt_search);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Controls.Add(this.UiComboBox1);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_4EC_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_4EC_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_51D_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(1189, 544);
			arg_51D_0.Size = size;
			this.UiGroupBox1.TabIndex = 2;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiCheckBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox3.BackColor = global::System.Drawing.Color.Transparent;
			this.UiCheckBox3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_595_0 = this.UiCheckBox3;
			location = new global::System.Drawing.Point(713, 97);
			arg_595_0.Location = location;
			this.UiCheckBox3.Name = "UiCheckBox3";
			global::System.Windows.Forms.Control arg_5C0_0 = this.UiCheckBox3;
			size = new global::System.Drawing.Size(74, 23);
			arg_5C0_0.Size = size;
			this.UiCheckBox3.TabIndex = 29;
			this.UiCheckBox3.TabStop = false;
			this.UiCheckBox3.Text = "از تاریخ";
			this.txt_ta_tarikh.AcceptEnter = true;
			this.txt_ta_tarikh.AllowEdit = true;
			this.txt_ta_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ta_tarikh.ButtonEnable = false;
			this.txt_ta_tarikh.Enabled = false;
			this.txt_ta_tarikh.FocusDatePart = 2;
			this.txt_ta_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_67A_0 = this.txt_ta_tarikh;
			location = new global::System.Drawing.Point(306, 92);
			arg_67A_0.Location = location;
			this.txt_ta_tarikh.Mask = "0000/00/00";
			this.txt_ta_tarikh.Name = "txt_ta_tarikh";
			this.txt_ta_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_6C3_0 = this.txt_ta_tarikh;
			size = new global::System.Drawing.Size(115, 36);
			arg_6C3_0.Size = size;
			this.txt_ta_tarikh.TabIndex = 31;
			this.txt_ta_tarikh.Text = "1392/10/02";
			this.txt_ta_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_az_tarikh.AcceptEnter = true;
			this.txt_az_tarikh.AllowEdit = true;
			this.txt_az_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_az_tarikh.ButtonEnable = false;
			this.txt_az_tarikh.Enabled = false;
			this.txt_az_tarikh.FocusDatePart = 2;
			this.txt_az_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_77D_0 = this.txt_az_tarikh;
			location = new global::System.Drawing.Point(595, 92);
			arg_77D_0.Location = location;
			this.txt_az_tarikh.Mask = "0000/00/00";
			this.txt_az_tarikh.Name = "txt_az_tarikh";
			this.txt_az_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_7C6_0 = this.txt_az_tarikh;
			size = new global::System.Drawing.Size(115, 36);
			arg_7C6_0.Size = size;
			this.txt_az_tarikh.TabIndex = 30;
			this.txt_az_tarikh.Text = "1392/10/02";
			this.txt_az_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_85D_0 = this.Label6;
			location = new global::System.Drawing.Point(423, 102);
			arg_85D_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_888_0 = this.Label6;
			size = new global::System.Drawing.Size(53, 19);
			arg_888_0.Size = size;
			this.Label6.TabIndex = 28;
			this.Label6.Text = "تا تاریخ";
			this.txt_noe_moshtari.AcceptEnter = true;
			this.txt_noe_moshtari.AddNewForm = null;
			this.txt_noe_moshtari.AllowEdit = true;
			this.txt_noe_moshtari.AllowNew = true;
			this.txt_noe_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_noe_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_noe_moshtari.ButtonText = "...";
			this.txt_noe_moshtari.CanEdit = false;
			this.txt_noe_moshtari.DisplayMember = null;
			this.txt_noe_moshtari.Edit_Frm = null;
			this.txt_noe_moshtari.ExtraData = 0L;
			this.txt_noe_moshtari.FocusColor = true;
			this.txt_noe_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_988_0 = this.txt_noe_moshtari;
			location = new global::System.Drawing.Point(229, 50);
			arg_988_0.Location = location;
			this.txt_noe_moshtari.Name = "txt_noe_moshtari";
			this.txt_noe_moshtari.Nullable = true;
			this.txt_noe_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_noe_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_noe_moshtari.SelectCommand = null;
			this.txt_noe_moshtari.SelectedRow = null;
			this.txt_noe_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_A08_0 = this.txt_noe_moshtari;
			size = new global::System.Drawing.Size(192, 36);
			arg_A08_0.Size = size;
			this.txt_noe_moshtari.TabIndex = 27;
			this.txt_noe_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_noe_moshtari.Value = null;
			this.txt_noe_moshtari.ValueMember = null;
			this.txt_noe_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiCheckBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_A83_0 = this.UiCheckBox2;
			location = new global::System.Drawing.Point(12, 99);
			arg_A83_0.Location = location;
			this.UiCheckBox2.Name = "UiCheckBox2";
			global::System.Windows.Forms.Control arg_AB1_0 = this.UiCheckBox2;
			size = new global::System.Drawing.Size(133, 23);
			arg_AB1_0.Size = size;
			this.UiCheckBox2.TabIndex = 5;
			this.UiCheckBox2.Text = "چاپ شماره تلفن";
			this.UiCheckBox2.Visible = false;
			this.UiCheckBox2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiCheckBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_B25_0 = this.UiCheckBox1;
			location = new global::System.Drawing.Point(164, 97);
			arg_B25_0.Location = location;
			this.UiCheckBox1.Name = "UiCheckBox1";
			global::System.Windows.Forms.Control arg_B50_0 = this.UiCheckBox1;
			size = new global::System.Drawing.Size(104, 23);
			arg_B50_0.Size = size;
			this.UiCheckBox1.TabIndex = 5;
			this.UiCheckBox1.Text = "چاپ جمع کل";
			this.UiCheckBox1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_tedadruz.AcceptEnter = true;
			this.txt_tedadruz.AllowEdit = true;
			this.txt_tedadruz.AllowNew = true;
			this.txt_tedadruz.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedadruz.FocusColor = true;
			this.txt_tedadruz.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_BF9_0 = this.txt_tedadruz;
			location = new global::System.Drawing.Point(12, 50);
			arg_BF9_0.Location = location;
			this.txt_tedadruz.Name = "txt_tedadruz";
			this.txt_tedadruz.Nullable = true;
			this.txt_tedadruz.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tedadruz.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_C4F_0 = this.txt_tedadruz;
			size = new global::System.Drawing.Size(56, 36);
			arg_C4F_0.Size = size;
			this.txt_tedadruz.TabIndex = 4;
			this.txt_tedadruz.Visible = false;
			this.txt_tedadruz.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_search.AcceptEnter = true;
			this.txt_search.AllowEdit = true;
			this.txt_search.AllowNew = true;
			this.txt_search.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_search.FocusColor = true;
			this.txt_search.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_CF7_0 = this.txt_search;
			location = new global::System.Drawing.Point(859, 92);
			arg_CF7_0.Location = location;
			this.txt_search.Name = "txt_search";
			this.txt_search.Nullable = true;
			this.txt_search.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_search.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_D50_0 = this.txt_search;
			size = new global::System.Drawing.Size(166, 36);
			arg_D50_0.Size = size;
			this.txt_search.TabIndex = 4;
			this.txt_search.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari.AcceptEnter = true;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = false;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "عنوان";
			column.Name = "Name";
			column.Size = 100;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column
			});
			global::System.Windows.Forms.Control arg_E91_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(530, 50);
			arg_E91_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = true;
			this.txt_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_F1B_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(180, 36);
			arg_F1B_0.Size = size;
			this.txt_moshtari.TabIndex = 3;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiComboBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiComboBox1.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.UiComboBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem.FormatStyle.Alpha = 0;
			uIComboBoxItem.IsSeparator = false;
			uIComboBoxItem.Text = "مانده از تاریخ";
			uIComboBoxItem.Value = "0";
			uIComboBoxItem2.FormatStyle.Alpha = 0;
			uIComboBoxItem2.IsSeparator = false;
			uIComboBoxItem2.Text = "بدهکاری";
			uIComboBoxItem2.Value = "1";
			uIComboBoxItem3.FormatStyle.Alpha = 0;
			uIComboBoxItem3.IsSeparator = false;
			uIComboBoxItem3.Text = "نام مشتری";
			uIComboBoxItem3.Value = "3";
			this.UiComboBox1.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem,
				uIComboBoxItem2,
				uIComboBoxItem3
			});
			global::System.Windows.Forms.Control arg_1078_0 = this.UiComboBox1;
			location = new global::System.Drawing.Point(859, 50);
			arg_1078_0.Location = location;
			this.UiComboBox1.Name = "UiComboBox1";
			global::System.Windows.Forms.Control arg_10A6_0 = this.UiComboBox1;
			size = new global::System.Drawing.Size(166, 36);
			arg_10A6_0.Size = size;
			this.UiComboBox1.TabIndex = 2;
			this.UiComboBox1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1128_0 = this.Label4;
			location = new global::System.Drawing.Point(74, 59);
			arg_1128_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1156_0 = this.Label4;
			size = new global::System.Drawing.Size(140, 19);
			arg_1156_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "تعداد روزهای دیرکرد";
			this.Label4.Visible = false;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11EC_0 = this.Label5;
			location = new global::System.Drawing.Point(427, 59);
			arg_11EC_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_1217_0 = this.Label5;
			size = new global::System.Drawing.Size(87, 19);
			arg_1217_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "نوع مشتری";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12A0_0 = this.Label2;
			location = new global::System.Drawing.Point(713, 59);
			arg_12A0_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_12CB_0 = this.Label2;
			size = new global::System.Drawing.Size(127, 19);
			arg_12CB_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "شهر / شهرستان";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1354_0 = this.Label3;
			location = new global::System.Drawing.Point(1028, 101);
			arg_1354_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_137F_0 = this.Label3;
			size = new global::System.Drawing.Size(61, 19);
			arg_137F_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "جستجو";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1408_0 = this.Label1;
			location = new global::System.Drawing.Point(1028, 59);
			arg_1408_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_1436_0 = this.Label1;
			size = new global::System.Drawing.Size(154, 19);
			arg_1436_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "مرتب سازی بر اساس";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem3,
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem5,
				this.ButtonItem4,
				this.ButtonItem6,
				this.ButtonItem8,
				this.ButtonItem7
			});
			global::DevComponents.DotNetBar.Bar arg_1517_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_1517_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_1545_0 = this.Bar1;
			size = new global::System.Drawing.Size(1189, 41);
			arg_1545_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 25;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "صورتحساب (F3)";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "چاپ (F4)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.filter_delete;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "پاک کردن فیلتر (F5)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.list_add;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "افزودن به لیست سوخته ها";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.list_error;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "لیست سوخته ها";
			this.ButtonItem6.AutoCheckOnClick = true;
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.check1;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "احتساب چک های وصول نشده";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem8.Image = global::FruitBox.My.Resources.Resources.document_attach;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "PDF";
			this.Timer1.Enabled = true;
			this.Timer1.Interval = 1000;
			this.UiProgressBar1.BorderStyle = global::Janus.Windows.UI.BorderStyle.None;
			this.UiProgressBar1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			global::System.Windows.Forms.Control arg_17AC_0 = this.UiProgressBar1;
			location = new global::System.Drawing.Point(0, 521);
			arg_17AC_0.Location = location;
			this.UiProgressBar1.Name = "UiProgressBar1";
			this.UiProgressBar1.ShowPercentage = true;
			global::System.Windows.Forms.Control arg_17E7_0 = this.UiProgressBar1;
			size = new global::System.Drawing.Size(1189, 23);
			arg_17E7_0.Size = size;
			this.UiProgressBar1.TabIndex = 26;
			this.UiProgressBar1.Visible = false;
			this.UiProgressBar1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "excel";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1189, 544);
			this.ClientSize = size;
			this.Controls.Add(this.UiProgressBar1);
			this.Controls.Add(this.Bar1);
			this.Controls.Add(this.GridEX1);
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_rpt_bedehkaran";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "صورتحساب بدهکاران";
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04001081 RID: 4225
		private global::System.ComponentModel.IContainer components;
	}
}
