namespace FruitBox
{
	// Token: 0x02000028 RID: 40
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Sud : global::System.Windows.Forms.Form
	{
		// Token: 0x06000242 RID: 578 RVA: 0x0002F1DC File Offset: 0x0002D3DC
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000243 RID: 579 RVA: 0x0002F22C File Offset: 0x0002D42C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Sud));
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.chk_sukhte = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_jam_kol = new global::FruitBox.CurrencyBox(this.components);
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.txt_sud = new global::FruitBox.CurrencyBox(this.components);
			this.txt_barzamin = new global::FruitBox.CurrencyBox(this.components);
			this.txt_sukhte = new global::FruitBox.CurrencyBox(this.components);
			this.txt_hazine = new global::FruitBox.CurrencyBox(this.components);
			this.txt_kasrezafe = new global::FruitBox.CurrencyBox(this.components);
			this.txt_daramad = new global::FruitBox.CurrencyBox(this.components);
			this.txt_ta_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_az_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_num = new global::FruitBox.NavBox();
			this.Bar3 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Bar2 = new global::DevComponents.DotNetBar.Bar();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar2).BeginInit();
			this.SuspendLayout();
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2
			});
			global::DevComponents.DotNetBar.Bar arg_323_0 = this.Bar1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_323_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_351_0 = this.Bar1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(589, 41);
			arg_351_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 16;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_3E3_0 = this.Label1;
			location = new global::System.Drawing.Point(1030, 157);
			arg_3E3_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_40E_0 = this.Label1;
			size = new global::System.Drawing.Size(65, 16);
			arg_40E_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "جمع درآمد";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_478_0 = this.Label2;
			location = new global::System.Drawing.Point(1030, 242);
			arg_478_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_4A3_0 = this.Label2;
			size = new global::System.Drawing.Size(76, 16);
			arg_4A3_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "- جمع هزینه";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_50D_0 = this.Label3;
			location = new global::System.Drawing.Point(1030, 368);
			arg_50D_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_538_0 = this.Label3;
			size = new global::System.Drawing.Size(33, 16);
			arg_538_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "سود";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "چاپ (F4)";
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.chk_sukhte);
			this.UiGroupBox1.Controls.Add(this.txt_jam_kol);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.txt_sud);
			this.UiGroupBox1.Controls.Add(this.txt_barzamin);
			this.UiGroupBox1.Controls.Add(this.txt_sukhte);
			this.UiGroupBox1.Controls.Add(this.txt_hazine);
			this.UiGroupBox1.Controls.Add(this.txt_kasrezafe);
			this.UiGroupBox1.Controls.Add(this.txt_daramad);
			this.UiGroupBox1.Controls.Add(this.txt_ta_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_az_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.Bar3);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_7E6_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_7E6_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_817_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(1145, 774);
			arg_817_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.chk_sukhte.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.chk_sukhte.BackColor = global::System.Drawing.Color.Transparent;
			this.chk_sukhte.Checked = true;
			this.chk_sukhte.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.chk_sukhte.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_8AC_0 = this.chk_sukhte;
			location = new global::System.Drawing.Point(663, 150);
			arg_8AC_0.Location = location;
			this.chk_sukhte.Name = "chk_sukhte";
			global::System.Windows.Forms.Control arg_8DA_0 = this.chk_sukhte;
			size = new global::System.Drawing.Size(149, 23);
			arg_8DA_0.Size = size;
			this.chk_sukhte.TabIndex = 30;
			this.chk_sukhte.TabStop = false;
			this.chk_sukhte.Text = "محاسبه سوخته ها";
			this.txt_jam_kol.AcceptEnter = false;
			this.txt_jam_kol.AllowEdit = true;
			this.txt_jam_kol.AllowNew = true;
			this.txt_jam_kol.AllowZero = true;
			this.txt_jam_kol.FocusColor = false;
			global::System.Windows.Forms.Control arg_967_0 = this.txt_jam_kol;
			location = new global::System.Drawing.Point(629, 314);
			arg_967_0.Location = location;
			this.txt_jam_kol.Name = "txt_jam_kol";
			this.txt_jam_kol.Nullable = true;
			this.txt_jam_kol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jam_kol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_9BD_0 = this.txt_jam_kol;
			size = new global::System.Drawing.Size(100, 23);
			arg_9BD_0.Size = size;
			this.txt_jam_kol.TabIndex = 25;
			this.txt_jam_kol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_jam_kol.Value = value;
			this.txt_jam_kol.Visible = false;
			this.txt_jam_kol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			global::System.Windows.Forms.Control arg_A6F_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(12, 146);
			arg_A6F_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_A9D_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(380, 120);
			arg_A9D_0.Size = size;
			this.UiGroupBox2.TabIndex = 24;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B20_0 = this.Label5;
			location = new global::System.Drawing.Point(39, 84);
			arg_B20_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_B4E_0 = this.Label5;
			size = new global::System.Drawing.Size(335, 28);
			arg_B4E_0.Size = size;
			this.Label5.TabIndex = 1;
			this.Label5.Text = "از طریق تعریف شرکا اقدام به ثبت درصدها بفرمائید";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_BD7_0 = this.Label4;
			location = new global::System.Drawing.Point(171, 42);
			arg_BD7_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_C05_0 = this.Label4;
			size = new global::System.Drawing.Size(203, 28);
			arg_C05_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "جمع درصد شرکا 100 نمیباشد";
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.Image = global::FruitBox.My.Resources.Resources.onebit_36;
			global::System.Windows.Forms.Control arg_C6D_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(18, 20);
			arg_C6D_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_C98_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(48, 48);
			arg_C98_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.PictureBox1.TabIndex = 0;
			this.PictureBox1.TabStop = false;
			this.txt_sud.AcceptEnter = true;
			this.txt_sud.AllowEdit = false;
			this.txt_sud.AllowNew = true;
			this.txt_sud.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sud.FocusColor = true;
			this.txt_sud.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D43_0 = this.txt_sud;
			location = new global::System.Drawing.Point(820, 356);
			arg_D43_0.Location = location;
			this.txt_sud.Name = "txt_sud";
			this.txt_sud.Nullable = true;
			this.txt_sud.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sud.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_D9C_0 = this.txt_sud;
			size = new global::System.Drawing.Size(208, 36);
			arg_D9C_0.Size = size;
			this.txt_sud.TabIndex = 23;
			this.txt_sud.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sud.Value = value;
			this.txt_sud.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_barzamin.AcceptEnter = true;
			this.txt_barzamin.AllowEdit = false;
			this.txt_barzamin.AllowNew = true;
			this.txt_barzamin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_barzamin.FocusColor = true;
			this.txt_barzamin.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E56_0 = this.txt_barzamin;
			location = new global::System.Drawing.Point(820, 272);
			arg_E56_0.Location = location;
			this.txt_barzamin.Name = "txt_barzamin";
			this.txt_barzamin.Nullable = true;
			this.txt_barzamin.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_barzamin.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_EAF_0 = this.txt_barzamin;
			size = new global::System.Drawing.Size(208, 36);
			arg_EAF_0.Size = size;
			this.txt_barzamin.TabIndex = 23;
			this.txt_barzamin.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_barzamin.Value = value;
			this.txt_barzamin.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sukhte.AcceptEnter = true;
			this.txt_sukhte.AllowEdit = false;
			this.txt_sukhte.AllowNew = true;
			this.txt_sukhte.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sukhte.FocusColor = true;
			this.txt_sukhte.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F69_0 = this.txt_sukhte;
			location = new global::System.Drawing.Point(820, 314);
			arg_F69_0.Location = location;
			this.txt_sukhte.Name = "txt_sukhte";
			this.txt_sukhte.Nullable = true;
			this.txt_sukhte.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sukhte.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_FC2_0 = this.txt_sukhte;
			size = new global::System.Drawing.Size(208, 36);
			arg_FC2_0.Size = size;
			this.txt_sukhte.TabIndex = 23;
			this.txt_sukhte.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sukhte.Value = value;
			this.txt_sukhte.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hazine.AcceptEnter = true;
			this.txt_hazine.AllowEdit = false;
			this.txt_hazine.AllowNew = true;
			this.txt_hazine.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_hazine.FocusColor = true;
			this.txt_hazine.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_107C_0 = this.txt_hazine;
			location = new global::System.Drawing.Point(820, 230);
			arg_107C_0.Location = location;
			this.txt_hazine.Name = "txt_hazine";
			this.txt_hazine.Nullable = true;
			this.txt_hazine.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hazine.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_10D5_0 = this.txt_hazine;
			size = new global::System.Drawing.Size(208, 36);
			arg_10D5_0.Size = size;
			this.txt_hazine.TabIndex = 23;
			this.txt_hazine.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hazine.Value = value;
			this.txt_hazine.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kasrezafe.AcceptEnter = true;
			this.txt_kasrezafe.AllowEdit = false;
			this.txt_kasrezafe.AllowNew = true;
			this.txt_kasrezafe.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kasrezafe.FocusColor = true;
			this.txt_kasrezafe.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_118F_0 = this.txt_kasrezafe;
			location = new global::System.Drawing.Point(820, 188);
			arg_118F_0.Location = location;
			this.txt_kasrezafe.Name = "txt_kasrezafe";
			this.txt_kasrezafe.Nullable = true;
			this.txt_kasrezafe.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kasrezafe.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_11E8_0 = this.txt_kasrezafe;
			size = new global::System.Drawing.Size(208, 36);
			arg_11E8_0.Size = size;
			this.txt_kasrezafe.TabIndex = 23;
			this.txt_kasrezafe.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kasrezafe.Value = value;
			this.txt_kasrezafe.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_daramad.AcceptEnter = true;
			this.txt_daramad.AllowEdit = false;
			this.txt_daramad.AllowNew = true;
			this.txt_daramad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_daramad.FocusColor = true;
			this.txt_daramad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12A2_0 = this.txt_daramad;
			location = new global::System.Drawing.Point(820, 146);
			arg_12A2_0.Location = location;
			this.txt_daramad.Name = "txt_daramad";
			this.txt_daramad.Nullable = true;
			this.txt_daramad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_daramad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_12FB_0 = this.txt_daramad;
			size = new global::System.Drawing.Size(208, 36);
			arg_12FB_0.Size = size;
			this.txt_daramad.TabIndex = 23;
			this.txt_daramad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_daramad.Value = value;
			this.txt_daramad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_ta_tarikh.AcceptEnter = true;
			this.txt_ta_tarikh.AllowEdit = false;
			this.txt_ta_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ta_tarikh.ButtonEnable = false;
			this.txt_ta_tarikh.FocusDatePart = 2;
			this.txt_ta_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_13B2_0 = this.txt_ta_tarikh;
			location = new global::System.Drawing.Point(913, 104);
			arg_13B2_0.Location = location;
			this.txt_ta_tarikh.Mask = "0000/00/00";
			this.txt_ta_tarikh.Name = "txt_ta_tarikh";
			this.txt_ta_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_13FB_0 = this.txt_ta_tarikh;
			size = new global::System.Drawing.Size(115, 36);
			arg_13FB_0.Size = size;
			this.txt_ta_tarikh.TabIndex = 22;
			this.txt_ta_tarikh.Text = "1392/10/02";
			this.txt_ta_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_az_tarikh.AcceptEnter = true;
			this.txt_az_tarikh.AllowEdit = false;
			this.txt_az_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_az_tarikh.ButtonEnable = false;
			this.txt_az_tarikh.Enabled = false;
			this.txt_az_tarikh.FocusDatePart = 2;
			this.txt_az_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_14B5_0 = this.txt_az_tarikh;
			location = new global::System.Drawing.Point(614, 61);
			arg_14B5_0.Location = location;
			this.txt_az_tarikh.Mask = "0000/00/00";
			this.txt_az_tarikh.Name = "txt_az_tarikh";
			this.txt_az_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_14FE_0 = this.txt_az_tarikh;
			size = new global::System.Drawing.Size(115, 36);
			arg_14FE_0.Size = size;
			this.txt_az_tarikh.TabIndex = 22;
			this.txt_az_tarikh.Text = "1392/10/02";
			this.txt_az_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1588_0 = this.txt_num;
			location = new global::System.Drawing.Point(826, 61);
			arg_1588_0.Location = location;
			global::System.Windows.Forms.Control arg_15A2_0 = this.txt_num;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			arg_15A2_0.Margin = margin;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_15D0_0 = this.txt_num;
			size = new global::System.Drawing.Size(200, 36);
			arg_15D0_0.Size = size;
			this.txt_num.TabIndex = 21;
			this.txt_num.Value = "";
			this.Bar3.AntiAlias = true;
			this.Bar3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar3.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar3.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar3.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem3,
				this.ButtonItem4,
				this.ButtonItem5
			});
			global::DevComponents.DotNetBar.Bar arg_1683_0 = this.Bar3;
			location = new global::System.Drawing.Point(0, 0);
			arg_1683_0.Location = location;
			this.Bar3.Name = "Bar3";
			global::DevComponents.DotNetBar.Bar arg_16B1_0 = this.Bar3;
			size = new global::System.Drawing.Size(1145, 41);
			arg_16B1_0.Size = size;
			this.Bar3.Stretch = true;
			this.Bar3.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar3.TabIndex = 20;
			this.Bar3.TabStop = false;
			this.Bar3.Text = "Bar3";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "ثبت (F2)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.customer_coins;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "تعریف شرکا";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "حذف (F5)";
			this.GridEX1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1869_0 = this.GridEX1;
			location = new global::System.Drawing.Point(0, 398);
			arg_1869_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_18C1_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1145, 376);
			arg_18C1_0.Size = size;
			this.GridEX1.TabIndex = 19;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1980_0 = this.Label7;
			location = new global::System.Drawing.Point(1031, 200);
			arg_1980_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_19AB_0 = this.Label7;
			size = new global::System.Drawing.Size(95, 16);
			arg_19AB_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "- کسری صندوق";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1A15_0 = this.Label8;
			location = new global::System.Drawing.Point(1033, 284);
			arg_1A15_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_1A40_0 = this.Label8;
			size = new global::System.Drawing.Size(86, 16);
			arg_1A40_0.Size = size;
			this.Label8.TabIndex = 0;
			this.Label8.Text = "- بار روی زمین";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1AAA_0 = this.Label6;
			location = new global::System.Drawing.Point(1034, 326);
			arg_1AAA_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_1AD5_0 = this.Label6;
			size = new global::System.Drawing.Size(103, 16);
			arg_1AD5_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "- جمع سوخته ها";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1B3C_0 = this.Label11;
			location = new global::System.Drawing.Point(1031, 115);
			arg_1B3C_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1B67_0 = this.Label11;
			size = new global::System.Drawing.Size(95, 16);
			arg_1B67_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "محاسبه تا تاریخ";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1BCE_0 = this.Label10;
			location = new global::System.Drawing.Point(732, 72);
			arg_1BCE_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_1BF9_0 = this.Label10;
			size = new global::System.Drawing.Size(83, 16);
			arg_1BF9_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "تاریخ محاسبه";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1C60_0 = this.Label9;
			location = new global::System.Drawing.Point(1030, 70);
			arg_1C60_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_1C8B_0 = this.Label9;
			size = new global::System.Drawing.Size(44, 16);
			arg_1C8B_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "شماره";
			this.Bar2.AntiAlias = true;
			this.Bar2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar2.DockSide = global::DevComponents.DotNetBar.eDockSide.Top;
			this.Bar2.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar2.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1
			});
			global::DevComponents.DotNetBar.Bar arg_1D29_0 = this.Bar2;
			location = new global::System.Drawing.Point(0, 0);
			arg_1D29_0.Location = location;
			this.Bar2.Name = "Bar2";
			global::DevComponents.DotNetBar.Bar arg_1D57_0 = this.Bar2;
			size = new global::System.Drawing.Size(589, 41);
			arg_1D57_0.Size = size;
			this.Bar2.Stretch = true;
			this.Bar2.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar2.TabIndex = 15;
			this.Bar2.TabStop = false;
			this.Bar2.Text = "Bar2";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1145, 774);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Sud";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "محاسبه درآمد";
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar2).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040000E6 RID: 230
		private global::System.ComponentModel.IContainer components;
	}
}
