namespace FruitBox
{
	// Token: 0x020000C7 RID: 199
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Daramad_avaldore : global::System.Windows.Forms.Form
	{
		// Token: 0x06001065 RID: 4197 RVA: 0x000B4AD0 File Offset: 0x000B2CD0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001066 RID: 4198 RVA: 0x000B4B20 File Offset: 0x000B2D20
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Daramad_avaldore));
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_ezafi = new global::FruitBox.CurrencyBox(this.components);
			this.txt_kasri = new global::FruitBox.CurrencyBox(this.components);
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txt_takhlie = new global::FruitBox.CurrencyBox(this.components);
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txt_sandugh = new global::FruitBox.CurrencyBox(this.components);
			this.Label4 = new global::System.Windows.Forms.Label();
			this.txt_hazine = new global::FruitBox.CurrencyBox(this.components);
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txt_daramad = new global::FruitBox.CurrencyBox(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_ezafi);
			this.UiGroupBox1.Controls.Add(this.txt_kasri);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.txt_takhlie);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.txt_sandugh);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.txt_hazine);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.txt_daramad);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_26C_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 41);
			arg_26C_0.Location = location;
			global::System.Windows.Forms.Control arg_286_0 = this.UiGroupBox1;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			arg_286_0.Margin = margin;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_2C4_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(782, 472);
			arg_2C4_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_ezafi.AcceptEnter = true;
			this.txt_ezafi.AllowEdit = true;
			this.txt_ezafi.AllowNew = true;
			this.txt_ezafi.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ezafi.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_ezafi.ButtonImage");
			this.txt_ezafi.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_ezafi.FocusColor = true;
			global::System.Windows.Forms.Control arg_368_0 = this.txt_ezafi;
			location = new global::System.Drawing.Point(394, 231);
			arg_368_0.Location = location;
			this.txt_ezafi.Name = "txt_ezafi";
			this.txt_ezafi.Nullable = true;
			this.txt_ezafi.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_ezafi.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3C1_0 = this.txt_ezafi;
			size = new global::System.Drawing.Size(217, 36);
			arg_3C1_0.Size = size;
			this.txt_ezafi.TabIndex = 1;
			this.txt_ezafi.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_ezafi.Value = value;
			this.txt_ezafi.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kasri.AcceptEnter = true;
			this.txt_kasri.AllowEdit = true;
			this.txt_kasri.AllowNew = true;
			this.txt_kasri.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kasri.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_kasri.ButtonImage");
			this.txt_kasri.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_kasri.FocusColor = true;
			global::System.Windows.Forms.Control arg_480_0 = this.txt_kasri;
			location = new global::System.Drawing.Point(394, 189);
			arg_480_0.Location = location;
			this.txt_kasri.Name = "txt_kasri";
			this.txt_kasri.Nullable = true;
			this.txt_kasri.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kasri.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_4D9_0 = this.txt_kasri;
			size = new global::System.Drawing.Size(217, 36);
			arg_4D9_0.Size = size;
			this.txt_kasri.TabIndex = 1;
			this.txt_kasri.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kasri.Value = value;
			this.txt_kasri.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label6.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_58C_0 = this.Label6;
			location = new global::System.Drawing.Point(613, 243);
			arg_58C_0.Location = location;
			global::System.Windows.Forms.Control arg_5A6_0 = this.Label6;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_5A6_0.Margin = margin;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_5D4_0 = this.Label6;
			size = new global::System.Drawing.Size(154, 19);
			arg_5D4_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "الباقی اضافی صندوق";
			this.txt_takhlie.AcceptEnter = true;
			this.txt_takhlie.AllowEdit = true;
			this.txt_takhlie.AllowNew = true;
			this.txt_takhlie.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_takhlie.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_takhlie.ButtonImage");
			this.txt_takhlie.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_takhlie.FocusColor = true;
			global::System.Windows.Forms.Control arg_67C_0 = this.txt_takhlie;
			location = new global::System.Drawing.Point(394, 147);
			arg_67C_0.Location = location;
			this.txt_takhlie.Name = "txt_takhlie";
			this.txt_takhlie.Nullable = true;
			this.txt_takhlie.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_takhlie.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_6D5_0 = this.txt_takhlie;
			size = new global::System.Drawing.Size(217, 36);
			arg_6D5_0.Size = size;
			this.txt_takhlie.TabIndex = 1;
			this.txt_takhlie.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_takhlie.Value = value;
			this.txt_takhlie.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label5.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_788_0 = this.Label5;
			location = new global::System.Drawing.Point(613, 201);
			arg_788_0.Location = location;
			global::System.Windows.Forms.Control arg_7A2_0 = this.Label5;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_7A2_0.Margin = margin;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_7D0_0 = this.Label5;
			size = new global::System.Drawing.Size(156, 19);
			arg_7D0_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "الباقی کسری صندوق";
			this.txt_sandugh.AcceptEnter = true;
			this.txt_sandugh.AllowEdit = true;
			this.txt_sandugh.AllowNew = true;
			this.txt_sandugh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sandugh.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_sandugh.ButtonImage");
			this.txt_sandugh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_sandugh.FocusColor = true;
			global::System.Windows.Forms.Control arg_875_0 = this.txt_sandugh;
			location = new global::System.Drawing.Point(394, 105);
			arg_875_0.Location = location;
			this.txt_sandugh.Name = "txt_sandugh";
			this.txt_sandugh.Nullable = true;
			this.txt_sandugh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sandugh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_8CE_0 = this.txt_sandugh;
			size = new global::System.Drawing.Size(217, 36);
			arg_8CE_0.Size = size;
			this.txt_sandugh.TabIndex = 1;
			this.txt_sandugh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sandugh.Value = value;
			this.txt_sandugh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label4.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_981_0 = this.Label4;
			location = new global::System.Drawing.Point(613, 159);
			arg_981_0.Location = location;
			global::System.Windows.Forms.Control arg_99B_0 = this.Label4;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_99B_0.Margin = margin;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_9C6_0 = this.Label4;
			size = new global::System.Drawing.Size(93, 19);
			arg_9C6_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "الباقی تخلیه";
			this.txt_hazine.AcceptEnter = true;
			this.txt_hazine.AllowEdit = true;
			this.txt_hazine.AllowNew = true;
			this.txt_hazine.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_hazine.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_hazine.ButtonImage");
			this.txt_hazine.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_hazine.FocusColor = true;
			global::System.Windows.Forms.Control arg_A6B_0 = this.txt_hazine;
			location = new global::System.Drawing.Point(394, 63);
			arg_A6B_0.Location = location;
			this.txt_hazine.Name = "txt_hazine";
			this.txt_hazine.Nullable = true;
			this.txt_hazine.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hazine.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_AC4_0 = this.txt_hazine;
			size = new global::System.Drawing.Size(217, 36);
			arg_AC4_0.Size = size;
			this.txt_hazine.TabIndex = 1;
			this.txt_hazine.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hazine.Value = value;
			this.txt_hazine.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label3.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_B74_0 = this.Label3;
			location = new global::System.Drawing.Point(613, 117);
			arg_B74_0.Location = location;
			global::System.Windows.Forms.Control arg_B8E_0 = this.Label3;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_B8E_0.Margin = margin;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_BB9_0 = this.Label3;
			size = new global::System.Drawing.Size(105, 19);
			arg_BB9_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "الباقی صندوق";
			this.txt_daramad.AcceptEnter = true;
			this.txt_daramad.AllowEdit = true;
			this.txt_daramad.AllowNew = true;
			this.txt_daramad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_daramad.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_daramad.ButtonImage");
			this.txt_daramad.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_daramad.FocusColor = true;
			global::System.Windows.Forms.Control arg_C5E_0 = this.txt_daramad;
			location = new global::System.Drawing.Point(394, 21);
			arg_C5E_0.Location = location;
			this.txt_daramad.Name = "txt_daramad";
			this.txt_daramad.Nullable = true;
			this.txt_daramad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_daramad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_CB7_0 = this.txt_daramad;
			size = new global::System.Drawing.Size(217, 36);
			arg_CB7_0.Size = size;
			this.txt_daramad.TabIndex = 0;
			this.txt_daramad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_daramad.Value = value;
			this.txt_daramad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label2.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_D67_0 = this.Label2;
			location = new global::System.Drawing.Point(613, 75);
			arg_D67_0.Location = location;
			global::System.Windows.Forms.Control arg_D81_0 = this.Label2;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_D81_0.Margin = margin;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_DAC_0 = this.Label2;
			size = new global::System.Drawing.Size(94, 19);
			arg_DAC_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "الباقی هزینه";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label1.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_E45_0 = this.Label1;
			location = new global::System.Drawing.Point(613, 32);
			arg_E45_0.Location = location;
			global::System.Windows.Forms.Control arg_E5F_0 = this.Label1;
			margin = new global::System.Windows.Forms.Padding(5, 0, 5, 0);
			arg_E5F_0.Margin = margin;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_E8A_0 = this.Label1;
			size = new global::System.Drawing.Size(91, 19);
			arg_E8A_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "الباقی درآمد";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2
			});
			global::DevComponents.DotNetBar.Bar arg_F1D_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_F1D_0.Location = location;
			global::System.Windows.Forms.Control arg_F37_0 = this.Bar1;
			margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			arg_F37_0.Margin = margin;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_F65_0 = this.Bar1;
			size = new global::System.Drawing.Size(782, 41);
			arg_F65_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 15;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(10f, 28f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(782, 513);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.Bar1);
			this.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Daramad_avaldore";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "ثبت الباقی حساب ها";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x0400063E RID: 1598
		private global::System.ComponentModel.IContainer components;
	}
}
