namespace FruitBox
{
	// Token: 0x02000076 RID: 118
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Register2 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000971 RID: 2417 RVA: 0x0007E264 File Offset: 0x0007C464
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000972 RID: 2418 RVA: 0x0007E2B4 File Offset: 0x0007C4B4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.txt_days0 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txt_code = new global::Janus.Windows.GridEX.EditControls.EditBox();
			this.txt_precode = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.UiButton3 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txt_owner = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txt_days = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txt_installdate = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_1DA_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_1DA_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_20A_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(685, 688);
			arg_20A_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.Label8);
			this.UiGroupBox2.Controls.Add(this.Label10);
			this.UiGroupBox2.Controls.Add(this.txt_days0);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.Label1);
			this.UiGroupBox2.Controls.Add(this.txt_code);
			this.UiGroupBox2.Controls.Add(this.txt_precode);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			this.UiGroupBox2.Controls.Add(this.UiButton3);
			this.UiGroupBox2.Controls.Add(this.UiButton2);
			this.UiGroupBox2.Controls.Add(this.UiButton1);
			this.UiGroupBox2.Controls.Add(this.Label6);
			this.UiGroupBox2.Controls.Add(this.txt_owner);
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.Label3);
			this.UiGroupBox2.Controls.Add(this.txt_days);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.txt_installdate);
			this.UiGroupBox2.Controls.Add(this.Label9);
			global::System.Windows.Forms.Control arg_415_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(12, 3);
			arg_415_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_445_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(661, 681);
			arg_445_0.Size = size;
			this.UiGroupBox2.TabIndex = 1;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_4BE_0 = this.Label8;
			location = new global::System.Drawing.Point(372, 591);
			arg_4BE_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_4EB_0 = this.Label8;
			size = new global::System.Drawing.Size(147, 19);
			arg_4EB_0.Size = size;
			this.Label8.TabIndex = 6;
			this.Label8.Text = "www.tazminco.ir";
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_568_0 = this.Label10;
			location = new global::System.Drawing.Point(525, 588);
			arg_568_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_592_0 = this.Label10;
			size = new global::System.Drawing.Size(118, 28);
			arg_592_0.Size = size;
			this.Label10.TabIndex = 7;
			this.Label10.Text = "آدرس وب سایت";
			this.txt_days0.AutoSize = true;
			this.txt_days0.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_days0.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_60F_0 = this.txt_days0;
			location = new global::System.Drawing.Point(395, 367);
			arg_60F_0.Location = location;
			this.txt_days0.Name = "txt_days0";
			global::System.Windows.Forms.Control arg_63C_0 = this.txt_days0;
			size = new global::System.Drawing.Size(215, 28);
			arg_63C_0.Size = size;
			this.txt_days0.TabIndex = 0;
			this.txt_days0.Text = "روز مانده تا اتمام اشتراک سالانه";
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_6B9_0 = this.Label2;
			location = new global::System.Drawing.Point(550, 497);
			arg_6B9_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_6E3_0 = this.Label2;
			size = new global::System.Drawing.Size(89, 28);
			arg_6E3_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "شماره کارت";
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label1.Font = new global::System.Drawing.Font("Courier New", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_760_0 = this.Label1;
			location = new global::System.Drawing.Point(240, 495);
			arg_760_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_78D_0 = this.Label1;
			size = new global::System.Drawing.Size(405, 44);
			arg_78D_0.Size = size;
			this.Label1.TabIndex = 5;
			this.Label1.Text = "6362 1411 0457 6815";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txt_code.Font = new global::System.Drawing.Font("Courier New", 18f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_7F4_0 = this.txt_code;
			location = new global::System.Drawing.Point(240, 542);
			arg_7F4_0.Location = location;
			this.txt_code.Name = "txt_code";
			global::System.Windows.Forms.Control arg_821_0 = this.txt_code;
			size = new global::System.Drawing.Size(405, 35);
			arg_821_0.Size = size;
			this.txt_code.TabIndex = 0;
			this.txt_code.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_precode.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_precode.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.txt_precode.Font = new global::System.Drawing.Font("Courier New", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_897_0 = this.txt_precode;
			location = new global::System.Drawing.Point(16, 542);
			arg_897_0.Location = location;
			this.txt_precode.Name = "txt_precode";
			global::System.Windows.Forms.Control arg_8C4_0 = this.txt_precode;
			size = new global::System.Drawing.Size(218, 35);
			arg_8C4_0.Size = size;
			this.txt_precode.TabIndex = 4;
			this.txt_precode.Text = "0-1395/02/23";
			this.txt_precode.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.Image = global::FruitBox.My.Resources.Resources._1_Shopping;
			global::System.Windows.Forms.Control arg_92E_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(240, 23);
			arg_92E_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_95E_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(192, 192);
			arg_95E_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.PictureBox1.TabIndex = 2;
			this.PictureBox1.TabStop = false;
			this.UiButton3.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9C6_0 = this.UiButton3;
			location = new global::System.Drawing.Point(348, 619);
			arg_9C6_0.Location = location;
			this.UiButton3.Name = "UiButton3";
			this.UiButton3.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton3.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_A11_0 = this.UiButton3;
			size = new global::System.Drawing.Size(154, 48);
			arg_A11_0.Size = size;
			this.UiButton3.TabIndex = 1;
			this.UiButton3.Text = "فعلا ثبت نمی کنم";
			this.UiButton3.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiButton2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A7D_0 = this.UiButton2;
			location = new global::System.Drawing.Point(242, 619);
			arg_A7D_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			this.UiButton2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_AC5_0 = this.UiButton2;
			size = new global::System.Drawing.Size(99, 48);
			arg_AC5_0.Size = size;
			this.UiButton2.TabIndex = 1;
			this.UiButton2.Text = "خروج";
			this.UiButton2.Visible = false;
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiButton1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B3E_0 = this.UiButton1;
			location = new global::System.Drawing.Point(508, 619);
			arg_B3E_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			this.UiButton1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton1.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_B89_0 = this.UiButton1;
			size = new global::System.Drawing.Size(139, 48);
			arg_B89_0.Size = size;
			this.UiButton1.TabIndex = 2;
			this.UiButton1.Text = "ثبت کد اشتراک";
			this.UiButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C10_0 = this.Label6;
			location = new global::System.Drawing.Point(40, 343);
			arg_C10_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_C3A_0 = this.Label6;
			size = new global::System.Drawing.Size(97, 19);
			arg_C3A_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "@tazminsoft";
			this.Label6.Visible = false;
			this.txt_owner.AutoSize = true;
			this.txt_owner.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_owner.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_CC4_0 = this.txt_owner;
			location = new global::System.Drawing.Point(269, 234);
			arg_CC4_0.Location = location;
			this.txt_owner.Name = "txt_owner";
			global::System.Windows.Forms.Control arg_CED_0 = this.txt_owner;
			size = new global::System.Drawing.Size(0, 28);
			arg_CED_0.Size = size;
			this.txt_owner.TabIndex = 0;
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D59_0 = this.Label5;
			location = new global::System.Drawing.Point(143, 340);
			arg_D59_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_D86_0 = this.Label5;
			size = new global::System.Drawing.Size(147, 28);
			arg_D86_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "کانال تلگرام نرم افزار";
			this.Label5.Visible = false;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E10_0 = this.Label4;
			location = new global::System.Drawing.Point(395, 467);
			arg_E10_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_E3D_0 = this.Label4;
			size = new global::System.Drawing.Size(249, 28);
			arg_E3D_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "تلفن بخش فروش : 09390244096";
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_EBA_0 = this.Label3;
			location = new global::System.Drawing.Point(198, 429);
			arg_EBA_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_EE7_0 = this.Label3;
			size = new global::System.Drawing.Size(446, 28);
			arg_EE7_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "جهت دریافت کد اشتراک سالانه با بخش فروش تماس حاصل فرمایید";
			this.txt_days.AutoSize = true;
			this.txt_days.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_days.Font = new global::System.Drawing.Font("Mitra", 20.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_days.ForeColor = global::System.Drawing.Color.ForestGreen;
			global::System.Windows.Forms.Control arg_F75_0 = this.txt_days;
			location = new global::System.Drawing.Point(599, 364);
			arg_F75_0.Location = location;
			this.txt_days.Name = "txt_days";
			this.txt_days.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_FAC_0 = this.txt_days;
			size = new global::System.Drawing.Size(45, 40);
			arg_FAC_0.Size = size;
			this.txt_days.TabIndex = 0;
			this.txt_days.Text = "15";
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1019_0 = this.Label7;
			location = new global::System.Drawing.Point(26, 249);
			arg_1019_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_1046_0 = this.Label7;
			size = new global::System.Drawing.Size(614, 119);
			arg_1046_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "با توجه به اینکه تمامی امور پشتیبانی و رفع مشکل و پاسخ دهی به مشکلات و همچنین ارائه نسخه های جدید کاملا رایگان میباشد لطفا با پرداخت اشتراک سالیانه ما را در این امر دلگرم فرمایید";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txt_installdate.AutoSize = true;
			this.txt_installdate.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_installdate.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10D1_0 = this.txt_installdate;
			location = new global::System.Drawing.Point(365, 395);
			arg_10D1_0.Location = location;
			this.txt_installdate.Name = "txt_installdate";
			this.txt_installdate.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_110B_0 = this.txt_installdate;
			size = new global::System.Drawing.Size(135, 28);
			arg_110B_0.Size = size;
			this.txt_installdate.TabIndex = 0;
			this.txt_installdate.Text = "تاریخ ثبت نرم افزار";
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1188_0 = this.Label9;
			location = new global::System.Drawing.Point(505, 395);
			arg_1188_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_11B5_0 = this.Label9;
			size = new global::System.Drawing.Size(135, 28);
			arg_11B5_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "تاریخ ثبت نرم افزار";
			this.Timer1.Enabled = true;
			this.Timer1.Interval = 1500;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(685, 688);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Register2";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040003B9 RID: 953
		private global::System.ComponentModel.IContainer components;
	}
}
