namespace FruitBox
{
	// Token: 0x0200007C RID: 124
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Setting : global::System.Windows.Forms.Form
	{
		// Token: 0x06000A71 RID: 2673 RVA: 0x00086A5C File Offset: 0x00084C5C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000A72 RID: 2674 RVA: 0x00086AAC File Offset: 0x00084CAC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem2 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem3 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem4 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem5 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem6 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem7 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem8 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem9 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem10 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem11 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem12 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem13 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem14 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_sarbarg = new global::Janus.Windows.EditControls.UIComboBox();
			this.txt_kargari_fee = new global::FruitBox.CurrencyBox(this.components);
			this.txt_kargari_kind = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txt_arz_kind = new global::Janus.Windows.EditControls.UIComboBox();
			this.txt_kharid_kind = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.txt_bank_hesab = new global::FruitBox.SelectItem(this.components);
			this.txt_nahve_furush = new global::Janus.Windows.EditControls.UIComboBox();
			this.txt_salmali = new global::FruitBox.EditBox(this.components);
			this.Label11 = new global::System.Windows.Forms.Label();
			this.txt_print_font_number = new global::FruitBox.EditBox(this.components);
			this.txt_gridfont = new global::FruitBox.EditBox(this.components);
			this.txt_font = new global::FruitBox.EditBox(this.components);
			this.DateBox21 = new global::FruitBox.DateBox2(this.components);
			this.txt_sarresid_pardakht = new global::FruitBox.NumericBox(this.components);
			this.txt_sarresid_daryaft = new global::FruitBox.NumericBox(this.components);
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.UiGroupBox5 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox4 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox3 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.EditBox1 = new global::Janus.Windows.GridEX.EditControls.EditBox();
			this.txt_oft = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_tasvie = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_no_bed_alert = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_kargari = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_show_avg = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox9 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox8 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox7 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox1 = new global::Janus.Windows.EditControls.UICheckBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.FontDialog1 = new global::System.Windows.Forms.FontDialog();
			this.UiGroupBox6 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_oft_kind = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox6).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_oft_kind);
			this.UiGroupBox1.Controls.Add(this.Label15);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox6);
			this.UiGroupBox1.Controls.Add(this.txt_sarbarg);
			this.UiGroupBox1.Controls.Add(this.txt_kargari_fee);
			this.UiGroupBox1.Controls.Add(this.txt_kargari_kind);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.txt_arz_kind);
			this.UiGroupBox1.Controls.Add(this.txt_kharid_kind);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label30);
			this.UiGroupBox1.Controls.Add(this.txt_bank_hesab);
			this.UiGroupBox1.Controls.Add(this.txt_nahve_furush);
			this.UiGroupBox1.Controls.Add(this.txt_salmali);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.txt_print_font_number);
			this.UiGroupBox1.Controls.Add(this.txt_gridfont);
			this.UiGroupBox1.Controls.Add(this.txt_font);
			this.UiGroupBox1.Controls.Add(this.DateBox21);
			this.UiGroupBox1.Controls.Add(this.txt_sarresid_pardakht);
			this.UiGroupBox1.Controls.Add(this.txt_sarresid_daryaft);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox5);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox4);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox3);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.EditBox1);
			this.UiGroupBox1.Controls.Add(this.txt_oft);
			this.UiGroupBox1.Controls.Add(this.txt_tasvie);
			this.UiGroupBox1.Controls.Add(this.txt_no_bed_alert);
			this.UiGroupBox1.Controls.Add(this.txt_kargari);
			this.UiGroupBox1.Controls.Add(this.txt_show_avg);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox9);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox8);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox7);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox1);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_81B_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_81B_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_84C_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1077, 662);
			arg_84C_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_sarbarg.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sarbarg.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_sarbarg.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem.FormatStyle.Alpha = 0;
			uIComboBoxItem.IsSeparator = false;
			uIComboBoxItem.Text = "خرید از یک نفر باشد";
			uIComboBoxItem.Value = "1";
			uIComboBoxItem2.FormatStyle.Alpha = 0;
			uIComboBoxItem2.IsSeparator = false;
			uIComboBoxItem2.Text = "خرید از چند نفر باشد";
			uIComboBoxItem2.Value = "2";
			this.txt_sarbarg.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem,
				uIComboBoxItem2
			});
			global::System.Windows.Forms.Control arg_94B_0 = this.txt_sarbarg;
			location = new global::System.Drawing.Point(29, 287);
			arg_94B_0.Location = location;
			this.txt_sarbarg.Name = "txt_sarbarg";
			global::System.Windows.Forms.Control arg_979_0 = this.txt_sarbarg;
			size = new global::System.Drawing.Size(277, 36);
			arg_979_0.Size = size;
			this.txt_sarbarg.TabIndex = 33;
			this.txt_sarbarg.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_kargari_fee.AcceptEnter = true;
			this.txt_kargari_fee.AllowEdit = true;
			this.txt_kargari_fee.AllowNew = true;
			this.txt_kargari_fee.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kargari_fee.FocusColor = true;
			this.txt_kargari_fee.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A18_0 = this.txt_kargari_fee;
			location = new global::System.Drawing.Point(801, 439);
			arg_A18_0.Location = location;
			this.txt_kargari_fee.Name = "txt_kargari_fee";
			this.txt_kargari_fee.Nullable = true;
			this.txt_kargari_fee.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kargari_fee.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_A71_0 = this.txt_kargari_fee;
			size = new global::System.Drawing.Size(146, 36);
			arg_A71_0.Size = size;
			this.txt_kargari_fee.TabIndex = 32;
			this.txt_kargari_fee.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_kargari_fee.Value = value;
			this.txt_kargari_fee.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kargari_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kargari_kind.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_kargari_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem3.FormatStyle.Alpha = 0;
			uIComboBoxItem3.IsSeparator = false;
			uIComboBoxItem3.Text = "بر حسب تعداد";
			uIComboBoxItem3.Value = "1";
			uIComboBoxItem4.FormatStyle.Alpha = 0;
			uIComboBoxItem4.IsSeparator = false;
			uIComboBoxItem4.Text = "بر حسب کیلو";
			uIComboBoxItem4.Value = "2";
			this.txt_kargari_kind.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem3,
				uIComboBoxItem4
			});
			global::System.Windows.Forms.Control arg_B8F_0 = this.txt_kargari_kind;
			location = new global::System.Drawing.Point(670, 404);
			arg_B8F_0.Location = location;
			this.txt_kargari_kind.Name = "txt_kargari_kind";
			global::System.Windows.Forms.Control arg_BBD_0 = this.txt_kargari_kind;
			size = new global::System.Drawing.Size(277, 36);
			arg_BBD_0.Size = size;
			this.txt_kargari_kind.TabIndex = 30;
			this.txt_kargari_kind.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_C24_0 = this.Label8;
			location = new global::System.Drawing.Point(949, 450);
			arg_C24_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_C4F_0 = this.Label8;
			size = new global::System.Drawing.Size(106, 16);
			arg_C4F_0.Size = size;
			this.Label8.TabIndex = 29;
			this.Label8.Text = "نرخ هرکیلو کارگری";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_CBA_0 = this.Label7;
			location = new global::System.Drawing.Point(949, 416);
			arg_CBA_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_CE5_0 = this.Label7;
			size = new global::System.Drawing.Size(123, 16);
			arg_CE5_0.Size = size;
			this.Label7.TabIndex = 29;
			this.Label7.Text = "نحوه محاسبه کارگری";
			this.txt_arz_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_arz_kind.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_arz_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem5.FormatStyle.Alpha = 0;
			uIComboBoxItem5.IsSeparator = false;
			uIComboBoxItem5.Text = "ریال";
			uIComboBoxItem5.Value = "0";
			uIComboBoxItem6.FormatStyle.Alpha = 0;
			uIComboBoxItem6.IsSeparator = false;
			uIComboBoxItem6.Text = "تومان";
			uIComboBoxItem6.Value = "1";
			this.txt_arz_kind.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem5,
				uIComboBoxItem6
			});
			global::System.Windows.Forms.Control arg_DE6_0 = this.txt_arz_kind;
			location = new global::System.Drawing.Point(29, 117);
			arg_DE6_0.Location = location;
			this.txt_arz_kind.Name = "txt_arz_kind";
			global::System.Windows.Forms.Control arg_E14_0 = this.txt_arz_kind;
			size = new global::System.Drawing.Size(134, 36);
			arg_E14_0.Size = size;
			this.txt_arz_kind.TabIndex = 30;
			this.txt_arz_kind.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_kharid_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kharid_kind.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_kharid_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem7.FormatStyle.Alpha = 0;
			uIComboBoxItem7.IsSeparator = false;
			uIComboBoxItem7.Text = "خرید از یک نفر باشد";
			uIComboBoxItem7.Value = "1";
			uIComboBoxItem8.FormatStyle.Alpha = 0;
			uIComboBoxItem8.IsSeparator = false;
			uIComboBoxItem8.Text = "خرید از چند نفر باشد";
			uIComboBoxItem8.Value = "2";
			this.txt_kharid_kind.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem7,
				uIComboBoxItem8
			});
			global::System.Windows.Forms.Control arg_F0F_0 = this.txt_kharid_kind;
			location = new global::System.Drawing.Point(29, 253);
			arg_F0F_0.Location = location;
			this.txt_kharid_kind.Name = "txt_kharid_kind";
			global::System.Windows.Forms.Control arg_F3D_0 = this.txt_kharid_kind;
			size = new global::System.Drawing.Size(277, 36);
			arg_F3D_0.Size = size;
			this.txt_kharid_kind.TabIndex = 30;
			this.txt_kharid_kind.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_FA4_0 = this.Label14;
			location = new global::System.Drawing.Point(308, 296);
			arg_FA4_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_FCF_0 = this.Label14;
			size = new global::System.Drawing.Size(47, 16);
			arg_FCF_0.Size = size;
			this.Label14.TabIndex = 29;
			this.Label14.Text = "سربرگ";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_103A_0 = this.Label3;
			location = new global::System.Drawing.Point(308, 265);
			arg_103A_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1065_0 = this.Label3;
			size = new global::System.Drawing.Size(87, 16);
			arg_1065_0.Size = size;
			this.Label3.TabIndex = 29;
			this.Label3.Text = "نحوه ثبت خرید";
			this.Label30.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label30.AutoSize = true;
			this.Label30.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_10D0_0 = this.Label30;
			location = new global::System.Drawing.Point(922, 305);
			arg_10D0_0.Location = location;
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control arg_10FE_0 = this.Label30;
			size = new global::System.Drawing.Size(141, 32);
			arg_10FE_0.Size = size;
			this.Label30.TabIndex = 28;
			this.Label30.Text = "واگذاری چک به بانک\r\nحساب بانکی پیش فرض\r\n";
			this.txt_bank_hesab.AcceptEnter = true;
			this.txt_bank_hesab.AddNewForm = null;
			this.txt_bank_hesab.AllowEdit = true;
			this.txt_bank_hesab.AllowNew = true;
			this.txt_bank_hesab.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_bank_hesab.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_bank_hesab.ButtonText = "...";
			this.txt_bank_hesab.CanEdit = false;
			this.txt_bank_hesab.DisplayMember = "Name";
			this.txt_bank_hesab.Edit_Frm = null;
			this.txt_bank_hesab.ExtraData = 0L;
			this.txt_bank_hesab.FocusColor = true;
			this.txt_bank_hesab.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "حساب بانکی";
			column2.Name = "Name";
			column2.Size = 85;
			this.txt_bank_hesab.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2
			});
			global::System.Windows.Forms.Control arg_126E_0 = this.txt_bank_hesab;
			location = new global::System.Drawing.Point(604, 302);
			arg_126E_0.Location = location;
			this.txt_bank_hesab.Name = "txt_bank_hesab";
			this.txt_bank_hesab.Nullable = true;
			this.txt_bank_hesab.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_bank_hesab.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_bank_hesab.SelectCommand = "SELECT    Bank_Hesab.ID, Bank.Name+' '+ Bank_Hesab.Shobe +' - '+ Bank_Hesab.SahebHesab as name FROM Bank_Hesab INNER JOIN Bank ON Bank_Hesab.Bank_ID = Bank.ID";
			this.txt_bank_hesab.SelectedRow = null;
			this.txt_bank_hesab.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_12F2_0 = this.txt_bank_hesab;
			size = new global::System.Drawing.Size(316, 36);
			arg_12F2_0.Size = size;
			this.txt_bank_hesab.TabIndex = 27;
			this.txt_bank_hesab.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_bank_hesab.Value = null;
			this.txt_bank_hesab.ValueMember = "ID";
			this.txt_bank_hesab.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_nahve_furush.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_nahve_furush.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_nahve_furush.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem9.FormatStyle.Alpha = 0;
			uIComboBoxItem9.IsSeparator = false;
			uIComboBoxItem9.Text = "تعداد - وزن خالص";
			uIComboBoxItem9.Value = "1";
			uIComboBoxItem10.FormatStyle.Alpha = 0;
			uIComboBoxItem10.IsSeparator = false;
			uIComboBoxItem10.Text = "وزن خالص";
			uIComboBoxItem10.Value = "2";
			uIComboBoxItem11.FormatStyle.Alpha = 0;
			uIComboBoxItem11.IsSeparator = false;
			uIComboBoxItem11.Text = "تعداد";
			uIComboBoxItem11.Value = "3";
			uIComboBoxItem12.FormatStyle.Alpha = 0;
			uIComboBoxItem12.IsSeparator = false;
			uIComboBoxItem12.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			uIComboBoxItem12.Value = "4";
			this.txt_nahve_furush.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem9,
				uIComboBoxItem10,
				uIComboBoxItem11,
				uIComboBoxItem12
			});
			global::System.Windows.Forms.Control arg_148D_0 = this.txt_nahve_furush;
			location = new global::System.Drawing.Point(29, 222);
			arg_148D_0.Location = location;
			this.txt_nahve_furush.Name = "txt_nahve_furush";
			global::System.Windows.Forms.Control arg_14BB_0 = this.txt_nahve_furush;
			size = new global::System.Drawing.Size(277, 36);
			arg_14BB_0.Size = size;
			this.txt_nahve_furush.TabIndex = 26;
			this.txt_nahve_furush.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_salmali.AcceptEnter = true;
			this.txt_salmali.AllowEdit = true;
			this.txt_salmali.AllowNew = true;
			this.txt_salmali.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_salmali.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_salmali.ButtonText = "...";
			this.txt_salmali.FocusColor = true;
			this.txt_salmali.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_158D_0 = this.txt_salmali;
			location = new global::System.Drawing.Point(604, 267);
			arg_158D_0.Location = location;
			this.txt_salmali.Name = "txt_salmali";
			this.txt_salmali.Nullable = true;
			this.txt_salmali.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_salmali.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_15E6_0 = this.txt_salmali;
			size = new global::System.Drawing.Size(316, 36);
			arg_15E6_0.Size = size;
			this.txt_salmali.TabIndex = 25;
			this.txt_salmali.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_164D_0 = this.Label11;
			location = new global::System.Drawing.Point(973, 281);
			arg_164D_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1678_0 = this.Label11;
			size = new global::System.Drawing.Size(65, 16);
			arg_1678_0.Size = size;
			this.Label11.TabIndex = 24;
			this.Label11.Text = "سال مالی";
			this.txt_print_font_number.AcceptEnter = true;
			this.txt_print_font_number.AllowEdit = true;
			this.txt_print_font_number.AllowNew = true;
			this.txt_print_font_number.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_print_font_number.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_print_font_number.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_print_font_number.ButtonText = "...";
			this.txt_print_font_number.FocusColor = true;
			this.txt_print_font_number.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_175B_0 = this.txt_print_font_number;
			location = new global::System.Drawing.Point(604, 232);
			arg_175B_0.Location = location;
			this.txt_print_font_number.Name = "txt_print_font_number";
			this.txt_print_font_number.Nullable = true;
			this.txt_print_font_number.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_print_font_number.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_17B4_0 = this.txt_print_font_number;
			size = new global::System.Drawing.Size(316, 36);
			arg_17B4_0.Size = size;
			this.txt_print_font_number.TabIndex = 23;
			this.txt_print_font_number.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_print_font_number.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_gridfont.AcceptEnter = true;
			this.txt_gridfont.AllowEdit = true;
			this.txt_gridfont.AllowNew = true;
			this.txt_gridfont.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_gridfont.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_gridfont.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_gridfont.ButtonText = "...";
			this.txt_gridfont.FocusColor = true;
			this.txt_gridfont.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_18A0_0 = this.txt_gridfont;
			location = new global::System.Drawing.Point(604, 197);
			arg_18A0_0.Location = location;
			this.txt_gridfont.Name = "txt_gridfont";
			this.txt_gridfont.Nullable = true;
			this.txt_gridfont.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_gridfont.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_18F9_0 = this.txt_gridfont;
			size = new global::System.Drawing.Size(316, 36);
			arg_18F9_0.Size = size;
			this.txt_gridfont.TabIndex = 23;
			this.txt_gridfont.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_gridfont.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_font.AcceptEnter = true;
			this.txt_font.AllowEdit = true;
			this.txt_font.AllowNew = true;
			this.txt_font.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_font.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_font.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_font.ButtonText = "...";
			this.txt_font.FocusColor = true;
			this.txt_font.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_19E5_0 = this.txt_font;
			location = new global::System.Drawing.Point(615, 623);
			arg_19E5_0.Location = location;
			this.txt_font.Name = "txt_font";
			this.txt_font.Nullable = true;
			this.txt_font.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_font.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1A3E_0 = this.txt_font;
			size = new global::System.Drawing.Size(316, 36);
			arg_1A3E_0.Size = size;
			this.txt_font.TabIndex = 23;
			this.txt_font.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_font.Visible = false;
			this.txt_font.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.DateBox21.AcceptEnter = true;
			this.DateBox21.AllowEdit = true;
			this.DateBox21.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.DateBox21.ButtonEnable = true;
			this.DateBox21.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			this.DateBox21.FocusDatePart = 2;
			this.DateBox21.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1AFE_0 = this.DateBox21;
			location = new global::System.Drawing.Point(29, 82);
			arg_1AFE_0.Location = location;
			this.DateBox21.Mask = "0000/00/00";
			this.DateBox21.Name = "DateBox21";
			this.DateBox21.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_1B4A_0 = this.DateBox21;
			size = new global::System.Drawing.Size(134, 36);
			arg_1B4A_0.Size = size;
			this.DateBox21.TabIndex = 21;
			this.DateBox21.Text = "1394/08/16";
			this.DateBox21.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sarresid_pardakht.AcceptEnter = true;
			this.txt_sarresid_pardakht.AllowEdit = true;
			this.txt_sarresid_pardakht.AllowNew = true;
			this.txt_sarresid_pardakht.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sarresid_pardakht.FocusColor = true;
			this.txt_sarresid_pardakht.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BF7_0 = this.txt_sarresid_pardakht;
			location = new global::System.Drawing.Point(29, 187);
			arg_1BF7_0.Location = location;
			this.txt_sarresid_pardakht.Name = "txt_sarresid_pardakht";
			this.txt_sarresid_pardakht.Nullable = true;
			this.txt_sarresid_pardakht.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sarresid_pardakht.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1C50_0 = this.txt_sarresid_pardakht;
			size = new global::System.Drawing.Size(134, 36);
			arg_1C50_0.Size = size;
			this.txt_sarresid_pardakht.TabIndex = 20;
			this.txt_sarresid_pardakht.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sarresid_pardakht.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sarresid_daryaft.AcceptEnter = true;
			this.txt_sarresid_daryaft.AllowEdit = true;
			this.txt_sarresid_daryaft.AllowNew = true;
			this.txt_sarresid_daryaft.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sarresid_daryaft.FocusColor = true;
			this.txt_sarresid_daryaft.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1CF9_0 = this.txt_sarresid_daryaft;
			location = new global::System.Drawing.Point(29, 152);
			arg_1CF9_0.Location = location;
			this.txt_sarresid_daryaft.Name = "txt_sarresid_daryaft";
			this.txt_sarresid_daryaft.Nullable = true;
			this.txt_sarresid_daryaft.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sarresid_daryaft.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1D52_0 = this.txt_sarresid_daryaft;
			size = new global::System.Drawing.Size(134, 36);
			arg_1D52_0.Size = size;
			this.txt_sarresid_daryaft.TabIndex = 20;
			this.txt_sarresid_daryaft.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sarresid_daryaft.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1DC6_0 = this.Label5;
			location = new global::System.Drawing.Point(165, 195);
			arg_1DC6_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_1DF4_0 = this.Label5;
			size = new global::System.Drawing.Size(279, 16);
			arg_1DF4_0.Size = size;
			this.Label5.TabIndex = 19;
			this.Label5.Text = "تعداد روزهای مانده به سررسید چک های پرداختی";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1E5F_0 = this.Label2;
			location = new global::System.Drawing.Point(937, 243);
			arg_1E5F_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_1E8A_0 = this.Label2;
			size = new global::System.Drawing.Size(109, 16);
			arg_1E8A_0.Size = size;
			this.Label2.TabIndex = 17;
			this.Label2.Text = "فونت اعداد در چاپ";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1EF5_0 = this.Label4;
			location = new global::System.Drawing.Point(165, 162);
			arg_1EF5_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1F23_0 = this.Label4;
			size = new global::System.Drawing.Size(276, 16);
			arg_1F23_0.Size = size;
			this.Label4.TabIndex = 19;
			this.Label4.Text = "تعداد روزهای مانده به سررسید چک های دریافتی";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1F8E_0 = this.Label10;
			location = new global::System.Drawing.Point(972, 211);
			arg_1F8E_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_1FB9_0 = this.Label10;
			size = new global::System.Drawing.Size(70, 16);
			arg_1FB9_0.Size = size;
			this.Label10.TabIndex = 17;
			this.Label10.Text = "فونت برنامه";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2024_0 = this.Label9;
			location = new global::System.Drawing.Point(937, 641);
			arg_2024_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_204F_0 = this.Label9;
			size = new global::System.Drawing.Size(105, 16);
			arg_204F_0.Size = size;
			this.Label9.TabIndex = 17;
			this.Label9.Text = "فونت اصلی برنامه";
			this.Label9.Visible = false;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2,
				this.ButtonItem1,
				this.ButtonItem3,
				this.ButtonItem4,
				this.ButtonItem5
			});
			global::DevComponents.DotNetBar.Bar arg_212A_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_212A_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_2158_0 = this.Bar1;
			size = new global::System.Drawing.Size(1077, 41);
			arg_2158_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 16;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.comment;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "تنظیمات پیامک";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.useredit;
			global::DevComponents.DotNetBar.ButtonItem arg_2256_0 = this.ButtonItem3;
			size = new global::System.Drawing.Size(32, 32);
			arg_2256_0.ImageFixedSize = size;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "تنظیمات امنیتی";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.gear;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "تنظیمات پیشرفته";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.gear;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "تنظیمات فاکتور فروش";
			this.UiGroupBox5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox5.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox5.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_2339_0 = this.UiGroupBox5;
			location = new global::System.Drawing.Point(-1, 58);
			arg_2339_0.Location = location;
			this.UiGroupBox5.Name = "UiGroupBox5";
			global::System.Windows.Forms.Control arg_2367_0 = this.UiGroupBox5;
			size = new global::System.Drawing.Size(461, 21);
			arg_2367_0.Size = size;
			this.UiGroupBox5.TabIndex = 3;
			this.UiGroupBox5.Text = "عملیات";
			this.UiGroupBox5.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox4.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox4.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_23DA_0 = this.UiGroupBox4;
			location = new global::System.Drawing.Point(599, 351);
			arg_23DA_0.Location = location;
			this.UiGroupBox4.Name = "UiGroupBox4";
			global::System.Windows.Forms.Control arg_2408_0 = this.UiGroupBox4;
			size = new global::System.Drawing.Size(461, 21);
			arg_2408_0.Size = size;
			this.UiGroupBox4.TabIndex = 3;
			this.UiGroupBox4.Text = "کارگری";
			this.UiGroupBox4.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox3.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox3.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_247B_0 = this.UiGroupBox3;
			location = new global::System.Drawing.Point(604, 167);
			arg_247B_0.Location = location;
			this.UiGroupBox3.Name = "UiGroupBox3";
			global::System.Windows.Forms.Control arg_24A9_0 = this.UiGroupBox3;
			size = new global::System.Drawing.Size(461, 21);
			arg_24A9_0.Size = size;
			this.UiGroupBox3.TabIndex = 3;
			this.UiGroupBox3.Text = "محیط کاربری";
			this.UiGroupBox3.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_2519_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(604, 59);
			arg_2519_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_2547_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(461, 21);
			arg_2547_0.Size = size;
			this.UiGroupBox2.TabIndex = 3;
			this.UiGroupBox2.Text = "تهیه پشتیبان";
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.EditBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox1.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.EditBox1.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.EditBox1.ButtonText = "...";
			this.EditBox1.Font = new global::System.Drawing.Font("Courier New", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_25FF_0 = this.EditBox1;
			location = new global::System.Drawing.Point(465, 114);
			arg_25FF_0.Location = location;
			this.EditBox1.Name = "EditBox1";
			global::System.Windows.Forms.Control arg_262D_0 = this.EditBox1;
			size = new global::System.Drawing.Size(455, 26);
			arg_262D_0.Size = size;
			this.EditBox1.TabIndex = 2;
			this.EditBox1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.EditBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_oft.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_oft.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2693_0 = this.txt_oft;
			location = new global::System.Drawing.Point(674, 503);
			arg_2693_0.Location = location;
			this.txt_oft.Name = "txt_oft";
			this.txt_oft.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_26CE_0 = this.txt_oft;
			size = new global::System.Drawing.Size(273, 23);
			arg_26CE_0.Size = size;
			this.txt_oft.TabIndex = 1;
			this.txt_oft.Text = "ثبت افت در ریزبار خرید";
			this.txt_tasvie.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tasvie.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_272B_0 = this.txt_tasvie;
			location = new global::System.Drawing.Point(165, 467);
			arg_272B_0.Location = location;
			this.txt_tasvie.Name = "txt_tasvie";
			this.txt_tasvie.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2766_0 = this.txt_tasvie;
			size = new global::System.Drawing.Size(273, 23);
			arg_2766_0.Size = size;
			this.txt_tasvie.TabIndex = 1;
			this.txt_tasvie.Text = "نمایش صورتحساب از تاریخ تسویه به بعد";
			this.txt_no_bed_alert.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_no_bed_alert.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_27C3_0 = this.txt_no_bed_alert;
			location = new global::System.Drawing.Point(165, 438);
			arg_27C3_0.Location = location;
			this.txt_no_bed_alert.Name = "txt_no_bed_alert";
			this.txt_no_bed_alert.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_27FE_0 = this.txt_no_bed_alert;
			size = new global::System.Drawing.Size(273, 23);
			arg_27FE_0.Size = size;
			this.txt_no_bed_alert.TabIndex = 1;
			this.txt_no_bed_alert.Text = "عدم نمایش هشدار دریافت بیشتر از بدهکاری";
			this.txt_kargari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kargari.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_285B_0 = this.txt_kargari;
			location = new global::System.Drawing.Point(702, 375);
			arg_285B_0.Location = location;
			this.txt_kargari.Name = "txt_kargari";
			this.txt_kargari.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2896_0 = this.txt_kargari;
			size = new global::System.Drawing.Size(245, 23);
			arg_2896_0.Size = size;
			this.txt_kargari.TabIndex = 1;
			this.txt_kargari.Text = "دریافت کارگری به اضاء هر ردیف فروش";
			this.txt_show_avg.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_show_avg.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_28F3_0 = this.txt_show_avg;
			location = new global::System.Drawing.Point(193, 409);
			arg_28F3_0.Location = location;
			this.txt_show_avg.Name = "txt_show_avg";
			this.txt_show_avg.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_292E_0 = this.txt_show_avg;
			size = new global::System.Drawing.Size(245, 23);
			arg_292E_0.Size = size;
			this.txt_show_avg.TabIndex = 1;
			this.txt_show_avg.Text = "نمایش وزن میانگین در فروش";
			this.UiCheckBox9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox9.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_298B_0 = this.UiCheckBox9;
			location = new global::System.Drawing.Point(193, 380);
			arg_298B_0.Location = location;
			this.UiCheckBox9.Name = "UiCheckBox9";
			this.UiCheckBox9.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_29C6_0 = this.UiCheckBox9;
			size = new global::System.Drawing.Size(245, 23);
			arg_29C6_0.Size = size;
			this.UiCheckBox9.TabIndex = 1;
			this.UiCheckBox9.Text = "نمایش توضیحات اتوماتیک در صورتحساب";
			this.UiCheckBox8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2A23_0 = this.UiCheckBox8;
			location = new global::System.Drawing.Point(193, 351);
			arg_2A23_0.Location = location;
			this.UiCheckBox8.Name = "UiCheckBox8";
			this.UiCheckBox8.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2A5E_0 = this.UiCheckBox8;
			size = new global::System.Drawing.Size(245, 23);
			arg_2A5E_0.Size = size;
			this.UiCheckBox8.TabIndex = 1;
			this.UiCheckBox8.Text = "تسویه حساب تخلیه بصورت دستی";
			this.UiCheckBox7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox7.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2ABB_0 = this.UiCheckBox7;
			location = new global::System.Drawing.Point(352, 612);
			arg_2ABB_0.Location = location;
			this.UiCheckBox7.Name = "UiCheckBox7";
			this.UiCheckBox7.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2AF6_0 = this.UiCheckBox7;
			size = new global::System.Drawing.Size(245, 23);
			arg_2AF6_0.Size = size;
			this.UiCheckBox7.TabIndex = 1;
			this.UiCheckBox7.Text = "نمایش گزینه اول دوره در خرید و فروش";
			this.UiCheckBox7.Visible = false;
			this.UiCheckBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2B5D_0 = this.UiCheckBox1;
			location = new global::System.Drawing.Point(837, 79);
			arg_2B5D_0.Location = location;
			this.UiCheckBox1.Name = "UiCheckBox1";
			this.UiCheckBox1.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2B98_0 = this.UiCheckBox1;
			size = new global::System.Drawing.Size(219, 23);
			arg_2B98_0.Size = size;
			this.UiCheckBox1.TabIndex = 1;
			this.UiCheckBox1.Text = "تهیه پشتیبان هنگام خروج از برنامه";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2BFF_0 = this.Label6;
			location = new global::System.Drawing.Point(926, 117);
			arg_2BFF_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_2C2A_0 = this.Label6;
			size = new global::System.Drawing.Size(116, 16);
			arg_2C2A_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "مسیر تهیه پشتیبان";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2C94_0 = this.Label12;
			location = new global::System.Drawing.Point(308, 234);
			arg_2C94_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_2CBF_0 = this.Label12;
			size = new global::System.Drawing.Size(68, 16);
			arg_2CBF_0.Size = size;
			this.Label12.TabIndex = 0;
			this.Label12.Text = "نحوه فروش";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2D26_0 = this.Label13;
			location = new global::System.Drawing.Point(165, 127);
			arg_2D26_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_2D51_0 = this.Label13;
			size = new global::System.Drawing.Size(63, 16);
			arg_2D51_0.Size = size;
			this.Label13.TabIndex = 0;
			this.Label13.Text = "واحد پولی";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2DB8_0 = this.Label1;
			location = new global::System.Drawing.Point(165, 94);
			arg_2DB8_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_2DE3_0 = this.Label1;
			size = new global::System.Drawing.Size(111, 16);
			arg_2DE3_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "تاریخ کار با نرم افزار";
			this.FontDialog1.Color = global::System.Drawing.SystemColors.ControlText;
			this.FontDialog1.ShowEffects = false;
			this.UiGroupBox6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox6.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox6.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_2E67_0 = this.UiGroupBox6;
			location = new global::System.Drawing.Point(599, 481);
			arg_2E67_0.Location = location;
			this.UiGroupBox6.Name = "UiGroupBox6";
			global::System.Windows.Forms.Control arg_2E95_0 = this.UiGroupBox6;
			size = new global::System.Drawing.Size(461, 21);
			arg_2E95_0.Size = size;
			this.UiGroupBox6.TabIndex = 34;
			this.UiGroupBox6.Text = "افت بار";
			this.UiGroupBox6.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_oft_kind.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_oft_kind.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_oft_kind.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem13.FormatStyle.Alpha = 0;
			uIComboBoxItem13.IsSeparator = false;
			uIComboBoxItem13.Text = "برحسب درصد";
			uIComboBoxItem13.Value = "1";
			uIComboBoxItem14.FormatStyle.Alpha = 0;
			uIComboBoxItem14.IsSeparator = false;
			uIComboBoxItem14.Text = "بر حسب کیلو";
			uIComboBoxItem14.Value = "2";
			this.txt_oft_kind.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem13,
				uIComboBoxItem14
			});
			global::System.Windows.Forms.Control arg_2FA4_0 = this.txt_oft_kind;
			location = new global::System.Drawing.Point(670, 532);
			arg_2FA4_0.Location = location;
			this.txt_oft_kind.Name = "txt_oft_kind";
			global::System.Windows.Forms.Control arg_2FD2_0 = this.txt_oft_kind;
			size = new global::System.Drawing.Size(277, 36);
			arg_2FD2_0.Size = size;
			this.txt_oft_kind.TabIndex = 36;
			this.txt_oft_kind.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_3039_0 = this.Label15;
			location = new global::System.Drawing.Point(949, 544);
			arg_3039_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_3064_0 = this.Label15;
			size = new global::System.Drawing.Size(123, 16);
			arg_3064_0.Size = size;
			this.Label15.TabIndex = 35;
			this.Label15.Text = "نحوه محاسبه افت بار";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1077, 662);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Setting";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "تنظیمات";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox6).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x0400041A RID: 1050
		private global::System.ComponentModel.IContainer components;
	}
}
