namespace FruitBox
{
	// Token: 0x020000C3 RID: 195
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Bank_Hesab : global::System.Windows.Forms.Form
	{
		// Token: 0x06000FAC RID: 4012 RVA: 0x000ADE28 File Offset: 0x000AC028
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000FAD RID: 4013 RVA: 0x000ADE78 File Offset: 0x000AC078
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::FruitBox.Column column = new global::FruitBox.Column();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.UiGroupBox3 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_mablagh = new global::FruitBox.CurrencyBox(this.components);
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.txt_address = new global::FruitBox.EditBox(this.components);
			this.txt_codemelli = new global::FruitBox.EditBox(this.components);
			this.txt_shsh = new global::FruitBox.EditBox(this.components);
			this.txt_namepedar = new global::FruitBox.EditBox(this.components);
			this.UiCheckBox1 = new global::Janus.Windows.EditControls.UICheckBox();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.txt_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_bank = new global::FruitBox.SelectItem(this.components);
			this.txt_shobe = new global::FruitBox.EditBox(this.components);
			this.txt_hesab = new global::FruitBox.NumericBox(this.components);
			this.txt_kart = new global::FruitBox.NumericBox(this.components);
			this.txt_sahebhesab = new global::FruitBox.EditBox(this.components);
			this.txt_codeposti = new global::FruitBox.EditBox(this.components);
			this.txt_tel = new global::FruitBox.EditBox(this.components);
			this.txt_sadere = new global::FruitBox.EditBox(this.components);
			this.txt_shaba = new global::FruitBox.EditBox(this.components);
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.txt_enable = new global::Janus.Windows.EditControls.UICheckBox();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.SuspendLayout();
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_32F_0 = this.Label1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(570, 61);
			arg_32F_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_35A_0 = this.Label1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(37, 19);
			arg_35A_0.Size = size;
			this.Label1.TabIndex = 24;
			this.Label1.Text = "بانک";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3E6_0 = this.Label3;
			location = new global::System.Drawing.Point(574, 292);
			arg_3E6_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_411_0 = this.Label3;
			size = new global::System.Drawing.Size(86, 19);
			arg_411_0.Size = size;
			this.Label3.TabIndex = 26;
			this.Label3.Text = "شماره شبا";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_49D_0 = this.Label4;
			location = new global::System.Drawing.Point(230, 250);
			arg_49D_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_4C8_0 = this.Label4;
			size = new global::System.Drawing.Size(91, 19);
			arg_4C8_0.Size = size;
			this.Label4.TabIndex = 27;
			this.Label4.Text = "شماره کارت";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_554_0 = this.Label5;
			location = new global::System.Drawing.Point(574, 251);
			arg_554_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_57F_0 = this.Label5;
			size = new global::System.Drawing.Size(105, 19);
			arg_57F_0.Size = size;
			this.Label5.TabIndex = 28;
			this.Label5.Text = "شماره حساب";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_608_0 = this.Label6;
			location = new global::System.Drawing.Point(226, 60);
			arg_608_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_633_0 = this.Label6;
			size = new global::System.Drawing.Size(48, 19);
			arg_633_0.Size = size;
			this.Label6.TabIndex = 29;
			this.Label6.Text = "شعبه";
			this.Label16.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label16.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_6D0_0 = this.Label16;
			location = new global::System.Drawing.Point(230, 170);
			arg_6D0_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_6FB_0 = this.Label16;
			size = new global::System.Drawing.Size(93, 19);
			arg_6FB_0.Size = size;
			this.Label16.TabIndex = 34;
			this.Label16.Text = "مانده از تاریخ";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Label14.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_798_0 = this.Label14;
			location = new global::System.Drawing.Point(574, 173);
			arg_798_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_7C3_0 = this.Label14;
			size = new global::System.Drawing.Size(38, 19);
			arg_7C3_0.Size = size;
			this.Label14.TabIndex = 35;
			this.Label14.Text = "مبلغ";
			this.UiGroupBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox3.BackColor = global::System.Drawing.Color.Transparent;
			this.UiGroupBox3.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox3.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_84B_0 = this.UiGroupBox3;
			location = new global::System.Drawing.Point(7, 146);
			arg_84B_0.Location = location;
			this.UiGroupBox3.Name = "UiGroupBox3";
			global::System.Windows.Forms.Control arg_879_0 = this.UiGroupBox3;
			size = new global::System.Drawing.Size(674, 24);
			arg_879_0.Size = size;
			this.UiGroupBox3.TabIndex = 42;
			this.UiGroupBox3.Text = "الباقی موجودی";
			this.UiGroupBox3.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_mablagh.AcceptEnter = true;
			this.txt_mablagh.AllowEdit = true;
			this.txt_mablagh.AllowNew = true;
			this.txt_mablagh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mablagh.FocusColor = true;
			this.txt_mablagh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_928_0 = this.txt_mablagh;
			location = new global::System.Drawing.Point(358, 161);
			arg_928_0.Location = location;
			this.txt_mablagh.Name = "txt_mablagh";
			this.txt_mablagh.Nullable = true;
			this.txt_mablagh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_981_0 = this.txt_mablagh;
			size = new global::System.Drawing.Size(210, 36);
			arg_981_0.Size = size;
			this.txt_mablagh.TabIndex = 3;
			this.txt_mablagh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_mablagh.Value = value;
			this.txt_mablagh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox1.BackColor = global::System.Drawing.Color.White;
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_mablagh);
			this.UiGroupBox1.Controls.Add(this.UiButton2);
			this.UiGroupBox1.Controls.Add(this.UiButton1);
			this.UiGroupBox1.Controls.Add(this.PictureBox1);
			this.UiGroupBox1.Controls.Add(this.txt_address);
			this.UiGroupBox1.Controls.Add(this.txt_codemelli);
			this.UiGroupBox1.Controls.Add(this.txt_shsh);
			this.UiGroupBox1.Controls.Add(this.txt_namepedar);
			this.UiGroupBox1.Controls.Add(this.txt_enable);
			this.UiGroupBox1.Controls.Add(this.UiCheckBox1);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label15);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label16);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_bank);
			this.UiGroupBox1.Controls.Add(this.txt_shobe);
			this.UiGroupBox1.Controls.Add(this.txt_hesab);
			this.UiGroupBox1.Controls.Add(this.txt_kart);
			this.UiGroupBox1.Controls.Add(this.txt_sahebhesab);
			this.UiGroupBox1.Controls.Add(this.txt_codeposti);
			this.UiGroupBox1.Controls.Add(this.txt_tel);
			this.UiGroupBox1.Controls.Add(this.txt_sadere);
			this.UiGroupBox1.Controls.Add(this.txt_shaba);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox3);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_D86_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_D86_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeCustomColor = global::System.Drawing.Color.SpringGreen;
			global::System.Windows.Forms.Control arg_DC8_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(681, 506);
			arg_DC8_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			global::System.Windows.Forms.Control arg_E0C_0 = this.UiButton2;
			location = new global::System.Drawing.Point(18, 463);
			arg_E0C_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			global::System.Windows.Forms.Control arg_E37_0 = this.UiButton2;
			size = new global::System.Drawing.Size(103, 26);
			arg_E37_0.Size = size;
			this.UiButton2.TabIndex = 46;
			this.UiButton2.Text = "حذف تصویر";
			this.UiButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			global::System.Windows.Forms.Control arg_E80_0 = this.UiButton1;
			location = new global::System.Drawing.Point(18, 430);
			arg_E80_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			global::System.Windows.Forms.Control arg_EAB_0 = this.UiButton1;
			size = new global::System.Drawing.Size(103, 27);
			arg_EAB_0.Size = size;
			this.UiButton1.TabIndex = 46;
			this.UiButton1.Text = "بارگذاری تصویر";
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			global::System.Windows.Forms.Control arg_EF4_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(127, 411);
			arg_EF4_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_F1F_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(101, 78);
			arg_F1F_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 45;
			this.PictureBox1.TabStop = false;
			this.txt_address.AcceptEnter = true;
			this.txt_address.AllowEdit = true;
			this.txt_address.AllowNew = true;
			this.txt_address.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_address.FocusColor = true;
			this.txt_address.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_FCA_0 = this.txt_address;
			location = new global::System.Drawing.Point(362, 453);
			arg_FCA_0.Location = location;
			this.txt_address.Name = "txt_address";
			this.txt_address.Nullable = true;
			this.txt_address.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_address.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1023_0 = this.txt_address;
			size = new global::System.Drawing.Size(210, 36);
			arg_1023_0.Size = size;
			this.txt_address.TabIndex = 14;
			this.txt_address.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_codemelli.AcceptEnter = true;
			this.txt_codemelli.AllowEdit = true;
			this.txt_codemelli.AllowNew = true;
			this.txt_codemelli.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_codemelli.FocusColor = true;
			this.txt_codemelli.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10C1_0 = this.txt_codemelli;
			location = new global::System.Drawing.Point(362, 327);
			arg_10C1_0.Location = location;
			this.txt_codemelli.MaxLength = 10;
			this.txt_codemelli.Name = "txt_codemelli";
			this.txt_codemelli.Nullable = true;
			this.txt_codemelli.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_codemelli.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1128_0 = this.txt_codemelli;
			size = new global::System.Drawing.Size(210, 36);
			arg_1128_0.Size = size;
			this.txt_codemelli.TabIndex = 9;
			this.txt_codemelli.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shsh.AcceptEnter = true;
			this.txt_shsh.AllowEdit = true;
			this.txt_shsh.AllowNew = true;
			this.txt_shsh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shsh.FocusColor = true;
			this.txt_shsh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11C3_0 = this.txt_shsh;
			location = new global::System.Drawing.Point(18, 327);
			arg_11C3_0.Location = location;
			this.txt_shsh.Name = "txt_shsh";
			this.txt_shsh.Nullable = true;
			this.txt_shsh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shsh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_121C_0 = this.txt_shsh;
			size = new global::System.Drawing.Size(210, 36);
			arg_121C_0.Size = size;
			this.txt_shsh.TabIndex = 10;
			this.txt_shsh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_namepedar.AcceptEnter = true;
			this.txt_namepedar.AllowEdit = true;
			this.txt_namepedar.AllowNew = true;
			this.txt_namepedar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_namepedar.FocusColor = true;
			this.txt_namepedar.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12B7_0 = this.txt_namepedar;
			location = new global::System.Drawing.Point(18, 284);
			arg_12B7_0.Location = location;
			this.txt_namepedar.Name = "txt_namepedar";
			this.txt_namepedar.Nullable = true;
			this.txt_namepedar.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_namepedar.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1310_0 = this.txt_namepedar;
			size = new global::System.Drawing.Size(210, 36);
			arg_1310_0.Size = size;
			this.txt_namepedar.TabIndex = 8;
			this.txt_namepedar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiCheckBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.UiCheckBox1.Checked = true;
			this.UiCheckBox1.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.UiCheckBox1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_139E_0 = this.UiCheckBox1;
			location = new global::System.Drawing.Point(76, 94);
			arg_139E_0.Location = location;
			this.UiCheckBox1.Name = "UiCheckBox1";
			global::System.Windows.Forms.Control arg_13CC_0 = this.UiCheckBox1;
			size = new global::System.Drawing.Size(152, 23);
			arg_13CC_0.Size = size;
			this.UiCheckBox1.TabIndex = 0;
			this.UiCheckBox1.TabStop = false;
			this.UiCheckBox1.Text = "متصل به کارتخوان";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3
			});
			global::DevComponents.DotNetBar.Bar arg_148F_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_148F_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_14BD_0 = this.Bar1;
			size = new global::System.Drawing.Size(681, 41);
			arg_14BD_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 44;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف (F5)";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1630_0 = this.Label2;
			location = new global::System.Drawing.Point(335, 293);
			arg_1630_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_165B_0 = this.Label2;
			size = new global::System.Drawing.Size(25, 19);
			arg_165B_0.Size = size;
			this.Label2.TabIndex = 43;
			this.Label2.Text = "IR";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_16E7_0 = this.Label8;
			location = new global::System.Drawing.Point(574, 460);
			arg_16E7_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_1712_0 = this.Label8;
			size = new global::System.Drawing.Size(45, 19);
			arg_1712_0.Size = size;
			this.Label8.TabIndex = 26;
			this.Label8.Text = "آدرس";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_179E_0 = this.Label12;
			location = new global::System.Drawing.Point(574, 336);
			arg_179E_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_17C9_0 = this.Label12;
			size = new global::System.Drawing.Size(61, 19);
			arg_17C9_0.Size = size;
			this.Label12.TabIndex = 26;
			this.Label12.Text = "کد ملی";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1852_0 = this.Label7;
			location = new global::System.Drawing.Point(570, 103);
			arg_1852_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_187D_0 = this.Label7;
			size = new global::System.Drawing.Size(103, 19);
			arg_187D_0.Size = size;
			this.Label7.TabIndex = 26;
			this.Label7.Text = "صاحب حساب";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1909_0 = this.Label11;
			location = new global::System.Drawing.Point(230, 337);
			arg_1909_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1937_0 = this.Label11;
			size = new global::System.Drawing.Size(130, 19);
			arg_1937_0.Size = size;
			this.Label11.TabIndex = 26;
			this.Label11.Text = "شماره شناسنامه";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_19C3_0 = this.Label10;
			location = new global::System.Drawing.Point(230, 293);
			arg_19C3_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_19EE_0 = this.Label10;
			size = new global::System.Drawing.Size(51, 19);
			arg_19EE_0.Size = size;
			this.Label10.TabIndex = 26;
			this.Label10.Text = "نام پدر";
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A7A_0 = this.Label15;
			location = new global::System.Drawing.Point(574, 419);
			arg_1A7A_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_1AA5_0 = this.Label15;
			size = new global::System.Drawing.Size(74, 19);
			arg_1AA5_0.Size = size;
			this.Label15.TabIndex = 26;
			this.Label15.Text = "کد پستی";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1B31_0 = this.Label13;
			location = new global::System.Drawing.Point(230, 379);
			arg_1B31_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_1B5C_0 = this.Label13;
			size = new global::System.Drawing.Size(39, 19);
			arg_1B5C_0.Size = size;
			this.Label13.TabIndex = 26;
			this.Label13.Text = "تلفن";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BE8_0 = this.Label9;
			location = new global::System.Drawing.Point(574, 377);
			arg_1BE8_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_1C13_0 = this.Label9;
			size = new global::System.Drawing.Size(62, 19);
			arg_1C13_0.Size = size;
			this.Label9.TabIndex = 26;
			this.Label9.Text = "صادره از";
			this.txt_tarikh.AcceptEnter = true;
			this.txt_tarikh.AllowEdit = true;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh.ButtonEnable = false;
			this.txt_tarikh.FocusDatePart = 2;
			this.txt_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1CB2_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(98, 161);
			arg_1CB2_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_1CFE_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(130, 36);
			arg_1CFE_0.Size = size;
			this.txt_tarikh.TabIndex = 4;
			this.txt_tarikh.Text = "1392/08/02";
			this.txt_tarikh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Center;
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_bank.AcceptEnter = true;
			this.txt_bank.AddNewForm = null;
			this.txt_bank.AllowEdit = true;
			this.txt_bank.AllowNew = true;
			this.txt_bank.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_bank.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_bank.ButtonText = "...";
			this.txt_bank.CanEdit = false;
			this.txt_bank.DisplayMember = "Name";
			this.txt_bank.Edit_Frm = null;
			this.txt_bank.ExtraData = 0L;
			this.txt_bank.FocusColor = true;
			this.txt_bank.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "بانک";
			column.Name = "Name";
			column.Size = 100;
			this.txt_bank.Items.AddRange(new global::FruitBox.Column[]
			{
				column
			});
			global::System.Windows.Forms.Control arg_1E5C_0 = this.txt_bank;
			location = new global::System.Drawing.Point(358, 52);
			arg_1E5C_0.Location = location;
			this.txt_bank.Name = "txt_bank";
			this.txt_bank.Nullable = false;
			this.txt_bank.NullToolTipText = "بانک مورد نظر را انتخاب فرمائید";
			this.txt_bank.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_bank.SelectCommand = "select Id,Name From Bank";
			this.txt_bank.SelectedRow = null;
			this.txt_bank.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1EE0_0 = this.txt_bank;
			size = new global::System.Drawing.Size(210, 36);
			arg_1EE0_0.Size = size;
			this.txt_bank.TabIndex = 0;
			this.txt_bank.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_bank.Value = null;
			this.txt_bank.ValueMember = "ID";
			this.txt_bank.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shobe.AcceptEnter = true;
			this.txt_shobe.AllowEdit = true;
			this.txt_shobe.AllowNew = true;
			this.txt_shobe.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shobe.FocusColor = true;
			this.txt_shobe.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1FA2_0 = this.txt_shobe;
			location = new global::System.Drawing.Point(14, 51);
			arg_1FA2_0.Location = location;
			this.txt_shobe.Name = "txt_shobe";
			this.txt_shobe.Nullable = false;
			this.txt_shobe.NullToolTipText = "شعبه بانک را وارد نمائید";
			this.txt_shobe.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1FFB_0 = this.txt_shobe;
			size = new global::System.Drawing.Size(210, 36);
			arg_1FFB_0.Size = size;
			this.txt_shobe.TabIndex = 1;
			this.txt_shobe.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hesab.AcceptEnter = true;
			this.txt_hesab.AllowEdit = true;
			this.txt_hesab.AllowNew = true;
			this.txt_hesab.AllowZero = true;
			this.txt_hesab.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_hesab.FocusColor = true;
			this.txt_hesab.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20A5_0 = this.txt_hesab;
			location = new global::System.Drawing.Point(362, 243);
			arg_20A5_0.Location = location;
			this.txt_hesab.Name = "txt_hesab";
			this.txt_hesab.Nullable = true;
			this.txt_hesab.NullToolTipText = "شماره حساب را وارد نمائید";
			this.txt_hesab.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_20FE_0 = this.txt_hesab;
			size = new global::System.Drawing.Size(210, 36);
			arg_20FE_0.Size = size;
			this.txt_hesab.TabIndex = 5;
			this.txt_hesab.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hesab.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kart.AcceptEnter = true;
			this.txt_kart.AllowEdit = true;
			this.txt_kart.AllowNew = true;
			this.txt_kart.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kart.FocusColor = true;
			this.txt_kart.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_21A5_0 = this.txt_kart;
			location = new global::System.Drawing.Point(18, 242);
			arg_21A5_0.Location = location;
			this.txt_kart.Name = "txt_kart";
			this.txt_kart.Nullable = true;
			this.txt_kart.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kart.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_21FE_0 = this.txt_kart;
			size = new global::System.Drawing.Size(210, 36);
			arg_21FE_0.Size = size;
			this.txt_kart.TabIndex = 6;
			this.txt_kart.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kart.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sahebhesab.AcceptEnter = true;
			this.txt_sahebhesab.AllowEdit = true;
			this.txt_sahebhesab.AllowNew = true;
			this.txt_sahebhesab.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sahebhesab.FocusColor = true;
			this.txt_sahebhesab.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_22A5_0 = this.txt_sahebhesab;
			location = new global::System.Drawing.Point(358, 94);
			arg_22A5_0.Location = location;
			this.txt_sahebhesab.Name = "txt_sahebhesab";
			this.txt_sahebhesab.Nullable = false;
			this.txt_sahebhesab.NullToolTipText = "لطفا صاحب حساب را وارد نمائید";
			this.txt_sahebhesab.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_22FE_0 = this.txt_sahebhesab;
			size = new global::System.Drawing.Size(210, 36);
			arg_22FE_0.Size = size;
			this.txt_sahebhesab.TabIndex = 2;
			this.txt_sahebhesab.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_codeposti.AcceptEnter = true;
			this.txt_codeposti.AllowEdit = true;
			this.txt_codeposti.AllowNew = true;
			this.txt_codeposti.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_codeposti.FocusColor = true;
			this.txt_codeposti.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_239B_0 = this.txt_codeposti;
			location = new global::System.Drawing.Point(362, 411);
			arg_239B_0.Location = location;
			this.txt_codeposti.Name = "txt_codeposti";
			this.txt_codeposti.Nullable = true;
			this.txt_codeposti.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_codeposti.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_23F4_0 = this.txt_codeposti;
			size = new global::System.Drawing.Size(210, 36);
			arg_23F4_0.Size = size;
			this.txt_codeposti.TabIndex = 13;
			this.txt_codeposti.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tel.AcceptEnter = true;
			this.txt_tel.AllowEdit = true;
			this.txt_tel.AllowNew = true;
			this.txt_tel.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tel.FocusColor = true;
			this.txt_tel.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_248F_0 = this.txt_tel;
			location = new global::System.Drawing.Point(18, 369);
			arg_248F_0.Location = location;
			this.txt_tel.Name = "txt_tel";
			this.txt_tel.Nullable = true;
			this.txt_tel.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tel.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_24E8_0 = this.txt_tel;
			size = new global::System.Drawing.Size(210, 36);
			arg_24E8_0.Size = size;
			this.txt_tel.TabIndex = 12;
			this.txt_tel.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sadere.AcceptEnter = true;
			this.txt_sadere.AllowEdit = true;
			this.txt_sadere.AllowNew = true;
			this.txt_sadere.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sadere.FocusColor = true;
			this.txt_sadere.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2586_0 = this.txt_sadere;
			location = new global::System.Drawing.Point(362, 369);
			arg_2586_0.Location = location;
			this.txt_sadere.Name = "txt_sadere";
			this.txt_sadere.Nullable = true;
			this.txt_sadere.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sadere.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_25DF_0 = this.txt_sadere;
			size = new global::System.Drawing.Size(210, 36);
			arg_25DF_0.Size = size;
			this.txt_sadere.TabIndex = 11;
			this.txt_sadere.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shaba.AcceptEnter = true;
			this.txt_shaba.AllowEdit = true;
			this.txt_shaba.AllowNew = true;
			this.txt_shaba.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shaba.FocusColor = true;
			this.txt_shaba.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_267D_0 = this.txt_shaba;
			location = new global::System.Drawing.Point(362, 285);
			arg_267D_0.Location = location;
			this.txt_shaba.Name = "txt_shaba";
			this.txt_shaba.Nullable = true;
			this.txt_shaba.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shaba.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_26D6_0 = this.txt_shaba;
			size = new global::System.Drawing.Size(210, 36);
			arg_26D6_0.Size = size;
			this.txt_shaba.TabIndex = 7;
			this.txt_shaba.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.UiGroupBox2.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_2759_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(7, 212);
			arg_2759_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_2787_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(674, 24);
			arg_2787_0.Size = size;
			this.UiGroupBox2.TabIndex = 42;
			this.UiGroupBox2.Text = "اطلاعات صاحب حساب";
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this.OpenFileDialog1.RestoreDirectory = true;
			this.OpenFileDialog1.Title = "انتخاب تصویر";
			this.txt_enable.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_enable.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_enable.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_283C_0 = this.txt_enable;
			location = new global::System.Drawing.Point(76, 123);
			arg_283C_0.Location = location;
			this.txt_enable.Name = "txt_enable";
			global::System.Windows.Forms.Control arg_286A_0 = this.txt_enable;
			size = new global::System.Drawing.Size(152, 23);
			arg_286A_0.Size = size;
			this.txt_enable.TabIndex = 0;
			this.txt_enable.TabStop = false;
			this.txt_enable.Text = "حساب غیرفعال";
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Inherit;
			size = new global::System.Drawing.Size(681, 506);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Bank_Hesab";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "تعریف حساب بانکی";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040005E5 RID: 1509
		private global::System.ComponentModel.IContainer components;
	}
}
