namespace FruitBox
{
	// Token: 0x020000EF RID: 239
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frm_Frush_hag : global::System.Windows.Forms.Form
	{
		// Token: 0x06001A1E RID: 6686 RVA: 0x001296B8 File Offset: 0x001278B8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001A1F RID: 6687 RVA: 0x00129708 File Offset: 0x00127908
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column0.ButtonImage");
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.frm_Frush_hag));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference2 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column1.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference3 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column2.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference4 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column15.ButtonImage");
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_pardakhti = new global::FruitBox.CurrencyBox(this.components);
			this.txt_rizbar = new global::FruitBox.CurrencyBox(this.components);
			this.txt_makharej = new global::FruitBox.CurrencyBox(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_tarikhGrid = new global::FruitBox.DateBox2(this.components);
			this.Grid_RizBar = new global::FruitBox.DataEntryGrid(this.components);
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_jam_kol = new global::FruitBox.CurrencyBox(this.components);
			this.txt_fee = new global::FruitBox.CurrencyBox(this.components);
			this.txt_desc = new global::FruitBox.EditBox(this.components);
			this.txt_sh_mashin = new global::FruitBox.EditBox(this.components);
			this.txt_baskul_mabda = new global::FruitBox.NumericBox(this.components);
			this.txt_baskul = new global::FruitBox.NumericBox(this.components);
			this.txt_tedad = new global::FruitBox.NumericBox(this.components);
			this.txt_sh_barname = new global::FruitBox.EditBox(this.components);
			this.txt_tarikh_vurud = new global::FruitBox.DateBox2(this.components);
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			this.txt_num = new global::FruitBox.NavBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txt_kargari = new global::FruitBox.CurrencyBox(this.components);
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem14 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem13 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem10 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem12 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem15 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem16 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem17 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem18 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem19 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem1 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem2 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem3 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem4 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem5 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem6 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem9 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ControlContainerItem1 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.MicroChartItem1 = new global::DevComponents.DotNetBar.MicroChartItem();
			this.ItemContainer2 = new global::DevComponents.DotNetBar.ItemContainer();
			this.ControlContainerItem2 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_pardakhti);
			this.UiGroupBox1.Controls.Add(this.txt_rizbar);
			this.UiGroupBox1.Controls.Add(this.txt_makharej);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.txt_tarikhGrid);
			this.UiGroupBox1.Controls.Add(this.Grid_RizBar);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.txt_jam_kol);
			this.UiGroupBox1.Controls.Add(this.txt_fee);
			this.UiGroupBox1.Controls.Add(this.txt_desc);
			this.UiGroupBox1.Controls.Add(this.txt_sh_mashin);
			this.UiGroupBox1.Controls.Add(this.txt_baskul_mabda);
			this.UiGroupBox1.Controls.Add(this.txt_baskul);
			this.UiGroupBox1.Controls.Add(this.txt_tedad);
			this.UiGroupBox1.Controls.Add(this.txt_sh_barname);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh_vurud);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.txt_kargari);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_755_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 41);
			arg_755_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_793_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1536, 641);
			arg_793_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_pardakhti.AcceptEnter = true;
			this.txt_pardakhti.AllowEdit = true;
			this.txt_pardakhti.AllowNew = true;
			this.txt_pardakhti.AllowZero = true;
			this.txt_pardakhti.FocusColor = false;
			global::System.Windows.Forms.Control arg_80B_0 = this.txt_pardakhti;
			location = new global::System.Drawing.Point(65, 289);
			arg_80B_0.Location = location;
			this.txt_pardakhti.Name = "txt_pardakhti";
			this.txt_pardakhti.Nullable = true;
			this.txt_pardakhti.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_pardakhti.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_861_0 = this.txt_pardakhti;
			size = new global::System.Drawing.Size(100, 21);
			arg_861_0.Size = size;
			this.txt_pardakhti.TabIndex = 31;
			this.txt_pardakhti.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_pardakhti.Value = value;
			this.txt_pardakhti.Visible = false;
			this.txt_pardakhti.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_rizbar.AcceptEnter = true;
			this.txt_rizbar.AllowEdit = false;
			this.txt_rizbar.AllowNew = true;
			this.txt_rizbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_rizbar.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_rizbar.ButtonText = "...";
			this.txt_rizbar.FocusColor = true;
			this.txt_rizbar.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_942_0 = this.txt_rizbar;
			location = new global::System.Drawing.Point(976, 6);
			arg_942_0.Location = location;
			this.txt_rizbar.Name = "txt_rizbar";
			this.txt_rizbar.Nullable = true;
			this.txt_rizbar.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_rizbar.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_rizbar.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_9A8_0 = this.txt_rizbar;
			size = new global::System.Drawing.Size(144, 36);
			arg_9A8_0.Size = size;
			this.txt_rizbar.TabIndex = 5;
			this.txt_rizbar.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_rizbar.Value = value;
			this.txt_rizbar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_makharej.AcceptEnter = true;
			this.txt_makharej.AllowEdit = false;
			this.txt_makharej.AllowNew = true;
			this.txt_makharej.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_makharej.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_makharej.ButtonText = "...";
			this.txt_makharej.FocusColor = true;
			this.txt_makharej.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A7F_0 = this.txt_makharej;
			location = new global::System.Drawing.Point(976, 146);
			arg_A7F_0.Location = location;
			this.txt_makharej.Name = "txt_makharej";
			this.txt_makharej.Nullable = true;
			this.txt_makharej.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_makharej.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_makharej.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_AE5_0 = this.txt_makharej;
			size = new global::System.Drawing.Size(144, 36);
			arg_AE5_0.Size = size;
			this.txt_makharej.TabIndex = 9;
			this.txt_makharej.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_makharej.Value = value;
			this.txt_makharej.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B86_0 = this.Label2;
			location = new global::System.Drawing.Point(1122, 16);
			arg_B86_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_BB1_0 = this.Label2;
			size = new global::System.Drawing.Size(46, 19);
			arg_BB1_0.Size = size;
			this.Label2.TabIndex = 25;
			this.Label2.Text = "ریز بار";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C3E_0 = this.Label3;
			location = new global::System.Drawing.Point(1122, 155);
			arg_C3E_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_C69_0 = this.Label3;
			size = new global::System.Drawing.Size(98, 19);
			arg_C69_0.Size = size;
			this.Label3.TabIndex = 25;
			this.Label3.Text = "کرایه و مخارج";
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_CCB_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 615);
			arg_CCB_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_CF9_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1536, 26);
			arg_CF9_0.Size = size;
			this.UiGroupBox2.TabIndex = 24;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_tarikhGrid.AcceptEnter = false;
			this.txt_tarikhGrid.AllowEdit = true;
			this.txt_tarikhGrid.BorderStyle = global::Janus.Windows.GridEX.BorderStyle.None;
			this.txt_tarikhGrid.ButtonEnable = false;
			this.txt_tarikhGrid.ButtonEnabled = false;
			this.txt_tarikhGrid.FocusDatePart = 2;
			this.txt_tarikhGrid.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DA1_0 = this.txt_tarikhGrid;
			location = new global::System.Drawing.Point(12, 139);
			arg_DA1_0.Location = location;
			this.txt_tarikhGrid.Mask = "0000/00/00";
			this.txt_tarikhGrid.Name = "txt_tarikhGrid";
			this.txt_tarikhGrid.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_DEA_0 = this.txt_tarikhGrid;
			size = new global::System.Drawing.Size(100, 25);
			arg_DEA_0.Size = size;
			this.txt_tarikhGrid.TabIndex = 22;
			this.txt_tarikhGrid.Text = "1393/05/28";
			this.txt_tarikhGrid.Visible = false;
			this.txt_tarikhGrid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Grid_RizBar.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_RizBar.AlternatingColors = true;
			this.Grid_RizBar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.Grid_RizBar.AutoEdit = true;
			janusLayoutReference.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("Grid_RizBar_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference
			});
			gridEXLayout.LayoutString = componentResourceManager.GetString("Grid_RizBar_DesignTimeLayout.LayoutString");
			this.Grid_RizBar.DesignTimeLayout = gridEXLayout;
			this.Grid_RizBar.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_RizBar.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_RizBar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Grid_RizBar.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_RizBar.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_F1C_0 = this.Grid_RizBar;
			location = new global::System.Drawing.Point(0, 6);
			arg_F1C_0.Location = location;
			this.Grid_RizBar.Name = "Grid_RizBar";
			this.Grid_RizBar.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_RizBar.RowHeaderContent = global::Janus.Windows.GridEX.RowHeaderContent.RowIndex;
			global::System.Windows.Forms.Control arg_F67_0 = this.Grid_RizBar;
			size = new global::System.Drawing.Size(970, 211);
			arg_F67_0.Size = size;
			this.Grid_RizBar.TabIndex = 21;
			this.Grid_RizBar.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.Grid_RizBar.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_RizBar.Visible = false;
			this.Grid_RizBar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridEX1.AcceptsEscape = false;
			this.GridEX1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			janusLayoutReference2.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference3.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_1.Instance"));
			janusLayoutReference4.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_2.Instance"));
			gridEXLayout2.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference2,
				janusLayoutReference3,
				janusLayoutReference4
			});
			gridEXLayout2.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout2;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_10F2_0 = this.GridEX1;
			location = new global::System.Drawing.Point(0, 223);
			arg_10F2_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_114A_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1536, 391);
			arg_114A_0.Size = size;
			this.GridEX1.TabIndex = 13;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jam_kol.AcceptEnter = false;
			this.txt_jam_kol.AllowEdit = true;
			this.txt_jam_kol.AllowNew = true;
			this.txt_jam_kol.AllowZero = true;
			this.txt_jam_kol.FocusColor = false;
			global::System.Windows.Forms.Control arg_122B_0 = this.txt_jam_kol;
			location = new global::System.Drawing.Point(324, 271);
			arg_122B_0.Location = location;
			this.txt_jam_kol.Name = "txt_jam_kol";
			this.txt_jam_kol.Nullable = true;
			this.txt_jam_kol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jam_kol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1281_0 = this.txt_jam_kol;
			size = new global::System.Drawing.Size(100, 21);
			arg_1281_0.Size = size;
			this.txt_jam_kol.TabIndex = 14;
			this.txt_jam_kol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jam_kol.Value = value;
			this.txt_jam_kol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fee.AcceptEnter = true;
			this.txt_fee.AllowEdit = true;
			this.txt_fee.AllowNew = true;
			this.txt_fee.AllowZero = true;
			this.txt_fee.FocusColor = false;
			global::System.Windows.Forms.Control arg_1315_0 = this.txt_fee;
			location = new global::System.Drawing.Point(65, 262);
			arg_1315_0.Location = location;
			this.txt_fee.Name = "txt_fee";
			this.txt_fee.Nullable = true;
			this.txt_fee.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fee.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_136B_0 = this.txt_fee;
			size = new global::System.Drawing.Size(100, 21);
			arg_136B_0.Size = size;
			this.txt_fee.TabIndex = 13;
			this.txt_fee.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fee.Value = value;
			this.txt_fee.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_desc.AcceptEnter = false;
			this.txt_desc.AllowEdit = true;
			this.txt_desc.AllowNew = true;
			this.txt_desc.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_desc.FocusColor = true;
			this.txt_desc.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1425_0 = this.txt_desc;
			location = new global::System.Drawing.Point(976, 181);
			arg_1425_0.Location = location;
			this.txt_desc.Name = "txt_desc";
			this.txt_desc.Nullable = true;
			this.txt_desc.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_desc.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_147E_0 = this.txt_desc;
			size = new global::System.Drawing.Size(445, 36);
			arg_147E_0.Size = size;
			this.txt_desc.TabIndex = 10;
			this.txt_desc.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sh_mashin.AcceptEnter = true;
			this.txt_sh_mashin.AllowEdit = true;
			this.txt_sh_mashin.AllowNew = true;
			this.txt_sh_mashin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_mashin.FocusColor = true;
			this.txt_sh_mashin.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_151A_0 = this.txt_sh_mashin;
			location = new global::System.Drawing.Point(1224, 76);
			arg_151A_0.Location = location;
			this.txt_sh_mashin.MaxLength = 9;
			this.txt_sh_mashin.Name = "txt_sh_mashin";
			this.txt_sh_mashin.Nullable = true;
			this.txt_sh_mashin.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sh_mashin.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1581_0 = this.txt_sh_mashin;
			size = new global::System.Drawing.Size(197, 36);
			arg_1581_0.Size = size;
			this.txt_sh_mashin.TabIndex = 2;
			this.txt_sh_mashin.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_baskul_mabda.AcceptEnter = true;
			this.txt_baskul_mabda.AllowEdit = true;
			this.txt_baskul_mabda.AllowNew = true;
			this.txt_baskul_mabda.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_baskul_mabda.FocusColor = true;
			this.txt_baskul_mabda.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_161C_0 = this.txt_baskul_mabda;
			location = new global::System.Drawing.Point(976, 41);
			arg_161C_0.Location = location;
			this.txt_baskul_mabda.Name = "txt_baskul_mabda";
			this.txt_baskul_mabda.Nullable = true;
			this.txt_baskul_mabda.NullToolTipText = "لطفا وزن باسکول را وارد نمائید";
			this.txt_baskul_mabda.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1675_0 = this.txt_baskul_mabda;
			size = new global::System.Drawing.Size(144, 36);
			arg_1675_0.Size = size;
			this.txt_baskul_mabda.TabIndex = 6;
			this.txt_baskul_mabda.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_baskul_mabda.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_baskul.AcceptEnter = true;
			this.txt_baskul.AllowEdit = true;
			this.txt_baskul.AllowNew = true;
			this.txt_baskul.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_baskul.DecimalDigits = 1;
			this.txt_baskul.FocusColor = true;
			this.txt_baskul.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_172A_0 = this.txt_baskul;
			location = new global::System.Drawing.Point(976, 76);
			arg_172A_0.Location = location;
			this.txt_baskul.Name = "txt_baskul";
			this.txt_baskul.Nullable = true;
			this.txt_baskul.NullToolTipText = "لطفا وزن باسکول را وارد نمائید";
			this.txt_baskul.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1783_0 = this.txt_baskul;
			size = new global::System.Drawing.Size(144, 36);
			arg_1783_0.Size = size;
			this.txt_baskul.TabIndex = 7;
			this.txt_baskul.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_baskul.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tedad.AcceptEnter = true;
			this.txt_tedad.AllowEdit = true;
			this.txt_tedad.AllowNew = true;
			this.txt_tedad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedad.DecimalDigits = 1;
			this.txt_tedad.FocusColor = true;
			this.txt_tedad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1838_0 = this.txt_tedad;
			location = new global::System.Drawing.Point(976, 111);
			arg_1838_0.Location = location;
			this.txt_tedad.Name = "txt_tedad";
			this.txt_tedad.Nullable = true;
			this.txt_tedad.NullToolTipText = "لطفا تعداد کل بار را مشخص فرمائید";
			this.txt_tedad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1891_0 = this.txt_tedad;
			size = new global::System.Drawing.Size(144, 36);
			arg_1891_0.Size = size;
			this.txt_tedad.TabIndex = 8;
			this.txt_tedad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_tedad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sh_barname.AcceptEnter = true;
			this.txt_sh_barname.AllowEdit = true;
			this.txt_sh_barname.AllowNew = true;
			this.txt_sh_barname.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_barname.FocusColor = true;
			this.txt_sh_barname.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1939_0 = this.txt_sh_barname;
			location = new global::System.Drawing.Point(1224, 111);
			arg_1939_0.Location = location;
			this.txt_sh_barname.Name = "txt_sh_barname";
			this.txt_sh_barname.Nullable = true;
			this.txt_sh_barname.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sh_barname.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1992_0 = this.txt_sh_barname;
			size = new global::System.Drawing.Size(197, 36);
			arg_1992_0.Size = size;
			this.txt_sh_barname.TabIndex = 3;
			this.txt_sh_barname.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikh_vurud.AcceptEnter = true;
			this.txt_tarikh_vurud.AllowEdit = true;
			this.txt_tarikh_vurud.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh_vurud.ButtonEnable = false;
			this.txt_tarikh_vurud.FocusDatePart = 2;
			this.txt_tarikh_vurud.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A30_0 = this.txt_tarikh_vurud;
			location = new global::System.Drawing.Point(1224, 146);
			arg_1A30_0.Location = location;
			this.txt_tarikh_vurud.Mask = "0000/00/00";
			this.txt_tarikh_vurud.Name = "txt_tarikh_vurud";
			this.txt_tarikh_vurud.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_1A7C_0 = this.txt_tarikh_vurud;
			size = new global::System.Drawing.Size(197, 36);
			arg_1A7C_0.Size = size;
			this.txt_tarikh_vurud.TabIndex = 4;
			this.txt_tarikh_vurud.Text = "1392/07/08";
			this.txt_tarikh_vurud.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari.AcceptEnter = true;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = true;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "shahr";
			column3.Size = 20;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_1C1C_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(1224, 41);
			arg_1C1C_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = false;
			this.txt_moshtari.NullToolTipText = "لطفا صاحب بار را مشخص فرمائید";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1CA7_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(197, 36);
			arg_1CA7_0.Size = size;
			this.txt_moshtari.TabIndex = 1;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1D49_0 = this.txt_num;
			location = new global::System.Drawing.Point(1224, 6);
			arg_1D49_0.Location = location;
			global::System.Windows.Forms.Control arg_1D63_0 = this.txt_num;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			arg_1D63_0.Margin = margin;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_1D91_0 = this.txt_num;
			size = new global::System.Drawing.Size(197, 36);
			arg_1D91_0.Size = size;
			this.txt_num.TabIndex = 0;
			this.txt_num.Value = "";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1E1D_0 = this.Label12;
			location = new global::System.Drawing.Point(1423, 189);
			arg_1E1D_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_1E48_0 = this.Label12;
			size = new global::System.Drawing.Size(69, 19);
			arg_1E48_0.Size = size;
			this.Label12.TabIndex = 0;
			this.Label12.Text = "ملاحضات";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1ED4_0 = this.Label11;
			location = new global::System.Drawing.Point(1423, 154);
			arg_1ED4_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1EFF_0 = this.Label11;
			size = new global::System.Drawing.Size(91, 19);
			arg_1EFF_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "تاریخ ورود بار";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1F88_0 = this.Label7;
			location = new global::System.Drawing.Point(1122, 51);
			arg_1F88_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_1FB3_0 = this.Label7;
			size = new global::System.Drawing.Size(92, 19);
			arg_1FB3_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "باسکول مبدا";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_203C_0 = this.Label10;
			location = new global::System.Drawing.Point(1423, 119);
			arg_203C_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_2067_0 = this.Label10;
			size = new global::System.Drawing.Size(100, 19);
			arg_2067_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "شماره بارنامه";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20F0_0 = this.Label4;
			location = new global::System.Drawing.Point(1122, 85);
			arg_20F0_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_211B_0 = this.Label4;
			size = new global::System.Drawing.Size(60, 19);
			arg_211B_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "باسکول";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_21A4_0 = this.Label6;
			location = new global::System.Drawing.Point(1122, 119);
			arg_21A4_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_21CF_0 = this.Label6;
			size = new global::System.Drawing.Size(66, 19);
			arg_21CF_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "تعداد کل";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2258_0 = this.Label9;
			location = new global::System.Drawing.Point(1423, 85);
			arg_2258_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_2283_0 = this.Label9;
			size = new global::System.Drawing.Size(106, 19);
			arg_2283_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "شماره ماشین";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2319_0 = this.Label5;
			location = new global::System.Drawing.Point(1423, 49);
			arg_2319_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_2344_0 = this.Label5;
			size = new global::System.Drawing.Size(72, 19);
			arg_2344_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "صاحب بار";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_23DB_0 = this.Label1;
			location = new global::System.Drawing.Point(1423, 16);
			arg_23DB_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_2406_0 = this.Label1;
			size = new global::System.Drawing.Size(90, 19);
			arg_2406_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "شماره سند";
			this.txt_kargari.AcceptEnter = true;
			this.txt_kargari.AllowEdit = true;
			this.txt_kargari.AllowNew = true;
			this.txt_kargari.AllowZero = true;
			this.txt_kargari.FocusColor = false;
			global::System.Windows.Forms.Control arg_2482_0 = this.txt_kargari;
			location = new global::System.Drawing.Point(65, 362);
			arg_2482_0.Location = location;
			this.txt_kargari.Name = "txt_kargari";
			this.txt_kargari.Nullable = true;
			this.txt_kargari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kargari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_24D8_0 = this.txt_kargari;
			size = new global::System.Drawing.Size(100, 21);
			arg_24D8_0.Size = size;
			this.txt_kargari.TabIndex = 26;
			this.txt_kargari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kargari.Value = value;
			this.txt_kargari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem11,
				this.ButtonItem14,
				this.ButtonItem6,
				this.ButtonItem13,
				this.ButtonItem4,
				this.ButtonItem10,
				this.ButtonItem5,
				this.ButtonItem7,
				this.ButtonItem3,
				this.ButtonItem12,
				this.ButtonItem15
			});
			global::DevComponents.DotNetBar.Bar arg_260D_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_260D_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_263B_0 = this.Bar1;
			size = new global::System.Drawing.Size(1536, 41);
			arg_263B_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 12;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "صورتحساب (F3)";
			this.ButtonItem14.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem14.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem14.Name = "ButtonItem14";
			this.ButtonItem14.Text = "چاپ (F4)";
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "حذف ردیف (F5)";
			this.ButtonItem13.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem13.Image = global::FruitBox.My.Resources.Resources.report_open_edit;
			this.ButtonItem13.Name = "ButtonItem13";
			this.ButtonItem13.Text = "ویرایش بارنامه (F6)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.transport_table;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "ثبت ریز بار (F7)";
			this.ButtonItem10.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem10.Image = global::FruitBox.My.Resources.Resources.order_coins;
			this.ButtonItem10.Name = "ButtonItem10";
			this.ButtonItem10.Text = "کرایه و مخارج (F8)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.order;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "ثبت صافی بار (F9)";
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.report_open_edit;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "اصلاح اطلاعات (F10)";
			this.ButtonItem7.Visible = false;
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف سند  (Ctrl + F5)";
			this.ButtonItem12.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem12.Image = global::FruitBox.My.Resources.Resources.relations_remove;
			this.ButtonItem12.Name = "ButtonItem12";
			this.ButtonItem12.Text = "کسر اتوماتیک";
			this.ButtonItem15.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem15.Image = global::FruitBox.My.Resources.Resources.table;
			this.ButtonItem15.Name = "ButtonItem15";
			this.ButtonItem15.SubItems.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem16,
				this.ButtonItem17,
				this.ButtonItem18,
				this.ButtonItem19
			});
			this.ButtonItem15.Text = "نحوه فروش";
			this.ButtonItem16.Name = "ButtonItem16";
			this.ButtonItem16.Text = "تعداد - وزن خالص";
			this.ButtonItem17.Name = "ButtonItem17";
			this.ButtonItem17.Text = "وزن خالص";
			this.ButtonItem18.Name = "ButtonItem18";
			this.ButtonItem18.Text = "تعداد";
			this.ButtonItem19.Name = "ButtonItem19";
			this.ButtonItem19.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			this.LabelItem1.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem1.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem1.Name = "LabelItem1";
			this.LabelItem1.Text = "وضعیت مشتری";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.TextOnlyAlways;
			global::DevComponents.DotNetBar.ButtonItem arg_2B1B_0 = this.ButtonItem8;
			size = new global::System.Drawing.Size(150, 0);
			arg_2B1B_0.FixedSize = size;
			this.ButtonItem8.ItemAlignment = global::DevComponents.DotNetBar.eItemAlignment.Center;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "0";
			this.LabelItem2.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem2.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem2.Name = "LabelItem2";
			this.LabelItem2.Text = "         بدهکار";
			this.LabelItem3.BackColor = global::System.Drawing.Color.Transparent;
			this.LabelItem3.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem3.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem3.Name = "LabelItem3";
			this.LabelItem3.Text = "        آخرین پرداختی";
			this.LabelItem4.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem4.Name = "LabelItem4";
			this.LabelItem4.Text = "000";
			this.LabelItem5.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem5.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem5.Name = "LabelItem5";
			this.LabelItem5.Text = "        تاریخ آخرین پرداختی";
			this.LabelItem6.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem6.Name = "LabelItem6";
			this.LabelItem6.Text = "1393/05/05";
			this.ButtonItem9.Name = "ButtonItem9";
			this.ButtonItem9.Text = "صورتحساب";
			this.ControlContainerItem1.AllowItemResize = false;
			this.ControlContainerItem1.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem1.Name = "ControlContainerItem1";
			this.MicroChartItem1.Name = "MicroChartItem1";
			this.ItemContainer2.BackgroundStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ItemContainer2.Name = "ItemContainer2";
			this.ItemContainer2.TitleStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ControlContainerItem2.AllowItemResize = true;
			this.ControlContainerItem2.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem2.Name = "ControlContainerItem2";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_2E03_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 656);
			arg_2E03_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_2E78_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1536, 26);
			arg_2E78_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 25;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.LabelCommand5.Key = "LabelCommand5";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand6";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand6.Text = "جمع نسیه";
			this.LabelCommand7.Key = "LabelCommand7";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand8";
			this.LabelCommand8.Name = "LabelCommand8";
			this.LabelCommand8.Text = "جمع نقد";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1536, 682);
			this.ClientSize = size;
			this.Controls.Add(this.RibbonStatusBar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.Bar1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "frm_Frush_hag";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "فروش حق العمل";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000A2F RID: 2607
		private global::System.ComponentModel.IContainer components;
	}
}
