namespace FruitBox
{
	// Token: 0x020000F4 RID: 244
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Furush_Nesie : global::System.Windows.Forms.Form
	{
		// Token: 0x06001C32 RID: 7218 RVA: 0x0014972C File Offset: 0x0014792C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001C33 RID: 7219 RVA: 0x0014977C File Offset: 0x0014797C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column0.ButtonImage");
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Furush_Nesie));
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference2 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column0.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference3 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column1.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference4 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column13.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference5 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column19.ButtonImage");
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_num = new global::FruitBox.NavBox();
			this.txt_naghd = new global::FruitBox.CurrencyBox(this.components);
			this.grid_moshtari = new global::FruitBox.DataEntryGrid(this.components);
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txt_tarikh = new global::FruitBox.DateBox2(this.components);
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txt_fee_n = new global::FruitBox.CurrencyBox(this.components);
			this.txt_jamkol_n = new global::FruitBox.CurrencyBox(this.components);
			this.gridex1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_kargari = new global::FruitBox.CurrencyBox(this.components);
			this.txt_jam_kol = new global::FruitBox.CurrencyBox(this.components);
			this.txt_fee = new global::FruitBox.CurrencyBox(this.components);
			this.txt_sh_mashin = new global::FruitBox.EditBox(this.components);
			this.txt_makharej = new global::FruitBox.CurrencyBox(this.components);
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem15 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem16 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem17 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem18 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem19 = new global::DevComponents.DotNetBar.ButtonItem();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.object_8574e8dd_4059_400c_bbfc_de488f785574 = new global::FruitBox.NumericBox(this.components);
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e = new global::FruitBox.NumericBox(this.components);
			this.NumericBox1 = new global::FruitBox.NumericBox(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.grid_moshtari).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.gridex1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.txt_naghd);
			this.UiGroupBox1.Controls.Add(this.grid_moshtari);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.txt_fee_n);
			this.UiGroupBox1.Controls.Add(this.txt_jamkol_n);
			this.UiGroupBox1.Controls.Add(this.gridex1);
			this.UiGroupBox1.Controls.Add(this.txt_kargari);
			this.UiGroupBox1.Controls.Add(this.txt_jam_kol);
			this.UiGroupBox1.Controls.Add(this.txt_fee);
			this.UiGroupBox1.Controls.Add(this.txt_sh_mashin);
			this.UiGroupBox1.Controls.Add(this.txt_makharej);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.RibbonStatusBar1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_53B_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_53B_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_56C_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1299, 629);
			arg_56C_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_5E4_0 = this.txt_num;
			location = new global::System.Drawing.Point(808, 94);
			arg_5E4_0.Location = location;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_612_0 = this.txt_num;
			size = new global::System.Drawing.Size(171, 36);
			arg_612_0.Size = size;
			this.txt_num.TabIndex = 37;
			this.txt_num.Value = "";
			this.txt_naghd.AcceptEnter = true;
			this.txt_naghd.AllowEdit = true;
			this.txt_naghd.AllowNew = true;
			this.txt_naghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_naghd.FocusColor = true;
			this.txt_naghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_6B2_0 = this.txt_naghd;
			location = new global::System.Drawing.Point(1078, 94);
			arg_6B2_0.Location = location;
			this.txt_naghd.Name = "txt_naghd";
			this.txt_naghd.Nullable = true;
			this.txt_naghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_naghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_708_0 = this.txt_naghd;
			size = new global::System.Drawing.Size(124, 36);
			arg_708_0.Size = size;
			this.txt_naghd.TabIndex = 36;
			this.txt_naghd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_naghd.Value = value;
			this.txt_naghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.grid_moshtari.AcceptsEscape = false;
			this.grid_moshtari.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.grid_moshtari.AlternatingColors = true;
			this.grid_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			janusLayoutReference.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("grid_moshtari_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference
			});
			gridEXLayout.LayoutString = componentResourceManager.GetString("grid_moshtari_DesignTimeLayout.LayoutString");
			this.grid_moshtari.DesignTimeLayout = gridEXLayout;
			this.grid_moshtari.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.grid_moshtari.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.grid_moshtari.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.grid_moshtari.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.grid_moshtari.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_833_0 = this.grid_moshtari;
			location = new global::System.Drawing.Point(0, 136);
			arg_833_0.Location = location;
			this.grid_moshtari.Name = "grid_moshtari";
			this.grid_moshtari.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.grid_moshtari.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_87E_0 = this.grid_moshtari;
			size = new global::System.Drawing.Size(537, 467);
			arg_87E_0.Size = size;
			this.grid_moshtari.TabIndex = 35;
			this.grid_moshtari.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.grid_moshtari.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.grid_moshtari.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.grid_moshtari.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.grid_moshtari.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.grid_moshtari.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.grid_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_969_0 = this.Label6;
			location = new global::System.Drawing.Point(976, 103);
			arg_969_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_994_0 = this.Label6;
			size = new global::System.Drawing.Size(98, 19);
			arg_994_0.Size = size;
			this.Label6.TabIndex = 34;
			this.Label6.Text = "شماره فاکتور";
			this.txt_moshtari.AcceptEnter = true;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = true;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "shahr";
			column3.Size = 20;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_B28_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(748, 52);
			arg_B28_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = false;
			this.txt_moshtari.NullToolTipText = "لطفا صاحب بار را مشخص فرمائید";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_BB3_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(231, 36);
			arg_BB3_0.Size = size;
			this.txt_moshtari.TabIndex = 1;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C63_0 = this.Label2;
			location = new global::System.Drawing.Point(1204, 103);
			arg_C63_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_C8E_0 = this.Label2;
			size = new global::System.Drawing.Size(93, 19);
			arg_C8E_0.Size = size;
			this.Label2.TabIndex = 34;
			this.Label2.Text = "دریافت نقدی";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D18_0 = this.Label5;
			location = new global::System.Drawing.Point(981, 61);
			arg_D18_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_D43_0 = this.Label5;
			size = new global::System.Drawing.Size(61, 19);
			arg_D43_0.Size = size;
			this.Label5.TabIndex = 34;
			this.Label5.Text = "مشتری";
			this.txt_tarikh.AcceptEnter = true;
			this.txt_tarikh.AllowEdit = true;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh.ButtonEnable = true;
			this.txt_tarikh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			this.txt_tarikh.FocusDatePart = 2;
			this.txt_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DF0_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(1077, 52);
			arg_DF0_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_E39_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(125, 36);
			arg_E39_0.Size = size;
			this.txt_tarikh.TabIndex = 0;
			this.txt_tarikh.Text = "1392/10/02";
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_EAD_0 = this.Label1;
			location = new global::System.Drawing.Point(1204, 61);
			arg_EAD_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_ED8_0 = this.Label1;
			size = new global::System.Drawing.Size(39, 19);
			arg_ED8_0.Size = size;
			this.Label1.TabIndex = 32;
			this.Label1.Text = "تاریخ";
			this.txt_fee_n.AcceptEnter = false;
			this.txt_fee_n.AllowEdit = true;
			this.txt_fee_n.AllowNew = true;
			this.txt_fee_n.AllowZero = true;
			this.txt_fee_n.FocusColor = false;
			global::System.Windows.Forms.Control arg_F55_0 = this.txt_fee_n;
			location = new global::System.Drawing.Point(455, 84);
			arg_F55_0.Location = location;
			this.txt_fee_n.Name = "txt_fee_n";
			this.txt_fee_n.Nullable = true;
			this.txt_fee_n.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fee_n.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_FAB_0 = this.txt_fee_n;
			size = new global::System.Drawing.Size(100, 27);
			arg_FAB_0.Size = size;
			this.txt_fee_n.TabIndex = 31;
			this.txt_fee_n.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fee_n.Value = value;
			this.txt_fee_n.Visible = false;
			this.txt_fee_n.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jamkol_n.AcceptEnter = true;
			this.txt_jamkol_n.AllowEdit = true;
			this.txt_jamkol_n.AllowNew = true;
			this.txt_jamkol_n.AllowZero = true;
			this.txt_jamkol_n.FocusColor = false;
			global::System.Windows.Forms.Control arg_104C_0 = this.txt_jamkol_n;
			location = new global::System.Drawing.Point(339, 84);
			arg_104C_0.Location = location;
			this.txt_jamkol_n.Name = "txt_jamkol_n";
			this.txt_jamkol_n.Nullable = true;
			this.txt_jamkol_n.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jamkol_n.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_10A2_0 = this.txt_jamkol_n;
			size = new global::System.Drawing.Size(100, 27);
			arg_10A2_0.Size = size;
			this.txt_jamkol_n.TabIndex = 30;
			this.txt_jamkol_n.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jamkol_n.Value = value;
			this.txt_jamkol_n.Visible = false;
			this.txt_jamkol_n.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.gridex1.AcceptsEscape = false;
			this.gridex1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.gridex1.AlternatingColors = true;
			this.gridex1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			janusLayoutReference2.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("gridex1_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference3.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("gridex1_DesignTimeLayout_Reference_1.Instance"));
			janusLayoutReference4.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("gridex1_DesignTimeLayout_Reference_2.Instance"));
			janusLayoutReference5.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("gridex1_DesignTimeLayout_Reference_3.Instance"));
			gridEXLayout2.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference2,
				janusLayoutReference3,
				janusLayoutReference4,
				janusLayoutReference5
			});
			gridEXLayout2.LayoutString = componentResourceManager.GetString("gridex1_DesignTimeLayout.LayoutString");
			this.gridex1.DesignTimeLayout = gridEXLayout2;
			this.gridex1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.gridex1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.gridex1.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.gridex1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.gridex1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1242_0 = this.gridex1;
			location = new global::System.Drawing.Point(543, 136);
			arg_1242_0.Location = location;
			this.gridex1.Name = "gridex1";
			this.gridex1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.gridex1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_128D_0 = this.gridex1;
			size = new global::System.Drawing.Size(756, 467);
			arg_128D_0.Size = size;
			this.gridex1.TabIndex = 29;
			this.gridex1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.gridex1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.gridex1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.gridex1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.gridex1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.gridex1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.gridex1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kargari.AcceptEnter = true;
			this.txt_kargari.AllowEdit = true;
			this.txt_kargari.AllowNew = true;
			this.txt_kargari.AllowZero = true;
			this.txt_kargari.FocusColor = false;
			global::System.Windows.Forms.Control arg_136B_0 = this.txt_kargari;
			location = new global::System.Drawing.Point(239, 84);
			arg_136B_0.Location = location;
			this.txt_kargari.Name = "txt_kargari";
			this.txt_kargari.Nullable = true;
			this.txt_kargari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kargari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_13C1_0 = this.txt_kargari;
			size = new global::System.Drawing.Size(100, 27);
			arg_13C1_0.Size = size;
			this.txt_kargari.TabIndex = 27;
			this.txt_kargari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kargari.Value = value;
			this.txt_kargari.Visible = false;
			this.txt_kargari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jam_kol.AcceptEnter = false;
			this.txt_jam_kol.AllowEdit = true;
			this.txt_jam_kol.AllowNew = true;
			this.txt_jam_kol.AllowZero = true;
			this.txt_jam_kol.FocusColor = false;
			global::System.Windows.Forms.Control arg_1462_0 = this.txt_jam_kol;
			location = new global::System.Drawing.Point(133, 84);
			arg_1462_0.Location = location;
			this.txt_jam_kol.Name = "txt_jam_kol";
			this.txt_jam_kol.Nullable = true;
			this.txt_jam_kol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jam_kol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_14B8_0 = this.txt_jam_kol;
			size = new global::System.Drawing.Size(100, 27);
			arg_14B8_0.Size = size;
			this.txt_jam_kol.TabIndex = 22;
			this.txt_jam_kol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jam_kol.Value = value;
			this.txt_jam_kol.Visible = false;
			this.txt_jam_kol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fee.AcceptEnter = true;
			this.txt_fee.AllowEdit = true;
			this.txt_fee.AllowNew = true;
			this.txt_fee.AllowZero = true;
			this.txt_fee.FocusColor = false;
			global::System.Windows.Forms.Control arg_1556_0 = this.txt_fee;
			location = new global::System.Drawing.Point(17, 84);
			arg_1556_0.Location = location;
			this.txt_fee.Name = "txt_fee";
			this.txt_fee.Nullable = true;
			this.txt_fee.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fee.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_15AC_0 = this.txt_fee;
			size = new global::System.Drawing.Size(100, 27);
			arg_15AC_0.Size = size;
			this.txt_fee.TabIndex = 21;
			this.txt_fee.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fee.Value = value;
			this.txt_fee.Visible = false;
			this.txt_fee.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sh_mashin.AcceptEnter = true;
			this.txt_sh_mashin.AllowEdit = true;
			this.txt_sh_mashin.AllowNew = true;
			this.txt_sh_mashin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_mashin.FocusColor = true;
			this.txt_sh_mashin.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1670_0 = this.txt_sh_mashin;
			location = new global::System.Drawing.Point(254, 42);
			arg_1670_0.Location = location;
			this.txt_sh_mashin.MaxLength = 9;
			this.txt_sh_mashin.Name = "txt_sh_mashin";
			this.txt_sh_mashin.Nullable = true;
			this.txt_sh_mashin.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sh_mashin.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_16D7_0 = this.txt_sh_mashin;
			size = new global::System.Drawing.Size(197, 36);
			arg_16D7_0.Size = size;
			this.txt_sh_mashin.TabIndex = 2;
			this.txt_sh_mashin.Visible = false;
			this.txt_sh_mashin.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_makharej.AcceptEnter = true;
			this.txt_makharej.AllowEdit = true;
			this.txt_makharej.AllowNew = true;
			this.txt_makharej.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_makharej.ButtonText = "...";
			this.txt_makharej.FocusColor = true;
			this.txt_makharej.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_178D_0 = this.txt_makharej;
			location = new global::System.Drawing.Point(-38, 42);
			arg_178D_0.Location = location;
			this.txt_makharej.Name = "txt_makharej";
			this.txt_makharej.Nullable = true;
			this.txt_makharej.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_makharej.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_makharej.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_17F3_0 = this.txt_makharej;
			size = new global::System.Drawing.Size(197, 36);
			arg_17F3_0.Size = size;
			this.txt_makharej.TabIndex = 3;
			this.txt_makharej.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_makharej.Value = value;
			this.txt_makharej.Visible = false;
			this.txt_makharej.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_187E_0 = this.Label4;
			location = new global::System.Drawing.Point(161, 50);
			arg_187E_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_18A9_0 = this.Label4;
			size = new global::System.Drawing.Size(41, 19);
			arg_18A9_0.Size = size;
			this.Label4.TabIndex = 17;
			this.Label4.Text = "کرایه";
			this.Label4.Visible = false;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_191E_0 = this.Label3;
			location = new global::System.Drawing.Point(453, 50);
			arg_191E_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1949_0 = this.Label3;
			size = new global::System.Drawing.Size(106, 19);
			arg_1949_0.Size = size;
			this.Label3.TabIndex = 17;
			this.Label3.Text = "شماره ماشین";
			this.Label3.Visible = false;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem11,
				this.ButtonItem3,
				this.ButtonItem15
			});
			global::DevComponents.DotNetBar.Bar arg_1A24_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_1A24_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_1A52_0 = this.Bar1;
			size = new global::System.Drawing.Size(1299, 41);
			arg_1A52_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 16;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem1.Visible = false;
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "صورتحساب (F3)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف ردیف (F5)";
			this.ButtonItem15.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem15.Image = global::FruitBox.My.Resources.Resources.table;
			this.ButtonItem15.Name = "ButtonItem15";
			this.ButtonItem15.SubItems.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem16,
				this.ButtonItem17,
				this.ButtonItem18,
				this.ButtonItem19
			});
			this.ButtonItem15.Text = "نحوه فروش";
			this.ButtonItem16.Name = "ButtonItem16";
			this.ButtonItem16.Text = "تعداد - وزن خالص";
			this.ButtonItem17.Name = "ButtonItem17";
			this.ButtonItem17.Text = "وزن خالص";
			this.ButtonItem18.Name = "ButtonItem18";
			this.ButtonItem18.Text = "تعداد";
			this.ButtonItem19.Name = "ButtonItem19";
			this.ButtonItem19.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_1D39_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 603);
			arg_1D39_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_1DAE_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1299, 26);
			arg_1DAE_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 28;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.LabelCommand5.Key = "LabelCommand1";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand2";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand7.Key = "LabelCommand3";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand4";
			this.LabelCommand8.Name = "LabelCommand8";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			this.Timer1.Enabled = true;
			this.Timer1.Interval = 200;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.AcceptEnter = true;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.AllowEdit = true;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.AllowNew = true;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.FocusColor = true;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1FAB_0 = this.object_8574e8dd_4059_400c_bbfc_de488f785574;
			location = new global::System.Drawing.Point(0, 0);
			arg_1FAB_0.Location = location;
			global::System.Windows.Forms.Control arg_1FC5_0 = this.object_8574e8dd_4059_400c_bbfc_de488f785574;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 6, 3, 6);
			arg_1FC5_0.Margin = margin;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.Name = "object_8574e8dd_4059_400c_bbfc_de488f785574";
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.Nullable = true;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_201B_0 = this.object_8574e8dd_4059_400c_bbfc_de488f785574;
			size = new global::System.Drawing.Size(114, 27);
			arg_201B_0.Size = size;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.TabIndex = 0;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Center;
			this.object_8574e8dd_4059_400c_bbfc_de488f785574.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.AcceptEnter = true;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.AllowEdit = true;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.AllowNew = true;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.FocusColor = true;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20BD_0 = this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e;
			location = new global::System.Drawing.Point(0, 0);
			arg_20BD_0.Location = location;
			global::System.Windows.Forms.Control arg_20D7_0 = this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e;
			margin = new global::System.Windows.Forms.Padding(3, 6, 3, 6);
			arg_20D7_0.Margin = margin;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.Name = "object_f9b79304_ca6f_46b8_84fb_aeebc487606e";
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.Nullable = true;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_212D_0 = this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e;
			size = new global::System.Drawing.Size(114, 27);
			arg_212D_0.Size = size;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.TabIndex = 0;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Center;
			this.object_f9b79304_ca6f_46b8_84fb_aeebc487606e.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.NumericBox1.AcceptEnter = true;
			this.NumericBox1.AllowEdit = true;
			this.NumericBox1.AllowNew = true;
			this.NumericBox1.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.NumericBox1.FocusColor = true;
			this.NumericBox1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_21CF_0 = this.NumericBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_21CF_0.Location = location;
			global::System.Windows.Forms.Control arg_21E9_0 = this.NumericBox1;
			margin = new global::System.Windows.Forms.Padding(3, 5, 3, 5);
			arg_21E9_0.Margin = margin;
			this.NumericBox1.Name = "NumericBox1";
			this.NumericBox1.Nullable = true;
			this.NumericBox1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.NumericBox1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_223F_0 = this.NumericBox1;
			size = new global::System.Drawing.Size(98, 27);
			arg_223F_0.Size = size;
			this.NumericBox1.TabIndex = 0;
			this.NumericBox1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Center;
			this.NumericBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(9f, 19f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1299, 629);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Furush_Nesie";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "ثبت فاکتور فروش";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.grid_moshtari).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.gridex1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000AFB RID: 2811
		private global::System.ComponentModel.IContainer components;
	}
}
