namespace FruitBox
{
	// Token: 0x02000144 RID: 324
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_SuratHesab_Daryafti_Moshtari : global::System.Windows.Forms.Form
	{
		// Token: 0x06002F75 RID: 12149 RVA: 0x0022F464 File Offset: 0x0022D664
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002F76 RID: 12150 RVA: 0x0022F4B4 File Offset: 0x0022D6B4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_SuratHesab_Daryafti_Moshtari));
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_jamkharid = new global::Janus.Windows.EditControls.UICheckBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.lbl_shahr = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.lbl_tedad_havale = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.lbl_tedad_safi = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.lbl_addr = new global::System.Windows.Forms.Label();
			this.lbl_code = new global::System.Windows.Forms.Label();
			this.lbl_codemelli = new global::System.Windows.Forms.Label();
			this.lbl_tel3 = new global::System.Windows.Forms.Label();
			this.lbl_tel4 = new global::System.Windows.Forms.Label();
			this.lbl_tel2 = new global::System.Windows.Forms.Label();
			this.lbl_tel1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem9 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelCommand9 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.txt_ta_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_az_tarikh = new global::FruitBox.DateBox2(this.components);
			this.EditBox1 = new global::FruitBox.EditBox(this.components);
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.ButtonCommand1 = new global::Janus.Windows.Ribbon.ButtonCommand();
			this.LabelCommand10 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_jamkharid);
			this.UiGroupBox1.Controls.Add(this.txt_ta_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_az_tarikh);
			this.UiGroupBox1.Controls.Add(this.EditBox1);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.RibbonStatusBar1);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_4D6_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_4D6_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_507_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1381, 714);
			arg_507_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_jamkharid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_jamkharid.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_jamkharid.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_57F_0 = this.txt_jamkharid;
			location = new global::System.Drawing.Point(481, 86);
			arg_57F_0.Location = location;
			this.txt_jamkharid.Name = "txt_jamkharid";
			global::System.Windows.Forms.Control arg_5AD_0 = this.txt_jamkharid;
			size = new global::System.Drawing.Size(150, 31);
			arg_5AD_0.Size = size;
			this.txt_jamkharid.TabIndex = 33;
			this.txt_jamkharid.Text = "نمایش جمع فروش ها";
			this.txt_jamkharid.Visible = false;
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_644_0 = this.Label12;
			location = new global::System.Drawing.Point(921, 97);
			arg_644_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_66F_0 = this.Label12;
			size = new global::System.Drawing.Size(54, 19);
			arg_66F_0.Size = size;
			this.Label12.TabIndex = 32;
			this.Label12.Text = "از تاریخ";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_6F9_0 = this.Label10;
			location = new global::System.Drawing.Point(749, 98);
			arg_6F9_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_724_0 = this.Label10;
			size = new global::System.Drawing.Size(53, 19);
			arg_724_0.Size = size;
			this.Label10.TabIndex = 32;
			this.Label10.Text = "تا تاریخ";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_7AE_0 = this.Label9;
			location = new global::System.Drawing.Point(1318, 98);
			arg_7AE_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_7D9_0 = this.Label9;
			size = new global::System.Drawing.Size(61, 19);
			arg_7D9_0.Size = size;
			this.Label9.TabIndex = 32;
			this.Label9.Text = "جستجو";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_87D_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 688);
			arg_87D_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.ButtonCommand1,
				this.LabelCommand10,
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_908_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1381, 26);
			arg_908_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 31;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.lbl_shahr);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			this.UiGroupBox2.Controls.Add(this.Label6);
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label8);
			this.UiGroupBox2.Controls.Add(this.Label15);
			this.UiGroupBox2.Controls.Add(this.Label11);
			this.UiGroupBox2.Controls.Add(this.Label14);
			this.UiGroupBox2.Controls.Add(this.lbl_tedad_havale);
			this.UiGroupBox2.Controls.Add(this.Label16);
			this.UiGroupBox2.Controls.Add(this.lbl_tedad_safi);
			this.UiGroupBox2.Controls.Add(this.Label13);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.lbl_addr);
			this.UiGroupBox2.Controls.Add(this.lbl_code);
			this.UiGroupBox2.Controls.Add(this.lbl_codemelli);
			this.UiGroupBox2.Controls.Add(this.lbl_tel3);
			this.UiGroupBox2.Controls.Add(this.lbl_tel4);
			this.UiGroupBox2.Controls.Add(this.lbl_tel2);
			this.UiGroupBox2.Controls.Add(this.lbl_tel1);
			this.UiGroupBox2.Controls.Add(this.Label2);
			global::System.Windows.Forms.Control arg_B8A_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(6, 35);
			arg_B8A_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_BB5_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(25, 57);
			arg_BB5_0.Size = size;
			this.UiGroupBox2.TabIndex = 0;
			this.UiGroupBox2.Visible = false;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			global::System.Windows.Forms.Control arg_BF5_0 = this.lbl_shahr;
			location = new global::System.Drawing.Point(6, 110);
			arg_BF5_0.Location = location;
			this.lbl_shahr.Name = "lbl_shahr";
			global::System.Windows.Forms.Control arg_C20_0 = this.lbl_shahr;
			size = new global::System.Drawing.Size(49, 14);
			arg_C20_0.Size = size;
			this.lbl_shahr.TabIndex = 3;
			this.lbl_shahr.Visible = false;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_C75_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(-1313, 6);
			arg_C75_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_CA6_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(180, 129);
			arg_CA6_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 2;
			this.PictureBox1.TabStop = false;
			this.PictureBox1.Visible = false;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_D23_0 = this.Label6;
			location = new global::System.Drawing.Point(-428, 113);
			arg_D23_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_D4E_0 = this.Label6;
			size = new global::System.Drawing.Size(40, 14);
			arg_D4E_0.Size = size;
			this.Label6.TabIndex = 1;
			this.Label6.Text = "تلفن 2";
			this.Label6.Visible = false;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_DC2_0 = this.Label5;
			location = new global::System.Drawing.Point(-428, 83);
			arg_DC2_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_DED_0 = this.Label5;
			size = new global::System.Drawing.Size(40, 14);
			arg_DED_0.Size = size;
			this.Label5.TabIndex = 1;
			this.Label5.Text = "تلفن 1";
			this.Label5.Visible = false;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_E5E_0 = this.Label8;
			location = new global::System.Drawing.Point(-46, 84);
			arg_E5E_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_E89_0 = this.Label8;
			size = new global::System.Drawing.Size(35, 14);
			arg_E89_0.Size = size;
			this.Label8.TabIndex = 1;
			this.Label8.Text = "ضامن";
			this.Label8.Visible = false;
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_EFA_0 = this.Label15;
			location = new global::System.Drawing.Point(-46, 113);
			arg_EFA_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_F25_0 = this.Label15;
			size = new global::System.Drawing.Size(35, 14);
			arg_F25_0.Size = size;
			this.Label15.TabIndex = 1;
			this.Label15.Text = "آدرس";
			this.Label15.Visible = false;
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_F99_0 = this.Label11;
			location = new global::System.Drawing.Point(-257, 53);
			arg_F99_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_FC4_0 = this.Label11;
			size = new global::System.Drawing.Size(62, 14);
			arg_FC4_0.Size = size;
			this.Label11.TabIndex = 1;
			this.Label11.Text = "کد مشتری";
			this.Label11.Visible = false;
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1035_0 = this.Label14;
			location = new global::System.Drawing.Point(-45, 53);
			arg_1035_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_1060_0 = this.Label14;
			size = new global::System.Drawing.Size(46, 14);
			arg_1060_0.Size = size;
			this.Label14.TabIndex = 1;
			this.Label14.Text = "کد ملی";
			this.Label14.Visible = false;
			this.lbl_tedad_havale.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tedad_havale.AutoSize = true;
			this.lbl_tedad_havale.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tedad_havale.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10F6_0 = this.lbl_tedad_havale;
			location = new global::System.Drawing.Point(-778, 69);
			arg_10F6_0.Location = location;
			this.lbl_tedad_havale.Name = "lbl_tedad_havale";
			global::System.Windows.Forms.Control arg_1120_0 = this.lbl_tedad_havale;
			size = new global::System.Drawing.Size(0, 28);
			arg_1120_0.Size = size;
			this.lbl_tedad_havale.TabIndex = 1;
			this.lbl_tedad_havale.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_tedad_havale.Visible = false;
			this.Label16.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11B3_0 = this.Label16;
			location = new global::System.Drawing.Point(-684, 69);
			arg_11B3_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_11DE_0 = this.Label16;
			size = new global::System.Drawing.Size(84, 28);
			arg_11DE_0.Size = size;
			this.Label16.TabIndex = 1;
			this.Label16.Text = "تعداد حواله";
			this.Label16.Visible = false;
			this.lbl_tedad_safi.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tedad_safi.AutoSize = true;
			this.lbl_tedad_safi.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tedad_safi.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1274_0 = this.lbl_tedad_safi;
			location = new global::System.Drawing.Point(-778, 23);
			arg_1274_0.Location = location;
			this.lbl_tedad_safi.Name = "lbl_tedad_safi";
			global::System.Windows.Forms.Control arg_129E_0 = this.lbl_tedad_safi;
			size = new global::System.Drawing.Size(0, 28);
			arg_129E_0.Size = size;
			this.lbl_tedad_safi.TabIndex = 1;
			this.lbl_tedad_safi.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_tedad_safi.Visible = false;
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1331_0 = this.Label13;
			location = new global::System.Drawing.Point(-686, 22);
			arg_1331_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_135C_0 = this.Label13;
			size = new global::System.Drawing.Size(86, 28);
			arg_135C_0.Size = size;
			this.Label13.TabIndex = 1;
			this.Label13.Text = "تعداد صافی";
			this.Label13.Visible = false;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_13D0_0 = this.Label4;
			location = new global::System.Drawing.Point(-428, 22);
			arg_13D0_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_13FB_0 = this.Label4;
			size = new global::System.Drawing.Size(54, 14);
			arg_13FB_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "تلفن ثابت";
			this.Label4.Visible = false;
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Label7.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1491_0 = this.Label7;
			location = new global::System.Drawing.Point(-366, 80);
			arg_1491_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_14BF_0 = this.Label7;
			size = new global::System.Drawing.Size(317, 21);
			arg_14BF_0.Size = size;
			this.Label7.TabIndex = 1;
			this.Label7.Visible = false;
			this.lbl_addr.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_addr.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_addr.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_addr.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1544_0 = this.lbl_addr;
			location = new global::System.Drawing.Point(-366, 110);
			arg_1544_0.Location = location;
			this.lbl_addr.Name = "lbl_addr";
			global::System.Windows.Forms.Control arg_1572_0 = this.lbl_addr;
			size = new global::System.Drawing.Size(317, 21);
			arg_1572_0.Size = size;
			this.lbl_addr.TabIndex = 1;
			this.lbl_addr.Visible = false;
			this.lbl_code.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_code.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_code.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_code.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_15F7_0 = this.lbl_code;
			location = new global::System.Drawing.Point(-366, 50);
			arg_15F7_0.Location = location;
			this.lbl_code.Name = "lbl_code";
			global::System.Windows.Forms.Control arg_1622_0 = this.lbl_code;
			size = new global::System.Drawing.Size(106, 21);
			arg_1622_0.Size = size;
			this.lbl_code.TabIndex = 1;
			this.lbl_code.Visible = false;
			this.lbl_codemelli.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_codemelli.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_codemelli.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_codemelli.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_16A7_0 = this.lbl_codemelli;
			location = new global::System.Drawing.Point(-186, 50);
			arg_16A7_0.Location = location;
			this.lbl_codemelli.Name = "lbl_codemelli";
			global::System.Windows.Forms.Control arg_16D5_0 = this.lbl_codemelli;
			size = new global::System.Drawing.Size(137, 21);
			arg_16D5_0.Size = size;
			this.lbl_codemelli.TabIndex = 1;
			this.lbl_codemelli.Visible = false;
			this.lbl_tel3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel3.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel3.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel3.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_175A_0 = this.lbl_tel3;
			location = new global::System.Drawing.Point(-580, 80);
			arg_175A_0.Location = location;
			this.lbl_tel3.Name = "lbl_tel3";
			global::System.Windows.Forms.Control arg_1788_0 = this.lbl_tel3;
			size = new global::System.Drawing.Size(149, 21);
			arg_1788_0.Size = size;
			this.lbl_tel3.TabIndex = 1;
			this.lbl_tel3.Visible = false;
			this.lbl_tel4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel4.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel4.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel4.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_180D_0 = this.lbl_tel4;
			location = new global::System.Drawing.Point(-580, 110);
			arg_180D_0.Location = location;
			this.lbl_tel4.Name = "lbl_tel4";
			global::System.Windows.Forms.Control arg_183B_0 = this.lbl_tel4;
			size = new global::System.Drawing.Size(149, 21);
			arg_183B_0.Size = size;
			this.lbl_tel4.TabIndex = 1;
			this.lbl_tel4.Visible = false;
			this.lbl_tel2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel2.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel2.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel2.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_18C0_0 = this.lbl_tel2;
			location = new global::System.Drawing.Point(-580, 50);
			arg_18C0_0.Location = location;
			this.lbl_tel2.Name = "lbl_tel2";
			global::System.Windows.Forms.Control arg_18EE_0 = this.lbl_tel2;
			size = new global::System.Drawing.Size(149, 21);
			arg_18EE_0.Size = size;
			this.lbl_tel2.TabIndex = 1;
			this.lbl_tel2.Visible = false;
			this.lbl_tel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel1.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel1.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel1.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1973_0 = this.lbl_tel1;
			location = new global::System.Drawing.Point(-580, 19);
			arg_1973_0.Location = location;
			this.lbl_tel1.Name = "lbl_tel1";
			global::System.Windows.Forms.Control arg_19A1_0 = this.lbl_tel1;
			size = new global::System.Drawing.Size(149, 21);
			arg_19A1_0.Size = size;
			this.lbl_tel1.TabIndex = 1;
			this.lbl_tel1.Visible = false;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1A04_0 = this.Label2;
			location = new global::System.Drawing.Point(-427, 54);
			arg_1A04_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_1A2F_0 = this.Label2;
			size = new global::System.Drawing.Size(36, 14);
			arg_1A2F_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "همراه";
			this.Label2.Visible = false;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1AA6_0 = this.Label3;
			location = new global::System.Drawing.Point(1108, 489);
			arg_1AA6_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1AD1_0 = this.Label3;
			size = new global::System.Drawing.Size(40, 14);
			arg_1AD1_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "تا تاریخ";
			this.Label3.Visible = false;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1B67_0 = this.Label1;
			location = new global::System.Drawing.Point(1317, 57);
			arg_1B67_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_1B92_0 = this.Label1;
			size = new global::System.Drawing.Size(61, 19);
			arg_1B92_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "مشتری";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2,
				this.ButtonItem11,
				this.ButtonItem1,
				this.ButtonItem9,
				this.ButtonItem4,
				this.ButtonItem5,
				this.ButtonItem7,
				this.ButtonItem3,
				this.ButtonItem6,
				this.ButtonItem8
			});
			global::DevComponents.DotNetBar.Bar arg_1C8B_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_1C8B_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_1CB9_0 = this.Bar1;
			size = new global::System.Drawing.Size(1381, 41);
			arg_1CB9_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 13;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "صورتحساب گیری جدید (F3)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "صورتحساب گیری جدید (F3)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.page_edit;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "چک های دریافتی";
			this.ButtonItem11.Visible = false;
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "چاپ (F4)";
			this.ButtonItem9.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem9.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem9.Name = "ButtonItem9";
			this.ButtonItem9.Text = "چاپ صافی های چاپ نشده";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.useredit;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "ویرایش اطلاعات مشتری (F6)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.page_edit;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "لیست چک ها";
			this.ButtonItem5.Visible = false;
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.bank_customer;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "حساب های بانکی (F7)";
			this.ButtonItem7.Visible = false;
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "چاپ خرید و فروش";
			this.ButtonItem3.Visible = false;
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.comment;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "پیامک صورتحساب";
			this.ButtonItem6.Visible = false;
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem8.Image = global::FruitBox.My.Resources.Resources.document_attach;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "PDF";
			this.LabelCommand9.Key = "LabelCommand9";
			this.LabelCommand9.Name = "LabelCommand9";
			this.LabelCommand9.Text = "LabelCommand9";
			this.txt_ta_tarikh.AcceptEnter = true;
			this.txt_ta_tarikh.AllowEdit = true;
			this.txt_ta_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ta_tarikh.ButtonEnable = false;
			this.txt_ta_tarikh.FocusDatePart = 1;
			this.txt_ta_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2074_0 = this.txt_ta_tarikh;
			location = new global::System.Drawing.Point(647, 88);
			arg_2074_0.Location = location;
			this.txt_ta_tarikh.Mask = "0000/00/00";
			this.txt_ta_tarikh.Name = "txt_ta_tarikh";
			this.txt_ta_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_20BD_0 = this.txt_ta_tarikh;
			size = new global::System.Drawing.Size(100, 36);
			arg_20BD_0.Size = size;
			this.txt_ta_tarikh.TabIndex = 2;
			this.txt_ta_tarikh.Text = "1393/09/19";
			this.txt_ta_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_az_tarikh.AcceptEnter = true;
			this.txt_az_tarikh.AllowEdit = true;
			this.txt_az_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_az_tarikh.ButtonEnable = false;
			this.txt_az_tarikh.FocusDatePart = 1;
			this.txt_az_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2169_0 = this.txt_az_tarikh;
			location = new global::System.Drawing.Point(820, 88);
			arg_2169_0.Location = location;
			this.txt_az_tarikh.Mask = "0000/00/00";
			this.txt_az_tarikh.Name = "txt_az_tarikh";
			this.txt_az_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_21B2_0 = this.txt_az_tarikh;
			size = new global::System.Drawing.Size(100, 36);
			arg_21B2_0.Size = size;
			this.txt_az_tarikh.TabIndex = 1;
			this.txt_az_tarikh.Text = "1393/09/19";
			this.txt_az_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.EditBox1.AcceptEnter = true;
			this.EditBox1.AllowEdit = true;
			this.EditBox1.AllowNew = true;
			this.EditBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox1.FocusColor = true;
			this.EditBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_225E_0 = this.EditBox1;
			location = new global::System.Drawing.Point(997, 88);
			arg_225E_0.Location = location;
			this.EditBox1.Name = "EditBox1";
			this.EditBox1.Nullable = true;
			this.EditBox1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.EditBox1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_22B7_0 = this.EditBox1;
			size = new global::System.Drawing.Size(317, 36);
			arg_22B7_0.Size = size;
			this.EditBox1.TabIndex = 3;
			this.EditBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.LabelCommand5.Key = "LabelCommand1";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand2";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand7.Key = "LabelCommand3";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand4";
			this.LabelCommand8.Name = "LabelCommand8";
			this.ButtonCommand1.Key = "ButtonCommand1";
			this.ButtonCommand1.Name = "ButtonCommand1";
			this.LabelCommand10.Key = "LabelCommand5";
			this.LabelCommand10.Name = "LabelCommand10";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_24CB_0 = this.GridEX1;
			location = new global::System.Drawing.Point(3, 130);
			arg_24CB_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_2523_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1375, 559);
			arg_2523_0.Size = size;
			this.GridEX1.TabIndex = 4;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari.AcceptEnter = false;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = true;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد مشتری";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "Shahr";
			column3.Size = 20;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_2717_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(997, 47);
			arg_2717_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = true;
			this.txt_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_27A2_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(317, 36);
			arg_27A2_0.Size = size;
			this.txt_moshtari.TabIndex = 0;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 14f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1381, 714);
			this.ClientSize = size;
			this.Controls.Add(this.Bar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_SuratHesab_Daryafti_Moshtari";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "صورتحساب دریافتی از مشتری";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04001269 RID: 4713
		private global::System.ComponentModel.IContainer components;
	}
}
