namespace FruitBox
{
	// Token: 0x02000100 RID: 256
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Pardakht : global::System.Windows.Forms.Form
	{
		// Token: 0x0600212F RID: 8495 RVA: 0x0018B76C File Offset: 0x0018996C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002130 RID: 8496 RVA: 0x0018B7BC File Offset: 0x001899BC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Pardakht));
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			global::FruitBox.Column column4 = new global::FruitBox.Column();
			global::FruitBox.Column column5 = new global::FruitBox.Column();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Panel1 = new global::DevComponents.DotNetBar.PanelEx();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.group_dfish = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.group_checkmoshtari = new global::Janus.Windows.EditControls.UIGroupBox();
			this.lbl_sarresid = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.group_dnaghd = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Group_Dastecheck = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txt_mablagh = new global::FruitBox.CurrencyBox(this.components);
			this.txt_tarikh = new global::FruitBox.DateBox2(this.components);
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_babatcheckd = new global::FruitBox.EditBox(this.components);
			this.txt_mablaghd = new global::FruitBox.CurrencyBox(this.components);
			this.txt_shdcheck = new global::FruitBox.NumericBox(this.components);
			this.txt_checkHesabBanki = new global::FruitBox.SelectItem(this.components);
			this.txt_sarresid = new global::FruitBox.DateBox2(this.components);
			this.txt_fishbabat = new global::FruitBox.EditBox(this.components);
			this.txt_fishbank = new global::FruitBox.SelectItem(this.components);
			this.txt_fishtarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_fishbankhesab = new global::FruitBox.SelectItem(this.components);
			this.txt_shfish = new global::FruitBox.NumericBox(this.components);
			this.txt_shCheck = new global::FruitBox.SelectItem(this.components);
			this.txt_babatcheck = new global::FruitBox.EditBox(this.components);
			this.txt_babat = new global::FruitBox.EditBox(this.components);
			this.GridSize1 = new global::FruitBox.GridSize(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group_dfish).BeginInit();
			this.group_dfish.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group_checkmoshtari).BeginInit();
			this.group_checkmoshtari.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group_dnaghd).BeginInit();
			this.group_dnaghd.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Group_Dastecheck).BeginInit();
			this.Group_Dastecheck.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.Panel1);
			this.UiGroupBox1.Controls.Add(this.txt_mablagh);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_442_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_442_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_473_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1396, 699);
			arg_473_0.Size = size;
			this.UiGroupBox1.TabIndex = 1;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Panel1.CanvasColor = global::System.Drawing.SystemColors.Control;
			this.Panel1.ColorSchemeStyle = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeXP;
			global::System.Windows.Forms.Control arg_4C8_0 = this.Panel1;
			location = new global::System.Drawing.Point(338, 42);
			arg_4C8_0.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control arg_4F3_0 = this.Panel1;
			size = new global::System.Drawing.Size(20, 20);
			arg_4F3_0.Size = size;
			this.Panel1.Style.Alignment = global::System.Drawing.StringAlignment.Center;
			this.Panel1.Style.BackColor1.Color = global::System.Drawing.Color.White;
			this.Panel1.Style.BackColor2.Color = global::System.Drawing.Color.White;
			this.Panel1.Style.Border = global::DevComponents.DotNetBar.eBorderType.DoubleLine;
			this.Panel1.Style.BorderColor.Color = global::System.Drawing.Color.FromArgb(132, 157, 189);
			this.Panel1.Style.ForeColor.ColorSchemePart = global::DevComponents.DotNetBar.eColorSchemePart.PanelText;
			this.Panel1.Style.GradientAngle = 90;
			this.Panel1.TabIndex = 17;
			this.Panel1.Text = "PanelEx2";
			this.Panel1.Visible = false;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_639_0 = this.Label1;
			location = new global::System.Drawing.Point(1348, 44);
			arg_639_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_664_0 = this.Label1;
			size = new global::System.Drawing.Size(36, 18);
			arg_664_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "تاریخ";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3
			});
			global::DevComponents.DotNetBar.Bar arg_71B_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_71B_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_749_0 = this.Bar1;
			size = new global::System.Drawing.Size(1396, 41);
			arg_749_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 15;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.page;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید";
			this.ButtonItem1.Visible = false;
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف";
			this.ButtonItem3.Visible = false;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Rebar;
			this.UiGroupBox2.Controls.Add(this.Group_Dastecheck);
			this.UiGroupBox2.Controls.Add(this.group_dfish);
			this.UiGroupBox2.Controls.Add(this.group_checkmoshtari);
			this.UiGroupBox2.Controls.Add(this.group_dnaghd);
			global::System.Windows.Forms.Control arg_8FC_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(3, 596);
			arg_8FC_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			this.UiGroupBox2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			this.UiGroupBox2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_948_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1390, 100);
			arg_948_0.Size = size;
			this.UiGroupBox2.TabIndex = 2;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.group_dfish.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Rebar;
			this.group_dfish.Controls.Add(this.Label13);
			this.group_dfish.Controls.Add(this.txt_fishbabat);
			this.group_dfish.Controls.Add(this.txt_fishbank);
			this.group_dfish.Controls.Add(this.txt_fishtarikh);
			this.group_dfish.Controls.Add(this.txt_fishbankhesab);
			this.group_dfish.Controls.Add(this.txt_shfish);
			this.group_dfish.Controls.Add(this.Label10);
			this.group_dfish.Controls.Add(this.Label9);
			this.group_dfish.Controls.Add(this.Label11);
			this.group_dfish.Controls.Add(this.Label8);
			global::System.Windows.Forms.Control arg_A6E_0 = this.group_dfish;
			location = new global::System.Drawing.Point(9, 8);
			arg_A6E_0.Location = location;
			this.group_dfish.Name = "group_dfish";
			global::System.Windows.Forms.Control arg_A99_0 = this.group_dfish;
			size = new global::System.Drawing.Size(83, 88);
			arg_A99_0.Size = size;
			this.group_dfish.TabIndex = 2;
			this.group_dfish.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_AF9_0 = this.Label13;
			location = new global::System.Drawing.Point(9, 69);
			arg_AF9_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_B24_0 = this.Label13;
			size = new global::System.Drawing.Size(28, 14);
			arg_B24_0.Size = size;
			this.Label13.TabIndex = 7;
			this.Label13.Text = "بابت";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_B8B_0 = this.Label10;
			location = new global::System.Drawing.Point(-484, 20);
			arg_B8B_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_BB6_0 = this.Label10;
			size = new global::System.Drawing.Size(53, 14);
			arg_BB6_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "تاریخ واریز";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_C1D_0 = this.Label9;
			location = new global::System.Drawing.Point(-209, 19);
			arg_C1D_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_C48_0 = this.Label9;
			size = new global::System.Drawing.Size(80, 14);
			arg_C48_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "واریز به حساب";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_CAC_0 = this.Label11;
			location = new global::System.Drawing.Point(-13, 46);
			arg_CAC_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_CD7_0 = this.Label11;
			size = new global::System.Drawing.Size(93, 14);
			arg_CD7_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "پرداخت از حساب";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_D3B_0 = this.Label8;
			location = new global::System.Drawing.Point(-17, 21);
			arg_D3B_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_D66_0 = this.Label8;
			size = new global::System.Drawing.Size(69, 14);
			arg_D66_0.Size = size;
			this.Label8.TabIndex = 0;
			this.Label8.Text = "شماره فیش";
			this.group_checkmoshtari.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Rebar;
			this.group_checkmoshtari.Controls.Add(this.lbl_sarresid);
			this.group_checkmoshtari.Controls.Add(this.txt_shCheck);
			this.group_checkmoshtari.Controls.Add(this.Label7);
			this.group_checkmoshtari.Controls.Add(this.Label4);
			this.group_checkmoshtari.Controls.Add(this.Label3);
			this.group_checkmoshtari.Controls.Add(this.txt_babatcheck);
			global::System.Windows.Forms.Control arg_E35_0 = this.group_checkmoshtari;
			location = new global::System.Drawing.Point(98, 11);
			arg_E35_0.Location = location;
			this.group_checkmoshtari.Name = "group_checkmoshtari";
			global::System.Windows.Forms.Control arg_E60_0 = this.group_checkmoshtari;
			size = new global::System.Drawing.Size(73, 83);
			arg_E60_0.Size = size;
			this.group_checkmoshtari.TabIndex = 1;
			this.group_checkmoshtari.Visible = false;
			this.group_checkmoshtari.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.lbl_sarresid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sarresid.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_sarresid.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_EE5_0 = this.lbl_sarresid;
			location = new global::System.Drawing.Point(-403, 17);
			arg_EE5_0.Location = location;
			this.lbl_sarresid.Name = "lbl_sarresid";
			global::System.Windows.Forms.Control arg_F10_0 = this.lbl_sarresid;
			size = new global::System.Drawing.Size(120, 17);
			arg_F10_0.Size = size;
			this.lbl_sarresid.TabIndex = 12;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_F64_0 = this.Label6;
			location = new global::System.Drawing.Point(23, 9);
			arg_F64_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_F8F_0 = this.Label6;
			size = new global::System.Drawing.Size(74, 14);
			arg_F8F_0.Size = size;
			this.Label6.TabIndex = 11;
			this.Label6.Text = "حساب بانکی";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1019_0 = this.Label7;
			location = new global::System.Drawing.Point(-278, 17);
			arg_1019_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_1044_0 = this.Label7;
			size = new global::System.Drawing.Size(86, 16);
			arg_1044_0.Size = size;
			this.Label7.TabIndex = 1;
			this.Label7.Text = "تاریخ سررسید";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10CA_0 = this.Label4;
			location = new global::System.Drawing.Point(-13, 17);
			arg_10CA_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_10F5_0 = this.Label4;
			size = new global::System.Drawing.Size(70, 16);
			arg_10F5_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "شماره چک";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_117A_0 = this.Label3;
			location = new global::System.Drawing.Point(0, 45);
			arg_117A_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_11A5_0 = this.Label3;
			size = new global::System.Drawing.Size(32, 16);
			arg_11A5_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "بابت";
			this.group_dnaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.group_dnaghd.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Rebar;
			this.group_dnaghd.Controls.Add(this.Label2);
			this.group_dnaghd.Controls.Add(this.txt_babat);
			global::System.Windows.Forms.Control arg_1229_0 = this.group_dnaghd;
			location = new global::System.Drawing.Point(1043, 11);
			arg_1229_0.Location = location;
			this.group_dnaghd.Name = "group_dnaghd";
			global::System.Windows.Forms.Control arg_1257_0 = this.group_dnaghd;
			size = new global::System.Drawing.Size(341, 83);
			arg_1257_0.Size = size;
			this.group_dnaghd.TabIndex = 0;
			this.group_dnaghd.Visible = false;
			this.group_dnaghd.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12E9_0 = this.Label2;
			location = new global::System.Drawing.Point(300, 15);
			arg_12E9_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_1314_0 = this.Label2;
			size = new global::System.Drawing.Size(32, 16);
			arg_1314_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "بابت";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1377_0 = this.Label5;
			location = new global::System.Drawing.Point(4, 35);
			arg_1377_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_13A2_0 = this.Label5;
			size = new global::System.Drawing.Size(97, 14);
			arg_13A2_0.Size = size;
			this.Label5.TabIndex = 11;
			this.Label5.Text = "شماره دسته چک";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_140A_0 = this.Label12;
			location = new global::System.Drawing.Point(-283, 34);
			arg_140A_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_1435_0 = this.Label12;
			size = new global::System.Drawing.Size(28, 14);
			arg_1435_0.Size = size;
			this.Label12.TabIndex = 11;
			this.Label12.Text = "مبلغ";
			this.Label12.Visible = false;
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_14A7_0 = this.Label14;
			location = new global::System.Drawing.Point(23, 53);
			arg_14A7_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_14D2_0 = this.Label14;
			size = new global::System.Drawing.Size(28, 14);
			arg_14D2_0.Size = size;
			this.Label14.TabIndex = 11;
			this.Label14.Text = "بابت";
			this.Group_Dastecheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Group_Dastecheck.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Rebar;
			this.Group_Dastecheck.Controls.Add(this.txt_babatcheckd);
			this.Group_Dastecheck.Controls.Add(this.txt_mablaghd);
			this.Group_Dastecheck.Controls.Add(this.Label14);
			this.Group_Dastecheck.Controls.Add(this.Label15);
			this.Group_Dastecheck.Controls.Add(this.Label12);
			this.Group_Dastecheck.Controls.Add(this.txt_shdcheck);
			this.Group_Dastecheck.Controls.Add(this.txt_checkHesabBanki);
			this.Group_Dastecheck.Controls.Add(this.Label6);
			this.Group_Dastecheck.Controls.Add(this.Label5);
			this.Group_Dastecheck.Controls.Add(this.txt_sarresid);
			this.Group_Dastecheck.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_161C_0 = this.Group_Dastecheck;
			location = new global::System.Drawing.Point(935, 13);
			arg_161C_0.Location = location;
			this.Group_Dastecheck.Name = "Group_Dastecheck";
			global::System.Windows.Forms.Control arg_1647_0 = this.Group_Dastecheck;
			size = new global::System.Drawing.Size(102, 83);
			arg_1647_0.Size = size;
			this.Group_Dastecheck.TabIndex = 15;
			this.Group_Dastecheck.Visible = false;
			this.Group_Dastecheck.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_16B7_0 = this.Label15;
			location = new global::System.Drawing.Point(-285, 7);
			arg_16B7_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_16E2_0 = this.Label15;
			size = new global::System.Drawing.Size(77, 14);
			arg_16E2_0.Size = size;
			this.Label15.TabIndex = 11;
			this.Label15.Text = "تاریخ سررسید";
			this.txt_mablagh.AllowEdit = true;
			this.txt_mablagh.AllowNew = true;
			this.txt_mablagh.FocusColor = false;
			global::System.Windows.Forms.Control arg_1742_0 = this.txt_mablagh;
			location = new global::System.Drawing.Point(114, 42);
			arg_1742_0.Location = location;
			this.txt_mablagh.Name = "txt_mablagh";
			this.txt_mablagh.Nullable = true;
			this.txt_mablagh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1798_0 = this.txt_mablagh;
			size = new global::System.Drawing.Size(100, 22);
			arg_1798_0.Size = size;
			this.txt_mablagh.TabIndex = 16;
			this.txt_mablagh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_mablagh.Value = value;
			this.txt_mablagh.Visible = false;
			this.txt_mablagh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			global::System.Windows.Forms.Control arg_1813_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(1242, 45);
			arg_1813_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_185C_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(100, 22);
			arg_185C_0.Size = size;
			this.txt_tarikh.TabIndex = 0;
			this.txt_tarikh.Text = "1392/09/25";
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridEX1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1946_0 = this.GridEX1;
			location = new global::System.Drawing.Point(0, 70);
			arg_1946_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaderContent = global::Janus.Windows.GridEX.RowHeaderContent.RowPosition;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_19AB_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1393, 528);
			arg_19AB_0.Size = size;
			this.GridEX1.TabIndex = 14;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_babatcheckd.AllowEdit = true;
			this.txt_babatcheckd.AllowNew = true;
			this.txt_babatcheckd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_babatcheckd.FocusColor = true;
			global::System.Windows.Forms.Control arg_1A70_0 = this.txt_babatcheckd;
			location = new global::System.Drawing.Point(-406, 54);
			arg_1A70_0.Location = location;
			this.txt_babatcheckd.Name = "txt_babatcheckd";
			this.txt_babatcheckd.Nullable = true;
			this.txt_babatcheckd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_babatcheckd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1AC9_0 = this.txt_babatcheckd;
			size = new global::System.Drawing.Size(404, 22);
			arg_1AC9_0.Size = size;
			this.txt_babatcheckd.TabIndex = 4;
			this.txt_babatcheckd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_mablaghd.AllowEdit = true;
			this.txt_mablaghd.AllowNew = true;
			this.txt_mablaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mablaghd.FocusColor = true;
			global::System.Windows.Forms.Control arg_1B35_0 = this.txt_mablaghd;
			location = new global::System.Drawing.Point(-406, 29);
			arg_1B35_0.Location = location;
			this.txt_mablaghd.Name = "txt_mablaghd";
			this.txt_mablaghd.Nullable = true;
			this.txt_mablaghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablaghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1B8B_0 = this.txt_mablaghd;
			size = new global::System.Drawing.Size(117, 22);
			arg_1B8B_0.Size = size;
			this.txt_mablaghd.TabIndex = 3;
			this.txt_mablaghd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_mablaghd.Value = value;
			this.txt_mablaghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shdcheck.AllowEdit = true;
			this.txt_shdcheck.AllowNew = true;
			this.txt_shdcheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shdcheck.FocusColor = true;
			global::System.Windows.Forms.Control arg_1C12_0 = this.txt_shdcheck;
			location = new global::System.Drawing.Point(-146, 28);
			arg_1C12_0.Location = location;
			this.txt_shdcheck.Name = "txt_shdcheck";
			this.txt_shdcheck.Nullable = true;
			this.txt_shdcheck.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shdcheck.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1C6B_0 = this.txt_shdcheck;
			size = new global::System.Drawing.Size(144, 22);
			arg_1C6B_0.Size = size;
			this.txt_shdcheck.TabIndex = 2;
			this.txt_shdcheck.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_shdcheck.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_checkHesabBanki.AddNewForm = null;
			this.txt_checkHesabBanki.AllowEdit = true;
			this.txt_checkHesabBanki.AllowNew = true;
			this.txt_checkHesabBanki.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_checkHesabBanki.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_checkHesabBanki.ButtonText = "...";
			this.txt_checkHesabBanki.DisplayMember = "Name";
			this.txt_checkHesabBanki.FocusColor = true;
			column.Caption = "حساب بانکی";
			column.Name = "Name";
			column.Size = 100;
			this.txt_checkHesabBanki.Items.AddRange(new global::FruitBox.Column[]
			{
				column
			});
			global::System.Windows.Forms.Control arg_1D61_0 = this.txt_checkHesabBanki;
			location = new global::System.Drawing.Point(-146, 4);
			arg_1D61_0.Location = location;
			this.txt_checkHesabBanki.Name = "txt_checkHesabBanki";
			this.txt_checkHesabBanki.Nullable = true;
			this.txt_checkHesabBanki.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_checkHesabBanki.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_checkHesabBanki.SelectCommand = "SELECT Bank_Hesab.ID, Bank.Name+' - '+ Bank_Hesab.Shobe AS Name FROM Bank_Hesab INNER JOIN Bank ON Bank_Hesab.Bank_ID = Bank.ID";
			this.txt_checkHesabBanki.SelectedRow = null;
			this.txt_checkHesabBanki.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1DE5_0 = this.txt_checkHesabBanki;
			size = new global::System.Drawing.Size(144, 22);
			arg_1DE5_0.Size = size;
			this.txt_checkHesabBanki.TabIndex = 0;
			this.txt_checkHesabBanki.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_checkHesabBanki.Value = null;
			this.txt_checkHesabBanki.ValueMember = "ID";
			this.txt_checkHesabBanki.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sarresid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sarresid.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			global::System.Windows.Forms.Control arg_1E61_0 = this.txt_sarresid;
			location = new global::System.Drawing.Point(-406, 3);
			arg_1E61_0.Location = location;
			this.txt_sarresid.Mask = "0000/00/00";
			this.txt_sarresid.Name = "txt_sarresid";
			this.txt_sarresid.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_1EAA_0 = this.txt_sarresid;
			size = new global::System.Drawing.Size(117, 22);
			arg_1EAA_0.Size = size;
			this.txt_sarresid.TabIndex = 1;
			this.txt_sarresid.Text = "1392/09/28";
			this.txt_sarresid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fishbabat.AllowEdit = true;
			this.txt_fishbabat.AllowNew = true;
			this.txt_fishbabat.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fishbabat.FocusColor = true;
			global::System.Windows.Forms.Control arg_1F27_0 = this.txt_fishbabat;
			location = new global::System.Drawing.Point(-590, 69);
			arg_1F27_0.Location = location;
			this.txt_fishbabat.Name = "txt_fishbabat";
			this.txt_fishbabat.Nullable = true;
			this.txt_fishbabat.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fishbabat.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1F80_0 = this.txt_fishbabat;
			size = new global::System.Drawing.Size(569, 22);
			arg_1F80_0.Size = size;
			this.txt_fishbabat.TabIndex = 6;
			this.txt_fishbabat.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fishbank.AddNewForm = null;
			this.txt_fishbank.AllowEdit = true;
			this.txt_fishbank.AllowNew = true;
			this.txt_fishbank.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fishbank.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_fishbank.ButtonText = "...";
			this.txt_fishbank.DisplayMember = "Name";
			this.txt_fishbank.FocusColor = true;
			column2.Caption = "عنوان";
			column2.Name = "Name";
			column2.Size = 100;
			this.txt_fishbank.Items.AddRange(new global::FruitBox.Column[]
			{
				column2
			});
			global::System.Windows.Forms.Control arg_206A_0 = this.txt_fishbank;
			location = new global::System.Drawing.Point(-362, 42);
			arg_206A_0.Location = location;
			this.txt_fishbank.Name = "txt_fishbank";
			this.txt_fishbank.Nullable = true;
			this.txt_fishbank.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fishbank.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_fishbank.SelectCommand = "select id,name from bank";
			this.txt_fishbank.SelectedRow = null;
			this.txt_fishbank.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_20EE_0 = this.txt_fishbank;
			size = new global::System.Drawing.Size(341, 22);
			arg_20EE_0.Size = size;
			this.txt_fishbank.TabIndex = 4;
			this.txt_fishbank.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fishbank.Value = null;
			this.txt_fishbank.ValueMember = "ID";
			this.txt_fishbank.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fishtarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fishtarikh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			global::System.Windows.Forms.Control arg_216B_0 = this.txt_fishtarikh;
			location = new global::System.Drawing.Point(-590, 15);
			arg_216B_0.Location = location;
			this.txt_fishtarikh.Mask = "0000/00/00";
			this.txt_fishtarikh.Name = "txt_fishtarikh";
			this.txt_fishtarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_21B4_0 = this.txt_fishtarikh;
			size = new global::System.Drawing.Size(100, 22);
			arg_21B4_0.Size = size;
			this.txt_fishtarikh.TabIndex = 3;
			this.txt_fishtarikh.Text = "1392/09/30";
			this.txt_fishtarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fishbankhesab.AddNewForm = null;
			this.txt_fishbankhesab.AllowEdit = true;
			this.txt_fishbankhesab.AllowNew = true;
			this.txt_fishbankhesab.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fishbankhesab.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_fishbankhesab.ButtonText = "...";
			this.txt_fishbankhesab.DisplayMember = "Name";
			this.txt_fishbankhesab.FocusColor = true;
			column3.Caption = "حساب";
			column3.Name = "Name";
			column3.Size = 100;
			this.txt_fishbankhesab.Items.AddRange(new global::FruitBox.Column[]
			{
				column3
			});
			global::System.Windows.Forms.Control arg_22AF_0 = this.txt_fishbankhesab;
			location = new global::System.Drawing.Point(-362, 15);
			arg_22AF_0.Location = location;
			this.txt_fishbankhesab.Name = "txt_fishbankhesab";
			this.txt_fishbankhesab.Nullable = true;
			this.txt_fishbankhesab.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fishbankhesab.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_fishbankhesab.SelectCommand = "SELECT        Bank_Hesab.ID, Bank.Name + '-' + Bank_Hesab.Shobe AS Name  FROM  Bank_Hesab INNER JOIN    Bank ON Bank_Hesab.Bank_ID = Bank.ID";
			this.txt_fishbankhesab.SelectedRow = null;
			this.txt_fishbankhesab.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2333_0 = this.txt_fishbankhesab;
			size = new global::System.Drawing.Size(149, 22);
			arg_2333_0.Size = size;
			this.txt_fishbankhesab.TabIndex = 2;
			this.txt_fishbankhesab.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fishbankhesab.Value = null;
			this.txt_fishbankhesab.ValueMember = "ID";
			this.txt_fishbankhesab.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shfish.AllowEdit = true;
			this.txt_shfish.AllowNew = true;
			this.txt_shfish.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shfish.FocusColor = true;
			global::System.Windows.Forms.Control arg_23C7_0 = this.txt_shfish;
			location = new global::System.Drawing.Point(-123, 15);
			arg_23C7_0.Location = location;
			this.txt_shfish.Name = "txt_shfish";
			this.txt_shfish.Nullable = true;
			this.txt_shfish.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shfish.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_241D_0 = this.txt_shfish;
			size = new global::System.Drawing.Size(100, 22);
			arg_241D_0.Size = size;
			this.txt_shfish.TabIndex = 1;
			this.txt_shfish.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_shfish.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_shCheck.AddNewForm = null;
			this.txt_shCheck.AllowEdit = true;
			this.txt_shCheck.AllowNew = true;
			this.txt_shCheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shCheck.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_shCheck.ButtonText = "...";
			this.txt_shCheck.DisplayMember = "Sh_Check";
			this.txt_shCheck.FocusColor = true;
			column4.Caption = "شماره چک";
			column4.Name = "Sh_Check";
			column4.Size = 50;
			column5.Caption = "مبلغ";
			column5.Name = "Mablagh";
			column5.Size = 50;
			this.txt_shCheck.Items.AddRange(new global::FruitBox.Column[]
			{
				column4,
				column5
			});
			global::System.Windows.Forms.Control arg_253F_0 = this.txt_shCheck;
			location = new global::System.Drawing.Point(-171, 13);
			arg_253F_0.Location = location;
			this.txt_shCheck.Name = "txt_shCheck";
			this.txt_shCheck.Nullable = true;
			this.txt_shCheck.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_shCheck.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_shCheck.SelectCommand = null;
			this.txt_shCheck.SelectedRow = null;
			this.txt_shCheck.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_25BF_0 = this.txt_shCheck;
			size = new global::System.Drawing.Size(153, 22);
			arg_25BF_0.Size = size;
			this.txt_shCheck.TabIndex = 1;
			this.txt_shCheck.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_shCheck.Value = null;
			this.txt_shCheck.ValueMember = "ID";
			this.txt_shCheck.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_babatcheck.AllowEdit = true;
			this.txt_babatcheck.AllowNew = true;
			this.txt_babatcheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_babatcheck.FocusColor = true;
			global::System.Windows.Forms.Control arg_2656_0 = this.txt_babatcheck;
			location = new global::System.Drawing.Point(-597, 41);
			arg_2656_0.Location = location;
			this.txt_babatcheck.Name = "txt_babatcheck";
			this.txt_babatcheck.Nullable = true;
			this.txt_babatcheck.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_babatcheck.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_26AF_0 = this.txt_babatcheck;
			size = new global::System.Drawing.Size(578, 22);
			arg_26AF_0.Size = size;
			this.txt_babatcheck.TabIndex = 6;
			this.txt_babatcheck.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_babat.AllowEdit = true;
			this.txt_babat.AllowNew = true;
			this.txt_babat.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_babat.FocusColor = true;
			global::System.Windows.Forms.Control arg_2717_0 = this.txt_babat;
			location = new global::System.Drawing.Point(6, 11);
			arg_2717_0.Location = location;
			this.txt_babat.Name = "txt_babat";
			this.txt_babat.Nullable = true;
			this.txt_babat.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_babat.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2770_0 = this.txt_babat;
			size = new global::System.Drawing.Size(286, 22);
			arg_2770_0.Size = size;
			this.txt_babat.TabIndex = 0;
			this.txt_babat.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridSize1.Grid = this.GridEX1;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Inherit;
			size = new global::System.Drawing.Size(1396, 699);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Pardakht";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "پرداخت";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.group_dfish).EndInit();
			this.group_dfish.ResumeLayout(false);
			this.group_dfish.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group_checkmoshtari).EndInit();
			this.group_checkmoshtari.ResumeLayout(false);
			this.group_checkmoshtari.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.group_dnaghd).EndInit();
			this.group_dnaghd.ResumeLayout(false);
			this.group_dnaghd.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Group_Dastecheck).EndInit();
			this.Group_Dastecheck.ResumeLayout(false);
			this.Group_Dastecheck.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000CE7 RID: 3303
		private global::System.ComponentModel.IContainer components;
	}
}
