namespace FruitBox
{
	// Token: 0x02000075 RID: 117
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Register : global::System.Windows.Forms.Form
	{
		// Token: 0x06000945 RID: 2373 RVA: 0x0007CA5C File Offset: 0x0007AC5C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000946 RID: 2374 RVA: 0x0007CAAC File Offset: 0x0007ACAC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.lbl_head2 = new global::System.Windows.Forms.Label();
			this.lbl_head1 = new global::System.Windows.Forms.Label();
			this.txt_head2 = new global::FruitBox.EditBox(this.components);
			this.txt_head1 = new global::FruitBox.EditBox(this.components);
			this.txt_company = new global::FruitBox.EditBox(this.components);
			this.UiGroupBox4 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.EditBox1 = new global::Janus.Windows.GridEX.EditControls.EditBox();
			this.EditBox2 = new global::Janus.Windows.GridEX.EditControls.EditBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_17C_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_17C_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_1AC_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(761, 355);
			arg_1AC_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.lbl_head2);
			this.UiGroupBox2.Controls.Add(this.lbl_head1);
			this.UiGroupBox2.Controls.Add(this.txt_head2);
			this.UiGroupBox2.Controls.Add(this.txt_head1);
			this.UiGroupBox2.Controls.Add(this.txt_company);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox4);
			this.UiGroupBox2.Controls.Add(this.Label8);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.Label3);
			this.UiGroupBox2.Controls.Add(this.UiButton2);
			this.UiGroupBox2.Controls.Add(this.UiButton1);
			this.UiGroupBox2.Controls.Add(this.EditBox1);
			this.UiGroupBox2.Controls.Add(this.EditBox2);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.Label1);
			global::System.Windows.Forms.Control arg_343_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(7, 3);
			arg_343_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_373_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(745, 347);
			arg_373_0.Size = size;
			this.UiGroupBox2.TabIndex = 3;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.lbl_head2.AutoSize = true;
			global::System.Windows.Forms.Control arg_3B6_0 = this.lbl_head2;
			location = new global::System.Drawing.Point(16, 252);
			arg_3B6_0.Location = location;
			this.lbl_head2.Name = "lbl_head2";
			global::System.Windows.Forms.Control arg_3E3_0 = this.lbl_head2;
			size = new global::System.Drawing.Size(620, 19);
			arg_3E3_0.Size = size;
			this.lbl_head2.TabIndex = 27;
			this.lbl_head2.Text = "مانند : میدان بزرگ میوه و تره بار تهران پلاک 99 - تلفن :0214410 - همراه : 091235687412";
			this.lbl_head1.AutoSize = true;
			global::System.Windows.Forms.Control arg_42E_0 = this.lbl_head1;
			location = new global::System.Drawing.Point(451, 174);
			arg_42E_0.Location = location;
			this.lbl_head1.Name = "lbl_head1";
			global::System.Windows.Forms.Control arg_45B_0 = this.lbl_head1;
			size = new global::System.Drawing.Size(185, 19);
			arg_45B_0.Size = size;
			this.lbl_head1.TabIndex = 27;
			this.lbl_head1.Text = "مانند : بارفروشی کیوانمهر";
			this.txt_head2.AcceptEnter = true;
			this.txt_head2.AllowEdit = true;
			this.txt_head2.AllowNew = true;
			this.txt_head2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_head2.FocusColor = true;
			this.txt_head2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_4FA_0 = this.txt_head2;
			location = new global::System.Drawing.Point(16, 203);
			arg_4FA_0.Location = location;
			this.txt_head2.Name = "txt_head2";
			this.txt_head2.Nullable = true;
			this.txt_head2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_head2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_552_0 = this.txt_head2;
			size = new global::System.Drawing.Size(573, 36);
			arg_552_0.Size = size;
			this.txt_head2.TabIndex = 2;
			this.txt_head2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_head1.AcceptEnter = true;
			this.txt_head1.AllowEdit = true;
			this.txt_head1.AllowNew = true;
			this.txt_head1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_head1.FocusColor = true;
			this.txt_head1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_5EC_0 = this.txt_head1;
			location = new global::System.Drawing.Point(16, 135);
			arg_5EC_0.Location = location;
			this.txt_head1.Name = "txt_head1";
			this.txt_head1.Nullable = true;
			this.txt_head1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_head1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_644_0 = this.txt_head1;
			size = new global::System.Drawing.Size(573, 36);
			arg_644_0.Size = size;
			this.txt_head1.TabIndex = 1;
			this.txt_head1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_company.AcceptEnter = true;
			this.txt_company.AllowEdit = true;
			this.txt_company.AllowNew = true;
			this.txt_company.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_company.FocusColor = true;
			this.txt_company.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_6DE_0 = this.txt_company;
			location = new global::System.Drawing.Point(94, 320);
			arg_6DE_0.Location = location;
			this.txt_company.Name = "txt_company";
			this.txt_company.Nullable = true;
			this.txt_company.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_company.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_733_0 = this.txt_company;
			size = new global::System.Drawing.Size(52, 36);
			arg_733_0.Size = size;
			this.txt_company.TabIndex = 1;
			this.txt_company.Visible = false;
			this.txt_company.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox4.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox4.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_79B_0 = this.UiGroupBox4;
			location = new global::System.Drawing.Point(16, 107);
			arg_79B_0.Location = location;
			this.UiGroupBox4.Name = "UiGroupBox4";
			global::System.Windows.Forms.Control arg_7C8_0 = this.UiGroupBox4;
			size = new global::System.Drawing.Size(704, 22);
			arg_7C8_0.Size = size;
			this.UiGroupBox4.TabIndex = 26;
			this.UiGroupBox4.Text = "اطلاعات سربرگ";
			this.UiGroupBox4.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_861_0 = this.Label8;
			location = new global::System.Drawing.Point(591, 207);
			arg_861_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_88E_0 = this.Label8;
			size = new global::System.Drawing.Size(150, 28);
			arg_88E_0.Size = size;
			this.Label8.TabIndex = 23;
			this.Label8.Text = "متن سربرگ سطر دوم";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_91A_0 = this.Label7;
			location = new global::System.Drawing.Point(591, 140);
			arg_91A_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_947_0 = this.Label7;
			size = new global::System.Drawing.Size(148, 28);
			arg_947_0.Size = size;
			this.Label7.TabIndex = 24;
			this.Label7.Text = "متن سربرگ سطر اول";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9D3_0 = this.Label3;
			location = new global::System.Drawing.Point(148, 325);
			arg_9D3_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_A00_0 = this.Label3;
			size = new global::System.Drawing.Size(146, 28);
			arg_A00_0.Size = size;
			this.Label3.TabIndex = 25;
			this.Label3.Text = "عنوان مالک نرم افزار";
			this.Label3.Visible = false;
			this.UiButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A7B_0 = this.UiButton2;
			location = new global::System.Drawing.Point(341, 284);
			arg_A7B_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			this.UiButton2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_AC3_0 = this.UiButton2;
			size = new global::System.Drawing.Size(115, 38);
			arg_AC3_0.Size = size;
			this.UiButton2.TabIndex = 9;
			this.UiButton2.TabStop = false;
			this.UiButton2.Text = "خروج";
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiButton1.Image = global::FruitBox.My.Resources.Resources.accept;
			global::System.Windows.Forms.Control arg_B5C_0 = this.UiButton1;
			location = new global::System.Drawing.Point(462, 284);
			arg_B5C_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			this.UiButton1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton1.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_BA7_0 = this.UiButton1;
			size = new global::System.Drawing.Size(128, 38);
			arg_BA7_0.Size = size;
			this.UiButton1.TabIndex = 3;
			this.UiButton1.Text = "ثبت";
			this.UiButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.EditBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox1.ButtonFont = new global::System.Drawing.Font("Courier New", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.EditBox1.Font = new global::System.Drawing.Font("Courier New", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C3D_0 = this.EditBox1;
			location = new global::System.Drawing.Point(16, 27);
			arg_C3D_0.Location = location;
			this.EditBox1.Name = "EditBox1";
			this.EditBox1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_C77_0 = this.EditBox1;
			size = new global::System.Drawing.Size(573, 35);
			arg_C77_0.Size = size;
			this.EditBox1.TabIndex = 0;
			this.EditBox1.TabStop = false;
			this.EditBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.EditBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox2.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.EditBox2.Font = new global::System.Drawing.Font("Courier New", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_CF4_0 = this.EditBox2;
			location = new global::System.Drawing.Point(16, 61);
			arg_CF4_0.Location = location;
			this.EditBox2.MaxLength = 39;
			this.EditBox2.Name = "EditBox2";
			this.EditBox2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_D3C_0 = this.EditBox2;
			size = new global::System.Drawing.Size(573, 35);
			arg_D3C_0.Size = size;
			this.EditBox2.TabIndex = 0;
			this.EditBox2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DC0_0 = this.Label2;
			location = new global::System.Drawing.Point(591, 65);
			arg_DC0_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_DED_0 = this.Label2;
			size = new global::System.Drawing.Size(129, 28);
			arg_DED_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "سریال فعال سازی";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E75_0 = this.Label1;
			location = new global::System.Drawing.Point(591, 32);
			arg_E75_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_E9F_0 = this.Label1;
			size = new global::System.Drawing.Size(79, 28);
			arg_E9F_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "کد سیستم";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(9f, 19f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(761, 355);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.KeyPreview = true;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Register";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040003A5 RID: 933
		private global::System.ComponentModel.IContainer components;
	}
}
