namespace FruitBox
{
	// Token: 0x0200014C RID: 332
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_SuratHesab_Moshtari : global::System.Windows.Forms.Form
	{
		// Token: 0x06003154 RID: 12628 RVA: 0x0024040C File Offset: 0x0023E60C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06003155 RID: 12629 RVA: 0x0024045C File Offset: 0x0023E65C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_SuratHesab_Moshtari));
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_jamkharid = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_ta_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_az_tarikh = new global::FruitBox.DateBox2(this.components);
			this.txt_search = new global::FruitBox.EditBox(this.components);
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_tedad_safi_mande = new global::FruitBox.EditBox(this.components);
			this.Label17 = new global::System.Windows.Forms.Label();
			this.txt_tedad_havale = new global::FruitBox.EditBox(this.components);
			this.txt_tedad_safi = new global::FruitBox.EditBox(this.components);
			this.lbl_shahr = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.lbl_addr = new global::System.Windows.Forms.Label();
			this.lbl_code = new global::System.Windows.Forms.Label();
			this.lbl_codemelli = new global::System.Windows.Forms.Label();
			this.lbl_tel3 = new global::System.Windows.Forms.Label();
			this.lbl_tel4 = new global::System.Windows.Forms.Label();
			this.lbl_tel2 = new global::System.Windows.Forms.Label();
			this.lbl_tel1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem9 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelCommand9 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.ButtonCommand1 = new global::Janus.Windows.Ribbon.ButtonCommand();
			this.LabelCommand10 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_jamkharid);
			this.UiGroupBox1.Controls.Add(this.txt_ta_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_az_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_search);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.RibbonStatusBar1);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_4D2_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_4D2_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_503_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1381, 583);
			arg_503_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_jamkharid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_jamkharid.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_jamkharid.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_57E_0 = this.txt_jamkharid;
			location = new global::System.Drawing.Point(476, 187);
			arg_57E_0.Location = location;
			this.txt_jamkharid.Name = "txt_jamkharid";
			global::System.Windows.Forms.Control arg_5AC_0 = this.txt_jamkharid;
			size = new global::System.Drawing.Size(150, 31);
			arg_5AC_0.Size = size;
			this.txt_jamkharid.TabIndex = 33;
			this.txt_jamkharid.Text = "نمایش جمع فروش ها";
			this.txt_ta_tarikh.AcceptEnter = true;
			this.txt_ta_tarikh.AllowEdit = true;
			this.txt_ta_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ta_tarikh.ButtonEnable = false;
			this.txt_ta_tarikh.FocusDatePart = 1;
			this.txt_ta_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_64F_0 = this.txt_ta_tarikh;
			location = new global::System.Drawing.Point(641, 182);
			arg_64F_0.Location = location;
			this.txt_ta_tarikh.Mask = "0000/00/00";
			this.txt_ta_tarikh.Name = "txt_ta_tarikh";
			this.txt_ta_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_698_0 = this.txt_ta_tarikh;
			size = new global::System.Drawing.Size(100, 36);
			arg_698_0.Size = size;
			this.txt_ta_tarikh.TabIndex = 2;
			this.txt_ta_tarikh.Text = "1393/09/19";
			this.txt_ta_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_az_tarikh.AcceptEnter = true;
			this.txt_az_tarikh.AllowEdit = true;
			this.txt_az_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_az_tarikh.ButtonEnable = false;
			this.txt_az_tarikh.FocusDatePart = 1;
			this.txt_az_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_747_0 = this.txt_az_tarikh;
			location = new global::System.Drawing.Point(814, 182);
			arg_747_0.Location = location;
			this.txt_az_tarikh.Mask = "0000/00/00";
			this.txt_az_tarikh.Name = "txt_az_tarikh";
			this.txt_az_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_790_0 = this.txt_az_tarikh;
			size = new global::System.Drawing.Size(100, 36);
			arg_790_0.Size = size;
			this.txt_az_tarikh.TabIndex = 1;
			this.txt_az_tarikh.Text = "1393/09/19";
			this.txt_az_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_search.AcceptEnter = true;
			this.txt_search.AllowEdit = true;
			this.txt_search.AllowNew = true;
			this.txt_search.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_search.FocusColor = true;
			this.txt_search.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_83F_0 = this.txt_search;
			location = new global::System.Drawing.Point(991, 182);
			arg_83F_0.Location = location;
			this.txt_search.Name = "txt_search";
			this.txt_search.Nullable = true;
			this.txt_search.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_search.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_898_0 = this.txt_search;
			size = new global::System.Drawing.Size(317, 36);
			arg_898_0.Size = size;
			this.txt_search.TabIndex = 3;
			this.txt_search.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_920_0 = this.Label12;
			location = new global::System.Drawing.Point(915, 191);
			arg_920_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_94B_0 = this.Label12;
			size = new global::System.Drawing.Size(54, 19);
			arg_94B_0.Size = size;
			this.Label12.TabIndex = 32;
			this.Label12.Text = "از تاریخ";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9D8_0 = this.Label10;
			location = new global::System.Drawing.Point(743, 192);
			arg_9D8_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_A03_0 = this.Label10;
			size = new global::System.Drawing.Size(53, 19);
			arg_A03_0.Size = size;
			this.Label10.TabIndex = 32;
			this.Label10.Text = "تا تاریخ";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A90_0 = this.Label9;
			location = new global::System.Drawing.Point(1312, 192);
			arg_A90_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_ABB_0 = this.Label9;
			size = new global::System.Drawing.Size(61, 19);
			arg_ABB_0.Size = size;
			this.Label9.TabIndex = 32;
			this.Label9.Text = "جستجو";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_B5F_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 557);
			arg_B5F_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.ButtonCommand1,
				this.LabelCommand10,
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_BEA_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1381, 26);
			arg_BEA_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 31;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_CE4_0 = this.GridEX1;
			location = new global::System.Drawing.Point(3, 224);
			arg_CE4_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_D3C_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1375, 334);
			arg_D3C_0.Size = size;
			this.GridEX1.TabIndex = 4;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.txt_tedad_safi_mande);
			this.UiGroupBox2.Controls.Add(this.Label17);
			this.UiGroupBox2.Controls.Add(this.txt_tedad_havale);
			this.UiGroupBox2.Controls.Add(this.txt_tedad_safi);
			this.UiGroupBox2.Controls.Add(this.lbl_shahr);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			this.UiGroupBox2.Controls.Add(this.Label6);
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label8);
			this.UiGroupBox2.Controls.Add(this.Label15);
			this.UiGroupBox2.Controls.Add(this.Label11);
			this.UiGroupBox2.Controls.Add(this.Label14);
			this.UiGroupBox2.Controls.Add(this.Label16);
			this.UiGroupBox2.Controls.Add(this.Label13);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.lbl_addr);
			this.UiGroupBox2.Controls.Add(this.lbl_code);
			this.UiGroupBox2.Controls.Add(this.lbl_codemelli);
			this.UiGroupBox2.Controls.Add(this.lbl_tel3);
			this.UiGroupBox2.Controls.Add(this.lbl_tel4);
			this.UiGroupBox2.Controls.Add(this.lbl_tel2);
			this.UiGroupBox2.Controls.Add(this.lbl_tel1);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.Label1);
			this.UiGroupBox2.Controls.Add(this.txt_moshtari);
			global::System.Windows.Forms.Control arg_1045_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(6, 35);
			arg_1045_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_1076_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1375, 141);
			arg_1076_0.Size = size;
			this.UiGroupBox2.TabIndex = 0;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_tedad_safi_mande.AcceptEnter = true;
			this.txt_tedad_safi_mande.AllowEdit = true;
			this.txt_tedad_safi_mande.AllowNew = true;
			this.txt_tedad_safi_mande.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedad_safi_mande.FocusColor = true;
			this.txt_tedad_safi_mande.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1111_0 = this.txt_tedad_safi_mande;
			location = new global::System.Drawing.Point(578, 94);
			arg_1111_0.Location = location;
			this.txt_tedad_safi_mande.Name = "txt_tedad_safi_mande";
			this.txt_tedad_safi_mande.Nullable = true;
			this.txt_tedad_safi_mande.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tedad_safi_mande.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1167_0 = this.txt_tedad_safi_mande;
			size = new global::System.Drawing.Size(72, 36);
			arg_1167_0.Size = size;
			this.txt_tedad_safi_mande.TabIndex = 7;
			this.txt_tedad_safi_mande.Visible = false;
			this.txt_tedad_safi_mande.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label17.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11F9_0 = this.Label17;
			location = new global::System.Drawing.Point(651, 99);
			arg_11F9_0.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control arg_1224_0 = this.Label17;
			size = new global::System.Drawing.Size(116, 28);
			arg_1224_0.Size = size;
			this.Label17.TabIndex = 6;
			this.Label17.Text = "صافی های مانده";
			this.Label17.Visible = false;
			this.txt_tedad_havale.AcceptEnter = true;
			this.txt_tedad_havale.AllowEdit = true;
			this.txt_tedad_havale.AllowNew = true;
			this.txt_tedad_havale.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedad_havale.FocusColor = true;
			this.txt_tedad_havale.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12D0_0 = this.txt_tedad_havale;
			location = new global::System.Drawing.Point(578, 53);
			arg_12D0_0.Location = location;
			this.txt_tedad_havale.Name = "txt_tedad_havale";
			this.txt_tedad_havale.Nullable = true;
			this.txt_tedad_havale.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tedad_havale.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1326_0 = this.txt_tedad_havale;
			size = new global::System.Drawing.Size(72, 36);
			arg_1326_0.Size = size;
			this.txt_tedad_havale.TabIndex = 5;
			this.txt_tedad_havale.TabStop = false;
			this.txt_tedad_havale.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tedad_safi.AcceptEnter = true;
			this.txt_tedad_safi.AllowEdit = true;
			this.txt_tedad_safi.AllowNew = true;
			this.txt_tedad_safi.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedad_safi.FocusColor = true;
			this.txt_tedad_safi.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_13CE_0 = this.txt_tedad_safi;
			location = new global::System.Drawing.Point(578, 12);
			arg_13CE_0.Location = location;
			this.txt_tedad_safi.Name = "txt_tedad_safi";
			this.txt_tedad_safi.Nullable = true;
			this.txt_tedad_safi.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tedad_safi.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1424_0 = this.txt_tedad_safi;
			size = new global::System.Drawing.Size(72, 36);
			arg_1424_0.Size = size;
			this.txt_tedad_safi.TabIndex = 4;
			this.txt_tedad_safi.TabStop = false;
			this.txt_tedad_safi.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Windows.Forms.Control arg_1464_0 = this.lbl_shahr;
			location = new global::System.Drawing.Point(6, 110);
			arg_1464_0.Location = location;
			this.lbl_shahr.Name = "lbl_shahr";
			global::System.Windows.Forms.Control arg_148F_0 = this.lbl_shahr;
			size = new global::System.Drawing.Size(49, 14);
			arg_148F_0.Size = size;
			this.lbl_shahr.TabIndex = 3;
			this.lbl_shahr.Visible = false;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_14E1_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(37, 6);
			arg_14E1_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_1512_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(180, 129);
			arg_1512_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 2;
			this.PictureBox1.TabStop = false;
			this.PictureBox1.Visible = false;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_158F_0 = this.Label6;
			location = new global::System.Drawing.Point(922, 113);
			arg_158F_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_15BA_0 = this.Label6;
			size = new global::System.Drawing.Size(40, 14);
			arg_15BA_0.Size = size;
			this.Label6.TabIndex = 1;
			this.Label6.Text = "تلفن 2";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1621_0 = this.Label5;
			location = new global::System.Drawing.Point(922, 83);
			arg_1621_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_164C_0 = this.Label5;
			size = new global::System.Drawing.Size(40, 14);
			arg_164C_0.Size = size;
			this.Label5.TabIndex = 1;
			this.Label5.Text = "تلفن 1";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_16B3_0 = this.Label8;
			location = new global::System.Drawing.Point(1304, 84);
			arg_16B3_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_16DE_0 = this.Label8;
			size = new global::System.Drawing.Size(35, 14);
			arg_16DE_0.Size = size;
			this.Label8.TabIndex = 1;
			this.Label8.Text = "ضامن";
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1745_0 = this.Label15;
			location = new global::System.Drawing.Point(1304, 113);
			arg_1745_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_1770_0 = this.Label15;
			size = new global::System.Drawing.Size(35, 14);
			arg_1770_0.Size = size;
			this.Label15.TabIndex = 1;
			this.Label15.Text = "آدرس";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_17D7_0 = this.Label11;
			location = new global::System.Drawing.Point(1093, 53);
			arg_17D7_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1802_0 = this.Label11;
			size = new global::System.Drawing.Size(62, 14);
			arg_1802_0.Size = size;
			this.Label11.TabIndex = 1;
			this.Label11.Text = "کد مشتری";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1869_0 = this.Label14;
			location = new global::System.Drawing.Point(1305, 53);
			arg_1869_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_1894_0 = this.Label14;
			size = new global::System.Drawing.Size(46, 14);
			arg_1894_0.Size = size;
			this.Label14.TabIndex = 1;
			this.Label14.Text = "کد ملی";
			this.Label16.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_191D_0 = this.Label16;
			location = new global::System.Drawing.Point(652, 58);
			arg_191D_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_1948_0 = this.Label16;
			size = new global::System.Drawing.Size(84, 28);
			arg_1948_0.Size = size;
			this.Label16.TabIndex = 1;
			this.Label16.Text = "تعداد حواله";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_19D1_0 = this.Label13;
			location = new global::System.Drawing.Point(652, 17);
			arg_19D1_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_19FC_0 = this.Label13;
			size = new global::System.Drawing.Size(86, 28);
			arg_19FC_0.Size = size;
			this.Label13.TabIndex = 1;
			this.Label13.Text = "تعداد صافی";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1A63_0 = this.Label4;
			location = new global::System.Drawing.Point(922, 22);
			arg_1A63_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1A8E_0 = this.Label4;
			size = new global::System.Drawing.Size(54, 14);
			arg_1A8E_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "تلفن ثابت";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Label7.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1B17_0 = this.Label7;
			location = new global::System.Drawing.Point(984, 80);
			arg_1B17_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_1B45_0 = this.Label7;
			size = new global::System.Drawing.Size(317, 21);
			arg_1B45_0.Size = size;
			this.Label7.TabIndex = 1;
			this.lbl_addr.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_addr.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_addr.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_addr.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BBD_0 = this.lbl_addr;
			location = new global::System.Drawing.Point(984, 110);
			arg_1BBD_0.Location = location;
			this.lbl_addr.Name = "lbl_addr";
			global::System.Windows.Forms.Control arg_1BEB_0 = this.lbl_addr;
			size = new global::System.Drawing.Size(317, 21);
			arg_1BEB_0.Size = size;
			this.lbl_addr.TabIndex = 1;
			this.lbl_code.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_code.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_code.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_code.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1C63_0 = this.lbl_code;
			location = new global::System.Drawing.Point(984, 50);
			arg_1C63_0.Location = location;
			this.lbl_code.Name = "lbl_code";
			global::System.Windows.Forms.Control arg_1C8E_0 = this.lbl_code;
			size = new global::System.Drawing.Size(106, 21);
			arg_1C8E_0.Size = size;
			this.lbl_code.TabIndex = 1;
			this.lbl_codemelli.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_codemelli.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_codemelli.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_codemelli.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1D06_0 = this.lbl_codemelli;
			location = new global::System.Drawing.Point(1164, 50);
			arg_1D06_0.Location = location;
			this.lbl_codemelli.Name = "lbl_codemelli";
			global::System.Windows.Forms.Control arg_1D34_0 = this.lbl_codemelli;
			size = new global::System.Drawing.Size(137, 21);
			arg_1D34_0.Size = size;
			this.lbl_codemelli.TabIndex = 1;
			this.lbl_tel3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel3.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel3.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel3.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1DAC_0 = this.lbl_tel3;
			location = new global::System.Drawing.Point(770, 80);
			arg_1DAC_0.Location = location;
			this.lbl_tel3.Name = "lbl_tel3";
			global::System.Windows.Forms.Control arg_1DDA_0 = this.lbl_tel3;
			size = new global::System.Drawing.Size(149, 21);
			arg_1DDA_0.Size = size;
			this.lbl_tel3.TabIndex = 1;
			this.lbl_tel4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel4.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel4.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel4.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1E52_0 = this.lbl_tel4;
			location = new global::System.Drawing.Point(770, 110);
			arg_1E52_0.Location = location;
			this.lbl_tel4.Name = "lbl_tel4";
			global::System.Windows.Forms.Control arg_1E80_0 = this.lbl_tel4;
			size = new global::System.Drawing.Size(149, 21);
			arg_1E80_0.Size = size;
			this.lbl_tel4.TabIndex = 1;
			this.lbl_tel2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel2.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel2.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel2.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1EF8_0 = this.lbl_tel2;
			location = new global::System.Drawing.Point(770, 50);
			arg_1EF8_0.Location = location;
			this.lbl_tel2.Name = "lbl_tel2";
			global::System.Windows.Forms.Control arg_1F26_0 = this.lbl_tel2;
			size = new global::System.Drawing.Size(149, 21);
			arg_1F26_0.Size = size;
			this.lbl_tel2.TabIndex = 1;
			this.lbl_tel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tel1.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tel1.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tel1.Font = new global::System.Drawing.Font("Mitra", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1F9E_0 = this.lbl_tel1;
			location = new global::System.Drawing.Point(770, 19);
			arg_1F9E_0.Location = location;
			this.lbl_tel1.Name = "lbl_tel1";
			global::System.Windows.Forms.Control arg_1FCC_0 = this.lbl_tel1;
			size = new global::System.Drawing.Size(149, 21);
			arg_1FCC_0.Size = size;
			this.lbl_tel1.TabIndex = 1;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2022_0 = this.Label2;
			location = new global::System.Drawing.Point(923, 54);
			arg_2022_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_204D_0 = this.Label2;
			size = new global::System.Drawing.Size(36, 14);
			arg_204D_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "همراه";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20D6_0 = this.Label1;
			location = new global::System.Drawing.Point(1303, 20);
			arg_20D6_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_2101_0 = this.Label1;
			size = new global::System.Drawing.Size(61, 19);
			arg_2101_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "مشتری";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_216B_0 = this.Label3;
			location = new global::System.Drawing.Point(1108, 489);
			arg_216B_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_2196_0 = this.Label3;
			size = new global::System.Drawing.Size(40, 14);
			arg_2196_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "تا تاریخ";
			this.Label3.Visible = false;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2,
				this.ButtonItem11,
				this.ButtonItem1,
				this.ButtonItem9,
				this.ButtonItem4,
				this.ButtonItem5,
				this.ButtonItem7,
				this.ButtonItem3,
				this.ButtonItem6,
				this.ButtonItem8
			});
			global::DevComponents.DotNetBar.Bar arg_229C_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_229C_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_22CA_0 = this.Bar1;
			size = new global::System.Drawing.Size(1381, 41);
			arg_22CA_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 13;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "صورتحساب گیری جدید (F3)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "صورتحساب گیری جدید (F3)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.page_edit;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "چک های دریافتی";
			this.ButtonItem11.Visible = false;
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "چاپ (F4)";
			this.ButtonItem9.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem9.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem9.Name = "ButtonItem9";
			this.ButtonItem9.Text = "چاپ صافی های چاپ نشده";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.useredit;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "ویرایش اطلاعات مشتری (F6)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.page_edit;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "لیست چک ها";
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.bank_customer;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "حساب های بانکی (F7)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "چاپ خرید و فروش";
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.comment;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "پیامک صورتحساب";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem8.Image = global::FruitBox.My.Resources.Resources.document_attach;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "PDF";
			this.LabelCommand9.Key = "LabelCommand9";
			this.LabelCommand9.Name = "LabelCommand9";
			this.LabelCommand9.Text = "LabelCommand9";
			this.LabelCommand5.Key = "LabelCommand1";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand2";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand7.Key = "LabelCommand3";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand4";
			this.LabelCommand8.Name = "LabelCommand8";
			this.ButtonCommand1.Key = "ButtonCommand1";
			this.ButtonCommand1.Name = "ButtonCommand1";
			this.LabelCommand10.Key = "LabelCommand5";
			this.LabelCommand10.Name = "LabelCommand10";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			this.txt_moshtari.AcceptEnter = false;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = true;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد مشتری";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "Shahr";
			column3.Size = 20;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_2899_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(984, 11);
			arg_2899_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = true;
			this.txt_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2924_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(317, 36);
			arg_2924_0.Size = size;
			this.txt_moshtari.TabIndex = 0;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 14f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1381, 583);
			this.ClientSize = size;
			this.Controls.Add(this.Bar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_SuratHesab_Moshtari";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "صورتحساب مشتری";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x0400131E RID: 4894
		private global::System.ComponentModel.IContainer components;
	}
}
