namespace FruitBox
{
	// Token: 0x0200010A RID: 266
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Safi : global::System.Windows.Forms.Form
	{
		// Token: 0x06002518 RID: 9496 RVA: 0x001BF610 File Offset: 0x001BD810
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002519 RID: 9497 RVA: 0x001BF660 File Offset: 0x001BD860
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Safi));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.WarningBox1 = new global::DevComponents.DotNetBar.Controls.WarningBox();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.txt_jamkol = new global::FruitBox.CurrencyBox(this.components);
			this.Label25 = new global::System.Windows.Forms.Label();
			this.txt_mablagh2 = new global::FruitBox.CurrencyBox(this.components);
			this.UiRadioButton4 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.UiRadioButton3 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.UiRadioButton2 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.UiRadioButton1 = new global::Janus.Windows.EditControls.UIRadioButton();
			this.txt_tozih = new global::FruitBox.EditBox(this.components);
			this.MetroStatusBar1 = new global::DevComponents.DotNetBar.Metro.MetroStatusBar();
			this.LabelItem2 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem1 = new global::DevComponents.DotNetBar.LabelItem();
			this.txt_num = new global::FruitBox.NumericBox(this.components);
			this.lbl_vurudbar = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.lbl_tedadkol = new global::System.Windows.Forms.Label();
			this.lbl_baskulmabda = new global::System.Windows.Forms.Label();
			this.lbl_baskul = new global::System.Windows.Forms.Label();
			this.lbl_shmashin = new global::System.Windows.Forms.Label();
			this.lbl_sh_barname = new global::System.Windows.Forms.Label();
			this.lbl_sahebbar = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Grid_RizBar = new global::FruitBox.DataEntryGrid(this.components);
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_jamFurush = new global::FruitBox.CurrencyBox(this.components);
			this.txt_saat = new global::Janus.Windows.GridEX.EditControls.MaskedEditBox();
			this.txt_tarikh = new global::Janus.Windows.GridEX.EditControls.MaskedEditBox();
			this.txt_darsad = new global::FruitBox.NumericBox(this.components);
			this.txt_hezar2 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_hezar1 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_mande = new global::FruitBox.CurrencyBox(this.components);
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txt_sayer = new global::FruitBox.CurrencyBox(this.components);
			this.Label21 = new global::System.Windows.Forms.Label();
			this.txt_takhlie = new global::FruitBox.CurrencyBox(this.components);
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txt_karmozd = new global::FruitBox.CurrencyBox(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txt_keraye = new global::FruitBox.CurrencyBox(this.components);
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Grid_rizFurush = new global::FruitBox.DataEntryGrid(this.components);
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_rizFurush).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.WarningBox1);
			this.UiGroupBox1.Controls.Add(this.UiButton2);
			this.UiGroupBox1.Controls.Add(this.UiButton1);
			this.UiGroupBox1.Controls.Add(this.txt_jamkol);
			this.UiGroupBox1.Controls.Add(this.Label25);
			this.UiGroupBox1.Controls.Add(this.txt_mablagh2);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton4);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton3);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton2);
			this.UiGroupBox1.Controls.Add(this.UiRadioButton1);
			this.UiGroupBox1.Controls.Add(this.txt_tozih);
			this.UiGroupBox1.Controls.Add(this.MetroStatusBar1);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.lbl_vurudbar);
			this.UiGroupBox1.Controls.Add(this.Label19);
			this.UiGroupBox1.Controls.Add(this.lbl_tedadkol);
			this.UiGroupBox1.Controls.Add(this.lbl_baskulmabda);
			this.UiGroupBox1.Controls.Add(this.lbl_baskul);
			this.UiGroupBox1.Controls.Add(this.lbl_shmashin);
			this.UiGroupBox1.Controls.Add(this.lbl_sh_barname);
			this.UiGroupBox1.Controls.Add(this.lbl_sahebbar);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Grid_RizBar);
			this.UiGroupBox1.Controls.Add(this.Label20);
			this.UiGroupBox1.Controls.Add(this.Label17);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Controls.Add(this.Grid_rizFurush);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_78F_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_78F_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Silver;
			global::System.Windows.Forms.Control arg_7CD_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1046, 752);
			arg_7CD_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.WarningBox1.BackColor = global::System.Drawing.Color.FromArgb(255, 230, 159);
			this.WarningBox1.CloseButtonVisible = false;
			this.WarningBox1.ColorScheme = global::DevComponents.DotNetBar.Controls.eWarningBoxColorScheme.Yellow;
			this.WarningBox1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.WarningBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.WarningBox1.ForeColor = global::System.Drawing.Color.Black;
			this.WarningBox1.Image = global::FruitBox.My.Resources.Resources.clipboard_error;
			global::System.Windows.Forms.Control arg_892_0 = this.WarningBox1;
			location = new global::System.Drawing.Point(260, 650);
			arg_892_0.Location = location;
			this.WarningBox1.Name = "WarningBox1";
			this.WarningBox1.OptionsButtonVisible = false;
			global::System.Windows.Forms.Control arg_8CD_0 = this.WarningBox1;
			size = new global::System.Drawing.Size(786, 77);
			arg_8CD_0.Size = size;
			this.WarningBox1.TabIndex = 20;
			this.WarningBox1.Visible = false;
			this.UiButton2.Image = global::FruitBox.My.Resources.Resources.arrow_down;
			global::Janus.Windows.EditControls.UIButton arg_913_0 = this.UiButton2;
			size = new global::System.Drawing.Size(32, 32);
			arg_913_0.ImageSize = size;
			global::System.Windows.Forms.Control arg_933_0 = this.UiButton2;
			location = new global::System.Drawing.Point(266, 194);
			arg_933_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			this.UiButton2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_97C_0 = this.UiButton2;
			size = new global::System.Drawing.Size(42, 39);
			arg_97C_0.Size = size;
			this.UiButton2.TabIndex = 37;
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiButton1.Image = global::FruitBox.My.Resources.Resources.arrow_up;
			global::Janus.Windows.EditControls.UIButton arg_9C2_0 = this.UiButton1;
			size = new global::System.Drawing.Size(32, 32);
			arg_9C2_0.ImageSize = size;
			global::System.Windows.Forms.Control arg_9E2_0 = this.UiButton1;
			location = new global::System.Drawing.Point(314, 194);
			arg_9E2_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			this.UiButton1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton1.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_A2B_0 = this.UiButton1;
			size = new global::System.Drawing.Size(42, 39);
			arg_A2B_0.Size = size;
			this.UiButton1.TabIndex = 38;
			this.UiButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_jamkol.AcceptEnter = false;
			this.txt_jamkol.AllowEdit = true;
			this.txt_jamkol.AllowNew = true;
			this.txt_jamkol.AllowZero = true;
			this.txt_jamkol.FocusColor = false;
			global::System.Windows.Forms.Control arg_AA7_0 = this.txt_jamkol;
			location = new global::System.Drawing.Point(266, 151);
			arg_AA7_0.Location = location;
			this.txt_jamkol.Name = "txt_jamkol";
			this.txt_jamkol.Nullable = true;
			this.txt_jamkol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jamkol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_AFD_0 = this.txt_jamkol;
			size = new global::System.Drawing.Size(100, 21);
			arg_AFD_0.Size = size;
			this.txt_jamkol.TabIndex = 36;
			this.txt_jamkol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_jamkol.Value = value;
			this.txt_jamkol.Visible = false;
			this.txt_jamkol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label25.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label25.AutoSize = true;
			this.Label25.BackColor = global::System.Drawing.Color.Transparent;
			this.Label25.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_BAB_0 = this.Label25;
			location = new global::System.Drawing.Point(463, 65);
			arg_BAB_0.Location = location;
			this.Label25.Name = "Label25";
			global::System.Windows.Forms.Control arg_BD6_0 = this.Label25;
			size = new global::System.Drawing.Size(87, 17);
			arg_BD6_0.Size = size;
			this.Label25.TabIndex = 35;
			this.Label25.Text = "افزایش صافی";
			this.txt_mablagh2.AcceptEnter = false;
			this.txt_mablagh2.AllowEdit = true;
			this.txt_mablagh2.AllowNew = true;
			this.txt_mablagh2.AllowZero = true;
			this.txt_mablagh2.FocusColor = false;
			global::System.Windows.Forms.Control arg_C56_0 = this.txt_mablagh2;
			location = new global::System.Drawing.Point(362, 201);
			arg_C56_0.Location = location;
			this.txt_mablagh2.Name = "txt_mablagh2";
			this.txt_mablagh2.Nullable = true;
			this.txt_mablagh2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_CAC_0 = this.txt_mablagh2;
			size = new global::System.Drawing.Size(49, 21);
			arg_CAC_0.Size = size;
			this.txt_mablagh2.TabIndex = 34;
			this.txt_mablagh2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_mablagh2.Value = value;
			this.txt_mablagh2.Visible = false;
			this.txt_mablagh2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiRadioButton4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton4.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton4.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D50_0 = this.UiRadioButton4;
			location = new global::System.Drawing.Point(499, 198);
			arg_D50_0.Location = location;
			this.UiRadioButton4.Name = "UiRadioButton4";
			global::System.Windows.Forms.Control arg_D7B_0 = this.UiRadioButton4;
			size = new global::System.Drawing.Size(85, 23);
			arg_D7B_0.Size = size;
			this.UiRadioButton4.TabIndex = 32;
			this.UiRadioButton4.Text = "فی فروش";
			this.UiRadioButton4.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiRadioButton3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton3.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton3.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E08_0 = this.UiRadioButton3;
			location = new global::System.Drawing.Point(599, 199);
			arg_E08_0.Location = location;
			this.UiRadioButton3.Name = "UiRadioButton3";
			global::System.Windows.Forms.Control arg_E33_0 = this.UiRadioButton3;
			size = new global::System.Drawing.Size(85, 23);
			arg_E33_0.Size = size;
			this.UiRadioButton3.TabIndex = 32;
			this.UiRadioButton3.Text = "ریز فروش";
			this.UiRadioButton3.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiRadioButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton2.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton2.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_EC0_0 = this.UiRadioButton2;
			location = new global::System.Drawing.Point(713, 198);
			arg_EC0_0.Location = location;
			this.UiRadioButton2.Name = "UiRadioButton2";
			global::System.Windows.Forms.Control arg_EEB_0 = this.UiRadioButton2;
			size = new global::System.Drawing.Size(85, 23);
			arg_EEB_0.Size = size;
			this.UiRadioButton2.TabIndex = 32;
			this.UiRadioButton2.Text = "نوع جنس";
			this.UiRadioButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiRadioButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiRadioButton1.BackColor = global::System.Drawing.Color.Transparent;
			this.UiRadioButton1.Checked = true;
			this.UiRadioButton1.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F85_0 = this.UiRadioButton1;
			location = new global::System.Drawing.Point(839, 199);
			arg_F85_0.Location = location;
			this.UiRadioButton1.Name = "UiRadioButton1";
			global::System.Windows.Forms.Control arg_FB0_0 = this.UiRadioButton1;
			size = new global::System.Drawing.Size(104, 23);
			arg_FB0_0.Size = size;
			this.UiRadioButton1.TabIndex = 32;
			this.UiRadioButton1.TabStop = true;
			this.UiRadioButton1.Text = "قیمت میانگین";
			this.UiRadioButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_tozih.AcceptEnter = true;
			this.txt_tozih.AllowEdit = true;
			this.txt_tozih.AllowNew = true;
			this.txt_tozih.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tozih.FocusColor = true;
			this.txt_tozih.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_106D_0 = this.txt_tozih;
			location = new global::System.Drawing.Point(321, 156);
			arg_106D_0.Location = location;
			this.txt_tozih.Name = "txt_tozih";
			this.txt_tozih.Nullable = true;
			this.txt_tozih.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_tozih.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_10C6_0 = this.txt_tozih;
			size = new global::System.Drawing.Size(622, 36);
			arg_10C6_0.Size = size;
			this.txt_tozih.TabIndex = 2;
			this.txt_tozih.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.MetroStatusBar1.BackColor = global::System.Drawing.Color.White;
			this.MetroStatusBar1.BackgroundStyle.BackColor = global::System.Drawing.Color.FromArgb(0, 122, 204);
			this.MetroStatusBar1.BackgroundStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.MetroStatusBar1.ContainerControlProcessDialogKey = true;
			this.MetroStatusBar1.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.MetroStatusBar1.DragDropSupport = true;
			this.MetroStatusBar1.Font = new global::System.Drawing.Font("Segoe UI", 10.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MetroStatusBar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.LabelItem2,
				this.LabelItem1
			});
			global::System.Windows.Forms.Control arg_11B7_0 = this.MetroStatusBar1;
			location = new global::System.Drawing.Point(260, 727);
			arg_11B7_0.Location = location;
			this.MetroStatusBar1.Name = "MetroStatusBar1";
			this.MetroStatusBar1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_11F2_0 = this.MetroStatusBar1;
			size = new global::System.Drawing.Size(786, 25);
			arg_11F2_0.Size = size;
			this.MetroStatusBar1.TabIndex = 30;
			this.MetroStatusBar1.Text = "MetroStatusBar1";
			this.LabelItem2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem2.ForeColor = global::System.Drawing.Color.Black;
			this.LabelItem2.Name = "LabelItem2";
			this.LabelItem2.Text = "صافی مانده به حروف :";
			this.LabelItem1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem1.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem1.Name = "LabelItem1";
			this.txt_num.AcceptEnter = true;
			this.txt_num.AllowEdit = true;
			this.txt_num.AllowNew = true;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_num.ButtonText = "...";
			this.txt_num.FocusColor = true;
			this.txt_num.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1349_0 = this.txt_num;
			location = new global::System.Drawing.Point(818, 51);
			arg_1349_0.Location = location;
			this.txt_num.Name = "txt_num";
			this.txt_num.Nullable = true;
			this.txt_num.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_num.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_139F_0 = this.txt_num;
			size = new global::System.Drawing.Size(125, 36);
			arg_139F_0.Size = size;
			this.txt_num.TabIndex = 0;
			this.txt_num.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_num.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_vurudbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_vurudbar.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_vurudbar.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_vurudbar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1431_0 = this.lbl_vurudbar;
			location = new global::System.Drawing.Point(818, 93);
			arg_1431_0.Location = location;
			this.lbl_vurudbar.Name = "lbl_vurudbar";
			global::System.Windows.Forms.Control arg_145C_0 = this.lbl_vurudbar;
			size = new global::System.Drawing.Size(125, 23);
			arg_145C_0.Size = size;
			this.lbl_vurudbar.TabIndex = 28;
			this.lbl_vurudbar.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label19.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label19.BackColor = global::System.Drawing.Color.Transparent;
			this.Label19.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Label19.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_14E3_0 = this.Label19;
			location = new global::System.Drawing.Point(321, 62);
			arg_14E3_0.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control arg_1511_0 = this.Label19;
			size = new global::System.Drawing.Size(140, 23);
			arg_1511_0.Size = size;
			this.Label19.TabIndex = 28;
			this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_tedadkol.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_tedadkol.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_tedadkol.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_tedadkol.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1598_0 = this.lbl_tedadkol;
			location = new global::System.Drawing.Point(321, 125);
			arg_1598_0.Location = location;
			this.lbl_tedadkol.Name = "lbl_tedadkol";
			global::System.Windows.Forms.Control arg_15C6_0 = this.lbl_tedadkol;
			size = new global::System.Drawing.Size(140, 23);
			arg_15C6_0.Size = size;
			this.lbl_tedadkol.TabIndex = 28;
			this.lbl_tedadkol.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_baskulmabda.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_baskulmabda.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_baskulmabda.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_baskulmabda.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_164D_0 = this.lbl_baskulmabda;
			location = new global::System.Drawing.Point(554, 126);
			arg_164D_0.Location = location;
			this.lbl_baskulmabda.Name = "lbl_baskulmabda";
			global::System.Windows.Forms.Control arg_167B_0 = this.lbl_baskulmabda;
			size = new global::System.Drawing.Size(165, 23);
			arg_167B_0.Size = size;
			this.lbl_baskulmabda.TabIndex = 28;
			this.lbl_baskulmabda.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_baskul.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_baskul.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_baskul.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_baskul.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1702_0 = this.lbl_baskul;
			location = new global::System.Drawing.Point(818, 126);
			arg_1702_0.Location = location;
			this.lbl_baskul.Name = "lbl_baskul";
			global::System.Windows.Forms.Control arg_172D_0 = this.lbl_baskul;
			size = new global::System.Drawing.Size(125, 23);
			arg_172D_0.Size = size;
			this.lbl_baskul.TabIndex = 28;
			this.lbl_baskul.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_shmashin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_shmashin.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_shmashin.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_shmashin.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_17B4_0 = this.lbl_shmashin;
			location = new global::System.Drawing.Point(554, 94);
			arg_17B4_0.Location = location;
			this.lbl_shmashin.Name = "lbl_shmashin";
			global::System.Windows.Forms.Control arg_17E2_0 = this.lbl_shmashin;
			size = new global::System.Drawing.Size(165, 23);
			arg_17E2_0.Size = size;
			this.lbl_shmashin.TabIndex = 28;
			this.lbl_shmashin.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_sh_barname.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sh_barname.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_sh_barname.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_sh_barname.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1869_0 = this.lbl_sh_barname;
			location = new global::System.Drawing.Point(321, 92);
			arg_1869_0.Location = location;
			this.lbl_sh_barname.Name = "lbl_sh_barname";
			global::System.Windows.Forms.Control arg_1897_0 = this.lbl_sh_barname;
			size = new global::System.Drawing.Size(140, 23);
			arg_1897_0.Size = size;
			this.lbl_sh_barname.TabIndex = 28;
			this.lbl_sh_barname.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_sahebbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sahebbar.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_sahebbar.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_sahebbar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_191E_0 = this.lbl_sahebbar;
			location = new global::System.Drawing.Point(554, 60);
			arg_191E_0.Location = location;
			this.lbl_sahebbar.Name = "lbl_sahebbar";
			global::System.Windows.Forms.Control arg_194C_0 = this.lbl_sahebbar;
			size = new global::System.Drawing.Size(165, 23);
			arg_194C_0.Size = size;
			this.lbl_sahebbar.TabIndex = 28;
			this.lbl_sahebbar.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_19D3_0 = this.Label8;
			location = new global::System.Drawing.Point(722, 127);
			arg_19D3_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_19FE_0 = this.Label8;
			size = new global::System.Drawing.Size(79, 17);
			arg_19FE_0.Size = size;
			this.Label8.TabIndex = 25;
			this.Label8.Text = "باسکول مبدا";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A8B_0 = this.Label13;
			location = new global::System.Drawing.Point(946, 129);
			arg_1A8B_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_1AB6_0 = this.Label13;
			size = new global::System.Drawing.Size(52, 17);
			arg_1AB6_0.Size = size;
			this.Label13.TabIndex = 26;
			this.Label13.Text = "باسکول";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1B43_0 = this.Label14;
			location = new global::System.Drawing.Point(464, 128);
			arg_1B43_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_1B6E_0 = this.Label14;
			size = new global::System.Drawing.Size(58, 17);
			arg_1B6E_0.Size = size;
			this.Label14.TabIndex = 27;
			this.Label14.Text = "تعداد کل";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BF8_0 = this.Label11;
			location = new global::System.Drawing.Point(945, 96);
			arg_1BF8_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_1C23_0 = this.Label11;
			size = new global::System.Drawing.Size(80, 17);
			arg_1C23_0.Size = size;
			this.Label11.TabIndex = 21;
			this.Label11.Text = "تاریخ ورود بار";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1CAD_0 = this.Label10;
			location = new global::System.Drawing.Point(464, 95);
			arg_1CAD_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_1CD8_0 = this.Label10;
			size = new global::System.Drawing.Size(87, 17);
			arg_1CD8_0.Size = size;
			this.Label10.TabIndex = 22;
			this.Label10.Text = "شماره بارنامه";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1D62_0 = this.Label9;
			location = new global::System.Drawing.Point(722, 98);
			arg_1D62_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_1D8D_0 = this.Label9;
			size = new global::System.Drawing.Size(92, 17);
			arg_1D8D_0.Size = size;
			this.Label9.TabIndex = 23;
			this.Label9.Text = "شماره ماشین";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1E17_0 = this.Label12;
			location = new global::System.Drawing.Point(722, 63);
			arg_1E17_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_1E42_0 = this.Label12;
			size = new global::System.Drawing.Size(62, 17);
			arg_1E42_0.Size = size;
			this.Label12.TabIndex = 24;
			this.Label12.Text = "صاحب بار";
			this.Grid_RizBar.AlternatingColors = true;
			this.Grid_RizBar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.Grid_RizBar.AutoEdit = true;
			gridEXLayout.LayoutString = componentResourceManager.GetString("Grid_RizBar_DesignTimeLayout.LayoutString");
			this.Grid_RizBar.DesignTimeLayout = gridEXLayout;
			this.Grid_RizBar.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_RizBar.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_RizBar.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.Grid_RizBar.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_RizBar.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1F17_0 = this.Grid_RizBar;
			location = new global::System.Drawing.Point(266, 239);
			arg_1F17_0.Location = location;
			this.Grid_RizBar.Name = "Grid_RizBar";
			this.Grid_RizBar.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_RizBar.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_1F62_0 = this.Grid_RizBar;
			size = new global::System.Drawing.Size(780, 412);
			arg_1F62_0.Size = size;
			this.Grid_RizBar.TabIndex = 2;
			this.Grid_RizBar.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_RizBar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label20.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label20.AutoSize = true;
			this.Label20.BackColor = global::System.Drawing.Color.Transparent;
			this.Label20.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1FF7_0 = this.Label20;
			location = new global::System.Drawing.Point(942, 204);
			arg_1FF7_0.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control arg_2022_0 = this.Label20;
			size = new global::System.Drawing.Size(99, 17);
			arg_2022_0.Size = size;
			this.Label20.TabIndex = 17;
			this.Label20.Text = "صافی بر اساس";
			this.Label17.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20AF_0 = this.Label17;
			location = new global::System.Drawing.Point(949, 168);
			arg_20AF_0.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control arg_20DA_0 = this.Label17;
			size = new global::System.Drawing.Size(59, 17);
			arg_20DA_0.Size = size;
			this.Label17.TabIndex = 17;
			this.Label17.Text = "توضیحات";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2164_0 = this.Label6;
			location = new global::System.Drawing.Point(945, 61);
			arg_2164_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_218F_0 = this.Label6;
			size = new global::System.Drawing.Size(78, 17);
			arg_218F_0.Size = size;
			this.Label6.TabIndex = 17;
			this.Label6.Text = "شماره سند";
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.txt_jamFurush);
			this.UiGroupBox2.Controls.Add(this.txt_saat);
			this.UiGroupBox2.Controls.Add(this.txt_tarikh);
			this.UiGroupBox2.Controls.Add(this.txt_darsad);
			this.UiGroupBox2.Controls.Add(this.txt_hezar2);
			this.UiGroupBox2.Controls.Add(this.txt_hezar1);
			this.UiGroupBox2.Controls.Add(this.txt_mande);
			this.UiGroupBox2.Controls.Add(this.Label22);
			this.UiGroupBox2.Controls.Add(this.Label23);
			this.UiGroupBox2.Controls.Add(this.Label7);
			this.UiGroupBox2.Controls.Add(this.txt_sayer);
			this.UiGroupBox2.Controls.Add(this.Label21);
			this.UiGroupBox2.Controls.Add(this.txt_takhlie);
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label16);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.Label24);
			this.UiGroupBox2.Controls.Add(this.Label18);
			this.UiGroupBox2.Controls.Add(this.Label15);
			this.UiGroupBox2.Controls.Add(this.Label3);
			this.UiGroupBox2.Controls.Add(this.txt_karmozd);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.txt_keraye);
			this.UiGroupBox2.Controls.Add(this.Label1);
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Left;
			global::System.Windows.Forms.Control arg_2409_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 41);
			arg_2409_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_243A_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(260, 711);
			arg_243A_0.Size = size;
			this.UiGroupBox2.TabIndex = 0;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_jamFurush.AcceptEnter = true;
			this.txt_jamFurush.AllowEdit = false;
			this.txt_jamFurush.AllowNew = true;
			this.txt_jamFurush.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_jamFurush.FocusColor = true;
			this.txt_jamFurush.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_24E6_0 = this.txt_jamFurush;
			location = new global::System.Drawing.Point(12, 20);
			arg_24E6_0.Location = location;
			this.txt_jamFurush.Name = "txt_jamFurush";
			this.txt_jamFurush.Nullable = true;
			this.txt_jamFurush.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jamFurush.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_253F_0 = this.txt_jamFurush;
			size = new global::System.Drawing.Size(135, 36);
			arg_253F_0.Size = size;
			this.txt_jamFurush.TabIndex = 0;
			this.txt_jamFurush.TabStop = false;
			this.txt_jamFurush.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jamFurush.Value = value;
			this.txt_jamFurush.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_saat.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			global::System.Windows.Forms.Control arg_25AB_0 = this.txt_saat;
			location = new global::System.Drawing.Point(14, 682);
			arg_25AB_0.Location = location;
			this.txt_saat.Mask = "00:00";
			this.txt_saat.Name = "txt_saat";
			this.txt_saat.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_25F4_0 = this.txt_saat;
			size = new global::System.Drawing.Size(91, 21);
			arg_25F4_0.Size = size;
			this.txt_saat.TabIndex = 4;
			this.txt_saat.TabStop = false;
			this.txt_saat.Visible = false;
			this.txt_saat.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.VS2010;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			global::System.Windows.Forms.Control arg_2652_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(14, 655);
			arg_2652_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::System.Windows.Forms.Control arg_269B_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(91, 21);
			arg_269B_0.Size = size;
			this.txt_tarikh.TabIndex = 3;
			this.txt_tarikh.TabStop = false;
			this.txt_tarikh.Visible = false;
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.VS2010;
			this.txt_darsad.AcceptEnter = true;
			this.txt_darsad.AllowEdit = true;
			this.txt_darsad.AllowNew = true;
			this.txt_darsad.AllowZero = true;
			this.txt_darsad.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_darsad.DecimalDigits = 2;
			this.txt_darsad.FixLength = 2;
			this.txt_darsad.FocusColor = true;
			this.txt_darsad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2788_0 = this.txt_darsad;
			location = new global::System.Drawing.Point(12, 62);
			arg_2788_0.Location = location;
			this.txt_darsad.MaxLength = 5;
			this.txt_darsad.Name = "txt_darsad";
			this.txt_darsad.Nullable = true;
			this.txt_darsad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_darsad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_27EE_0 = this.txt_darsad;
			size = new global::System.Drawing.Size(135, 36);
			arg_27EE_0.Size = size;
			this.txt_darsad.TabIndex = 0;
			this.txt_darsad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_darsad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hezar2.AcceptEnter = true;
			this.txt_hezar2.AllowEdit = false;
			this.txt_hezar2.AllowNew = true;
			this.txt_hezar2.FocusColor = true;
			this.txt_hezar2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2888_0 = this.txt_hezar2;
			location = new global::System.Drawing.Point(14, 450);
			arg_2888_0.Location = location;
			this.txt_hezar2.MaxLength = 10;
			this.txt_hezar2.Name = "txt_hezar2";
			this.txt_hezar2.Nullable = true;
			this.txt_hezar2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hezar2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_28EF_0 = this.txt_hezar2;
			size = new global::System.Drawing.Size(135, 36);
			arg_28EF_0.Size = size;
			this.txt_hezar2.TabIndex = 5;
			this.txt_hezar2.TabStop = false;
			this.txt_hezar2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hezar2.Value = value;
			this.txt_hezar2.Visible = false;
			this.txt_hezar2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hezar1.AcceptEnter = true;
			this.txt_hezar1.AllowEdit = false;
			this.txt_hezar1.AllowNew = true;
			this.txt_hezar1.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_hezar1.FocusColor = true;
			this.txt_hezar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_29D3_0 = this.txt_hezar1;
			location = new global::System.Drawing.Point(12, 315);
			arg_29D3_0.Location = location;
			this.txt_hezar1.MaxLength = 10;
			this.txt_hezar1.Name = "txt_hezar1";
			this.txt_hezar1.Nullable = true;
			this.txt_hezar1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hezar1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2A3A_0 = this.txt_hezar1;
			size = new global::System.Drawing.Size(135, 36);
			arg_2A3A_0.Size = size;
			this.txt_hezar1.TabIndex = 5;
			this.txt_hezar1.TabStop = false;
			this.txt_hezar1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hezar1.Value = value;
			this.txt_hezar1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_mande.AcceptEnter = true;
			this.txt_mande.AllowEdit = true;
			this.txt_mande.AllowNew = true;
			this.txt_mande.FocusColor = true;
			this.txt_mande.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2AEF_0 = this.txt_mande;
			location = new global::System.Drawing.Point(12, 273);
			arg_2AEF_0.Location = location;
			this.txt_mande.MaxLength = 10;
			this.txt_mande.Name = "txt_mande";
			this.txt_mande.Nullable = true;
			this.txt_mande.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mande.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2B56_0 = this.txt_mande;
			size = new global::System.Drawing.Size(135, 36);
			arg_2B56_0.Size = size;
			this.txt_mande.TabIndex = 2;
			this.txt_mande.TabStop = false;
			this.txt_mande.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_mande.Value = value;
			this.txt_mande.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label22.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label22.AutoSize = true;
			this.Label22.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2BE0_0 = this.Label22;
			location = new global::System.Drawing.Point(113, 690);
			arg_2BE0_0.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control arg_2C0B_0 = this.Label22;
			size = new global::System.Drawing.Size(118, 13);
			arg_2C0B_0.Size = size;
			this.Label22.TabIndex = 15;
			this.Label22.Text = "ساعت اعلام به مشتری";
			this.Label22.Visible = false;
			this.Label23.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label23.AutoSize = true;
			this.Label23.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2C7F_0 = this.Label23;
			location = new global::System.Drawing.Point(117, 663);
			arg_2C7F_0.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control arg_2CAA_0 = this.Label23;
			size = new global::System.Drawing.Size(108, 13);
			arg_2CAA_0.Size = size;
			this.Label23.TabIndex = 15;
			this.Label23.Text = "تاریخ اعلام به مشتری";
			this.Label23.Visible = false;
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2D36_0 = this.Label7;
			location = new global::System.Drawing.Point(149, 282);
			arg_2D36_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_2D61_0 = this.Label7;
			size = new global::System.Drawing.Size(88, 19);
			arg_2D61_0.Size = size;
			this.Label7.TabIndex = 15;
			this.Label7.Text = "صافی مانده";
			this.txt_sayer.AcceptEnter = true;
			this.txt_sayer.AllowEdit = false;
			this.txt_sayer.AllowNew = true;
			this.txt_sayer.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_sayer.FocusColor = true;
			this.txt_sayer.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2E15_0 = this.txt_sayer;
			location = new global::System.Drawing.Point(12, 231);
			arg_2E15_0.Location = location;
			this.txt_sayer.MaxLength = 10;
			this.txt_sayer.Name = "txt_sayer";
			this.txt_sayer.Nullable = true;
			this.txt_sayer.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sayer.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2E7C_0 = this.txt_sayer;
			size = new global::System.Drawing.Size(135, 36);
			arg_2E7C_0.Size = size;
			this.txt_sayer.TabIndex = 4;
			this.txt_sayer.TabStop = false;
			this.txt_sayer.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sayer.Value = value;
			this.txt_sayer.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label21.AutoSize = true;
			this.Label21.BackColor = global::System.Drawing.Color.Transparent;
			this.Label21.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2F1E_0 = this.Label21;
			location = new global::System.Drawing.Point(149, 242);
			arg_2F1E_0.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control arg_2F49_0 = this.Label21;
			size = new global::System.Drawing.Size(104, 19);
			arg_2F49_0.Size = size;
			this.Label21.TabIndex = 15;
			this.Label21.Text = "سایر هزینه ها";
			this.txt_takhlie.AcceptEnter = true;
			this.txt_takhlie.AllowEdit = false;
			this.txt_takhlie.AllowNew = true;
			this.txt_takhlie.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_takhlie.FocusColor = true;
			this.txt_takhlie.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2FFD_0 = this.txt_takhlie;
			location = new global::System.Drawing.Point(12, 189);
			arg_2FFD_0.Location = location;
			this.txt_takhlie.MaxLength = 10;
			this.txt_takhlie.Name = "txt_takhlie";
			this.txt_takhlie.Nullable = true;
			this.txt_takhlie.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_takhlie.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3064_0 = this.txt_takhlie;
			size = new global::System.Drawing.Size(135, 36);
			arg_3064_0.Size = size;
			this.txt_takhlie.TabIndex = 4;
			this.txt_takhlie.TabStop = false;
			this.txt_takhlie.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_takhlie.Value = value;
			this.txt_takhlie.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3106_0 = this.Label5;
			location = new global::System.Drawing.Point(149, 198);
			arg_3106_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_3131_0 = this.Label5;
			size = new global::System.Drawing.Size(45, 19);
			arg_3131_0.Size = size;
			this.Label5.TabIndex = 15;
			this.Label5.Text = "تخلیه";
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_31B0_0 = this.Label16;
			location = new global::System.Drawing.Point(151, 460);
			arg_31B0_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_31DB_0 = this.Label16;
			size = new global::System.Drawing.Size(101, 17);
			arg_31DB_0.Size = size;
			this.Label16.TabIndex = 15;
			this.Label16.Text = "افزایش هزار ریال";
			this.Label16.Visible = false;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3267_0 = this.Label4;
			location = new global::System.Drawing.Point(150, 155);
			arg_3267_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_3292_0 = this.Label4;
			size = new global::System.Drawing.Size(41, 19);
			arg_3292_0.Size = size;
			this.Label4.TabIndex = 15;
			this.Label4.Text = "کرایه";
			this.Label24.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label24.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Label24.Font = new global::System.Drawing.Font("Tahoma", 15.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3312_0 = this.Label24;
			location = new global::System.Drawing.Point(162, 362);
			arg_3312_0.Location = location;
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control arg_333D_0 = this.Label24;
			size = new global::System.Drawing.Size(96, 37);
			arg_333D_0.Size = size;
			this.Label24.TabIndex = 27;
			this.Label24.Text = "صافی کل";
			this.Label24.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label18.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label18.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Label18.Font = new global::System.Drawing.Font("Mitra", 15.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_33C7_0 = this.Label18;
			location = new global::System.Drawing.Point(3, 362);
			arg_33C7_0.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control arg_33F5_0 = this.Label18;
			size = new global::System.Drawing.Size(168, 37);
			arg_33F5_0.Size = size;
			this.Label18.TabIndex = 27;
			this.Label18.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3471_0 = this.Label15;
			location = new global::System.Drawing.Point(149, 326);
			arg_3471_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_349C_0 = this.Label15;
			size = new global::System.Drawing.Size(104, 19);
			arg_349C_0.Size = size;
			this.Label15.TabIndex = 15;
			this.Label15.Text = "کسر هزار ریال";
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3518_0 = this.Label3;
			location = new global::System.Drawing.Point(150, 113);
			arg_3518_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_3543_0 = this.Label3;
			size = new global::System.Drawing.Size(50, 19);
			arg_3543_0.Size = size;
			this.Label3.TabIndex = 15;
			this.Label3.Text = "کارمزد";
			this.txt_karmozd.AcceptEnter = false;
			this.txt_karmozd.AllowEdit = true;
			this.txt_karmozd.AllowNegative = true;
			this.txt_karmozd.AllowNew = true;
			this.txt_karmozd.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_karmozd.FixLength = 15;
			this.txt_karmozd.FocusColor = true;
			this.txt_karmozd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_360F_0 = this.txt_karmozd;
			location = new global::System.Drawing.Point(12, 104);
			arg_360F_0.Location = location;
			this.txt_karmozd.MaxLength = 15;
			this.txt_karmozd.Name = "txt_karmozd";
			this.txt_karmozd.Nullable = false;
			this.txt_karmozd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_karmozd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_3676_0 = this.txt_karmozd;
			size = new global::System.Drawing.Size(135, 36);
			arg_3676_0.Size = size;
			this.txt_karmozd.TabIndex = 1;
			this.txt_karmozd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_karmozd.Value = value;
			this.txt_karmozd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3708_0 = this.Label2;
			location = new global::System.Drawing.Point(149, 72);
			arg_3708_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_3733_0 = this.Label2;
			size = new global::System.Drawing.Size(89, 19);
			arg_3733_0.Size = size;
			this.Label2.TabIndex = 15;
			this.Label2.Text = "درصد کارمزد";
			this.txt_keraye.AcceptEnter = true;
			this.txt_keraye.AllowEdit = false;
			this.txt_keraye.AllowNew = true;
			this.txt_keraye.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_keraye.FocusColor = true;
			this.txt_keraye.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_37E7_0 = this.txt_keraye;
			location = new global::System.Drawing.Point(12, 146);
			arg_37E7_0.Location = location;
			this.txt_keraye.MaxLength = 10;
			this.txt_keraye.Name = "txt_keraye";
			this.txt_keraye.Nullable = true;
			this.txt_keraye.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_keraye.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_384E_0 = this.txt_keraye;
			size = new global::System.Drawing.Size(135, 36);
			arg_384E_0.Size = size;
			this.txt_keraye.TabIndex = 3;
			this.txt_keraye.TabStop = false;
			this.txt_keraye.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_keraye.Value = value;
			this.txt_keraye.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_38ED_0 = this.Label1;
			location = new global::System.Drawing.Point(148, 25);
			arg_38ED_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_3918_0 = this.Label1;
			size = new global::System.Drawing.Size(84, 19);
			arg_3918_0.Size = size;
			this.Label1.TabIndex = 15;
			this.Label1.Text = "جمع فروش";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3,
				this.ButtonItem4,
				this.ButtonItem5,
				this.ButtonItem6,
				this.ButtonItem7,
				this.ButtonItem8
			});
			global::DevComponents.DotNetBar.Bar arg_3A07_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_3A07_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_3A35_0 = this.Bar1;
			size = new global::System.Drawing.Size(1046, 41);
			arg_3A35_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 13;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.page;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem1.Visible = false;
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف (F5)";
			this.ButtonItem3.Visible = false;
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "چاپ (F4)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.customers_coins;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "شراکت";
			this.ButtonItem6.AutoCheckOnClick = true;
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.money_coins_add;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "افزایش / کاهش مبلغ صافی";
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.comment;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "پیامک صافی";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem8.Image = global::FruitBox.My.Resources.Resources.document_attach;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "PDF";
			this.Grid_rizFurush.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_rizFurush.AlternatingColors = true;
			this.Grid_rizFurush.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout2.LayoutString = componentResourceManager.GetString("Grid_rizFurush_DesignTimeLayout.LayoutString");
			this.Grid_rizFurush.DesignTimeLayout = gridEXLayout2;
			this.Grid_rizFurush.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_rizFurush.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_rizFurush.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.Grid_rizFurush.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_rizFurush.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_3D58_0 = this.Grid_rizFurush;
			location = new global::System.Drawing.Point(266, 239);
			arg_3D58_0.Location = location;
			this.Grid_rizFurush.Name = "Grid_rizFurush";
			this.Grid_rizFurush.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_rizFurush.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_3DA3_0 = this.Grid_rizFurush;
			size = new global::System.Drawing.Size(780, 412);
			arg_3DA3_0.Size = size;
			this.Grid_rizFurush.TabIndex = 33;
			this.Grid_rizFurush.TabStop = false;
			this.Grid_rizFurush.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_rizFurush.Visible = false;
			this.Grid_rizFurush.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1046, 752);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Safi";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "ثبت صافی فروش";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_rizFurush).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000E6D RID: 3693
		private global::System.ComponentModel.IContainer components;
	}
}
