namespace FruitBox
{
	// Token: 0x02000114 RID: 276
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_SudKhorde : global::System.Windows.Forms.Form
	{
		// Token: 0x060027D8 RID: 10200 RVA: 0x001E19F0 File Offset: 0x001DFBF0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060027D9 RID: 10201 RVA: 0x001E1A40 File Offset: 0x001DFC40
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_SudKhorde));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Bar3 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Bar2 = new global::DevComponents.DotNetBar.Bar();
			this.DataEntryGrid1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_ta_tarikh = new global::FruitBox.EditBox(this.components);
			this.txt_az_tarikh = new global::FruitBox.EditBox(this.components);
			this.CurrencyBox2 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_sud = new global::FruitBox.CurrencyBox(this.components);
			this.txt_hazine = new global::FruitBox.CurrencyBox(this.components);
			this.CurrencyBox1 = new global::FruitBox.CurrencyBox(this.components);
			this.txt_kharid = new global::FruitBox.CurrencyBox(this.components);
			this.txt_furush = new global::FruitBox.CurrencyBox(this.components);
			this.txt_num = new global::FruitBox.NavBox();
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataEntryGrid1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			this.SuspendLayout();
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2
			});
			global::DevComponents.DotNetBar.Bar arg_329_0 = this.Bar1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_329_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_357_0 = this.Bar1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(589, 41);
			arg_357_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 16;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_3E9_0 = this.Label1;
			location = new global::System.Drawing.Point(1132, 151);
			arg_3E9_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_414_0 = this.Label1;
			size = new global::System.Drawing.Size(68, 16);
			arg_414_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "جمع فروش";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_47B_0 = this.Label2;
			location = new global::System.Drawing.Point(1389, 110);
			arg_47B_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_4A6_0 = this.Label2;
			size = new global::System.Drawing.Size(62, 16);
			arg_4A6_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "جمع خرید";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_510_0 = this.Label3;
			location = new global::System.Drawing.Point(919, 152);
			arg_510_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_53B_0 = this.Label3;
			size = new global::System.Drawing.Size(33, 16);
			arg_53B_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "سود";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "چاپ (F4)";
			this.UiGroupBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.DataEntryGrid1);
			this.UiGroupBox1.Controls.Add(this.txt_ta_tarikh);
			this.UiGroupBox1.Controls.Add(this.txt_az_tarikh);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.CurrencyBox2);
			this.UiGroupBox1.Controls.Add(this.txt_sud);
			this.UiGroupBox1.Controls.Add(this.txt_hazine);
			this.UiGroupBox1.Controls.Add(this.CurrencyBox1);
			this.UiGroupBox1.Controls.Add(this.txt_kharid);
			this.UiGroupBox1.Controls.Add(this.txt_furush);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.Bar3);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_7D3_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_7D3_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_804_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(1476, 508);
			arg_804_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.Label5);
			this.UiGroupBox2.Controls.Add(this.Label4);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			global::System.Windows.Forms.Control arg_889_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(3, 64);
			arg_889_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_8B7_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(485, 112);
			arg_8B7_0.Size = size;
			this.UiGroupBox2.TabIndex = 24;
			this.UiGroupBox2.Visible = false;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_94A_0 = this.Label5;
			location = new global::System.Drawing.Point(144, 84);
			arg_94A_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_978_0 = this.Label5;
			size = new global::System.Drawing.Size(335, 28);
			arg_978_0.Size = size;
			this.Label5.TabIndex = 1;
			this.Label5.Text = "از طریق تعریف شرکا اقدام به ثبت درصدها بفرمائید";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A01_0 = this.Label4;
			location = new global::System.Drawing.Point(276, 42);
			arg_A01_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_A2F_0 = this.Label4;
			size = new global::System.Drawing.Size(203, 28);
			arg_A2F_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "جمع درصد شرکا 100 نمیباشد";
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.Image = global::FruitBox.My.Resources.Resources.onebit_36;
			global::System.Windows.Forms.Control arg_A97_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(123, 20);
			arg_A97_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_AC2_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(48, 48);
			arg_AC2_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.PictureBox1.TabIndex = 0;
			this.PictureBox1.TabStop = false;
			this.Bar3.AntiAlias = true;
			this.Bar3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar3.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar3.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem3,
				this.ButtonItem4,
				this.ButtonItem5
			});
			global::DevComponents.DotNetBar.Bar arg_B70_0 = this.Bar3;
			location = new global::System.Drawing.Point(0, 0);
			arg_B70_0.Location = location;
			this.Bar3.Name = "Bar3";
			global::DevComponents.DotNetBar.Bar arg_B9E_0 = this.Bar3;
			size = new global::System.Drawing.Size(1476, 41);
			arg_B9E_0.Size = size;
			this.Bar3.Stretch = true;
			this.Bar3.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar3.TabIndex = 20;
			this.Bar3.TabStop = false;
			this.Bar3.Text = "Bar3";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "ثبت (F2)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.customer_coins;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "تعریف شرکا";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "حذف (F5)";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_CED_0 = this.Label11;
			location = new global::System.Drawing.Point(919, 110);
			arg_CED_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_D18_0 = this.Label11;
			size = new global::System.Drawing.Size(68, 16);
			arg_D18_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "خرید از قبل";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_D7F_0 = this.Label6;
			location = new global::System.Drawing.Point(1133, 67);
			arg_D7F_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_DAA_0 = this.Label6;
			size = new global::System.Drawing.Size(46, 16);
			arg_DAA_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "تا تاریخ";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_E11_0 = this.Label8;
			location = new global::System.Drawing.Point(1132, 110);
			arg_E11_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_E3C_0 = this.Label8;
			size = new global::System.Drawing.Size(112, 16);
			arg_E3C_0.Size = size;
			this.Label8.TabIndex = 0;
			this.Label8.Text = "خرید مانده در مغازه";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_EA6_0 = this.Label7;
			location = new global::System.Drawing.Point(1389, 152);
			arg_EA6_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_ED1_0 = this.Label7;
			size = new global::System.Drawing.Size(84, 16);
			arg_ED1_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "جمع هزینه ها";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_F38_0 = this.Label10;
			location = new global::System.Drawing.Point(1390, 68);
			arg_F38_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_F63_0 = this.Label10;
			size = new global::System.Drawing.Size(46, 16);
			arg_F63_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "از تاریخ";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_FCD_0 = this.Label9;
			location = new global::System.Drawing.Point(1028, 470);
			arg_FCD_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_FF8_0 = this.Label9;
			size = new global::System.Drawing.Size(44, 16);
			arg_FF8_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "شماره";
			this.Label9.Visible = false;
			this.Bar2.AntiAlias = true;
			this.Bar2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar2.DockSide = global::DevComponents.DotNetBar.eDockSide.Top;
			this.Bar2.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar2.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1
			});
			global::DevComponents.DotNetBar.Bar arg_10A3_0 = this.Bar2;
			location = new global::System.Drawing.Point(0, 0);
			arg_10A3_0.Location = location;
			this.Bar2.Name = "Bar2";
			global::DevComponents.DotNetBar.Bar arg_10D1_0 = this.Bar2;
			size = new global::System.Drawing.Size(589, 41);
			arg_10D1_0.Size = size;
			this.Bar2.Stretch = true;
			this.Bar2.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar2.TabIndex = 15;
			this.Bar2.TabStop = false;
			this.Bar2.Text = "Bar2";
			this.DataEntryGrid1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.DataEntryGrid1.AlternatingColors = true;
			this.DataEntryGrid1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("DataEntryGrid1_DesignTimeLayout.LayoutString");
			this.DataEntryGrid1.DesignTimeLayout = gridEXLayout;
			this.DataEntryGrid1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.DataEntryGrid1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.DataEntryGrid1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.DataEntryGrid1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.DataEntryGrid1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_11CD_0 = this.DataEntryGrid1;
			location = new global::System.Drawing.Point(479, 182);
			arg_11CD_0.Location = location;
			this.DataEntryGrid1.Name = "DataEntryGrid1";
			this.DataEntryGrid1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.DataEntryGrid1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.DataEntryGrid1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_1225_0 = this.DataEntryGrid1;
			size = new global::System.Drawing.Size(997, 326);
			arg_1225_0.Size = size;
			this.DataEntryGrid1.TabIndex = 26;
			this.DataEntryGrid1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.DataEntryGrid1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.DataEntryGrid1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.DataEntryGrid1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.DataEntryGrid1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.DataEntryGrid1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.DataEntryGrid1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_ta_tarikh.AcceptEnter = true;
			this.txt_ta_tarikh.AllowEdit = false;
			this.txt_ta_tarikh.AllowNew = true;
			this.txt_ta_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ta_tarikh.FocusColor = true;
			this.txt_ta_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1326_0 = this.txt_ta_tarikh;
			location = new global::System.Drawing.Point(993, 56);
			arg_1326_0.Location = location;
			this.txt_ta_tarikh.Name = "txt_ta_tarikh";
			this.txt_ta_tarikh.Nullable = true;
			this.txt_ta_tarikh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_ta_tarikh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_137F_0 = this.txt_ta_tarikh;
			size = new global::System.Drawing.Size(137, 36);
			arg_137F_0.Size = size;
			this.txt_ta_tarikh.TabIndex = 25;
			this.txt_ta_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_az_tarikh.AcceptEnter = true;
			this.txt_az_tarikh.AllowEdit = false;
			this.txt_az_tarikh.AllowNew = true;
			this.txt_az_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_az_tarikh.FocusColor = true;
			this.txt_az_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_141B_0 = this.txt_az_tarikh;
			location = new global::System.Drawing.Point(1250, 57);
			arg_141B_0.Location = location;
			this.txt_az_tarikh.Name = "txt_az_tarikh";
			this.txt_az_tarikh.Nullable = true;
			this.txt_az_tarikh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_az_tarikh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1474_0 = this.txt_az_tarikh;
			size = new global::System.Drawing.Size(137, 36);
			arg_1474_0.Size = size;
			this.txt_az_tarikh.TabIndex = 25;
			this.txt_az_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.CurrencyBox2.AcceptEnter = true;
			this.CurrencyBox2.AllowEdit = false;
			this.CurrencyBox2.AllowNew = true;
			this.CurrencyBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.CurrencyBox2.FocusColor = true;
			this.CurrencyBox2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1510_0 = this.CurrencyBox2;
			location = new global::System.Drawing.Point(780, 98);
			arg_1510_0.Location = location;
			this.CurrencyBox2.Name = "CurrencyBox2";
			this.CurrencyBox2.Nullable = true;
			this.CurrencyBox2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.CurrencyBox2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1569_0 = this.CurrencyBox2;
			size = new global::System.Drawing.Size(137, 36);
			arg_1569_0.Size = size;
			this.CurrencyBox2.TabIndex = 23;
			this.CurrencyBox2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.CurrencyBox2.Value = value;
			this.CurrencyBox2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sud.AcceptEnter = true;
			this.txt_sud.AllowEdit = false;
			this.txt_sud.AllowNew = true;
			this.txt_sud.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sud.FocusColor = true;
			this.txt_sud.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_sud.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control arg_1634_0 = this.txt_sud;
			location = new global::System.Drawing.Point(780, 140);
			arg_1634_0.Location = location;
			this.txt_sud.Name = "txt_sud";
			this.txt_sud.Nullable = true;
			this.txt_sud.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sud.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_168D_0 = this.txt_sud;
			size = new global::System.Drawing.Size(137, 36);
			arg_168D_0.Size = size;
			this.txt_sud.TabIndex = 23;
			this.txt_sud.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_sud.Value = value;
			this.txt_sud.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_hazine.AcceptEnter = true;
			this.txt_hazine.AllowEdit = false;
			this.txt_hazine.AllowNew = true;
			this.txt_hazine.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_hazine.FocusColor = true;
			this.txt_hazine.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1747_0 = this.txt_hazine;
			location = new global::System.Drawing.Point(1250, 140);
			arg_1747_0.Location = location;
			this.txt_hazine.Name = "txt_hazine";
			this.txt_hazine.Nullable = true;
			this.txt_hazine.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_hazine.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_17A0_0 = this.txt_hazine;
			size = new global::System.Drawing.Size(137, 36);
			arg_17A0_0.Size = size;
			this.txt_hazine.TabIndex = 23;
			this.txt_hazine.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_hazine.Value = value;
			this.txt_hazine.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.CurrencyBox1.AcceptEnter = true;
			this.CurrencyBox1.AllowEdit = true;
			this.CurrencyBox1.AllowNew = true;
			this.CurrencyBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.CurrencyBox1.FocusColor = true;
			this.CurrencyBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1857_0 = this.CurrencyBox1;
			location = new global::System.Drawing.Point(993, 98);
			arg_1857_0.Location = location;
			this.CurrencyBox1.Name = "CurrencyBox1";
			this.CurrencyBox1.Nullable = true;
			this.CurrencyBox1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.CurrencyBox1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_18B0_0 = this.CurrencyBox1;
			size = new global::System.Drawing.Size(137, 36);
			arg_18B0_0.Size = size;
			this.CurrencyBox1.TabIndex = 23;
			this.CurrencyBox1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.CurrencyBox1.Value = value;
			this.CurrencyBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kharid.AcceptEnter = true;
			this.txt_kharid.AllowEdit = false;
			this.txt_kharid.AllowNew = true;
			this.txt_kharid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kharid.FocusColor = true;
			this.txt_kharid.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1967_0 = this.txt_kharid;
			location = new global::System.Drawing.Point(1250, 98);
			arg_1967_0.Location = location;
			this.txt_kharid.Name = "txt_kharid";
			this.txt_kharid.Nullable = true;
			this.txt_kharid.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kharid.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_19C0_0 = this.txt_kharid;
			size = new global::System.Drawing.Size(137, 36);
			arg_19C0_0.Size = size;
			this.txt_kharid.TabIndex = 23;
			this.txt_kharid.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_kharid.Value = value;
			this.txt_kharid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_furush.AcceptEnter = true;
			this.txt_furush.AllowEdit = false;
			this.txt_furush.AllowNew = true;
			this.txt_furush.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_furush.FocusColor = true;
			this.txt_furush.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A7A_0 = this.txt_furush;
			location = new global::System.Drawing.Point(993, 140);
			arg_1A7A_0.Location = location;
			this.txt_furush.Name = "txt_furush";
			this.txt_furush.Nullable = true;
			this.txt_furush.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_furush.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1AD3_0 = this.txt_furush;
			size = new global::System.Drawing.Size(137, 36);
			arg_1AD3_0.Size = size;
			this.txt_furush.TabIndex = 23;
			this.txt_furush.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_furush.Value = value;
			this.txt_furush.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1B6A_0 = this.txt_num;
			location = new global::System.Drawing.Point(818, 466);
			arg_1B6A_0.Location = location;
			global::System.Windows.Forms.Control arg_1B84_0 = this.txt_num;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			arg_1B84_0.Margin = margin;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_1BB2_0 = this.txt_num;
			size = new global::System.Drawing.Size(208, 36);
			arg_1BB2_0.Size = size;
			this.txt_num.TabIndex = 21;
			this.txt_num.Value = "";
			this.txt_num.Visible = false;
			this.GridEX1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			gridEXLayout2.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout2;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1C8F_0 = this.GridEX1;
			location = new global::System.Drawing.Point(0, 182);
			arg_1C8F_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_1CE7_0 = this.GridEX1;
			size = new global::System.Drawing.Size(473, 326);
			arg_1CE7_0.Size = size;
			this.GridEX1.TabIndex = 19;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 16f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1476, 508);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_SudKhorde";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "محاسبه سود";
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataEntryGrid1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000F8D RID: 3981
		private global::System.ComponentModel.IContainer components;
	}
}
