namespace FruitBox
{
	// Token: 0x0200006A RID: 106
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Extra_Setting : global::System.Windows.Forms.Form
	{
		// Token: 0x060007BB RID: 1979 RVA: 0x00070ED4 File Offset: 0x0006F0D4
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060007BC RID: 1980 RVA: 0x00070F24 File Offset: 0x0006F124
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem2 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem3 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem4 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem5 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem6 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem7 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			global::Janus.Windows.EditControls.UIComboBoxItem uIComboBoxItem8 = new global::Janus.Windows.EditControls.UIComboBoxItem();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_kharid_keraye_tozih = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_kharid_keraye_moshtari = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiGroupBox10 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_three_zero = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txt_moshtari_exit_on_save = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_moshtari_pic = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_moshtari_mahal = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_moshtari_show_contact = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiGroupBox9 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_nahve_kharid = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.txt_sahebcheck = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_shobe = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_bank = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_shomarehesab = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiGroupBox6 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_altbackupPath = new global::Janus.Windows.GridEX.EditControls.EditBox();
			this.txt_altbackup = new global::Janus.Windows.EditControls.UICheckBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.UiGroupBox5 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox8 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox7 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox4 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txt_desktop_note = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox7 = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_elan_check = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox1 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox6 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox5 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox4 = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox3 = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_sh_factor = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_sardkhane_keraye_tozih = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_sardkhane_keraye_moshtari = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_sardkhane_vaznkol = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_fullscreen = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_backupCategory = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_oneBackup = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiGroupBox3 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_newrow_kala = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_auto_vusul_d = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_Auto_Vusul = new global::Janus.Windows.EditControls.UICheckBox();
			this.txt_kiosk_auto_kasr = new global::Janus.Windows.EditControls.UICheckBox();
			this.UiCheckBox2 = new global::Janus.Windows.EditControls.UICheckBox();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.BackgroundWorker1 = new global::System.ComponentModel.BackgroundWorker();
			this.FolderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.txt_surat_bank = new global::Janus.Windows.EditControls.UIComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox10).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox9).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_3EB_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_3EB_0.Location = location;
			global::System.Windows.Forms.Control arg_405_0 = this.UiGroupBox1;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			arg_405_0.Margin = margin;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_436_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1126, 757);
			arg_436_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.AutoScroll = true;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.txt_surat_bank);
			this.UiGroupBox2.Controls.Add(this.Label2);
			this.UiGroupBox2.Controls.Add(this.txt_kharid_keraye_tozih);
			this.UiGroupBox2.Controls.Add(this.txt_kharid_keraye_moshtari);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox10);
			this.UiGroupBox2.Controls.Add(this.txt_three_zero);
			this.UiGroupBox2.Controls.Add(this.Label1);
			this.UiGroupBox2.Controls.Add(this.txt_moshtari_exit_on_save);
			this.UiGroupBox2.Controls.Add(this.txt_moshtari_pic);
			this.UiGroupBox2.Controls.Add(this.txt_moshtari_mahal);
			this.UiGroupBox2.Controls.Add(this.txt_moshtari_show_contact);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox9);
			this.UiGroupBox2.Controls.Add(this.txt_nahve_kharid);
			this.UiGroupBox2.Controls.Add(this.Label12);
			this.UiGroupBox2.Controls.Add(this.txt_sahebcheck);
			this.UiGroupBox2.Controls.Add(this.txt_shobe);
			this.UiGroupBox2.Controls.Add(this.txt_bank);
			this.UiGroupBox2.Controls.Add(this.txt_shomarehesab);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox6);
			this.UiGroupBox2.Controls.Add(this.txt_altbackupPath);
			this.UiGroupBox2.Controls.Add(this.txt_altbackup);
			this.UiGroupBox2.Controls.Add(this.Label6);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox5);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox8);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox7);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox4);
			this.UiGroupBox2.Controls.Add(this.PictureBox1);
			this.UiGroupBox2.Controls.Add(this.Label3);
			this.UiGroupBox2.Controls.Add(this.txt_desktop_note);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox7);
			this.UiGroupBox2.Controls.Add(this.txt_elan_check);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox1);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox6);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox5);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox4);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox3);
			this.UiGroupBox2.Controls.Add(this.txt_sh_factor);
			this.UiGroupBox2.Controls.Add(this.txt_sardkhane_keraye_tozih);
			this.UiGroupBox2.Controls.Add(this.txt_sardkhane_keraye_moshtari);
			this.UiGroupBox2.Controls.Add(this.txt_sardkhane_vaznkol);
			this.UiGroupBox2.Controls.Add(this.txt_fullscreen);
			this.UiGroupBox2.Controls.Add(this.txt_backupCategory);
			this.UiGroupBox2.Controls.Add(this.txt_oneBackup);
			this.UiGroupBox2.Controls.Add(this.UiGroupBox3);
			this.UiGroupBox2.Controls.Add(this.txt_newrow_kala);
			this.UiGroupBox2.Controls.Add(this.txt_auto_vusul_d);
			this.UiGroupBox2.Controls.Add(this.txt_Auto_Vusul);
			this.UiGroupBox2.Controls.Add(this.txt_kiosk_auto_kasr);
			this.UiGroupBox2.Controls.Add(this.UiCheckBox2);
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control arg_8F7_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 41);
			arg_8F7_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			this.UiGroupBox2.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_935_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1126, 716);
			arg_935_0.Size = size;
			this.UiGroupBox2.TabIndex = 31;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_kharid_keraye_tozih.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kharid_keraye_tozih.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_989_0 = this.txt_kharid_keraye_tozih;
			location = new global::System.Drawing.Point(53, 77);
			arg_989_0.Location = location;
			this.txt_kharid_keraye_tozih.Name = "txt_kharid_keraye_tozih";
			this.txt_kharid_keraye_tozih.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_9C4_0 = this.txt_kharid_keraye_tozih;
			size = new global::System.Drawing.Size(365, 23);
			arg_9C4_0.Size = size;
			this.txt_kharid_keraye_tozih.TabIndex = 59;
			this.txt_kharid_keraye_tozih.Text = "نمایش توضیحات در کرایه و مخارج";
			this.txt_kharid_keraye_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kharid_keraye_moshtari.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_A1C_0 = this.txt_kharid_keraye_moshtari;
			location = new global::System.Drawing.Point(53, 48);
			arg_A1C_0.Location = location;
			this.txt_kharid_keraye_moshtari.Name = "txt_kharid_keraye_moshtari";
			this.txt_kharid_keraye_moshtari.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_A57_0 = this.txt_kharid_keraye_moshtari;
			size = new global::System.Drawing.Size(365, 23);
			arg_A57_0.Size = size;
			this.txt_kharid_keraye_moshtari.TabIndex = 60;
			this.txt_kharid_keraye_moshtari.Text = "نمایش مشتری در کرایه و مخارج";
			this.UiGroupBox10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox10.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox10.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_AB8_0 = this.UiGroupBox10;
			location = new global::System.Drawing.Point(53, 21);
			arg_AB8_0.Location = location;
			this.UiGroupBox10.Name = "UiGroupBox10";
			global::System.Windows.Forms.Control arg_AE6_0 = this.UiGroupBox10;
			size = new global::System.Drawing.Size(386, 21);
			arg_AE6_0.Size = size;
			this.UiGroupBox10.TabIndex = 58;
			this.UiGroupBox10.Text = "خرید";
			this.UiGroupBox10.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_three_zero.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_three_zero.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_three_zero.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem.FormatStyle.Alpha = 0;
			uIComboBoxItem.IsSeparator = false;
			uIComboBoxItem.Text = "000";
			uIComboBoxItem.Value = true;
			uIComboBoxItem2.FormatStyle.Alpha = 0;
			uIComboBoxItem2.IsSeparator = false;
			uIComboBoxItem2.Text = "00";
			uIComboBoxItem2.Value = false;
			this.txt_three_zero.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem,
				uIComboBoxItem2
			});
			global::System.Windows.Forms.Control arg_BF2_0 = this.txt_three_zero;
			location = new global::System.Drawing.Point(667, 378);
			arg_BF2_0.Location = location;
			this.txt_three_zero.Name = "txt_three_zero";
			global::System.Windows.Forms.Control arg_C20_0 = this.txt_three_zero;
			size = new global::System.Drawing.Size(288, 36);
			arg_C20_0.Size = size;
			this.txt_three_zero.TabIndex = 57;
			this.txt_three_zero.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_C87_0 = this.Label1;
			location = new global::System.Drawing.Point(970, 386);
			arg_C87_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_CB5_0 = this.Label1;
			size = new global::System.Drawing.Size(148, 19);
			arg_CB5_0.Size = size;
			this.Label1.TabIndex = 56;
			this.Label1.Text = "نحوه عملکرد دکمه +";
			this.txt_moshtari_exit_on_save.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari_exit_on_save.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_D10_0 = this.txt_moshtari_exit_on_save;
			location = new global::System.Drawing.Point(23, 609);
			arg_D10_0.Location = location;
			this.txt_moshtari_exit_on_save.Name = "txt_moshtari_exit_on_save";
			this.txt_moshtari_exit_on_save.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_D4B_0 = this.txt_moshtari_exit_on_save;
			size = new global::System.Drawing.Size(395, 23);
			arg_D4B_0.Size = size;
			this.txt_moshtari_exit_on_save.TabIndex = 54;
			this.txt_moshtari_exit_on_save.Text = "خروج از صفحه بعد از ثبت اطلاعات";
			this.txt_moshtari_pic.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari_pic.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_DA6_0 = this.txt_moshtari_pic;
			location = new global::System.Drawing.Point(23, 580);
			arg_DA6_0.Location = location;
			this.txt_moshtari_pic.Name = "txt_moshtari_pic";
			this.txt_moshtari_pic.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_DE1_0 = this.txt_moshtari_pic;
			size = new global::System.Drawing.Size(395, 23);
			arg_DE1_0.Size = size;
			this.txt_moshtari_pic.TabIndex = 54;
			this.txt_moshtari_pic.Text = "نمایش تصویر";
			this.txt_moshtari_mahal.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari_mahal.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_E3C_0 = this.txt_moshtari_mahal;
			location = new global::System.Drawing.Point(23, 551);
			arg_E3C_0.Location = location;
			this.txt_moshtari_mahal.Name = "txt_moshtari_mahal";
			this.txt_moshtari_mahal.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_E77_0 = this.txt_moshtari_mahal;
			size = new global::System.Drawing.Size(395, 23);
			arg_E77_0.Size = size;
			this.txt_moshtari_mahal.TabIndex = 55;
			this.txt_moshtari_mahal.Text = "نمایش محل فعالیت";
			this.txt_moshtari_show_contact.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari_show_contact.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_ED2_0 = this.txt_moshtari_show_contact;
			location = new global::System.Drawing.Point(23, 522);
			arg_ED2_0.Location = location;
			this.txt_moshtari_show_contact.Name = "txt_moshtari_show_contact";
			this.txt_moshtari_show_contact.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_F0D_0 = this.txt_moshtari_show_contact;
			size = new global::System.Drawing.Size(395, 23);
			arg_F0D_0.Size = size;
			this.txt_moshtari_show_contact.TabIndex = 52;
			this.txt_moshtari_show_contact.Text = "نمایش اطلاعات تماس";
			this.UiGroupBox9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox9.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox9.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_F71_0 = this.UiGroupBox9;
			location = new global::System.Drawing.Point(53, 495);
			arg_F71_0.Location = location;
			this.UiGroupBox9.Name = "UiGroupBox9";
			global::System.Windows.Forms.Control arg_F9F_0 = this.UiGroupBox9;
			size = new global::System.Drawing.Size(386, 21);
			arg_F9F_0.Size = size;
			this.UiGroupBox9.TabIndex = 51;
			this.UiGroupBox9.Text = "تعریف مشتری";
			this.UiGroupBox9.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_nahve_kharid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_nahve_kharid.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_nahve_kharid.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem3.FormatStyle.Alpha = 0;
			uIComboBoxItem3.IsSeparator = false;
			uIComboBoxItem3.Text = "تعداد - وزن خالص";
			uIComboBoxItem3.Value = "1";
			uIComboBoxItem4.FormatStyle.Alpha = 0;
			uIComboBoxItem4.IsSeparator = false;
			uIComboBoxItem4.Text = "وزن خالص";
			uIComboBoxItem4.Value = "2";
			uIComboBoxItem5.FormatStyle.Alpha = 0;
			uIComboBoxItem5.IsSeparator = false;
			uIComboBoxItem5.Text = "تعداد";
			uIComboBoxItem5.Value = "3";
			uIComboBoxItem6.FormatStyle.Alpha = 0;
			uIComboBoxItem6.IsSeparator = false;
			uIComboBoxItem6.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			uIComboBoxItem6.Value = "4";
			this.txt_nahve_kharid.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem3,
				uIComboBoxItem4,
				uIComboBoxItem5,
				uIComboBoxItem6
			});
			global::System.Windows.Forms.Control arg_1120_0 = this.txt_nahve_kharid;
			location = new global::System.Drawing.Point(53, 447);
			arg_1120_0.Location = location;
			this.txt_nahve_kharid.Name = "txt_nahve_kharid";
			global::System.Windows.Forms.Control arg_114E_0 = this.txt_nahve_kharid;
			size = new global::System.Drawing.Size(288, 36);
			arg_114E_0.Size = size;
			this.txt_nahve_kharid.TabIndex = 50;
			this.txt_nahve_kharid.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_11B5_0 = this.Label12;
			location = new global::System.Drawing.Point(343, 459);
			arg_11B5_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_11E0_0 = this.Label12;
			size = new global::System.Drawing.Size(75, 19);
			arg_11E0_0.Size = size;
			this.Label12.TabIndex = 49;
			this.Label12.Text = "نحوه خرید";
			this.txt_sahebcheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sahebcheck.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_123B_0 = this.txt_sahebcheck;
			location = new global::System.Drawing.Point(23, 224);
			arg_123B_0.Location = location;
			this.txt_sahebcheck.Name = "txt_sahebcheck";
			this.txt_sahebcheck.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1276_0 = this.txt_sahebcheck;
			size = new global::System.Drawing.Size(395, 23);
			arg_1276_0.Size = size;
			this.txt_sahebcheck.TabIndex = 48;
			this.txt_sahebcheck.Text = "دریافت صاحب چک";
			this.txt_shobe.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shobe.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_12D1_0 = this.txt_shobe;
			location = new global::System.Drawing.Point(23, 195);
			arg_12D1_0.Location = location;
			this.txt_shobe.Name = "txt_shobe";
			this.txt_shobe.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_130C_0 = this.txt_shobe;
			size = new global::System.Drawing.Size(395, 23);
			arg_130C_0.Size = size;
			this.txt_shobe.TabIndex = 48;
			this.txt_shobe.Text = "دریافت شعبه";
			this.txt_bank.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_bank.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1367_0 = this.txt_bank;
			location = new global::System.Drawing.Point(23, 166);
			arg_1367_0.Location = location;
			this.txt_bank.Name = "txt_bank";
			this.txt_bank.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_13A2_0 = this.txt_bank;
			size = new global::System.Drawing.Size(395, 23);
			arg_13A2_0.Size = size;
			this.txt_bank.TabIndex = 48;
			this.txt_bank.Text = "دریافت بانک";
			this.txt_shomarehesab.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_shomarehesab.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_13FD_0 = this.txt_shomarehesab;
			location = new global::System.Drawing.Point(23, 137);
			arg_13FD_0.Location = location;
			this.txt_shomarehesab.Name = "txt_shomarehesab";
			this.txt_shomarehesab.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1438_0 = this.txt_shomarehesab;
			size = new global::System.Drawing.Size(395, 23);
			arg_1438_0.Size = size;
			this.txt_shomarehesab.TabIndex = 47;
			this.txt_shomarehesab.Text = "دریافت شماره حساب";
			this.UiGroupBox6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox6.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox6.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_1499_0 = this.UiGroupBox6;
			location = new global::System.Drawing.Point(53, 110);
			arg_1499_0.Location = location;
			this.UiGroupBox6.Name = "UiGroupBox6";
			global::System.Windows.Forms.Control arg_14C7_0 = this.UiGroupBox6;
			size = new global::System.Drawing.Size(386, 21);
			arg_14C7_0.Size = size;
			this.UiGroupBox6.TabIndex = 46;
			this.UiGroupBox6.Text = "گزینه های دریافت چک";
			this.UiGroupBox6.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_altbackupPath.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_altbackupPath.ButtonFont = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_altbackupPath.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_altbackupPath.ButtonText = "...";
			this.txt_altbackupPath.Font = new global::System.Drawing.Font("Courier New", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1580_0 = this.txt_altbackupPath;
			location = new global::System.Drawing.Point(513, 77);
			arg_1580_0.Location = location;
			this.txt_altbackupPath.Name = "txt_altbackupPath";
			global::System.Windows.Forms.Control arg_15AE_0 = this.txt_altbackupPath;
			size = new global::System.Drawing.Size(455, 26);
			arg_15AE_0.Size = size;
			this.txt_altbackupPath.TabIndex = 45;
			this.txt_altbackupPath.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_altbackupPath.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_altbackup.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_altbackup.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1612_0 = this.txt_altbackup;
			location = new global::System.Drawing.Point(818, 47);
			arg_1612_0.Location = location;
			this.txt_altbackup.Name = "txt_altbackup";
			this.txt_altbackup.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_164D_0 = this.txt_altbackup;
			size = new global::System.Drawing.Size(296, 23);
			arg_164D_0.Size = size;
			this.txt_altbackup.TabIndex = 44;
			this.txt_altbackup.Text = "تهیه پشتیبان ثانوی هنگام خروج از برنامه";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_16B5_0 = this.Label6;
			location = new global::System.Drawing.Point(969, 81);
			arg_16B5_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_16E3_0 = this.Label6;
			size = new global::System.Drawing.Size(140, 19);
			arg_16E3_0.Size = size;
			this.Label6.TabIndex = 43;
			this.Label6.Text = "مسیر تهیه پشتیبان";
			this.UiGroupBox5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox5.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox5.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_174A_0 = this.UiGroupBox5;
			location = new global::System.Drawing.Point(802, 457);
			arg_174A_0.Location = location;
			this.UiGroupBox5.Name = "UiGroupBox5";
			global::System.Windows.Forms.Control arg_1778_0 = this.UiGroupBox5;
			size = new global::System.Drawing.Size(323, 21);
			arg_1778_0.Size = size;
			this.UiGroupBox5.TabIndex = 42;
			this.UiGroupBox5.Text = "متفرقه";
			this.UiGroupBox5.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox8.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox8.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_17E9_0 = this.UiGroupBox8;
			location = new global::System.Drawing.Point(53, 420);
			arg_17E9_0.Location = location;
			this.UiGroupBox8.Name = "UiGroupBox8";
			global::System.Windows.Forms.Control arg_1817_0 = this.UiGroupBox8;
			size = new global::System.Drawing.Size(386, 21);
			arg_1817_0.Size = size;
			this.UiGroupBox8.TabIndex = 41;
			this.UiGroupBox8.Text = "واردات";
			this.UiGroupBox8.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox7.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox7.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_1888_0 = this.UiGroupBox7;
			location = new global::System.Drawing.Point(53, 266);
			arg_1888_0.Location = location;
			this.UiGroupBox7.Name = "UiGroupBox7";
			global::System.Windows.Forms.Control arg_18B6_0 = this.UiGroupBox7;
			size = new global::System.Drawing.Size(386, 21);
			arg_18B6_0.Size = size;
			this.UiGroupBox7.TabIndex = 41;
			this.UiGroupBox7.Text = "خرید به سردخانه";
			this.UiGroupBox7.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox4.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox4.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_192A_0 = this.UiGroupBox4;
			location = new global::System.Drawing.Point(801, 177);
			arg_192A_0.Location = location;
			this.UiGroupBox4.Name = "UiGroupBox4";
			global::System.Windows.Forms.Control arg_1958_0 = this.UiGroupBox4;
			size = new global::System.Drawing.Size(323, 21);
			arg_1958_0.Size = size;
			this.UiGroupBox4.TabIndex = 41;
			this.UiGroupBox4.Text = "محیط کاربری";
			this.UiGroupBox4.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.Image = global::FruitBox.My.Resources.Resources.warning;
			global::System.Windows.Forms.Control arg_19D4_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(830, 290);
			arg_19D4_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_19FF_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(24, 22);
			arg_19FF_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 40;
			this.PictureBox1.TabStop = false;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1A73_0 = this.Label3;
			location = new global::System.Drawing.Point(667, 293);
			arg_1A73_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1AA1_0 = this.Label3;
			size = new global::System.Drawing.Size(157, 19);
			arg_1AA1_0.Size = size;
			this.Label3.TabIndex = 39;
			this.Label3.Text = "نیاز به راه اندازی مجدد";
			this.txt_desktop_note.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_desktop_note.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1AFF_0 = this.txt_desktop_note;
			location = new global::System.Drawing.Point(739, 349);
			arg_1AFF_0.Location = location;
			this.txt_desktop_note.Name = "txt_desktop_note";
			this.txt_desktop_note.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1B3A_0 = this.txt_desktop_note;
			size = new global::System.Drawing.Size(375, 23);
			arg_1B3A_0.Size = size;
			this.txt_desktop_note.TabIndex = 34;
			this.txt_desktop_note.Text = "نمایش اطلاعات یادداشت بر روی دسکتاپ";
			this.UiCheckBox7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox7.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1B98_0 = this.UiCheckBox7;
			location = new global::System.Drawing.Point(895, 349);
			arg_1B98_0.Location = location;
			this.UiCheckBox7.Name = "UiCheckBox7";
			this.UiCheckBox7.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1BD3_0 = this.UiCheckBox7;
			size = new global::System.Drawing.Size(219, 23);
			arg_1BD3_0.Size = size;
			this.UiCheckBox7.TabIndex = 35;
			this.UiCheckBox7.Text = "نمایش Toolbar";
			this.UiCheckBox7.Visible = false;
			this.txt_elan_check.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_elan_check.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1C3E_0 = this.txt_elan_check;
			location = new global::System.Drawing.Point(739, 320);
			arg_1C3E_0.Location = location;
			this.txt_elan_check.Name = "txt_elan_check";
			this.txt_elan_check.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1C79_0 = this.txt_elan_check;
			size = new global::System.Drawing.Size(375, 23);
			arg_1C79_0.Size = size;
			this.txt_elan_check.TabIndex = 34;
			this.txt_elan_check.Text = "نمایش اعلان سررسید چک های دریافتی و پرداختی";
			this.UiCheckBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox1.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1CD7_0 = this.UiCheckBox1;
			location = new global::System.Drawing.Point(895, 320);
			arg_1CD7_0.Location = location;
			this.UiCheckBox1.Name = "UiCheckBox1";
			this.UiCheckBox1.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1D12_0 = this.UiCheckBox1;
			size = new global::System.Drawing.Size(219, 23);
			arg_1D12_0.Size = size;
			this.UiCheckBox1.TabIndex = 35;
			this.UiCheckBox1.Text = "نمایش Toolbar";
			this.UiCheckBox1.Visible = false;
			this.UiCheckBox6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox6.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1D7D_0 = this.UiCheckBox6;
			location = new global::System.Drawing.Point(855, 291);
			arg_1D7D_0.Location = location;
			this.UiCheckBox6.Name = "UiCheckBox6";
			this.UiCheckBox6.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1DB8_0 = this.UiCheckBox6;
			size = new global::System.Drawing.Size(259, 23);
			arg_1DB8_0.Size = size;
			this.UiCheckBox6.TabIndex = 34;
			this.UiCheckBox6.Text = "نمایش پنجره ها بصورت تمام صفحه";
			this.UiCheckBox5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox5.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1E16_0 = this.UiCheckBox5;
			location = new global::System.Drawing.Point(895, 291);
			arg_1E16_0.Location = location;
			this.UiCheckBox5.Name = "UiCheckBox5";
			this.UiCheckBox5.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1E51_0 = this.UiCheckBox5;
			size = new global::System.Drawing.Size(219, 23);
			arg_1E51_0.Size = size;
			this.UiCheckBox5.TabIndex = 35;
			this.UiCheckBox5.Text = "نمایش Toolbar";
			this.UiCheckBox5.Visible = false;
			this.UiCheckBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox4.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1EBC_0 = this.UiCheckBox4;
			location = new global::System.Drawing.Point(895, 262);
			arg_1EBC_0.Location = location;
			this.UiCheckBox4.Name = "UiCheckBox4";
			this.UiCheckBox4.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1EF7_0 = this.UiCheckBox4;
			size = new global::System.Drawing.Size(219, 23);
			arg_1EF7_0.Size = size;
			this.UiCheckBox4.TabIndex = 36;
			this.UiCheckBox4.Text = "نمایش یادداشت";
			this.UiCheckBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox3.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1F55_0 = this.UiCheckBox3;
			location = new global::System.Drawing.Point(895, 233);
			arg_1F55_0.Location = location;
			this.UiCheckBox3.Name = "UiCheckBox3";
			this.UiCheckBox3.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_1F90_0 = this.UiCheckBox3;
			size = new global::System.Drawing.Size(219, 23);
			arg_1F90_0.Size = size;
			this.UiCheckBox3.TabIndex = 37;
			this.UiCheckBox3.Text = "نمایش نوار وضعیت";
			this.txt_sh_factor.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_factor.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1FEB_0 = this.txt_sh_factor;
			location = new global::System.Drawing.Point(53, 382);
			arg_1FEB_0.Location = location;
			this.txt_sh_factor.Name = "txt_sh_factor";
			this.txt_sh_factor.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2026_0 = this.txt_sh_factor;
			size = new global::System.Drawing.Size(365, 23);
			arg_2026_0.Size = size;
			this.txt_sh_factor.TabIndex = 38;
			this.txt_sh_factor.Text = "نمایش شماره فاکتور در خرید";
			this.txt_sardkhane_keraye_tozih.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sardkhane_keraye_tozih.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2081_0 = this.txt_sardkhane_keraye_tozih;
			location = new global::System.Drawing.Point(53, 351);
			arg_2081_0.Location = location;
			this.txt_sardkhane_keraye_tozih.Name = "txt_sardkhane_keraye_tozih";
			this.txt_sardkhane_keraye_tozih.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_20BC_0 = this.txt_sardkhane_keraye_tozih;
			size = new global::System.Drawing.Size(365, 23);
			arg_20BC_0.Size = size;
			this.txt_sardkhane_keraye_tozih.TabIndex = 38;
			this.txt_sardkhane_keraye_tozih.Text = "نمایش توضیحات در کرایه و مخارج";
			this.txt_sardkhane_keraye_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sardkhane_keraye_moshtari.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2117_0 = this.txt_sardkhane_keraye_moshtari;
			location = new global::System.Drawing.Point(53, 322);
			arg_2117_0.Location = location;
			this.txt_sardkhane_keraye_moshtari.Name = "txt_sardkhane_keraye_moshtari";
			this.txt_sardkhane_keraye_moshtari.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2152_0 = this.txt_sardkhane_keraye_moshtari;
			size = new global::System.Drawing.Size(365, 23);
			arg_2152_0.Size = size;
			this.txt_sardkhane_keraye_moshtari.TabIndex = 38;
			this.txt_sardkhane_keraye_moshtari.Text = "نمایش مشتری در کرایه و مخارج";
			this.txt_sardkhane_vaznkol.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sardkhane_vaznkol.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_21AD_0 = this.txt_sardkhane_vaznkol;
			location = new global::System.Drawing.Point(53, 293);
			arg_21AD_0.Location = location;
			this.txt_sardkhane_vaznkol.Name = "txt_sardkhane_vaznkol";
			this.txt_sardkhane_vaznkol.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_21E8_0 = this.txt_sardkhane_vaznkol;
			size = new global::System.Drawing.Size(365, 23);
			arg_21E8_0.Size = size;
			this.txt_sardkhane_vaznkol.TabIndex = 38;
			this.txt_sardkhane_vaznkol.Text = "نمایش مانده وزن بر اساس وزن خالص";
			this.txt_fullscreen.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_fullscreen.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2246_0 = this.txt_fullscreen;
			location = new global::System.Drawing.Point(895, 204);
			arg_2246_0.Location = location;
			this.txt_fullscreen.Name = "txt_fullscreen";
			this.txt_fullscreen.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2281_0 = this.txt_fullscreen;
			size = new global::System.Drawing.Size(219, 23);
			arg_2281_0.Size = size;
			this.txt_fullscreen.TabIndex = 38;
			this.txt_fullscreen.Text = "نمایش تمام صفحه";
			this.txt_backupCategory.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_backupCategory.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_22DF_0 = this.txt_backupCategory;
			location = new global::System.Drawing.Point(818, 142);
			arg_22DF_0.Location = location;
			this.txt_backupCategory.Name = "txt_backupCategory";
			this.txt_backupCategory.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_231A_0 = this.txt_backupCategory;
			size = new global::System.Drawing.Size(296, 23);
			arg_231A_0.Size = size;
			this.txt_backupCategory.TabIndex = 33;
			this.txt_backupCategory.Text = "دسته بندی بکاپ ها بر اساس سال و ماه";
			this.txt_oneBackup.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_oneBackup.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2375_0 = this.txt_oneBackup;
			location = new global::System.Drawing.Point(855, 114);
			arg_2375_0.Location = location;
			this.txt_oneBackup.Name = "txt_oneBackup";
			this.txt_oneBackup.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_23B0_0 = this.txt_oneBackup;
			size = new global::System.Drawing.Size(259, 23);
			arg_23B0_0.Size = size;
			this.txt_oneBackup.TabIndex = 32;
			this.txt_oneBackup.Text = "نگه داری یک پشتیبان برای هر روز";
			this.UiGroupBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox3.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox3.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_2414_0 = this.UiGroupBox3;
			location = new global::System.Drawing.Point(797, 21);
			arg_2414_0.Location = location;
			this.UiGroupBox3.Name = "UiGroupBox3";
			global::System.Windows.Forms.Control arg_2442_0 = this.UiGroupBox3;
			size = new global::System.Drawing.Size(323, 21);
			arg_2442_0.Size = size;
			this.UiGroupBox3.TabIndex = 31;
			this.UiGroupBox3.Text = "تهیه پشتیبان";
			this.UiGroupBox3.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_newrow_kala.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_newrow_kala.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_24AD_0 = this.txt_newrow_kala;
			location = new global::System.Drawing.Point(721, 484);
			arg_24AD_0.Location = location;
			this.txt_newrow_kala.Name = "txt_newrow_kala";
			this.txt_newrow_kala.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_24E8_0 = this.txt_newrow_kala;
			size = new global::System.Drawing.Size(395, 23);
			arg_24E8_0.Size = size;
			this.txt_newrow_kala.TabIndex = 30;
			this.txt_newrow_kala.Text = "نمایش خودکار جنس ردیف بالایی در ردیف های جدید";
			this.txt_auto_vusul_d.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_auto_vusul_d.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2546_0 = this.txt_auto_vusul_d;
			location = new global::System.Drawing.Point(721, 571);
			arg_2546_0.Location = location;
			this.txt_auto_vusul_d.Name = "txt_auto_vusul_d";
			this.txt_auto_vusul_d.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_2581_0 = this.txt_auto_vusul_d;
			size = new global::System.Drawing.Size(395, 23);
			arg_2581_0.Size = size;
			this.txt_auto_vusul_d.TabIndex = 30;
			this.txt_auto_vusul_d.Text = "اعلام وصول چک مشتری بصورت اتوماتیک";
			this.txt_Auto_Vusul.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_Auto_Vusul.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_25DF_0 = this.txt_Auto_Vusul;
			location = new global::System.Drawing.Point(721, 542);
			arg_25DF_0.Location = location;
			this.txt_Auto_Vusul.Name = "txt_Auto_Vusul";
			this.txt_Auto_Vusul.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_261A_0 = this.txt_Auto_Vusul;
			size = new global::System.Drawing.Size(395, 23);
			arg_261A_0.Size = size;
			this.txt_Auto_Vusul.TabIndex = 30;
			this.txt_Auto_Vusul.Text = "اعلام وصول دسته چک بصورت اتوماتیک";
			this.txt_kiosk_auto_kasr.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kiosk_auto_kasr.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2678_0 = this.txt_kiosk_auto_kasr;
			location = new global::System.Drawing.Point(721, 513);
			arg_2678_0.Location = location;
			this.txt_kiosk_auto_kasr.Name = "txt_kiosk_auto_kasr";
			this.txt_kiosk_auto_kasr.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_26B3_0 = this.txt_kiosk_auto_kasr;
			size = new global::System.Drawing.Size(395, 23);
			arg_26B3_0.Size = size;
			this.txt_kiosk_auto_kasr.TabIndex = 30;
			this.txt_kiosk_auto_kasr.Text = "کسر اتوماتیک به صورت خودکار در کیوسک فروش";
			this.UiCheckBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiCheckBox2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2711_0 = this.UiCheckBox2;
			location = new global::System.Drawing.Point(721, 600);
			arg_2711_0.Location = location;
			this.UiCheckBox2.Name = "UiCheckBox2";
			this.UiCheckBox2.ShowFocusRectangle = false;
			global::System.Windows.Forms.Control arg_274C_0 = this.UiCheckBox2;
			size = new global::System.Drawing.Size(395, 23);
			arg_274C_0.Size = size;
			this.UiCheckBox2.TabIndex = 30;
			this.UiCheckBox2.Text = "عدم ثبت هزینه در پرداخت اقساط";
			this.UiCheckBox2.Visible = false;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.DockSide = global::DevComponents.DotNetBar.eDockSide.Document;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem2,
				this.ButtonItem1
			});
			global::DevComponents.DotNetBar.Bar arg_2806_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_2806_0.Location = location;
			global::System.Windows.Forms.Control arg_2820_0 = this.Bar1;
			margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			arg_2820_0.Margin = margin;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_284E_0 = this.Bar1;
			size = new global::System.Drawing.Size(1126, 41);
			arg_284E_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.Bar1.TabIndex = 17;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document_flat_edit;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "تنظیمات سربرگ";
			this.txt_surat_bank.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_surat_bank.ComboStyle = global::Janus.Windows.EditControls.ComboStyle.DropDownList;
			this.txt_surat_bank.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			uIComboBoxItem7.FormatStyle.Alpha = 0;
			uIComboBoxItem7.IsSeparator = false;
			uIComboBoxItem7.Text = "دریافت و پرداخت";
			uIComboBoxItem7.Value = "1";
			uIComboBoxItem8.FormatStyle.Alpha = 0;
			uIComboBoxItem8.IsSeparator = false;
			uIComboBoxItem8.Text = "بدهکار و بستانکار";
			uIComboBoxItem8.Value = "2";
			this.txt_surat_bank.Items.AddRange(new global::Janus.Windows.EditControls.UIComboBoxItem[]
			{
				uIComboBoxItem7,
				uIComboBoxItem8
			});
			global::System.Windows.Forms.Control arg_29F2_0 = this.txt_surat_bank;
			location = new global::System.Drawing.Point(667, 420);
			arg_29F2_0.Location = location;
			this.txt_surat_bank.Name = "txt_surat_bank";
			global::System.Windows.Forms.Control arg_2A20_0 = this.txt_surat_bank;
			size = new global::System.Drawing.Size(288, 36);
			arg_2A20_0.Size = size;
			this.txt_surat_bank.TabIndex = 62;
			this.txt_surat_bank.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_2A87_0 = this.Label2;
			location = new global::System.Drawing.Point(958, 429);
			arg_2A87_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_2AB5_0 = this.Label2;
			size = new global::System.Drawing.Size(166, 19);
			arg_2AB5_0.Size = size;
			this.Label2.TabIndex = 61;
			this.Label2.Text = "نمایش صورتحساب بانک";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(9f, 19f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1126, 757);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			margin = new global::System.Windows.Forms.Padding(4);
			this.Margin = margin;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Extra_Setting";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "تنظیمات پیشرفته";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox10).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox9).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040002F9 RID: 761
		private global::System.ComponentModel.IContainer components;
	}
}
