namespace FruitBox
{
	// Token: 0x02000138 RID: 312
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_rpt_Sandugh : global::System.Windows.Forms.Form
	{
		// Token: 0x06002D0F RID: 11535 RVA: 0x00217A08 File Offset: 0x00215C08
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06002D10 RID: 11536 RVA: 0x00217A58 File Offset: 0x00215C58
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_rpt_Sandugh));
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.UiGroupBox4 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox3 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.lbl_kasrezafe = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.lbl_ruzegabl = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.GridEx1 = new global::FruitBox.DataEntryGrid(this.components);
			this.EditBox1 = new global::FruitBox.EditBox(this.components);
			this.txt_kasrezafe = new global::FruitBox.EditBox(this.components);
			this.txt_entegalvajh = new global::FruitBox.EditBox(this.components);
			this.txt_mojod = new global::FruitBox.EditBox(this.components);
			this.txt_pardakhthazine = new global::FruitBox.EditBox(this.components);
			this.txt_mande = new global::FruitBox.EditBox(this.components);
			this.txt_jampardakhti = new global::FruitBox.EditBox(this.components);
			this.txt_jamdaryaft = new global::FruitBox.EditBox(this.components);
			this.txt_kartkhan = new global::FruitBox.EditBox(this.components);
			this.txt_checknaghd = new global::FruitBox.EditBox(this.components);
			this.txt_daramad = new global::FruitBox.EditBox(this.components);
			this.txt_pardakhtkeraye = new global::FruitBox.EditBox(this.components);
			this.txt_bank_be_sandugh = new global::FruitBox.EditBox(this.components);
			this.txt_naghdkardancheck = new global::FruitBox.EditBox(this.components);
			this.txt_pardakhtnaghd = new global::FruitBox.EditBox(this.components);
			this.txt_furushbar = new global::FruitBox.EditBox(this.components);
			this.txt_daryaftnaghd = new global::FruitBox.EditBox(this.components);
			this.txt_furushnaghd = new global::FruitBox.EditBox(this.components);
			this.txt_ruzegabl = new global::FruitBox.EditBox(this.components);
			this.txt_tarikh = new global::FruitBox.DateBox2(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEx1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.UiButton2);
			this.UiGroupBox1.Controls.Add(this.GridEx1);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.EditBox1);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox4);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox3);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.lbl_kasrezafe);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label15);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label18);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label20);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label17);
			this.UiGroupBox1.Controls.Add(this.Label19);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.lbl_ruzegabl);
			this.UiGroupBox1.Controls.Add(this.Label16);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.txt_kasrezafe);
			this.UiGroupBox1.Controls.Add(this.txt_entegalvajh);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.txt_mojod);
			this.UiGroupBox1.Controls.Add(this.txt_pardakhthazine);
			this.UiGroupBox1.Controls.Add(this.txt_mande);
			this.UiGroupBox1.Controls.Add(this.txt_jampardakhti);
			this.UiGroupBox1.Controls.Add(this.txt_jamdaryaft);
			this.UiGroupBox1.Controls.Add(this.txt_kartkhan);
			this.UiGroupBox1.Controls.Add(this.txt_checknaghd);
			this.UiGroupBox1.Controls.Add(this.txt_daramad);
			this.UiGroupBox1.Controls.Add(this.txt_pardakhtkeraye);
			this.UiGroupBox1.Controls.Add(this.txt_bank_be_sandugh);
			this.UiGroupBox1.Controls.Add(this.txt_naghdkardancheck);
			this.UiGroupBox1.Controls.Add(this.txt_pardakhtnaghd);
			this.UiGroupBox1.Controls.Add(this.txt_furushbar);
			this.UiGroupBox1.Controls.Add(this.txt_daryaftnaghd);
			this.UiGroupBox1.Controls.Add(this.txt_furushnaghd);
			this.UiGroupBox1.Controls.Add(this.txt_ruzegabl);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_7A0_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			arg_7A0_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_7D1_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1008, 802);
			arg_7D1_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton2.Image = global::FruitBox.My.Resources.Resources.print;
			global::System.Windows.Forms.Control arg_826_0 = this.UiButton2;
			location = new global::System.Drawing.Point(268, 10);
			arg_826_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			this.UiButton2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_86F_0 = this.UiButton2;
			size = new global::System.Drawing.Size(117, 36);
			arg_86F_0.Size = size;
			this.UiButton2.TabIndex = 27;
			this.UiButton2.Text = "چاپ";
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_8E3_0 = this.Label10;
			location = new global::System.Drawing.Point(621, 22);
			arg_8E3_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_90E_0 = this.Label10;
			size = new global::System.Drawing.Size(45, 14);
			arg_90E_0.Size = size;
			this.Label10.TabIndex = 26;
			this.Label10.Text = "جستجو";
			this.UiGroupBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox4.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox4.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_974_0 = this.UiGroupBox4;
			location = new global::System.Drawing.Point(471, 661);
			arg_974_0.Location = location;
			this.UiGroupBox4.Name = "UiGroupBox4";
			global::System.Windows.Forms.Control arg_9A2_0 = this.UiGroupBox4;
			size = new global::System.Drawing.Size(538, 18);
			arg_9A2_0.Size = size;
			this.UiGroupBox4.TabIndex = 3;
			this.UiGroupBox4.Text = "مانده صندوق";
			this.UiGroupBox4.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox3.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox3.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_A14_0 = this.UiGroupBox3;
			location = new global::System.Drawing.Point(468, 441);
			arg_A14_0.Location = location;
			this.UiGroupBox3.Name = "UiGroupBox3";
			global::System.Windows.Forms.Control arg_A42_0 = this.UiGroupBox3;
			size = new global::System.Drawing.Size(541, 18);
			arg_A42_0.Size = size;
			this.UiGroupBox3.TabIndex = 3;
			this.UiGroupBox3.Text = "پرداختی";
			this.UiGroupBox3.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.Top;
			global::System.Windows.Forms.Control arg_AB1_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(468, 94);
			arg_AB1_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_ADF_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(540, 18);
			arg_ADF_0.Size = size;
			this.UiGroupBox2.TabIndex = 3;
			this.UiGroupBox2.Text = "دریافتی";
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.lbl_kasrezafe.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_kasrezafe.AutoSize = true;
			this.lbl_kasrezafe.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_kasrezafe.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B77_0 = this.lbl_kasrezafe;
			location = new global::System.Drawing.Point(844, 725);
			arg_B77_0.Location = location;
			this.lbl_kasrezafe.Name = "lbl_kasrezafe";
			global::System.Windows.Forms.Control arg_BA2_0 = this.lbl_kasrezafe;
			size = new global::System.Drawing.Size(37, 18);
			arg_BA2_0.Size = size;
			this.lbl_kasrezafe.TabIndex = 2;
			this.lbl_kasrezafe.Text = "کسر";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C2D_0 = this.Label12;
			location = new global::System.Drawing.Point(844, 586);
			arg_C2D_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_C58_0 = this.Label12;
			size = new global::System.Drawing.Size(123, 18);
			arg_C58_0.Size = size;
			this.Label12.TabIndex = 2;
			this.Label12.Text = "انتقال وجه به بانک";
			this.Label15.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_CE3_0 = this.Label15;
			location = new global::System.Drawing.Point(844, 693);
			arg_CE3_0.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control arg_D0E_0 = this.Label15;
			size = new global::System.Drawing.Size(109, 18);
			arg_D0E_0.Size = size;
			this.Label15.TabIndex = 2;
			this.Label15.Text = "موجودی صندوق";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D99_0 = this.Label11;
			location = new global::System.Drawing.Point(843, 551);
			arg_D99_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_DC4_0 = this.Label11;
			size = new global::System.Drawing.Size(92, 18);
			arg_DC4_0.Size = size;
			this.Label11.TabIndex = 2;
			this.Label11.Text = "پرداخت هزینه";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E4F_0 = this.Label14;
			location = new global::System.Drawing.Point(843, 755);
			arg_E4F_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_E7A_0 = this.Label14;
			size = new global::System.Drawing.Size(122, 18);
			arg_E7A_0.Size = size;
			this.Label14.TabIndex = 2;
			this.Label14.Text = "مانده صندوق امروز";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F05_0 = this.Label13;
			location = new global::System.Drawing.Point(844, 637);
			arg_F05_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_F30_0 = this.Label13;
			size = new global::System.Drawing.Size(115, 18);
			arg_F30_0.Size = size;
			this.Label13.TabIndex = 2;
			this.Label13.Text = "جمع کل پرداختی";
			this.Label18.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label18.AutoSize = true;
			this.Label18.BackColor = global::System.Drawing.Color.Transparent;
			this.Label18.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_FBB_0 = this.Label18;
			location = new global::System.Drawing.Point(843, 368);
			arg_FBB_0.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control arg_FE9_0 = this.Label18;
			size = new global::System.Drawing.Size(152, 18);
			arg_FE9_0.Size = size;
			this.Label18.TabIndex = 2;
			this.Label18.Text = "واریزی کارتخوان به بانک";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1074_0 = this.Label7;
			location = new global::System.Drawing.Point(840, 410);
			arg_1074_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_109F_0 = this.Label7;
			size = new global::System.Drawing.Size(110, 18);
			arg_109F_0.Size = size;
			this.Label7.TabIndex = 2;
			this.Label7.Text = "جمع کل دریافتی";
			this.Label20.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label20.AutoSize = true;
			this.Label20.BackColor = global::System.Drawing.Color.Transparent;
			this.Label20.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_112A_0 = this.Label20;
			location = new global::System.Drawing.Point(841, 332);
			arg_112A_0.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control arg_1155_0 = this.Label20;
			size = new global::System.Drawing.Size(114, 18);
			arg_1155_0.Size = size;
			this.Label20.TabIndex = 2;
			this.Label20.Text = "منهای چک نقدی";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_11E0_0 = this.Label6;
			location = new global::System.Drawing.Point(841, 298);
			arg_11E0_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_120B_0 = this.Label6;
			size = new global::System.Drawing.Size(40, 18);
			arg_120B_0.Size = size;
			this.Label6.TabIndex = 2;
			this.Label6.Text = "درآمد";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1296_0 = this.Label9;
			location = new global::System.Drawing.Point(843, 515);
			arg_1296_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_12C4_0 = this.Label9;
			size = new global::System.Drawing.Size(140, 18);
			arg_12C4_0.Size = size;
			this.Label9.TabIndex = 2;
			this.Label9.Text = "پرداخت کرایه و مخارج";
			this.Label17.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_134F_0 = this.Label17;
			location = new global::System.Drawing.Point(840, 194);
			arg_134F_0.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control arg_137D_0 = this.Label17;
			size = new global::System.Drawing.Size(163, 18);
			arg_137D_0.Size = size;
			this.Label17.TabIndex = 2;
			this.Label17.Text = "فروش نقدی بار روی زمین";
			this.Label19.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label19.AutoSize = true;
			this.Label19.BackColor = global::System.Drawing.Color.Transparent;
			this.Label19.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1408_0 = this.Label19;
			location = new global::System.Drawing.Point(840, 266);
			arg_1408_0.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control arg_1433_0 = this.Label19;
			size = new global::System.Drawing.Size(102, 18);
			arg_1433_0.Size = size;
			this.Label19.TabIndex = 2;
			this.Label19.Text = "بانک به صندوق";
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_14BE_0 = this.Label5;
			location = new global::System.Drawing.Point(840, 228);
			arg_14BE_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_14E9_0 = this.Label5;
			size = new global::System.Drawing.Size(93, 18);
			arg_14E9_0.Size = size;
			this.Label5.TabIndex = 2;
			this.Label5.Text = "نقد کردن چک";
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1574_0 = this.Label8;
			location = new global::System.Drawing.Point(843, 481);
			arg_1574_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_15A2_0 = this.Label8;
			size = new global::System.Drawing.Size(149, 18);
			arg_15A2_0.Size = size;
			this.Label8.TabIndex = 2;
			this.Label8.Text = "پرداخت نقد به مشتری";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_162D_0 = this.Label4;
			location = new global::System.Drawing.Point(841, 158);
			arg_162D_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_165B_0 = this.Label4;
			size = new global::System.Drawing.Size(140, 18);
			arg_165B_0.Size = size;
			this.Label4.TabIndex = 2;
			this.Label4.Text = "دریافت نقد از مشتری";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_16E3_0 = this.Label3;
			location = new global::System.Drawing.Point(840, 123);
			arg_16E3_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_170E_0 = this.Label3;
			size = new global::System.Drawing.Size(82, 18);
			arg_170E_0.Size = size;
			this.Label3.TabIndex = 2;
			this.Label3.Text = "فروش نقدی";
			this.lbl_ruzegabl.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_ruzegabl.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_ruzegabl.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1789_0 = this.lbl_ruzegabl;
			location = new global::System.Drawing.Point(509, 55);
			arg_1789_0.Location = location;
			this.lbl_ruzegabl.Name = "lbl_ruzegabl";
			global::System.Windows.Forms.Control arg_17B7_0 = this.lbl_ruzegabl;
			size = new global::System.Drawing.Size(157, 18);
			arg_17B7_0.Size = size;
			this.lbl_ruzegabl.TabIndex = 2;
			this.Label16.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label16.BackColor = global::System.Drawing.Color.WhiteSmoke;
			this.Label16.Font = new global::System.Drawing.Font("Tahoma", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_181E_0 = this.Label16;
			location = new global::System.Drawing.Point(12, 10);
			arg_181E_0.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control arg_184C_0 = this.Label16;
			size = new global::System.Drawing.Size(250, 36);
			arg_184C_0.Size = size;
			this.Label16.TabIndex = 2;
			this.Label16.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_18D1_0 = this.Label2;
			location = new global::System.Drawing.Point(844, 55);
			arg_18D1_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_18FF_0 = this.Label2;
			size = new global::System.Drawing.Size(157, 18);
			arg_18FF_0.Size = size;
			this.Label2.TabIndex = 2;
			this.Label2.Text = "موجودی صندوق روز قبل";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1987_0 = this.Label1;
			location = new global::System.Drawing.Point(840, 20);
			arg_1987_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_19B2_0 = this.Label1;
			size = new global::System.Drawing.Size(36, 18);
			arg_19B2_0.Size = size;
			this.Label1.TabIndex = 2;
			this.Label1.Text = "تاریخ";
			this.GridEx1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.GridEx1.AlternatingColors = true;
			this.GridEx1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEx1_DesignTimeLayout.LayoutString");
			this.GridEx1.DesignTimeLayout = gridEXLayout;
			this.GridEx1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEx1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEx1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEx1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEx1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1A7E_0 = this.GridEx1;
			location = new global::System.Drawing.Point(0, 52);
			arg_1A7E_0.Location = location;
			this.GridEx1.Name = "GridEx1";
			this.GridEx1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEx1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEx1.RowHeaderContent = global::Janus.Windows.GridEX.RowHeaderContent.RowPosition;
			this.GridEx1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_1AE3_0 = this.GridEx1;
			size = new global::System.Drawing.Size(663, 689);
			arg_1AE3_0.Size = size;
			this.GridEx1.TabIndex = 17;
			this.GridEx1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEx1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEx1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEx1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEx1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEx1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEx1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.EditBox1.AcceptEnter = true;
			this.EditBox1.AllowEdit = true;
			this.EditBox1.AllowNew = true;
			this.EditBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox1.FocusColor = true;
			this.EditBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BE3_0 = this.EditBox1;
			location = new global::System.Drawing.Point(391, 10);
			arg_1BE3_0.Location = location;
			this.EditBox1.Name = "EditBox1";
			this.EditBox1.Nullable = true;
			this.EditBox1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.EditBox1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1C3C_0 = this.EditBox1;
			size = new global::System.Drawing.Size(228, 36);
			arg_1C3C_0.Size = size;
			this.EditBox1.TabIndex = 25;
			this.EditBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kasrezafe.AcceptEnter = true;
			this.txt_kasrezafe.AllowEdit = false;
			this.txt_kasrezafe.AllowNew = true;
			this.txt_kasrezafe.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kasrezafe.FocusColor = true;
			this.txt_kasrezafe.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1CDA_0 = this.txt_kasrezafe;
			location = new global::System.Drawing.Point(672, 711);
			arg_1CDA_0.Location = location;
			this.txt_kasrezafe.Name = "txt_kasrezafe";
			this.txt_kasrezafe.Nullable = true;
			this.txt_kasrezafe.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kasrezafe.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1D33_0 = this.txt_kasrezafe;
			size = new global::System.Drawing.Size(167, 36);
			arg_1D33_0.Size = size;
			this.txt_kasrezafe.TabIndex = 15;
			this.txt_kasrezafe.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_entegalvajh.AcceptEnter = true;
			this.txt_entegalvajh.AllowEdit = false;
			this.txt_entegalvajh.AllowNew = true;
			this.txt_entegalvajh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_entegalvajh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_entegalvajh.ButtonText = "...";
			this.txt_entegalvajh.FocusColor = true;
			this.txt_entegalvajh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1DEF_0 = this.txt_entegalvajh;
			location = new global::System.Drawing.Point(671, 570);
			arg_1DEF_0.Location = location;
			this.txt_entegalvajh.Name = "txt_entegalvajh";
			this.txt_entegalvajh.Nullable = true;
			this.txt_entegalvajh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_entegalvajh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1E48_0 = this.txt_entegalvajh;
			size = new global::System.Drawing.Size(167, 36);
			arg_1E48_0.Size = size;
			this.txt_entegalvajh.TabIndex = 11;
			this.txt_entegalvajh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_mojod.AcceptEnter = true;
			this.txt_mojod.AllowEdit = false;
			this.txt_mojod.AllowNew = true;
			this.txt_mojod.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mojod.FocusColor = true;
			this.txt_mojod.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1EE6_0 = this.txt_mojod;
			location = new global::System.Drawing.Point(672, 680);
			arg_1EE6_0.Location = location;
			this.txt_mojod.Name = "txt_mojod";
			this.txt_mojod.Nullable = true;
			this.txt_mojod.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mojod.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1F3F_0 = this.txt_mojod;
			size = new global::System.Drawing.Size(167, 36);
			arg_1F3F_0.Size = size;
			this.txt_mojod.TabIndex = 14;
			this.txt_mojod.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_pardakhthazine.AcceptEnter = true;
			this.txt_pardakhthazine.AllowEdit = false;
			this.txt_pardakhthazine.AllowNew = true;
			this.txt_pardakhthazine.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_pardakhthazine.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_pardakhthazine.ButtonText = "...";
			this.txt_pardakhthazine.FocusColor = true;
			this.txt_pardakhthazine.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1FFB_0 = this.txt_pardakhthazine;
			location = new global::System.Drawing.Point(671, 535);
			arg_1FFB_0.Location = location;
			this.txt_pardakhthazine.Name = "txt_pardakhthazine";
			this.txt_pardakhthazine.Nullable = true;
			this.txt_pardakhthazine.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_pardakhthazine.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2054_0 = this.txt_pardakhthazine;
			size = new global::System.Drawing.Size(167, 36);
			arg_2054_0.Size = size;
			this.txt_pardakhthazine.TabIndex = 10;
			this.txt_pardakhthazine.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_mande.AcceptEnter = true;
			this.txt_mande.AllowEdit = false;
			this.txt_mande.AllowNew = true;
			this.txt_mande.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mande.FocusColor = true;
			this.txt_mande.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20F2_0 = this.txt_mande;
			location = new global::System.Drawing.Point(672, 742);
			arg_20F2_0.Location = location;
			this.txt_mande.Name = "txt_mande";
			this.txt_mande.Nullable = true;
			this.txt_mande.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mande.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_214B_0 = this.txt_mande;
			size = new global::System.Drawing.Size(167, 36);
			arg_214B_0.Size = size;
			this.txt_mande.TabIndex = 16;
			this.txt_mande.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jampardakhti.AcceptEnter = true;
			this.txt_jampardakhti.AllowEdit = false;
			this.txt_jampardakhti.AllowNew = true;
			this.txt_jampardakhti.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_jampardakhti.FocusColor = true;
			this.txt_jampardakhti.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_jampardakhti.ForeColor = global::System.Drawing.Color.Green;
			global::System.Windows.Forms.Control arg_21FA_0 = this.txt_jampardakhti;
			location = new global::System.Drawing.Point(672, 621);
			arg_21FA_0.Location = location;
			this.txt_jampardakhti.Name = "txt_jampardakhti";
			this.txt_jampardakhti.Nullable = true;
			this.txt_jampardakhti.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jampardakhti.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2253_0 = this.txt_jampardakhti;
			size = new global::System.Drawing.Size(167, 36);
			arg_2253_0.Size = size;
			this.txt_jampardakhti.TabIndex = 13;
			this.txt_jampardakhti.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jamdaryaft.AcceptEnter = true;
			this.txt_jamdaryaft.AllowEdit = false;
			this.txt_jamdaryaft.AllowNew = true;
			this.txt_jamdaryaft.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_jamdaryaft.FocusColor = true;
			this.txt_jamdaryaft.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_jamdaryaft.ForeColor = global::System.Drawing.Color.Green;
			global::System.Windows.Forms.Control arg_2302_0 = this.txt_jamdaryaft;
			location = new global::System.Drawing.Point(671, 399);
			arg_2302_0.Location = location;
			this.txt_jamdaryaft.Name = "txt_jamdaryaft";
			this.txt_jamdaryaft.Nullable = true;
			this.txt_jamdaryaft.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jamdaryaft.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_235B_0 = this.txt_jamdaryaft;
			size = new global::System.Drawing.Size(167, 36);
			arg_235B_0.Size = size;
			this.txt_jamdaryaft.TabIndex = 7;
			this.txt_jamdaryaft.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_kartkhan.AcceptEnter = true;
			this.txt_kartkhan.AllowEdit = false;
			this.txt_kartkhan.AllowNew = true;
			this.txt_kartkhan.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_kartkhan.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_kartkhan.ButtonText = "...";
			this.txt_kartkhan.FocusColor = true;
			this.txt_kartkhan.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_kartkhan.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control arg_2427_0 = this.txt_kartkhan;
			location = new global::System.Drawing.Point(671, 357);
			arg_2427_0.Location = location;
			this.txt_kartkhan.Name = "txt_kartkhan";
			this.txt_kartkhan.Nullable = true;
			this.txt_kartkhan.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_kartkhan.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2480_0 = this.txt_kartkhan;
			size = new global::System.Drawing.Size(167, 36);
			arg_2480_0.Size = size;
			this.txt_kartkhan.TabIndex = 12;
			this.txt_kartkhan.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_checknaghd.AcceptEnter = true;
			this.txt_checknaghd.AllowEdit = false;
			this.txt_checknaghd.AllowNew = true;
			this.txt_checknaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_checknaghd.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_checknaghd.ButtonText = "...";
			this.txt_checknaghd.FocusColor = true;
			this.txt_checknaghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_checknaghd.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control arg_254D_0 = this.txt_checknaghd;
			location = new global::System.Drawing.Point(672, 322);
			arg_254D_0.Location = location;
			this.txt_checknaghd.Name = "txt_checknaghd";
			this.txt_checknaghd.Nullable = true;
			this.txt_checknaghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_checknaghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_25A6_0 = this.txt_checknaghd;
			size = new global::System.Drawing.Size(166, 36);
			arg_25A6_0.Size = size;
			this.txt_checknaghd.TabIndex = 6;
			this.txt_checknaghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_daramad.AcceptEnter = true;
			this.txt_daramad.AllowEdit = false;
			this.txt_daramad.AllowNew = true;
			this.txt_daramad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_daramad.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_daramad.ButtonText = "...";
			this.txt_daramad.FocusColor = true;
			this.txt_daramad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2661_0 = this.txt_daramad;
			location = new global::System.Drawing.Point(672, 287);
			arg_2661_0.Location = location;
			this.txt_daramad.Name = "txt_daramad";
			this.txt_daramad.Nullable = true;
			this.txt_daramad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_daramad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_26BA_0 = this.txt_daramad;
			size = new global::System.Drawing.Size(166, 36);
			arg_26BA_0.Size = size;
			this.txt_daramad.TabIndex = 6;
			this.txt_daramad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_pardakhtkeraye.AcceptEnter = true;
			this.txt_pardakhtkeraye.AllowEdit = false;
			this.txt_pardakhtkeraye.AllowNew = true;
			this.txt_pardakhtkeraye.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_pardakhtkeraye.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_pardakhtkeraye.ButtonText = "...";
			this.txt_pardakhtkeraye.FocusColor = true;
			this.txt_pardakhtkeraye.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2775_0 = this.txt_pardakhtkeraye;
			location = new global::System.Drawing.Point(671, 500);
			arg_2775_0.Location = location;
			this.txt_pardakhtkeraye.Name = "txt_pardakhtkeraye";
			this.txt_pardakhtkeraye.Nullable = true;
			this.txt_pardakhtkeraye.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_pardakhtkeraye.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_27CE_0 = this.txt_pardakhtkeraye;
			size = new global::System.Drawing.Size(167, 36);
			arg_27CE_0.Size = size;
			this.txt_pardakhtkeraye.TabIndex = 9;
			this.txt_pardakhtkeraye.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_bank_be_sandugh.AcceptEnter = true;
			this.txt_bank_be_sandugh.AllowEdit = false;
			this.txt_bank_be_sandugh.AllowNew = true;
			this.txt_bank_be_sandugh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_bank_be_sandugh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_bank_be_sandugh.ButtonText = "...";
			this.txt_bank_be_sandugh.FocusColor = true;
			this.txt_bank_be_sandugh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_288A_0 = this.txt_bank_be_sandugh;
			location = new global::System.Drawing.Point(672, 252);
			arg_288A_0.Location = location;
			this.txt_bank_be_sandugh.Name = "txt_bank_be_sandugh";
			this.txt_bank_be_sandugh.Nullable = true;
			this.txt_bank_be_sandugh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_bank_be_sandugh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_28E3_0 = this.txt_bank_be_sandugh;
			size = new global::System.Drawing.Size(166, 36);
			arg_28E3_0.Size = size;
			this.txt_bank_be_sandugh.TabIndex = 5;
			this.txt_bank_be_sandugh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_naghdkardancheck.AcceptEnter = true;
			this.txt_naghdkardancheck.AllowEdit = false;
			this.txt_naghdkardancheck.AllowNew = true;
			this.txt_naghdkardancheck.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_naghdkardancheck.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_naghdkardancheck.ButtonText = "...";
			this.txt_naghdkardancheck.FocusColor = true;
			this.txt_naghdkardancheck.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_299E_0 = this.txt_naghdkardancheck;
			location = new global::System.Drawing.Point(672, 217);
			arg_299E_0.Location = location;
			this.txt_naghdkardancheck.Name = "txt_naghdkardancheck";
			this.txt_naghdkardancheck.Nullable = true;
			this.txt_naghdkardancheck.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_naghdkardancheck.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_29F7_0 = this.txt_naghdkardancheck;
			size = new global::System.Drawing.Size(166, 36);
			arg_29F7_0.Size = size;
			this.txt_naghdkardancheck.TabIndex = 5;
			this.txt_naghdkardancheck.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_pardakhtnaghd.AcceptEnter = true;
			this.txt_pardakhtnaghd.AllowEdit = false;
			this.txt_pardakhtnaghd.AllowNew = true;
			this.txt_pardakhtnaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_pardakhtnaghd.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_pardakhtnaghd.ButtonText = "...";
			this.txt_pardakhtnaghd.FocusColor = true;
			this.txt_pardakhtnaghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2AB2_0 = this.txt_pardakhtnaghd;
			location = new global::System.Drawing.Point(671, 465);
			arg_2AB2_0.Location = location;
			this.txt_pardakhtnaghd.Name = "txt_pardakhtnaghd";
			this.txt_pardakhtnaghd.Nullable = true;
			this.txt_pardakhtnaghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_pardakhtnaghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2B0B_0 = this.txt_pardakhtnaghd;
			size = new global::System.Drawing.Size(167, 36);
			arg_2B0B_0.Size = size;
			this.txt_pardakhtnaghd.TabIndex = 8;
			this.txt_pardakhtnaghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_furushbar.AcceptEnter = true;
			this.txt_furushbar.AllowEdit = false;
			this.txt_furushbar.AllowNew = true;
			this.txt_furushbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_furushbar.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_furushbar.ButtonText = "...";
			this.txt_furushbar.FocusColor = true;
			this.txt_furushbar.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2BC6_0 = this.txt_furushbar;
			location = new global::System.Drawing.Point(672, 182);
			arg_2BC6_0.Location = location;
			this.txt_furushbar.Name = "txt_furushbar";
			this.txt_furushbar.Nullable = true;
			this.txt_furushbar.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_furushbar.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2C1F_0 = this.txt_furushbar;
			size = new global::System.Drawing.Size(166, 36);
			arg_2C1F_0.Size = size;
			this.txt_furushbar.TabIndex = 4;
			this.txt_furushbar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_daryaftnaghd.AcceptEnter = true;
			this.txt_daryaftnaghd.AllowEdit = false;
			this.txt_daryaftnaghd.AllowNew = true;
			this.txt_daryaftnaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_daryaftnaghd.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_daryaftnaghd.ButtonText = "...";
			this.txt_daryaftnaghd.FocusColor = true;
			this.txt_daryaftnaghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2CDA_0 = this.txt_daryaftnaghd;
			location = new global::System.Drawing.Point(672, 147);
			arg_2CDA_0.Location = location;
			this.txt_daryaftnaghd.Name = "txt_daryaftnaghd";
			this.txt_daryaftnaghd.Nullable = true;
			this.txt_daryaftnaghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_daryaftnaghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2D33_0 = this.txt_daryaftnaghd;
			size = new global::System.Drawing.Size(166, 36);
			arg_2D33_0.Size = size;
			this.txt_daryaftnaghd.TabIndex = 3;
			this.txt_daryaftnaghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_furushnaghd.AcceptEnter = true;
			this.txt_furushnaghd.AllowEdit = false;
			this.txt_furushnaghd.AllowNew = true;
			this.txt_furushnaghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_furushnaghd.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_furushnaghd.ButtonText = "...";
			this.txt_furushnaghd.FocusColor = true;
			this.txt_furushnaghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2DEB_0 = this.txt_furushnaghd;
			location = new global::System.Drawing.Point(672, 112);
			arg_2DEB_0.Location = location;
			this.txt_furushnaghd.Name = "txt_furushnaghd";
			this.txt_furushnaghd.Nullable = true;
			this.txt_furushnaghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_furushnaghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2E44_0 = this.txt_furushnaghd;
			size = new global::System.Drawing.Size(166, 36);
			arg_2E44_0.Size = size;
			this.txt_furushnaghd.TabIndex = 2;
			this.txt_furushnaghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_ruzegabl.AcceptEnter = true;
			this.txt_ruzegabl.AllowEdit = false;
			this.txt_ruzegabl.AllowNew = true;
			this.txt_ruzegabl.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_ruzegabl.FocusColor = true;
			this.txt_ruzegabl.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ruzegabl.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_2EEF_0 = this.txt_ruzegabl;
			location = new global::System.Drawing.Point(672, 52);
			arg_2EEF_0.Location = location;
			this.txt_ruzegabl.Name = "txt_ruzegabl";
			this.txt_ruzegabl.Nullable = true;
			this.txt_ruzegabl.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_ruzegabl.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2F48_0 = this.txt_ruzegabl;
			size = new global::System.Drawing.Size(166, 36);
			arg_2F48_0.Size = size;
			this.txt_ruzegabl.TabIndex = 1;
			this.txt_ruzegabl.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikh.AcceptEnter = true;
			this.txt_tarikh.AllowEdit = true;
			this.txt_tarikh.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh.ButtonEnable = true;
			this.txt_tarikh.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.DownArrow;
			this.txt_tarikh.FocusDatePart = 2;
			this.txt_tarikh.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2FEF_0 = this.txt_tarikh;
			location = new global::System.Drawing.Point(719, 10);
			arg_2FEF_0.Location = location;
			this.txt_tarikh.Mask = "0000/00/00";
			this.txt_tarikh.Name = "txt_tarikh";
			this.txt_tarikh.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_3038_0 = this.txt_tarikh;
			size = new global::System.Drawing.Size(119, 36);
			arg_3038_0.Size = size;
			this.txt_tarikh.TabIndex = 0;
			this.txt_tarikh.Text = "1394/08/27";
			this.txt_tarikh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(7f, 14f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1008, 802);
			this.ClientSize = size;
			this.Controls.Add(this.UiGroupBox1);
			this.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_rpt_Sandugh";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "گزارش روزانه صندوق";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEx1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04001181 RID: 4481
		private global::System.ComponentModel.IContainer components;
	}
}
