namespace FruitBox
{
	// Token: 0x02000116 RID: 278
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Varedat : global::System.Windows.Forms.Form
	{
		// Token: 0x0600284A RID: 10314 RVA: 0x001E6720 File Offset: 0x001E4920
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600284B RID: 10315 RVA: 0x001E6770 File Offset: 0x001E4970
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column1.ButtonImage");
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Varedat));
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference2 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column2.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference3 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column11.ButtonImage");
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference4 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column0.ButtonImage");
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.lbl_daramad = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem14 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem12 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem15 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem16 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem17 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem18 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem19 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem10 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem16_2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem17_2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem18_2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem19_2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem1 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem2 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem3 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem4 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem5 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem6 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem9 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ControlContainerItem1 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.MicroChartItem1 = new global::DevComponents.DotNetBar.MicroChartItem();
			this.ItemContainer2 = new global::DevComponents.DotNetBar.ItemContainer();
			this.ControlContainerItem2 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.lbl_sayer = new global::FruitBox.CurrencyBox(this.components);
			this.lbl_sardkhane2 = new global::FruitBox.CurrencyBox(this.components);
			this.lbl_sardkhane = new global::FruitBox.CurrencyBox(this.components);
			this.lbl_kerayekharid = new global::FruitBox.CurrencyBox(this.components);
			this.txt_makharej = new global::FruitBox.CurrencyBox(this.components);
			this.txt_rizbar = new global::FruitBox.CurrencyBox(this.components);
			this.txt_tarikhGrid = new global::FruitBox.DateBox2(this.components);
			this.Grid_RizBar = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_jam_kol = new global::FruitBox.CurrencyBox(this.components);
			this.txt_fee = new global::FruitBox.CurrencyBox(this.components);
			this.txt_desc = new global::FruitBox.EditBox(this.components);
			this.txt_num = new global::FruitBox.NavBox();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.lbl_sayer);
			this.UiGroupBox1.Controls.Add(this.lbl_sardkhane2);
			this.UiGroupBox1.Controls.Add(this.lbl_sardkhane);
			this.UiGroupBox1.Controls.Add(this.lbl_kerayekharid);
			this.UiGroupBox1.Controls.Add(this.txt_makharej);
			this.UiGroupBox1.Controls.Add(this.txt_rizbar);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.txt_tarikhGrid);
			this.UiGroupBox1.Controls.Add(this.Grid_RizBar);
			this.UiGroupBox1.Controls.Add(this.txt_jam_kol);
			this.UiGroupBox1.Controls.Add(this.txt_fee);
			this.UiGroupBox1.Controls.Add(this.txt_desc);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label18);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.lbl_daramad);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_674_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 41);
			arg_674_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_6B2_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1568, 641);
			arg_6B2_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_70F_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 615);
			arg_70F_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_73D_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1568, 26);
			arg_73D_0.Size = size;
			this.UiGroupBox2.TabIndex = 24;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_7C3_0 = this.Label12;
			location = new global::System.Drawing.Point(1441, 121);
			arg_7C3_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_7EE_0 = this.Label12;
			size = new global::System.Drawing.Size(69, 19);
			arg_7EE_0.Size = size;
			this.Label12.TabIndex = 0;
			this.Label12.Text = "ملاحضات";
			this.Label18.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label18.AutoSize = true;
			this.Label18.BackColor = global::System.Drawing.Color.Transparent;
			this.Label18.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_87A_0 = this.Label18;
			location = new global::System.Drawing.Point(1074, 165);
			arg_87A_0.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control arg_8A5_0 = this.Label18;
			size = new global::System.Drawing.Size(112, 19);
			arg_8A5_0.Size = size;
			this.Label18.TabIndex = 0;
			this.Label18.Text = "جمع مبلغ درآمد";
			this.Label18.Visible = false;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_93B_0 = this.Label8;
			location = new global::System.Drawing.Point(1074, 120);
			arg_93B_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_966_0 = this.Label8;
			size = new global::System.Drawing.Size(86, 19);
			arg_966_0.Size = size;
			this.Label8.TabIndex = 0;
			this.Label8.Text = "سایر مخارج";
			this.Label8.Visible = false;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9FC_0 = this.Label6;
			location = new global::System.Drawing.Point(1074, 86);
			arg_9FC_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_A2A_0 = this.Label6;
			size = new global::System.Drawing.Size(158, 19);
			arg_A2A_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "کرایه حمل از سردخانه";
			this.Label6.Visible = false;
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_AC0_0 = this.Label7;
			location = new global::System.Drawing.Point(1074, 51);
			arg_AC0_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_AEB_0 = this.Label7;
			size = new global::System.Drawing.Size(113, 19);
			arg_AEB_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "مخارج سردخانه";
			this.Label7.Visible = false;
			this.lbl_daramad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_daramad.BackColor = global::System.Drawing.Color.Transparent;
			this.lbl_daramad.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lbl_daramad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B84_0 = this.lbl_daramad;
			location = new global::System.Drawing.Point(939, 155);
			arg_B84_0.Location = location;
			this.lbl_daramad.Name = "lbl_daramad";
			global::System.Windows.Forms.Control arg_BB2_0 = this.lbl_daramad;
			size = new global::System.Drawing.Size(133, 36);
			arg_BB2_0.Size = size;
			this.lbl_daramad.TabIndex = 0;
			this.lbl_daramad.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lbl_daramad.Visible = false;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C45_0 = this.Label4;
			location = new global::System.Drawing.Point(1074, 15);
			arg_C45_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_C70_0 = this.Label4;
			size = new global::System.Drawing.Size(77, 19);
			arg_C70_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "کرایه خرید";
			this.Label4.Visible = false;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D06_0 = this.Label3;
			location = new global::System.Drawing.Point(1440, 85);
			arg_D06_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_D31_0 = this.Label3;
			size = new global::System.Drawing.Size(98, 19);
			arg_D31_0.Size = size;
			this.Label3.TabIndex = 0;
			this.Label3.Text = "کرایه و مخارج";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DBA_0 = this.Label2;
			location = new global::System.Drawing.Point(1444, 49);
			arg_DBA_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_DE5_0 = this.Label2;
			size = new global::System.Drawing.Size(46, 19);
			arg_DE5_0.Size = size;
			this.Label2.TabIndex = 0;
			this.Label2.Text = "ریز بار";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E6E_0 = this.Label1;
			location = new global::System.Drawing.Point(1440, 16);
			arg_E6E_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_E99_0 = this.Label1;
			size = new global::System.Drawing.Size(90, 19);
			arg_E99_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "شماره سند";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem14,
				this.ButtonItem11,
				this.ButtonItem12,
				this.ButtonItem6,
				this.ButtonItem4,
				this.ButtonItem7,
				this.ButtonItem5,
				this.ButtonItem3,
				this.ButtonItem15,
				this.ButtonItem10
			});
			global::DevComponents.DotNetBar.Bar arg_FAA_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_FAA_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_FD8_0 = this.Bar1;
			size = new global::System.Drawing.Size(1568, 41);
			arg_FD8_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 12;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem14.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem14.Image = global::FruitBox.My.Resources.Resources.account_book_ok;
			this.ButtonItem14.Name = "ButtonItem14";
			this.ButtonItem14.Text = "بستن سند (F9)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "صورتحساب (F3)";
			this.ButtonItem12.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem12.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem12.Name = "ButtonItem12";
			this.ButtonItem12.Text = "چاپ (F4)";
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "حذف ردیف (F5)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.transport_table;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "ثبت ریز خرید (F7)";
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.order_coins;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "کرایه و مخارج (F8)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.customers_coins;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "درصد مشارکت";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف سند (Ctrl + F5)";
			this.ButtonItem15.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem15.Image = global::FruitBox.My.Resources.Resources.table;
			this.ButtonItem15.Name = "ButtonItem15";
			this.ButtonItem15.SubItems.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem16,
				this.ButtonItem17,
				this.ButtonItem18,
				this.ButtonItem19
			});
			this.ButtonItem15.Text = "نحوه خرید";
			this.ButtonItem16.Name = "ButtonItem16";
			this.ButtonItem16.Text = "تعداد - وزن خالص";
			this.ButtonItem17.Name = "ButtonItem17";
			this.ButtonItem17.Text = "وزن خالص";
			this.ButtonItem18.Name = "ButtonItem18";
			this.ButtonItem18.Text = "تعداد";
			this.ButtonItem19.Name = "ButtonItem19";
			this.ButtonItem19.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			this.ButtonItem10.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem10.Image = global::FruitBox.My.Resources.Resources.table;
			this.ButtonItem10.Name = "ButtonItem10";
			this.ButtonItem10.SubItems.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem16_2,
				this.ButtonItem17_2,
				this.ButtonItem18_2,
				this.ButtonItem19_2
			});
			this.ButtonItem10.Text = "نحوه فروش";
			this.ButtonItem16_2.Name = "ButtonItem16_2";
			this.ButtonItem16_2.Text = "تعداد - وزن خالص";
			this.ButtonItem17_2.Name = "ButtonItem17_2";
			this.ButtonItem17_2.Text = "وزن خالص";
			this.ButtonItem18_2.Name = "ButtonItem18_2";
			this.ButtonItem18_2.Text = "تعداد";
			this.ButtonItem19_2.Name = "ButtonItem19_2";
			this.ButtonItem19_2.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			this.LabelItem1.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem1.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem1.Name = "LabelItem1";
			this.LabelItem1.Text = "وضعیت مشتری";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.TextOnlyAlways;
			global::DevComponents.DotNetBar.ButtonItem arg_153A_0 = this.ButtonItem8;
			size = new global::System.Drawing.Size(150, 0);
			arg_153A_0.FixedSize = size;
			this.ButtonItem8.ItemAlignment = global::DevComponents.DotNetBar.eItemAlignment.Center;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "0";
			this.LabelItem2.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem2.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem2.Name = "LabelItem2";
			this.LabelItem2.Text = "         بدهکار";
			this.LabelItem3.BackColor = global::System.Drawing.Color.Transparent;
			this.LabelItem3.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem3.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem3.Name = "LabelItem3";
			this.LabelItem3.Text = "        آخرین پرداختی";
			this.LabelItem4.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem4.Name = "LabelItem4";
			this.LabelItem4.Text = "000";
			this.LabelItem5.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem5.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem5.Name = "LabelItem5";
			this.LabelItem5.Text = "        تاریخ آخرین پرداختی";
			this.LabelItem6.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem6.Name = "LabelItem6";
			this.LabelItem6.Text = "1393/05/05";
			this.ButtonItem9.Name = "ButtonItem9";
			this.ButtonItem9.Text = "صورتحساب";
			this.ControlContainerItem1.AllowItemResize = false;
			this.ControlContainerItem1.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem1.Name = "ControlContainerItem1";
			this.MicroChartItem1.Name = "MicroChartItem1";
			this.ItemContainer2.BackgroundStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ItemContainer2.Name = "ItemContainer2";
			this.ItemContainer2.TitleStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ControlContainerItem2.AllowItemResize = true;
			this.ControlContainerItem2.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem2.Name = "ControlContainerItem2";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_1822_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 656);
			arg_1822_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_1897_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1568, 26);
			arg_1897_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 29;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.LabelCommand5.Key = "LabelCommand1";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand2";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand6.Text = "جمع نسیه";
			this.LabelCommand7.Key = "LabelCommand3";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand4";
			this.LabelCommand8.Name = "LabelCommand8";
			this.LabelCommand8.Text = "جمع نقد";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			this.GridEX1.AcceptsEscape = false;
			this.GridEX1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			janusLayoutReference.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference2.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_1.Instance"));
			janusLayoutReference3.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_2.Instance"));
			gridEXLayout.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference,
				janusLayoutReference2,
				janusLayoutReference3
			});
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_1B62_0 = this.GridEX1;
			location = new global::System.Drawing.Point(-3, 197);
			arg_1B62_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_1BBA_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1571, 417);
			arg_1BBA_0.Size = size;
			this.GridEX1.TabIndex = 29;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_sayer.AcceptEnter = true;
			this.lbl_sayer.AllowEdit = false;
			this.lbl_sayer.AllowNew = true;
			this.lbl_sayer.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sayer.FocusColor = true;
			this.lbl_sayer.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1CBB_0 = this.lbl_sayer;
			location = new global::System.Drawing.Point(939, 111);
			arg_1CBB_0.Location = location;
			this.lbl_sayer.Name = "lbl_sayer";
			this.lbl_sayer.Nullable = true;
			this.lbl_sayer.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.lbl_sayer.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1D14_0 = this.lbl_sayer;
			size = new global::System.Drawing.Size(133, 36);
			arg_1D14_0.Size = size;
			this.lbl_sayer.TabIndex = 28;
			this.lbl_sayer.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.lbl_sayer.Value = value;
			this.lbl_sayer.Visible = false;
			this.lbl_sayer.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_sardkhane2.AcceptEnter = true;
			this.lbl_sardkhane2.AllowEdit = false;
			this.lbl_sardkhane2.AllowNew = true;
			this.lbl_sardkhane2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sardkhane2.FocusColor = true;
			this.lbl_sardkhane2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1DD8_0 = this.lbl_sardkhane2;
			location = new global::System.Drawing.Point(939, 76);
			arg_1DD8_0.Location = location;
			this.lbl_sardkhane2.Name = "lbl_sardkhane2";
			this.lbl_sardkhane2.Nullable = true;
			this.lbl_sardkhane2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.lbl_sardkhane2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1E31_0 = this.lbl_sardkhane2;
			size = new global::System.Drawing.Size(133, 36);
			arg_1E31_0.Size = size;
			this.lbl_sardkhane2.TabIndex = 27;
			this.lbl_sardkhane2.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.lbl_sardkhane2.Value = value;
			this.lbl_sardkhane2.Visible = false;
			this.lbl_sardkhane2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_sardkhane.AcceptEnter = true;
			this.lbl_sardkhane.AllowEdit = false;
			this.lbl_sardkhane.AllowNew = true;
			this.lbl_sardkhane.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_sardkhane.FocusColor = true;
			this.lbl_sardkhane.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1EF5_0 = this.lbl_sardkhane;
			location = new global::System.Drawing.Point(939, 41);
			arg_1EF5_0.Location = location;
			this.lbl_sardkhane.Name = "lbl_sardkhane";
			this.lbl_sardkhane.Nullable = true;
			this.lbl_sardkhane.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.lbl_sardkhane.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1F4E_0 = this.lbl_sardkhane;
			size = new global::System.Drawing.Size(133, 36);
			arg_1F4E_0.Size = size;
			this.lbl_sardkhane.TabIndex = 26;
			this.lbl_sardkhane.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.lbl_sardkhane.Value = value;
			this.lbl_sardkhane.Visible = false;
			this.lbl_sardkhane.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.lbl_kerayekharid.AcceptEnter = false;
			this.lbl_kerayekharid.AllowEdit = false;
			this.lbl_kerayekharid.AllowNew = true;
			this.lbl_kerayekharid.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.lbl_kerayekharid.FocusColor = true;
			this.lbl_kerayekharid.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2011_0 = this.lbl_kerayekharid;
			location = new global::System.Drawing.Point(939, 6);
			arg_2011_0.Location = location;
			this.lbl_kerayekharid.Name = "lbl_kerayekharid";
			this.lbl_kerayekharid.Nullable = true;
			this.lbl_kerayekharid.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.lbl_kerayekharid.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_206A_0 = this.lbl_kerayekharid;
			size = new global::System.Drawing.Size(133, 36);
			arg_206A_0.Size = size;
			this.lbl_kerayekharid.TabIndex = 25;
			this.lbl_kerayekharid.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.lbl_kerayekharid.Value = value;
			this.lbl_kerayekharid.Visible = false;
			this.lbl_kerayekharid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_makharej.AcceptEnter = true;
			this.txt_makharej.AllowEdit = false;
			this.txt_makharej.AllowNew = true;
			this.txt_makharej.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_makharej.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_makharej.ButtonText = "...";
			this.txt_makharej.FocusColor = true;
			this.txt_makharej.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_214C_0 = this.txt_makharej;
			location = new global::System.Drawing.Point(1241, 76);
			arg_214C_0.Location = location;
			this.txt_makharej.Name = "txt_makharej";
			this.txt_makharej.Nullable = true;
			this.txt_makharej.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_makharej.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_makharej.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_21B2_0 = this.txt_makharej;
			size = new global::System.Drawing.Size(197, 36);
			arg_21B2_0.Size = size;
			this.txt_makharej.TabIndex = 6;
			this.txt_makharej.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_makharej.Value = value;
			this.txt_makharej.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_rizbar.AcceptEnter = true;
			this.txt_rizbar.AllowEdit = false;
			this.txt_rizbar.AllowNew = true;
			this.txt_rizbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_rizbar.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_rizbar.ButtonText = "...";
			this.txt_rizbar.FocusColor = true;
			this.txt_rizbar.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2286_0 = this.txt_rizbar;
			location = new global::System.Drawing.Point(1241, 41);
			arg_2286_0.Location = location;
			this.txt_rizbar.Name = "txt_rizbar";
			this.txt_rizbar.Nullable = true;
			this.txt_rizbar.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_rizbar.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_rizbar.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_22EC_0 = this.txt_rizbar;
			size = new global::System.Drawing.Size(197, 36);
			arg_22EC_0.Size = size;
			this.txt_rizbar.TabIndex = 2;
			this.txt_rizbar.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_rizbar.Value = value;
			this.txt_rizbar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikhGrid.AcceptEnter = false;
			this.txt_tarikhGrid.AllowEdit = true;
			this.txt_tarikhGrid.BorderStyle = global::Janus.Windows.GridEX.BorderStyle.None;
			this.txt_tarikhGrid.ButtonEnable = false;
			this.txt_tarikhGrid.ButtonEnabled = false;
			this.txt_tarikhGrid.FocusDatePart = 2;
			global::System.Windows.Forms.Control arg_238C_0 = this.txt_tarikhGrid;
			location = new global::System.Drawing.Point(12, 245);
			arg_238C_0.Location = location;
			this.txt_tarikhGrid.Mask = "0000/00/00";
			this.txt_tarikhGrid.Name = "txt_tarikhGrid";
			this.txt_tarikhGrid.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_23D5_0 = this.txt_tarikhGrid;
			size = new global::System.Drawing.Size(100, 19);
			arg_23D5_0.Size = size;
			this.txt_tarikhGrid.TabIndex = 22;
			this.txt_tarikhGrid.Text = "1393/05/28";
			this.txt_tarikhGrid.Visible = false;
			this.txt_tarikhGrid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Grid_RizBar.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_RizBar.AlternatingColors = true;
			this.Grid_RizBar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.Grid_RizBar.AutoEdit = true;
			janusLayoutReference4.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("Grid_RizBar_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout2.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference4
			});
			gridEXLayout2.LayoutString = componentResourceManager.GetString("Grid_RizBar_DesignTimeLayout.LayoutString");
			this.Grid_RizBar.DesignTimeLayout = gridEXLayout2;
			this.Grid_RizBar.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_RizBar.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_RizBar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Grid_RizBar.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_RizBar.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_2505_0 = this.Grid_RizBar;
			location = new global::System.Drawing.Point(0, 6);
			arg_2505_0.Location = location;
			this.Grid_RizBar.Name = "Grid_RizBar";
			this.Grid_RizBar.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_RizBar.RowHeaderContent = global::Janus.Windows.GridEX.RowHeaderContent.RowIndex;
			global::System.Windows.Forms.Control arg_2550_0 = this.Grid_RizBar;
			size = new global::System.Drawing.Size(933, 185);
			arg_2550_0.Size = size;
			this.Grid_RizBar.TabIndex = 21;
			this.Grid_RizBar.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.Grid_RizBar.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_RizBar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jam_kol.AcceptEnter = false;
			this.txt_jam_kol.AllowEdit = true;
			this.txt_jam_kol.AllowNew = true;
			this.txt_jam_kol.FocusColor = false;
			global::System.Windows.Forms.Control arg_25D6_0 = this.txt_jam_kol;
			location = new global::System.Drawing.Point(12, 218);
			arg_25D6_0.Location = location;
			this.txt_jam_kol.Name = "txt_jam_kol";
			this.txt_jam_kol.Nullable = true;
			this.txt_jam_kol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jam_kol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_262C_0 = this.txt_jam_kol;
			size = new global::System.Drawing.Size(100, 21);
			arg_262C_0.Size = size;
			this.txt_jam_kol.TabIndex = 14;
			this.txt_jam_kol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jam_kol.Value = value;
			this.txt_jam_kol.Visible = false;
			this.txt_jam_kol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fee.AcceptEnter = true;
			this.txt_fee.AllowEdit = true;
			this.txt_fee.AllowNew = true;
			this.txt_fee.AllowZero = true;
			this.txt_fee.FocusColor = false;
			global::System.Windows.Forms.Control arg_26CD_0 = this.txt_fee;
			location = new global::System.Drawing.Point(12, 186);
			arg_26CD_0.Location = location;
			this.txt_fee.Name = "txt_fee";
			this.txt_fee.Nullable = true;
			this.txt_fee.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fee.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2723_0 = this.txt_fee;
			size = new global::System.Drawing.Size(100, 21);
			arg_2723_0.Size = size;
			this.txt_fee.TabIndex = 13;
			this.txt_fee.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fee.Value = value;
			this.txt_fee.Visible = false;
			this.txt_fee.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_desc.AcceptEnter = false;
			this.txt_desc.AllowEdit = true;
			this.txt_desc.AllowNew = true;
			this.txt_desc.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_desc.FocusColor = true;
			this.txt_desc.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_27E7_0 = this.txt_desc;
			location = new global::System.Drawing.Point(1241, 111);
			arg_27E7_0.Location = location;
			this.txt_desc.Name = "txt_desc";
			this.txt_desc.Nullable = true;
			this.txt_desc.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_desc.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2840_0 = this.txt_desc;
			size = new global::System.Drawing.Size(197, 36);
			arg_2840_0.Size = size;
			this.txt_desc.TabIndex = 7;
			this.txt_desc.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_28B7_0 = this.txt_num;
			location = new global::System.Drawing.Point(1241, 6);
			arg_28B7_0.Location = location;
			global::System.Windows.Forms.Control arg_28D1_0 = this.txt_num;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			arg_28D1_0.Margin = margin;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_28FF_0 = this.txt_num;
			size = new global::System.Drawing.Size(197, 36);
			arg_28FF_0.Size = size;
			this.txt_num.TabIndex = 0;
			this.txt_num.Value = "";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1568, 682);
			this.ClientSize = size;
			this.Controls.Add(this.RibbonStatusBar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.Bar1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Varedat";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "واردات";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000FBD RID: 4029
		private global::System.ComponentModel.IContainer components;
	}
}
