namespace FruitBox
{
	// Token: 0x020000ED RID: 237
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Ersal_Bar : global::System.Windows.Forms.Form
	{
		// Token: 0x0600191C RID: 6428 RVA: 0x0011A7BC File Offset: 0x001189BC
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600191D RID: 6429 RVA: 0x0011A80C File Offset: 0x00118A0C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column0.ButtonImage");
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Ersal_Bar));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference2 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column1.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference3 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column2.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference4 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column14.ButtonImage");
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem11 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem14 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem6 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem13 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem4 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem10 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem5 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem7 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem12 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem15 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem16 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem17 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem18 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem19 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem1 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem8 = new global::DevComponents.DotNetBar.ButtonItem();
			this.LabelItem2 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem3 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem4 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem5 = new global::DevComponents.DotNetBar.LabelItem();
			this.LabelItem6 = new global::DevComponents.DotNetBar.LabelItem();
			this.ButtonItem9 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ControlContainerItem1 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.MicroChartItem1 = new global::DevComponents.DotNetBar.MicroChartItem();
			this.ItemContainer2 = new global::DevComponents.DotNetBar.ItemContainer();
			this.ControlContainerItem2 = new global::DevComponents.DotNetBar.ControlContainerItem();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand6 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand8 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand2 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand4 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.txt_safi = new global::FruitBox.CurrencyBox(this.components);
			this.txt_keraye = new global::FruitBox.CurrencyBox(this.components);
			this.txt_rizbar = new global::FruitBox.CurrencyBox(this.components);
			this.txt_daramad = new global::FruitBox.CurrencyBox(this.components);
			this.txt_keraye_mabda = new global::FruitBox.CurrencyBox(this.components);
			this.txt_safikol = new global::FruitBox.CurrencyBox(this.components);
			this.txt_makharej = new global::FruitBox.CurrencyBox(this.components);
			this.txt_tarikhGrid = new global::FruitBox.DateBox2(this.components);
			this.Grid_RizBar = new global::FruitBox.DataEntryGrid(this.components);
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.txt_jam_kol = new global::FruitBox.CurrencyBox(this.components);
			this.txt_fee = new global::FruitBox.CurrencyBox(this.components);
			this.txt_desc = new global::FruitBox.EditBox(this.components);
			this.txt_sh_mashin = new global::FruitBox.EditBox(this.components);
			this.txt_baskul_mabda = new global::FruitBox.NumericBox(this.components);
			this.txt_baskul = new global::FruitBox.NumericBox(this.components);
			this.txt_tedad = new global::FruitBox.NumericBox(this.components);
			this.txt_sh_barname = new global::FruitBox.EditBox(this.components);
			this.txt_tarikh_vurud = new global::FruitBox.DateBox2(this.components);
			this.txt_moshtari = new global::FruitBox.SelectItem(this.components);
			this.txt_num = new global::FruitBox.NavBox();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			this.SuspendLayout();
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_safi);
			this.UiGroupBox1.Controls.Add(this.txt_keraye);
			this.UiGroupBox1.Controls.Add(this.txt_rizbar);
			this.UiGroupBox1.Controls.Add(this.txt_daramad);
			this.UiGroupBox1.Controls.Add(this.txt_keraye_mabda);
			this.UiGroupBox1.Controls.Add(this.txt_safikol);
			this.UiGroupBox1.Controls.Add(this.txt_makharej);
			this.UiGroupBox1.Controls.Add(this.Label14);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label8);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.txt_tarikhGrid);
			this.UiGroupBox1.Controls.Add(this.Grid_RizBar);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.txt_jam_kol);
			this.UiGroupBox1.Controls.Add(this.txt_fee);
			this.UiGroupBox1.Controls.Add(this.txt_desc);
			this.UiGroupBox1.Controls.Add(this.txt_sh_mashin);
			this.UiGroupBox1.Controls.Add(this.txt_baskul_mabda);
			this.UiGroupBox1.Controls.Add(this.txt_baskul);
			this.UiGroupBox1.Controls.Add(this.txt_tedad);
			this.UiGroupBox1.Controls.Add(this.txt_sh_barname);
			this.UiGroupBox1.Controls.Add(this.txt_tarikh_vurud);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Controls.Add(this.txt_num);
			this.UiGroupBox1.Controls.Add(this.Label12);
			this.UiGroupBox1.Controls.Add(this.Label13);
			this.UiGroupBox1.Controls.Add(this.Label11);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label10);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label9);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_839_0 = this.UiGroupBox1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 41);
			arg_839_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_877_0 = this.UiGroupBox1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(1561, 641);
			arg_877_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_8FC_0 = this.Label14;
			location = new global::System.Drawing.Point(945, 11);
			arg_8FC_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_927_0 = this.Label14;
			size = new global::System.Drawing.Size(43, 19);
			arg_927_0.Size = size;
			this.Label14.TabIndex = 25;
			this.Label14.Text = "درآمد";
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9B4_0 = this.Label2;
			location = new global::System.Drawing.Point(279, 257);
			arg_9B4_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_9DF_0 = this.Label2;
			size = new global::System.Drawing.Size(46, 19);
			arg_9DF_0.Size = size;
			this.Label2.TabIndex = 25;
			this.Label2.Text = "ریز بار";
			this.Label2.Visible = false;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_A79_0 = this.Label8;
			location = new global::System.Drawing.Point(1147, 185);
			arg_A79_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_AA4_0 = this.Label8;
			size = new global::System.Drawing.Size(74, 19);
			arg_AA4_0.Size = size;
			this.Label8.TabIndex = 25;
			this.Label8.Text = "صافی کل";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_B2E_0 = this.Label3;
			location = new global::System.Drawing.Point(1147, 85);
			arg_B2E_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_B59_0 = this.Label3;
			size = new global::System.Drawing.Size(98, 19);
			arg_B59_0.Size = size;
			this.Label3.TabIndex = 25;
			this.Label3.Text = "کرایه و مخارج";
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_BBB_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 615);
			arg_BBB_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			global::System.Windows.Forms.Control arg_BE9_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(1561, 26);
			arg_BE9_0.Size = size;
			this.UiGroupBox2.TabIndex = 24;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C72_0 = this.Label12;
			location = new global::System.Drawing.Point(1448, 189);
			arg_C72_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_C9D_0 = this.Label12;
			size = new global::System.Drawing.Size(69, 19);
			arg_C9D_0.Size = size;
			this.Label12.TabIndex = 0;
			this.Label12.Text = "ملاحضات";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_D26_0 = this.Label13;
			location = new global::System.Drawing.Point(1147, 51);
			arg_D26_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_D51_0 = this.Label13;
			size = new global::System.Drawing.Size(73, 19);
			arg_D51_0.Size = size;
			this.Label13.TabIndex = 0;
			this.Label13.Text = "کرایه مبدا";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DDD_0 = this.Label11;
			location = new global::System.Drawing.Point(1448, 154);
			arg_DDD_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_E08_0 = this.Label11;
			size = new global::System.Drawing.Size(91, 19);
			arg_E08_0.Size = size;
			this.Label11.TabIndex = 0;
			this.Label11.Text = "تاریخ ورود بار";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_E91_0 = this.Label7;
			location = new global::System.Drawing.Point(1147, 16);
			arg_E91_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_EBC_0 = this.Label7;
			size = new global::System.Drawing.Size(92, 19);
			arg_EBC_0.Size = size;
			this.Label7.TabIndex = 0;
			this.Label7.Text = "باسکول مبدا";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F45_0 = this.Label10;
			location = new global::System.Drawing.Point(1448, 119);
			arg_F45_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_F70_0 = this.Label10;
			size = new global::System.Drawing.Size(100, 19);
			arg_F70_0.Size = size;
			this.Label10.TabIndex = 0;
			this.Label10.Text = "شماره بارنامه";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_FF9_0 = this.Label4;
			location = new global::System.Drawing.Point(1147, 120);
			arg_FF9_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1024_0 = this.Label4;
			size = new global::System.Drawing.Size(60, 19);
			arg_1024_0.Size = size;
			this.Label4.TabIndex = 0;
			this.Label4.Text = "باسکول";
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10B0_0 = this.Label6;
			location = new global::System.Drawing.Point(1147, 154);
			arg_10B0_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_10DB_0 = this.Label6;
			size = new global::System.Drawing.Size(66, 19);
			arg_10DB_0.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "تعداد کل";
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1164_0 = this.Label9;
			location = new global::System.Drawing.Point(1448, 85);
			arg_1164_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_118F_0 = this.Label9;
			size = new global::System.Drawing.Size(106, 19);
			arg_118F_0.Size = size;
			this.Label9.TabIndex = 0;
			this.Label9.Text = "شماره ماشین";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1225_0 = this.Label5;
			location = new global::System.Drawing.Point(1448, 49);
			arg_1225_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_1250_0 = this.Label5;
			size = new global::System.Drawing.Size(71, 19);
			arg_1250_0.Size = size;
			this.Label5.TabIndex = 0;
			this.Label5.Text = "گیرنده بار";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12E7_0 = this.Label1;
			location = new global::System.Drawing.Point(1448, 16);
			arg_12E7_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_1312_0 = this.Label1;
			size = new global::System.Drawing.Size(90, 19);
			arg_1312_0.Size = size;
			this.Label1.TabIndex = 0;
			this.Label1.Text = "شماره سند";
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem11,
				this.ButtonItem14,
				this.ButtonItem6,
				this.ButtonItem13,
				this.ButtonItem4,
				this.ButtonItem10,
				this.ButtonItem5,
				this.ButtonItem7,
				this.ButtonItem3,
				this.ButtonItem12,
				this.ButtonItem15
			});
			global::DevComponents.DotNetBar.Bar arg_142F_0 = this.Bar1;
			location = new global::System.Drawing.Point(0, 0);
			arg_142F_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_145D_0 = this.Bar1;
			size = new global::System.Drawing.Size(1561, 41);
			arg_145D_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 12;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.document;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.save;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem11.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem11.Image = global::FruitBox.My.Resources.Resources.list1;
			this.ButtonItem11.Name = "ButtonItem11";
			this.ButtonItem11.Text = "صورتحساب (F3)";
			this.ButtonItem14.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem14.Image = global::FruitBox.My.Resources.Resources.print1;
			this.ButtonItem14.Name = "ButtonItem14";
			this.ButtonItem14.Text = "چاپ (F4)";
			this.ButtonItem6.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem6.Image = global::FruitBox.My.Resources.Resources.trash_bin;
			this.ButtonItem6.Name = "ButtonItem6";
			this.ButtonItem6.Text = "حذف ردیف (F5)";
			this.ButtonItem13.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem13.Image = global::FruitBox.My.Resources.Resources.report_open_edit;
			this.ButtonItem13.Name = "ButtonItem13";
			this.ButtonItem13.Text = "ویرایش بارنامه (F6)";
			this.ButtonItem4.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem4.Image = global::FruitBox.My.Resources.Resources.transport_table;
			this.ButtonItem4.Name = "ButtonItem4";
			this.ButtonItem4.Text = "ثبت ریز بار (F7)";
			this.ButtonItem10.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem10.Image = global::FruitBox.My.Resources.Resources.order_coins;
			this.ButtonItem10.Name = "ButtonItem10";
			this.ButtonItem10.Text = "کرایه و مخارج (F8)";
			this.ButtonItem5.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem5.Image = global::FruitBox.My.Resources.Resources.order;
			this.ButtonItem5.Name = "ButtonItem5";
			this.ButtonItem5.Text = "ثبت صافی بار (F9)";
			this.ButtonItem5.Visible = false;
			this.ButtonItem7.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem7.Image = global::FruitBox.My.Resources.Resources.report_open_edit;
			this.ButtonItem7.Name = "ButtonItem7";
			this.ButtonItem7.Text = "اصلاح اطلاعات (F10)";
			this.ButtonItem7.Visible = false;
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف سند (Ctrl + F5)";
			this.ButtonItem12.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem12.Image = global::FruitBox.My.Resources.Resources.relations_remove;
			this.ButtonItem12.Name = "ButtonItem12";
			this.ButtonItem12.Text = "کسر اتوماتیک";
			this.ButtonItem12.Visible = false;
			this.ButtonItem15.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem15.Image = global::FruitBox.My.Resources.Resources.table;
			this.ButtonItem15.Name = "ButtonItem15";
			this.ButtonItem15.SubItems.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem16,
				this.ButtonItem17,
				this.ButtonItem18,
				this.ButtonItem19
			});
			this.ButtonItem15.Text = "نحوه فروش";
			this.ButtonItem16.Name = "ButtonItem16";
			this.ButtonItem16.Text = "تعداد - وزن خالص";
			this.ButtonItem17.Name = "ButtonItem17";
			this.ButtonItem17.Text = "وزن خالص";
			this.ButtonItem18.Name = "ButtonItem18";
			this.ButtonItem18.Text = "تعداد";
			this.ButtonItem19.Name = "ButtonItem19";
			this.ButtonItem19.Text = "تعداد - وزن با ظرف - ظرف - وزن خالص";
			this.LabelItem1.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem1.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem1.Name = "LabelItem1";
			this.LabelItem1.Text = "وضعیت مشتری";
			this.ButtonItem8.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.TextOnlyAlways;
			global::DevComponents.DotNetBar.ButtonItem arg_1957_0 = this.ButtonItem8;
			size = new global::System.Drawing.Size(150, 0);
			arg_1957_0.FixedSize = size;
			this.ButtonItem8.ItemAlignment = global::DevComponents.DotNetBar.eItemAlignment.Center;
			this.ButtonItem8.Name = "ButtonItem8";
			this.ButtonItem8.Text = "0";
			this.LabelItem2.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem2.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem2.Name = "LabelItem2";
			this.LabelItem2.Text = "         بدهکار";
			this.LabelItem3.BackColor = global::System.Drawing.Color.Transparent;
			this.LabelItem3.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem3.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem3.Name = "LabelItem3";
			this.LabelItem3.Text = "        آخرین پرداختی";
			this.LabelItem4.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem4.Name = "LabelItem4";
			this.LabelItem4.Text = "000";
			this.LabelItem5.Font = new global::System.Drawing.Font("Tahoma", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.LabelItem5.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem5.Name = "LabelItem5";
			this.LabelItem5.Text = "        تاریخ آخرین پرداختی";
			this.LabelItem6.ForeColor = global::System.Drawing.Color.White;
			this.LabelItem6.Name = "LabelItem6";
			this.LabelItem6.Text = "1393/05/05";
			this.ButtonItem9.Name = "ButtonItem9";
			this.ButtonItem9.Text = "صورتحساب";
			this.ControlContainerItem1.AllowItemResize = false;
			this.ControlContainerItem1.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem1.Name = "ControlContainerItem1";
			this.MicroChartItem1.Name = "MicroChartItem1";
			this.ItemContainer2.BackgroundStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ItemContainer2.Name = "ItemContainer2";
			this.ItemContainer2.TitleStyle.CornerType = global::DevComponents.DotNetBar.eCornerType.Square;
			this.ControlContainerItem2.AllowItemResize = true;
			this.ControlContainerItem2.MenuVisibility = global::DevComponents.DotNetBar.eMenuVisibility.VisibleAlways;
			this.ControlContainerItem2.Name = "ControlContainerItem2";
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand5,
				this.LabelCommand6,
				this.LabelCommand7,
				this.LabelCommand8
			});
			global::System.Windows.Forms.Control arg_1C3F_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 656);
			arg_1C3F_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand1,
				this.LabelCommand2,
				this.LabelCommand3,
				this.LabelCommand4
			});
			global::System.Windows.Forms.Control arg_1CB4_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(1561, 26);
			arg_1CB4_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 25;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.LabelCommand5.Key = "LabelCommand5";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand6.Key = "LabelCommand6";
			this.LabelCommand6.Name = "LabelCommand6";
			this.LabelCommand6.Text = "جمع نسیه";
			this.LabelCommand7.Key = "LabelCommand7";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand8.Key = "LabelCommand8";
			this.LabelCommand8.Name = "LabelCommand8";
			this.LabelCommand8.Text = "جمع نقد";
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.LabelCommand2.Key = "LabelCommand2";
			this.LabelCommand2.Name = "LabelCommand2";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand4.Key = "LabelCommand4";
			this.LabelCommand4.Name = "LabelCommand4";
			this.txt_safi.AcceptEnter = false;
			this.txt_safi.AllowEdit = true;
			this.txt_safi.AllowNew = true;
			this.txt_safi.AllowZero = true;
			this.txt_safi.FocusColor = false;
			global::System.Windows.Forms.Control arg_1E98_0 = this.txt_safi;
			location = new global::System.Drawing.Point(12, 316);
			arg_1E98_0.Location = location;
			this.txt_safi.Name = "txt_safi";
			this.txt_safi.Nullable = true;
			this.txt_safi.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_safi.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1EEE_0 = this.txt_safi;
			size = new global::System.Drawing.Size(100, 21);
			arg_1EEE_0.Size = size;
			this.txt_safi.TabIndex = 27;
			this.txt_safi.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_safi.Value = value;
			this.txt_safi.Visible = false;
			this.txt_safi.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_keraye.AcceptEnter = false;
			this.txt_keraye.AllowEdit = true;
			this.txt_keraye.AllowNew = true;
			this.txt_keraye.AllowZero = true;
			this.txt_keraye.FocusColor = false;
			global::System.Windows.Forms.Control arg_1F8F_0 = this.txt_keraye;
			location = new global::System.Drawing.Point(12, 289);
			arg_1F8F_0.Location = location;
			this.txt_keraye.Name = "txt_keraye";
			this.txt_keraye.Nullable = true;
			this.txt_keraye.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_keraye.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1FE5_0 = this.txt_keraye;
			size = new global::System.Drawing.Size(100, 21);
			arg_1FE5_0.Size = size;
			this.txt_keraye.TabIndex = 26;
			this.txt_keraye.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_keraye.Value = value;
			this.txt_keraye.Visible = false;
			this.txt_keraye.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_rizbar.AcceptEnter = true;
			this.txt_rizbar.AllowEdit = false;
			this.txt_rizbar.AllowNew = true;
			this.txt_rizbar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_rizbar.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_rizbar.ButtonText = "...";
			this.txt_rizbar.FocusColor = true;
			this.txt_rizbar.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20CA_0 = this.txt_rizbar;
			location = new global::System.Drawing.Point(133, 247);
			arg_20CA_0.Location = location;
			this.txt_rizbar.Name = "txt_rizbar";
			this.txt_rizbar.Nullable = true;
			this.txt_rizbar.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_rizbar.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_rizbar.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2130_0 = this.txt_rizbar;
			size = new global::System.Drawing.Size(144, 36);
			arg_2130_0.Size = size;
			this.txt_rizbar.TabIndex = 5;
			this.txt_rizbar.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_rizbar.Value = value;
			this.txt_rizbar.Visible = false;
			this.txt_rizbar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_daramad.AcceptEnter = true;
			this.txt_daramad.AllowEdit = false;
			this.txt_daramad.AllowNew = true;
			this.txt_daramad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_daramad.ButtonText = "...";
			this.txt_daramad.FocusColor = true;
			this.txt_daramad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2203_0 = this.txt_daramad;
			location = new global::System.Drawing.Point(764, 6);
			arg_2203_0.Location = location;
			this.txt_daramad.Name = "txt_daramad";
			this.txt_daramad.Nullable = true;
			this.txt_daramad.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_daramad.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_daramad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2269_0 = this.txt_daramad;
			size = new global::System.Drawing.Size(179, 36);
			arg_2269_0.Size = size;
			this.txt_daramad.TabIndex = 10;
			this.txt_daramad.TabStop = false;
			this.txt_daramad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_daramad.Value = value;
			this.txt_daramad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_keraye_mabda.AcceptEnter = true;
			this.txt_keraye_mabda.AllowEdit = true;
			this.txt_keraye_mabda.AllowNew = true;
			this.txt_keraye_mabda.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_keraye_mabda.ButtonText = "...";
			this.txt_keraye_mabda.FocusColor = true;
			this.txt_keraye_mabda.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_233E_0 = this.txt_keraye_mabda;
			location = new global::System.Drawing.Point(1001, 41);
			arg_233E_0.Location = location;
			this.txt_keraye_mabda.Name = "txt_keraye_mabda";
			this.txt_keraye_mabda.Nullable = true;
			this.txt_keraye_mabda.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_keraye_mabda.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_keraye_mabda.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_23A4_0 = this.txt_keraye_mabda;
			size = new global::System.Drawing.Size(144, 36);
			arg_23A4_0.Size = size;
			this.txt_keraye_mabda.TabIndex = 7;
			this.txt_keraye_mabda.TabStop = false;
			this.txt_keraye_mabda.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_keraye_mabda.Value = value;
			this.txt_keraye_mabda.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_safikol.AcceptEnter = true;
			this.txt_safikol.AllowEdit = true;
			this.txt_safikol.AllowNew = true;
			this.txt_safikol.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_safikol.ButtonText = "...";
			this.txt_safikol.FocusColor = true;
			this.txt_safikol.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_247B_0 = this.txt_safikol;
			location = new global::System.Drawing.Point(1001, 180);
			arg_247B_0.Location = location;
			this.txt_safikol.Name = "txt_safikol";
			this.txt_safikol.Nullable = true;
			this.txt_safikol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_safikol.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_safikol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_24E1_0 = this.txt_safikol;
			size = new global::System.Drawing.Size(144, 36);
			arg_24E1_0.Size = size;
			this.txt_safikol.TabIndex = 10;
			this.txt_safikol.TabStop = false;
			this.txt_safikol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_safikol.Value = value;
			this.txt_safikol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_makharej.AcceptEnter = true;
			this.txt_makharej.AllowEdit = false;
			this.txt_makharej.AllowNew = true;
			this.txt_makharej.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_makharej.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_makharej.ButtonText = "...";
			this.txt_makharej.FocusColor = true;
			this.txt_makharej.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_25C3_0 = this.txt_makharej;
			location = new global::System.Drawing.Point(1001, 76);
			arg_25C3_0.Location = location;
			this.txt_makharej.Name = "txt_makharej";
			this.txt_makharej.Nullable = true;
			this.txt_makharej.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_makharej.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_makharej.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2629_0 = this.txt_makharej;
			size = new global::System.Drawing.Size(144, 36);
			arg_2629_0.Size = size;
			this.txt_makharej.TabIndex = 8;
			this.txt_makharej.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_makharej.Value = value;
			this.txt_makharej.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikhGrid.AcceptEnter = false;
			this.txt_tarikhGrid.AllowEdit = true;
			this.txt_tarikhGrid.BorderStyle = global::Janus.Windows.GridEX.BorderStyle.None;
			this.txt_tarikhGrid.ButtonEnable = false;
			this.txt_tarikhGrid.ButtonEnabled = false;
			this.txt_tarikhGrid.FocusDatePart = 2;
			this.txt_tarikhGrid.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_26EB_0 = this.txt_tarikhGrid;
			location = new global::System.Drawing.Point(12, 139);
			arg_26EB_0.Location = location;
			this.txt_tarikhGrid.Mask = "0000/00/00";
			this.txt_tarikhGrid.Name = "txt_tarikhGrid";
			this.txt_tarikhGrid.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_2734_0 = this.txt_tarikhGrid;
			size = new global::System.Drawing.Size(100, 25);
			arg_2734_0.Size = size;
			this.txt_tarikhGrid.TabIndex = 22;
			this.txt_tarikhGrid.Text = "1393/05/28";
			this.txt_tarikhGrid.Visible = false;
			this.txt_tarikhGrid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Grid_RizBar.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.Grid_RizBar.AlternatingColors = true;
			this.Grid_RizBar.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.Grid_RizBar.AutoEdit = true;
			janusLayoutReference.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("Grid_RizBar_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference
			});
			gridEXLayout.LayoutString = componentResourceManager.GetString("Grid_RizBar_DesignTimeLayout.LayoutString");
			this.Grid_RizBar.DesignTimeLayout = gridEXLayout;
			this.Grid_RizBar.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.Grid_RizBar.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.Grid_RizBar.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.Grid_RizBar.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.Grid_RizBar.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_2866_0 = this.Grid_RizBar;
			location = new global::System.Drawing.Point(3, 6);
			arg_2866_0.Location = location;
			this.Grid_RizBar.Name = "Grid_RizBar";
			this.Grid_RizBar.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.Grid_RizBar.RowHeaderContent = global::Janus.Windows.GridEX.RowHeaderContent.RowIndex;
			global::System.Windows.Forms.Control arg_28B1_0 = this.Grid_RizBar;
			size = new global::System.Drawing.Size(635, 199);
			arg_28B1_0.Size = size;
			this.Grid_RizBar.TabIndex = 21;
			this.Grid_RizBar.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.Grid_RizBar.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.Grid_RizBar.Visible = false;
			this.Grid_RizBar.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridEX1.AcceptsEscape = false;
			this.GridEX1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			janusLayoutReference2.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference3.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_1.Instance"));
			janusLayoutReference4.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_2.Instance"));
			gridEXLayout2.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference2,
				janusLayoutReference3,
				janusLayoutReference4
			});
			gridEXLayout2.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout2;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_2A39_0 = this.GridEX1;
			location = new global::System.Drawing.Point(0, 223);
			arg_2A39_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_2A91_0 = this.GridEX1;
			size = new global::System.Drawing.Size(1561, 391);
			arg_2A91_0.Size = size;
			this.GridEX1.TabIndex = 13;
			this.GridEX1.TotalRow = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.TotalRowPosition = global::Janus.Windows.GridEX.TotalRowPosition.BottomFixed;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_jam_kol.AcceptEnter = false;
			this.txt_jam_kol.AllowEdit = true;
			this.txt_jam_kol.AllowNew = true;
			this.txt_jam_kol.AllowZero = true;
			this.txt_jam_kol.FocusColor = false;
			global::System.Windows.Forms.Control arg_2B72_0 = this.txt_jam_kol;
			location = new global::System.Drawing.Point(324, 271);
			arg_2B72_0.Location = location;
			this.txt_jam_kol.Name = "txt_jam_kol";
			this.txt_jam_kol.Nullable = true;
			this.txt_jam_kol.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_jam_kol.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2BC8_0 = this.txt_jam_kol;
			size = new global::System.Drawing.Size(100, 21);
			arg_2BC8_0.Size = size;
			this.txt_jam_kol.TabIndex = 14;
			this.txt_jam_kol.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_jam_kol.Value = value;
			this.txt_jam_kol.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_fee.AcceptEnter = true;
			this.txt_fee.AllowEdit = true;
			this.txt_fee.AllowNew = true;
			this.txt_fee.AllowZero = true;
			this.txt_fee.FocusColor = false;
			global::System.Windows.Forms.Control arg_2C5C_0 = this.txt_fee;
			location = new global::System.Drawing.Point(65, 262);
			arg_2C5C_0.Location = location;
			this.txt_fee.Name = "txt_fee";
			this.txt_fee.Nullable = true;
			this.txt_fee.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_fee.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2CB2_0 = this.txt_fee;
			size = new global::System.Drawing.Size(100, 21);
			arg_2CB2_0.Size = size;
			this.txt_fee.TabIndex = 13;
			this.txt_fee.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_fee.Value = value;
			this.txt_fee.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_desc.AcceptEnter = false;
			this.txt_desc.AllowEdit = true;
			this.txt_desc.AllowNew = true;
			this.txt_desc.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_desc.FocusColor = true;
			this.txt_desc.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2D6C_0 = this.txt_desc;
			location = new global::System.Drawing.Point(1249, 181);
			arg_2D6C_0.Location = location;
			this.txt_desc.Name = "txt_desc";
			this.txt_desc.Nullable = true;
			this.txt_desc.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_desc.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2DC5_0 = this.txt_desc;
			size = new global::System.Drawing.Size(197, 36);
			arg_2DC5_0.Size = size;
			this.txt_desc.TabIndex = 10;
			this.txt_desc.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sh_mashin.AcceptEnter = true;
			this.txt_sh_mashin.AllowEdit = true;
			this.txt_sh_mashin.AllowNew = true;
			this.txt_sh_mashin.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_mashin.FocusColor = true;
			this.txt_sh_mashin.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2E61_0 = this.txt_sh_mashin;
			location = new global::System.Drawing.Point(1249, 76);
			arg_2E61_0.Location = location;
			this.txt_sh_mashin.MaxLength = 9;
			this.txt_sh_mashin.Name = "txt_sh_mashin";
			this.txt_sh_mashin.Nullable = true;
			this.txt_sh_mashin.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sh_mashin.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2EC8_0 = this.txt_sh_mashin;
			size = new global::System.Drawing.Size(197, 36);
			arg_2EC8_0.Size = size;
			this.txt_sh_mashin.TabIndex = 2;
			this.txt_sh_mashin.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_baskul_mabda.AcceptEnter = true;
			this.txt_baskul_mabda.AllowEdit = true;
			this.txt_baskul_mabda.AllowNew = true;
			this.txt_baskul_mabda.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_baskul_mabda.FocusColor = true;
			this.txt_baskul_mabda.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2F62_0 = this.txt_baskul_mabda;
			location = new global::System.Drawing.Point(1001, 6);
			arg_2F62_0.Location = location;
			this.txt_baskul_mabda.Name = "txt_baskul_mabda";
			this.txt_baskul_mabda.Nullable = true;
			this.txt_baskul_mabda.NullToolTipText = "لطفا وزن باسکول را وارد نمائید";
			this.txt_baskul_mabda.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2FBB_0 = this.txt_baskul_mabda;
			size = new global::System.Drawing.Size(144, 36);
			arg_2FBB_0.Size = size;
			this.txt_baskul_mabda.TabIndex = 6;
			this.txt_baskul_mabda.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_baskul_mabda.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_baskul.AcceptEnter = true;
			this.txt_baskul.AllowEdit = true;
			this.txt_baskul.AllowNew = true;
			this.txt_baskul.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_baskul.DecimalDigits = 1;
			this.txt_baskul.FocusColor = true;
			this.txt_baskul.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3070_0 = this.txt_baskul;
			location = new global::System.Drawing.Point(1001, 111);
			arg_3070_0.Location = location;
			this.txt_baskul.Name = "txt_baskul";
			this.txt_baskul.Nullable = true;
			this.txt_baskul.NullToolTipText = "لطفا وزن باسکول را وارد نمائید";
			this.txt_baskul.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_30C9_0 = this.txt_baskul;
			size = new global::System.Drawing.Size(144, 36);
			arg_30C9_0.Size = size;
			this.txt_baskul.TabIndex = 7;
			this.txt_baskul.TabStop = false;
			this.txt_baskul.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_baskul.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tedad.AcceptEnter = true;
			this.txt_tedad.AllowEdit = true;
			this.txt_tedad.AllowNew = true;
			this.txt_tedad.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tedad.DecimalDigits = 1;
			this.txt_tedad.FocusColor = true;
			this.txt_tedad.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_318E_0 = this.txt_tedad;
			location = new global::System.Drawing.Point(1001, 146);
			arg_318E_0.Location = location;
			this.txt_tedad.Name = "txt_tedad";
			this.txt_tedad.Nullable = true;
			this.txt_tedad.NullToolTipText = "لطفا تعداد کل بار را مشخص فرمائید";
			this.txt_tedad.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_31E7_0 = this.txt_tedad;
			size = new global::System.Drawing.Size(144, 36);
			arg_31E7_0.Size = size;
			this.txt_tedad.TabIndex = 8;
			this.txt_tedad.TabStop = false;
			this.txt_tedad.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_tedad.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_sh_barname.AcceptEnter = true;
			this.txt_sh_barname.AllowEdit = true;
			this.txt_sh_barname.AllowNew = true;
			this.txt_sh_barname.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_sh_barname.FocusColor = true;
			this.txt_sh_barname.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_329C_0 = this.txt_sh_barname;
			location = new global::System.Drawing.Point(1249, 111);
			arg_329C_0.Location = location;
			this.txt_sh_barname.Name = "txt_sh_barname";
			this.txt_sh_barname.Nullable = true;
			this.txt_sh_barname.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_sh_barname.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_32F5_0 = this.txt_sh_barname;
			size = new global::System.Drawing.Size(197, 36);
			arg_32F5_0.Size = size;
			this.txt_sh_barname.TabIndex = 3;
			this.txt_sh_barname.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_tarikh_vurud.AcceptEnter = true;
			this.txt_tarikh_vurud.AllowEdit = true;
			this.txt_tarikh_vurud.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_tarikh_vurud.ButtonEnable = false;
			this.txt_tarikh_vurud.FocusDatePart = 2;
			this.txt_tarikh_vurud.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_3393_0 = this.txt_tarikh_vurud;
			location = new global::System.Drawing.Point(1249, 146);
			arg_3393_0.Location = location;
			this.txt_tarikh_vurud.Mask = "0000/00/00";
			this.txt_tarikh_vurud.Name = "txt_tarikh_vurud";
			this.txt_tarikh_vurud.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_33DF_0 = this.txt_tarikh_vurud;
			size = new global::System.Drawing.Size(197, 36);
			arg_33DF_0.Size = size;
			this.txt_tarikh_vurud.TabIndex = 4;
			this.txt_tarikh_vurud.Text = "1392/07/08";
			this.txt_tarikh_vurud.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari.AcceptEnter = true;
			this.txt_moshtari.AddNewForm = null;
			this.txt_moshtari.AllowEdit = true;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_moshtari.ButtonText = "...";
			this.txt_moshtari.CanEdit = true;
			this.txt_moshtari.DisplayMember = "Name";
			this.txt_moshtari.Edit_Frm = null;
			this.txt_moshtari.ExtraData = 0L;
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "shahr";
			column3.Size = 20;
			this.txt_moshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_357F_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(1249, 41);
			arg_357F_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = false;
			this.txt_moshtari.NullToolTipText = "لطفا صاحب بار را مشخص فرمائید";
			this.txt_moshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_moshtari.SelectCommand = componentResourceManager.GetString("txt_moshtari.SelectCommand");
			this.txt_moshtari.SelectedRow = null;
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_360A_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(197, 36);
			arg_360A_0.Size = size;
			this.txt_moshtari.TabIndex = 1;
			this.txt_moshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_moshtari.Value = null;
			this.txt_moshtari.ValueMember = "ID";
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_num.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_num.BackColor = global::System.Drawing.Color.Transparent;
			this.txt_num.Font = new global::System.Drawing.Font("Tahoma", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_36AC_0 = this.txt_num;
			location = new global::System.Drawing.Point(1249, 6);
			arg_36AC_0.Location = location;
			global::System.Windows.Forms.Control arg_36C6_0 = this.txt_num;
			global::System.Windows.Forms.Padding margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			arg_36C6_0.Margin = margin;
			this.txt_num.Name = "txt_num";
			global::System.Windows.Forms.Control arg_36F4_0 = this.txt_num;
			size = new global::System.Drawing.Size(197, 36);
			arg_36F4_0.Size = size;
			this.txt_num.TabIndex = 0;
			this.txt_num.Value = "";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1561, 682);
			this.ClientSize = size;
			this.Controls.Add(this.RibbonStatusBar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.Bar1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Ersal_Bar";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "باربارکنی";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Grid_RizBar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x040009CA RID: 2506
		private global::System.ComponentModel.IContainer components;
	}
}
