namespace FruitBox
{
	// Token: 0x02000065 RID: 101
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Coloring : global::System.Windows.Forms.Form
	{
		// Token: 0x06000718 RID: 1816 RVA: 0x0006C344 File Offset: 0x0006A544
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000719 RID: 1817 RVA: 0x0006C394 File Offset: 0x0006A594
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Coloring));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			this.ColorPickerButton1 = new global::DevComponents.DotNetBar.ColorPickerButton();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.SelectItem1 = new global::FruitBox.SelectItem(this.components);
			this.GridEX1 = new global::FruitBox.DataEntryGrid(this.components);
			this.NavBox1 = new global::FruitBox.NavBox();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.Bar1 = new global::DevComponents.DotNetBar.Bar();
			this.ButtonItem1 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem2 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ButtonItem3 = new global::DevComponents.DotNetBar.ButtonItem();
			this.ColorPickerButton2 = new global::DevComponents.DotNetBar.ColorPickerButton();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.ColorPickerButton3 = new global::DevComponents.DotNetBar.ColorPickerButton();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.UiButton3 = new global::Janus.Windows.EditControls.UIButton();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.ColorPickerButton4 = new global::DevComponents.DotNetBar.ColorPickerButton();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.EditBox1 = new global::FruitBox.EditBox(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).BeginInit();
			this.SuspendLayout();
			this.ColorPickerButton1.AccessibleRole = global::System.Windows.Forms.AccessibleRole.PushButton;
			this.ColorPickerButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.ColorPickerButton1.ColorTable = global::DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
			this.ColorPickerButton1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.ColorPickerButton1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ColorPickerButton1.Image");
			global::System.Windows.Forms.Control arg_1E4_0 = this.ColorPickerButton1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(1022, 54);
			arg_1E4_0.Location = location;
			this.ColorPickerButton1.Name = "ColorPickerButton1";
			this.ColorPickerButton1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::DevComponents.DotNetBar.ColorPickerButton arg_21E_0 = this.ColorPickerButton1;
			global::System.Drawing.Rectangle selectedColorImageRectangle = new global::System.Drawing.Rectangle(2, 2, 12, 12);
			arg_21E_0.SelectedColorImageRectangle = selectedColorImageRectangle;
			global::System.Windows.Forms.Control arg_238_0 = this.ColorPickerButton1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(48, 27);
			arg_238_0.Size = size;
			this.ColorPickerButton1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.ColorPickerButton1.TabIndex = 0;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_2AB_0 = this.Label1;
			location = new global::System.Drawing.Point(1076, 61);
			arg_2AB_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_2D9_0 = this.Label1;
			size = new global::System.Drawing.Size(134, 19);
			arg_2D9_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "رنگ زمینه Toolbar";
			this.UiGroupBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.SelectItem1);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.NavBox1);
			this.UiGroupBox1.Controls.Add(this.UiButton2);
			this.UiGroupBox1.Controls.Add(this.UiButton1);
			this.UiGroupBox1.Controls.Add(this.Bar1);
			global::System.Windows.Forms.Control arg_3B3_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 2);
			arg_3B3_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			global::System.Windows.Forms.Control arg_3E4_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(842, 531);
			arg_3E4_0.Size = size;
			this.UiGroupBox1.TabIndex = 2;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.SelectItem1.AcceptEnter = true;
			this.SelectItem1.AddNewForm = null;
			this.SelectItem1.AllowEdit = true;
			this.SelectItem1.AllowNew = true;
			this.SelectItem1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.SelectItem1.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.SelectItem1.ButtonText = "...";
			this.SelectItem1.CanEdit = false;
			this.SelectItem1.DisplayMember = null;
			this.SelectItem1.Edit_Frm = null;
			this.SelectItem1.ExtraData = 0L;
			this.SelectItem1.FocusColor = true;
			this.SelectItem1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_4E1_0 = this.SelectItem1;
			location = new global::System.Drawing.Point(239, 466);
			arg_4E1_0.Location = location;
			this.SelectItem1.Name = "SelectItem1";
			this.SelectItem1.Nullable = true;
			this.SelectItem1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.SelectItem1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.SelectItem1.SelectCommand = null;
			this.SelectItem1.SelectedRow = null;
			this.SelectItem1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_55E_0 = this.SelectItem1;
			size = new global::System.Drawing.Size(120, 36);
			arg_55E_0.Size = size;
			this.SelectItem1.TabIndex = 22;
			this.SelectItem1.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.SelectItem1.Value = null;
			this.SelectItem1.ValueMember = null;
			this.SelectItem1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridEX1.AllowEdit = global::Janus.Windows.GridEX.InheritableBoolean.False;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 10f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			global::System.Windows.Forms.Control arg_65B_0 = this.GridEX1;
			location = new global::System.Drawing.Point(6, 82);
			arg_65B_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			this.GridEX1.NewRowPosition = global::Janus.Windows.GridEX.NewRowPosition.BottomRow;
			this.GridEX1.OfficeColorScheme = global::Janus.Windows.GridEX.OfficeColorScheme.Blue;
			this.GridEX1.RowHeaders = global::Janus.Windows.GridEX.InheritableBoolean.True;
			global::System.Windows.Forms.Control arg_6B3_0 = this.GridEX1;
			size = new global::System.Drawing.Size(830, 378);
			arg_6B3_0.Size = size;
			this.GridEX1.TabIndex = 21;
			this.GridEX1.TotalRowFormatStyle.BackColor = global::System.Drawing.Color.AliceBlue;
			this.GridEX1.TotalRowFormatStyle.BackColorGradient = global::System.Drawing.Color.DarkTurquoise;
			this.GridEX1.TotalRowFormatStyle.BackgroundGradientMode = global::Janus.Windows.GridEX.BackgroundGradientMode.Vertical;
			this.GridEX1.UpdateMode = global::Janus.Windows.GridEX.UpdateMode.CellUpdate;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.NavBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.NavBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.NavBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_779_0 = this.NavBox1;
			location = new global::System.Drawing.Point(365, 474);
			arg_779_0.Location = location;
			this.NavBox1.Name = "NavBox1";
			global::System.Windows.Forms.Control arg_7A7_0 = this.NavBox1;
			size = new global::System.Drawing.Size(290, 28);
			arg_7A7_0.Size = size;
			this.NavBox1.TabIndex = 19;
			this.NavBox1.Value = "";
			this.UiButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_815_0 = this.UiButton2;
			location = new global::System.Drawing.Point(661, 467);
			arg_815_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			global::System.Windows.Forms.Control arg_840_0 = this.UiButton2;
			size = new global::System.Drawing.Size(75, 35);
			arg_840_0.Size = size;
			this.UiButton2.TabIndex = 17;
			this.UiButton2.Text = "انصراف";
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.UiButton1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_8BB_0 = this.UiButton1;
			location = new global::System.Drawing.Point(742, 467);
			arg_8BB_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			global::System.Windows.Forms.Control arg_8E6_0 = this.UiButton1;
			size = new global::System.Drawing.Size(75, 35);
			arg_8E6_0.Size = size;
			this.UiButton1.TabIndex = 17;
			this.UiButton1.Text = "تائید";
			this.UiButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.Bar1.AntiAlias = true;
			this.Bar1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Bar1.Font = new global::System.Drawing.Font("Tahoma", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Bar1.Items.AddRange(new global::DevComponents.DotNetBar.BaseItem[]
			{
				this.ButtonItem1,
				this.ButtonItem2,
				this.ButtonItem3
			});
			global::DevComponents.DotNetBar.Bar arg_99D_0 = this.Bar1;
			location = new global::System.Drawing.Point(3, 8);
			arg_99D_0.Location = location;
			this.Bar1.Name = "Bar1";
			global::DevComponents.DotNetBar.Bar arg_9CB_0 = this.Bar1;
			size = new global::System.Drawing.Size(836, 41);
			arg_9CB_0.Size = size;
			this.Bar1.Stretch = true;
			this.Bar1.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.Metro;
			this.Bar1.TabIndex = 16;
			this.Bar1.TabStop = false;
			this.Bar1.Text = "Bar1";
			this.ButtonItem1.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem1.Image = global::FruitBox.My.Resources.Resources.page;
			this.ButtonItem1.Name = "ButtonItem1";
			this.ButtonItem1.Text = "جدید (Ins)";
			this.ButtonItem2.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem2.Image = global::FruitBox.My.Resources.Resources.disk;
			this.ButtonItem2.Name = "ButtonItem2";
			this.ButtonItem2.Text = "ثبت (F2)";
			this.ButtonItem3.ButtonStyle = global::DevComponents.DotNetBar.eButtonStyle.ImageAndText;
			this.ButtonItem3.Image = global::FruitBox.My.Resources.Resources.bin_closed;
			this.ButtonItem3.Name = "ButtonItem3";
			this.ButtonItem3.Text = "حذف (F5)";
			this.ColorPickerButton2.AccessibleRole = global::System.Windows.Forms.AccessibleRole.PushButton;
			this.ColorPickerButton2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.ColorPickerButton2.ColorTable = global::DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
			this.ColorPickerButton2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.ColorPickerButton2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ColorPickerButton2.Image");
			global::System.Windows.Forms.Control arg_B54_0 = this.ColorPickerButton2;
			location = new global::System.Drawing.Point(1022, 87);
			arg_B54_0.Location = location;
			this.ColorPickerButton2.Name = "ColorPickerButton2";
			this.ColorPickerButton2.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::DevComponents.DotNetBar.ColorPickerButton arg_B8E_0 = this.ColorPickerButton2;
			selectedColorImageRectangle = new global::System.Drawing.Rectangle(2, 2, 12, 12);
			arg_B8E_0.SelectedColorImageRectangle = selectedColorImageRectangle;
			global::System.Windows.Forms.Control arg_BA8_0 = this.ColorPickerButton2;
			size = new global::System.Drawing.Size(48, 27);
			arg_BA8_0.Size = size;
			this.ColorPickerButton2.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.ColorPickerButton2.TabIndex = 0;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_C1B_0 = this.Label2;
			location = new global::System.Drawing.Point(1076, 95);
			arg_C1B_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_C46_0 = this.Label2;
			size = new global::System.Drawing.Size(74, 19);
			arg_C46_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "رنگ زمینه";
			this.ColorPickerButton3.AccessibleRole = global::System.Windows.Forms.AccessibleRole.PushButton;
			this.ColorPickerButton3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.ColorPickerButton3.ColorTable = global::DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
			this.ColorPickerButton3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.ColorPickerButton3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ColorPickerButton3.Image");
			global::System.Windows.Forms.Control arg_CE7_0 = this.ColorPickerButton3;
			location = new global::System.Drawing.Point(1022, 120);
			arg_CE7_0.Location = location;
			this.ColorPickerButton3.Name = "ColorPickerButton3";
			this.ColorPickerButton3.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::DevComponents.DotNetBar.ColorPickerButton arg_D21_0 = this.ColorPickerButton3;
			selectedColorImageRectangle = new global::System.Drawing.Rectangle(2, 2, 12, 12);
			arg_D21_0.SelectedColorImageRectangle = selectedColorImageRectangle;
			global::System.Windows.Forms.Control arg_D3B_0 = this.ColorPickerButton3;
			size = new global::System.Drawing.Size(48, 27);
			arg_D3B_0.Size = size;
			this.ColorPickerButton3.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.ColorPickerButton3.TabIndex = 0;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_DB1_0 = this.Label3;
			location = new global::System.Drawing.Point(1076, 128);
			arg_DB1_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_DDC_0 = this.Label3;
			size = new global::System.Drawing.Size(94, 19);
			arg_DDC_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "رنگ دکمه ها";
			this.UiButton3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.UiButton3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiButton3.Image = global::FruitBox.My.Resources.Resources.save;
			global::Janus.Windows.EditControls.UIButton arg_E55_0 = this.UiButton3;
			size = new global::System.Drawing.Size(32, 32);
			arg_E55_0.ImageSize = size;
			global::System.Windows.Forms.Control arg_E74_0 = this.UiButton3;
			location = new global::System.Drawing.Point(928, 195);
			arg_E74_0.Location = location;
			this.UiButton3.Name = "UiButton3";
			global::System.Windows.Forms.Control arg_EA2_0 = this.UiButton3;
			size = new global::System.Drawing.Size(142, 46);
			arg_EA2_0.Size = size;
			this.UiButton3.TabIndex = 3;
			this.UiButton3.Text = "ذخیره";
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F19_0 = this.Label10;
			location = new global::System.Drawing.Point(1076, 15);
			arg_F19_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_F44_0 = this.Label10;
			size = new global::System.Drawing.Size(114, 19);
			arg_F44_0.Size = size;
			this.Label10.TabIndex = 1;
			this.Label10.Text = "عنوان رنگ بندی";
			this.ColorPickerButton4.AccessibleRole = global::System.Windows.Forms.AccessibleRole.PushButton;
			this.ColorPickerButton4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.ColorPickerButton4.ColorTable = global::DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
			this.ColorPickerButton4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.ColorPickerButton4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ColorPickerButton4.Image");
			global::System.Windows.Forms.Control arg_FE8_0 = this.ColorPickerButton4;
			location = new global::System.Drawing.Point(1022, 153);
			arg_FE8_0.Location = location;
			this.ColorPickerButton4.Name = "ColorPickerButton4";
			this.ColorPickerButton4.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			global::DevComponents.DotNetBar.ColorPickerButton arg_1022_0 = this.ColorPickerButton4;
			selectedColorImageRectangle = new global::System.Drawing.Rectangle(2, 2, 12, 12);
			arg_1022_0.SelectedColorImageRectangle = selectedColorImageRectangle;
			global::System.Windows.Forms.Control arg_103C_0 = this.ColorPickerButton4;
			size = new global::System.Drawing.Size(48, 27);
			arg_103C_0.Size = size;
			this.ColorPickerButton4.Style = global::DevComponents.DotNetBar.eDotNetBarStyle.OfficeMobile2014;
			this.ColorPickerButton4.TabIndex = 0;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_10B2_0 = this.Label4;
			location = new global::System.Drawing.Point(1076, 161);
			arg_10B2_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_10DD_0 = this.Label4;
			size = new global::System.Drawing.Size(81, 19);
			arg_10DD_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "رنگ جدول ";
			this.EditBox1.AcceptEnter = true;
			this.EditBox1.AllowEdit = true;
			this.EditBox1.AllowNew = true;
			this.EditBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox1.FocusColor = true;
			this.EditBox1.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_117B_0 = this.EditBox1;
			location = new global::System.Drawing.Point(851, 10);
			arg_117B_0.Location = location;
			this.EditBox1.Name = "EditBox1";
			this.EditBox1.Nullable = true;
			this.EditBox1.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.EditBox1.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_11D4_0 = this.EditBox1;
			size = new global::System.Drawing.Size(218, 36);
			arg_11D4_0.Size = size;
			this.EditBox1.TabIndex = 5;
			this.EditBox1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1215, 562);
			this.ClientSize = size;
			this.Controls.Add(this.EditBox1);
			this.Controls.Add(this.UiButton3);
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.ColorPickerButton4);
			this.Controls.Add(this.ColorPickerButton3);
			this.Controls.Add(this.ColorPickerButton2);
			this.Controls.Add(this.ColorPickerButton1);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Coloring";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.Text = "تنظیمات رنگ بندی";
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Bar1).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040002B2 RID: 690
		private global::System.ComponentModel.IContainer components;
	}
}
