namespace FruitBox
{
	// Token: 0x020000E4 RID: 228
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Frm_Daryaft_AzMoshtari : global::System.Windows.Forms.Form
	{
		// Token: 0x06001524 RID: 5412 RVA: 0x000E457C File Offset: 0x000E277C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06001525 RID: 5413 RVA: 0x000E45CC File Offset: 0x000E27CC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column7.ButtonImage");
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::FruitBox.Frm_Daryaft_AzMoshtari));
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout2 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference2 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column4.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference3 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column5.ButtonImage");
			global::FruitBox.Column column = new global::FruitBox.Column();
			global::FruitBox.Column column2 = new global::FruitBox.Column();
			global::FruitBox.Column column3 = new global::FruitBox.Column();
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout3 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference4 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column4.ButtonImage");
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference5 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column5.ButtonImage");
			global::Janus.Windows.GridEX.GridEXLayout gridEXLayout4 = new global::Janus.Windows.GridEX.GridEXLayout();
			global::Janus.Windows.Common.Layouts.JanusLayoutReference janusLayoutReference6 = new global::Janus.Windows.Common.Layouts.JanusLayoutReference("GridEXLayoutData.RootTable.Columns.Column7.ButtonImage");
			this.GridEX1 = new global::Janus.Windows.GridEX.GridEX();
			this.GridEX2 = new global::Janus.Windows.GridEX.GridEX();
			this.UiGroupBox1 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_mablagh_BeMoshtari = new global::FruitBox.CurrencyBox(this.components);
			this.txt_moshtari = new global::FruitBox.EditBox(this.components);
			this.UiGroupBox2 = new global::Janus.Windows.EditControls.UIGroupBox();
			this.txt_beMoshtari = new global::FruitBox.SelectItem(this.components);
			this.txt_naghd = new global::FruitBox.CurrencyBox(this.components);
			this.EditBox2 = new global::FruitBox.EditBox(this.components);
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.GridEX3 = new global::Janus.Windows.GridEX.GridEX();
			this.UiButton2 = new global::Janus.Windows.EditControls.UIButton();
			this.GridEX4 = new global::Janus.Windows.GridEX.GridEX();
			this.DateBox21 = new global::FruitBox.DateBox2(this.components);
			this.txt_babat_kart = new global::FruitBox.EditBox(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.UiButton1 = new global::Janus.Windows.EditControls.UIButton();
			this.txt_tarikhGrid = new global::FruitBox.DateBox2(this.components);
			this.Highlighter1 = new global::DevComponents.DotNetBar.Validator.Highlighter();
			this.RibbonStatusBar1 = new global::Janus.Windows.Ribbon.RibbonStatusBar();
			this.LabelCommand1 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.lbl_jamcheck = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand3 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.lbl_jamkol = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand5 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.lbl_codem = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand7 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.lbl_name = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand9 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.LabelCommand10 = new global::Janus.Windows.Ribbon.LabelCommand();
			this.txt_mablagh = new global::FruitBox.CurrencyBox(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).BeginInit();
			this.UiGroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).BeginInit();
			this.UiGroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX4).BeginInit();
			this.SuspendLayout();
			this.GridEX1.AcceptsEscape = false;
			this.GridEX1.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX1.AlternatingColors = true;
			this.GridEX1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX1.AutoEdit = true;
			this.GridEX1.AutomaticSort = false;
			janusLayoutReference.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX1_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference
			});
			gridEXLayout.LayoutString = componentResourceManager.GetString("GridEX1_DesignTimeLayout.LayoutString");
			this.GridEX1.DesignTimeLayout = gridEXLayout;
			this.GridEX1.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX1.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX1.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX1.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX1.GroupByBoxVisible = false;
			this.Highlighter1.SetHighlightOnFocus(this.GridEX1, true);
			global::System.Windows.Forms.Control arg_450_0 = this.GridEX1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(7, 414);
			arg_450_0.Location = location;
			this.GridEX1.Name = "GridEX1";
			global::System.Windows.Forms.Control arg_481_0 = this.GridEX1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(655, 203);
			arg_481_0.Size = size;
			this.GridEX1.TabIndex = 5;
			this.GridEX1.Visible = false;
			this.GridEX1.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.GridEX2.AcceptsEscape = false;
			this.GridEX2.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX2.AlternatingColors = true;
			this.GridEX2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX2.AutoEdit = true;
			this.GridEX2.AutomaticSort = false;
			janusLayoutReference2.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX2_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference3.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX2_DesignTimeLayout_Reference_1.Instance"));
			gridEXLayout2.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference2,
				janusLayoutReference3
			});
			gridEXLayout2.LayoutString = componentResourceManager.GetString("GridEX2_DesignTimeLayout.LayoutString");
			this.GridEX2.DesignTimeLayout = gridEXLayout2;
			this.GridEX2.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX2.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX2.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX2.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX2.GroupByBoxVisible = false;
			this.Highlighter1.SetHighlightOnFocus(this.GridEX2, true);
			global::System.Windows.Forms.Control arg_5EE_0 = this.GridEX2;
			location = new global::System.Drawing.Point(7, 226);
			arg_5EE_0.Location = location;
			this.GridEX2.Name = "GridEX2";
			global::System.Windows.Forms.Control arg_61F_0 = this.GridEX2;
			size = new global::System.Drawing.Size(655, 182);
			arg_61F_0.Size = size;
			this.GridEX2.TabIndex = 4;
			this.GridEX2.Visible = false;
			this.GridEX2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox1.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox1.Controls.Add(this.txt_mablagh_BeMoshtari);
			this.UiGroupBox1.Controls.Add(this.txt_moshtari);
			this.UiGroupBox1.Controls.Add(this.UiGroupBox2);
			this.UiGroupBox1.Controls.Add(this.txt_babat_kart);
			this.UiGroupBox1.Controls.Add(this.Label2);
			this.UiGroupBox1.Controls.Add(this.Label6);
			this.UiGroupBox1.Controls.Add(this.Label5);
			this.UiGroupBox1.Controls.Add(this.Label4);
			this.UiGroupBox1.Controls.Add(this.Label7);
			this.UiGroupBox1.Controls.Add(this.Label3);
			this.UiGroupBox1.Controls.Add(this.Label1);
			this.UiGroupBox1.Controls.Add(this.GridEX2);
			this.UiGroupBox1.Controls.Add(this.UiButton1);
			this.UiGroupBox1.Controls.Add(this.GridEX1);
			this.UiGroupBox1.Controls.Add(this.txt_tarikhGrid);
			this.UiGroupBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox1.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_7DE_0 = this.UiGroupBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_7DE_0.Location = location;
			this.UiGroupBox1.Name = "UiGroupBox1";
			this.UiGroupBox1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_81C_0 = this.UiGroupBox1;
			size = new global::System.Drawing.Size(771, 184);
			arg_81C_0.Size = size;
			this.UiGroupBox1.TabIndex = 0;
			this.UiGroupBox1.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_mablagh_BeMoshtari.AcceptEnter = true;
			this.txt_mablagh_BeMoshtari.AllowEdit = true;
			this.txt_mablagh_BeMoshtari.AllowNew = true;
			this.txt_mablagh_BeMoshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_mablagh_BeMoshtari.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_mablagh_BeMoshtari.ButtonImage");
			this.txt_mablagh_BeMoshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_mablagh_BeMoshtari.FocusColor = true;
			this.txt_mablagh_BeMoshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_8E1_0 = this.txt_mablagh_BeMoshtari;
			location = new global::System.Drawing.Point(439, 96);
			arg_8E1_0.Location = location;
			this.txt_mablagh_BeMoshtari.Name = "txt_mablagh_BeMoshtari";
			this.txt_mablagh_BeMoshtari.Nullable = true;
			this.txt_mablagh_BeMoshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh_BeMoshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_mablagh_BeMoshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_947_0 = this.txt_mablagh_BeMoshtari;
			size = new global::System.Drawing.Size(223, 36);
			arg_947_0.Size = size;
			this.txt_mablagh_BeMoshtari.TabIndex = 1;
			this.txt_mablagh_BeMoshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			long? value;
			this.txt_mablagh_BeMoshtari.Value = value;
			this.txt_mablagh_BeMoshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_moshtari.AcceptEnter = true;
			this.txt_moshtari.AllowEdit = false;
			this.txt_moshtari.AllowNew = true;
			this.txt_moshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_moshtari.FocusColor = true;
			this.txt_moshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_9FD_0 = this.txt_moshtari;
			location = new global::System.Drawing.Point(439, 12);
			arg_9FD_0.Location = location;
			this.txt_moshtari.Name = "txt_moshtari";
			this.txt_moshtari.Nullable = true;
			this.txt_moshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_moshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_A56_0 = this.txt_moshtari;
			size = new global::System.Drawing.Size(223, 36);
			arg_A56_0.Size = size;
			this.txt_moshtari.TabIndex = 26;
			this.txt_moshtari.TabStop = false;
			this.txt_moshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiGroupBox2.BackgroundStyle = global::Janus.Windows.EditControls.BackgroundStyle.Panel;
			this.UiGroupBox2.Controls.Add(this.txt_beMoshtari);
			this.UiGroupBox2.Controls.Add(this.txt_naghd);
			this.UiGroupBox2.Controls.Add(this.EditBox2);
			this.UiGroupBox2.Controls.Add(this.Label8);
			this.UiGroupBox2.Controls.Add(this.Label9);
			this.UiGroupBox2.Controls.Add(this.Label10);
			this.UiGroupBox2.Controls.Add(this.Label11);
			this.UiGroupBox2.Controls.Add(this.Label12);
			this.UiGroupBox2.Controls.Add(this.Label13);
			this.UiGroupBox2.Controls.Add(this.Label14);
			this.UiGroupBox2.Controls.Add(this.GridEX3);
			this.UiGroupBox2.Controls.Add(this.UiButton2);
			this.UiGroupBox2.Controls.Add(this.GridEX4);
			this.UiGroupBox2.Controls.Add(this.DateBox21);
			this.UiGroupBox2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.UiGroupBox2.FrameStyle = global::Janus.Windows.EditControls.FrameStyle.None;
			global::System.Windows.Forms.Control arg_BFF_0 = this.UiGroupBox2;
			location = new global::System.Drawing.Point(0, 0);
			arg_BFF_0.Location = location;
			this.UiGroupBox2.Name = "UiGroupBox2";
			this.UiGroupBox2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Blue;
			global::System.Windows.Forms.Control arg_C3D_0 = this.UiGroupBox2;
			size = new global::System.Drawing.Size(771, 184);
			arg_C3D_0.Size = size;
			this.UiGroupBox2.TabIndex = 27;
			this.UiGroupBox2.VisualStyle = global::Janus.Windows.UI.Dock.PanelVisualStyle.Office2010;
			this.txt_beMoshtari.AcceptEnter = false;
			this.txt_beMoshtari.AddNewForm = null;
			this.txt_beMoshtari.AllowEdit = true;
			this.txt_beMoshtari.AllowNew = true;
			this.txt_beMoshtari.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_beMoshtari.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.TextButton;
			this.txt_beMoshtari.ButtonText = "...";
			this.txt_beMoshtari.CanEdit = true;
			this.txt_beMoshtari.DisplayMember = "Name";
			this.txt_beMoshtari.Edit_Frm = null;
			this.txt_beMoshtari.ExtraData = 0L;
			this.txt_beMoshtari.FocusColor = true;
			this.txt_beMoshtari.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			column.Caption = "کد مشتری";
			column.Name = "ID";
			column.Size = 15;
			column2.Caption = "مشتری";
			column2.Name = "Name";
			column2.Size = 65;
			column3.Caption = "منطقه";
			column3.Name = "Shahr";
			column3.Size = 20;
			this.txt_beMoshtari.Items.AddRange(new global::FruitBox.Column[]
			{
				column,
				column2,
				column3
			});
			global::System.Windows.Forms.Control arg_DCA_0 = this.txt_beMoshtari;
			location = new global::System.Drawing.Point(27, 96);
			arg_DCA_0.Location = location;
			this.txt_beMoshtari.Name = "txt_beMoshtari";
			this.txt_beMoshtari.Nullable = true;
			this.txt_beMoshtari.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_beMoshtari.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.txt_beMoshtari.SelectCommand = componentResourceManager.GetString("txt_beMoshtari.SelectCommand");
			this.txt_beMoshtari.SelectedRow = null;
			this.txt_beMoshtari.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_E55_0 = this.txt_beMoshtari;
			size = new global::System.Drawing.Size(317, 36);
			arg_E55_0.Size = size;
			this.txt_beMoshtari.TabIndex = 28;
			this.txt_beMoshtari.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_beMoshtari.Value = null;
			this.txt_beMoshtari.ValueMember = "ID";
			this.txt_beMoshtari.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_naghd.AcceptEnter = true;
			this.txt_naghd.AllowEdit = true;
			this.txt_naghd.AllowNew = true;
			this.txt_naghd.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_naghd.ButtonImage = (global::System.Drawing.Image)componentResourceManager.GetObject("txt_naghd.ButtonImage");
			this.txt_naghd.ButtonStyle = global::Janus.Windows.GridEX.EditControls.EditButtonStyle.Image;
			this.txt_naghd.FocusColor = true;
			this.txt_naghd.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_F46_0 = this.txt_naghd;
			location = new global::System.Drawing.Point(439, 54);
			arg_F46_0.Location = location;
			this.txt_naghd.Name = "txt_naghd";
			this.txt_naghd.Nullable = true;
			this.txt_naghd.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_naghd.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.txt_naghd.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_FAC_0 = this.txt_naghd;
			size = new global::System.Drawing.Size(223, 36);
			arg_FAC_0.Size = size;
			this.txt_naghd.TabIndex = 27;
			this.txt_naghd.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_naghd.Value = value;
			this.txt_naghd.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.EditBox2.AcceptEnter = true;
			this.EditBox2.AllowEdit = true;
			this.EditBox2.AllowNew = true;
			this.EditBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.EditBox2.FocusColor = true;
			this.EditBox2.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1063_0 = this.EditBox2;
			location = new global::System.Drawing.Point(-150, 54);
			arg_1063_0.Location = location;
			this.EditBox2.Name = "EditBox2";
			this.EditBox2.Nullable = true;
			this.EditBox2.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.EditBox2.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_10BC_0 = this.EditBox2;
			size = new global::System.Drawing.Size(176, 36);
			arg_10BC_0.Size = size;
			this.EditBox2.TabIndex = 3;
			this.EditBox2.Visible = false;
			this.EditBox2.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1151_0 = this.Label8;
			location = new global::System.Drawing.Point(681, 298);
			arg_1151_0.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control arg_117C_0 = this.Label8;
			size = new global::System.Drawing.Size(78, 19);
			arg_117C_0.Size = size;
			this.Label8.TabIndex = 1;
			this.Label8.Text = "دسته چک";
			this.Label8.Visible = false;
			this.Label9.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_120F_0 = this.Label9;
			location = new global::System.Drawing.Point(27, 63);
			arg_120F_0.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control arg_123A_0 = this.Label9;
			size = new global::System.Drawing.Size(105, 19);
			arg_123A_0.Size = size;
			this.Label9.TabIndex = 1;
			this.Label9.Text = "شماره پیگیری";
			this.Label9.Visible = false;
			this.Label10.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_12D0_0 = this.Label10;
			location = new global::System.Drawing.Point(346, 105);
			arg_12D0_0.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control arg_12FB_0 = this.Label10;
			size = new global::System.Drawing.Size(79, 19);
			arg_12FB_0.Size = size;
			this.Label10.TabIndex = 1;
			this.Label10.Text = "به مشتری";
			this.Label11.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1384_0 = this.Label11;
			location = new global::System.Drawing.Point(665, 105);
			arg_1384_0.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control arg_13AF_0 = this.Label11;
			size = new global::System.Drawing.Size(38, 19);
			arg_13AF_0.Size = size;
			this.Label11.TabIndex = 1;
			this.Label11.Text = "مبلغ";
			this.Label12.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1438_0 = this.Label12;
			location = new global::System.Drawing.Point(664, 17);
			arg_1438_0.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control arg_1463_0 = this.Label12;
			size = new global::System.Drawing.Size(61, 19);
			arg_1463_0.Size = size;
			this.Label12.TabIndex = 1;
			this.Label12.Text = "مشتری";
			this.Label13.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_14EC_0 = this.Label13;
			location = new global::System.Drawing.Point(664, 64);
			arg_14EC_0.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control arg_1517_0 = this.Label13;
			size = new global::System.Drawing.Size(64, 19);
			arg_1517_0.Size = size;
			this.Label13.TabIndex = 1;
			this.Label13.Text = "مبلغ نقد";
			this.Label14.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_15A3_0 = this.Label14;
			location = new global::System.Drawing.Point(667, 485);
			arg_15A3_0.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control arg_15CE_0 = this.Label14;
			size = new global::System.Drawing.Size(92, 19);
			arg_15CE_0.Size = size;
			this.Label14.TabIndex = 1;
			this.Label14.Text = "چک مشتری";
			this.Label14.Visible = false;
			this.GridEX3.AcceptsEscape = false;
			this.GridEX3.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX3.AlternatingColors = true;
			this.GridEX3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX3.AutoEdit = true;
			this.GridEX3.AutomaticSort = false;
			janusLayoutReference4.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX3_DesignTimeLayout_Reference_0.Instance"));
			janusLayoutReference5.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX3_DesignTimeLayout_Reference_1.Instance"));
			gridEXLayout3.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference4,
				janusLayoutReference5
			});
			gridEXLayout3.LayoutString = componentResourceManager.GetString("GridEX3_DesignTimeLayout.LayoutString");
			this.GridEX3.DesignTimeLayout = gridEXLayout3;
			this.GridEX3.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX3.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX3.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX3.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX3.GroupByBoxVisible = false;
			this.Highlighter1.SetHighlightOnFocus(this.GridEX3, true);
			global::System.Windows.Forms.Control arg_173F_0 = this.GridEX3;
			location = new global::System.Drawing.Point(7, 226);
			arg_173F_0.Location = location;
			this.GridEX3.Name = "GridEX3";
			global::System.Windows.Forms.Control arg_1770_0 = this.GridEX3;
			size = new global::System.Drawing.Size(655, 182);
			arg_1770_0.Size = size;
			this.GridEX3.TabIndex = 4;
			this.GridEX3.Visible = false;
			this.GridEX3.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.UiButton2.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiButton2.Image = global::FruitBox.My.Resources.Resources.check_print;
			global::Janus.Windows.EditControls.UIButton arg_17E4_0 = this.UiButton2;
			size = new global::System.Drawing.Size(32, 32);
			arg_17E4_0.ImageSize = size;
			global::System.Windows.Forms.Control arg_1804_0 = this.UiButton2;
			location = new global::System.Drawing.Point(827, 341);
			arg_1804_0.Location = location;
			this.UiButton2.Name = "UiButton2";
			this.UiButton2.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton2.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_184D_0 = this.UiButton2;
			size = new global::System.Drawing.Size(97, 41);
			arg_184D_0.Size = size;
			this.UiButton2.TabIndex = 25;
			this.UiButton2.Text = "چاپ چک";
			this.UiButton2.Visible = false;
			this.UiButton2.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.GridEX4.AcceptsEscape = false;
			this.GridEX4.AllowAddNew = global::Janus.Windows.GridEX.InheritableBoolean.True;
			this.GridEX4.AlternatingColors = true;
			this.GridEX4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GridEX4.AutoEdit = true;
			this.GridEX4.AutomaticSort = false;
			janusLayoutReference6.Instance = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("GridEX4_DesignTimeLayout_Reference_0.Instance"));
			gridEXLayout4.LayoutReferences.AddRange(new global::Janus.Windows.Common.Layouts.JanusLayoutReference[]
			{
				janusLayoutReference6
			});
			gridEXLayout4.LayoutString = componentResourceManager.GetString("GridEX4_DesignTimeLayout.LayoutString");
			this.GridEX4.DesignTimeLayout = gridEXLayout4;
			this.GridEX4.EnterKeyBehavior = global::Janus.Windows.GridEX.EnterKeyBehavior.None;
			this.GridEX4.FocusStyle = global::Janus.Windows.GridEX.FocusStyle.Solid;
			this.GridEX4.Font = new global::System.Drawing.Font("Tahoma", 12f);
			this.GridEX4.GridLineStyle = global::Janus.Windows.GridEX.GridLineStyle.Solid;
			this.GridEX4.GroupByBoxVisible = false;
			this.Highlighter1.SetHighlightOnFocus(this.GridEX4, true);
			global::System.Windows.Forms.Control arg_19AC_0 = this.GridEX4;
			location = new global::System.Drawing.Point(7, 414);
			arg_19AC_0.Location = location;
			this.GridEX4.Name = "GridEX4";
			global::System.Windows.Forms.Control arg_19DD_0 = this.GridEX4;
			size = new global::System.Drawing.Size(655, 203);
			arg_19DD_0.Size = size;
			this.GridEX4.TabIndex = 5;
			this.GridEX4.Visible = false;
			this.GridEX4.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.DateBox21.AcceptEnter = false;
			this.DateBox21.AllowEdit = true;
			this.DateBox21.BorderStyle = global::Janus.Windows.GridEX.BorderStyle.None;
			this.DateBox21.ButtonEnable = false;
			this.DateBox21.ButtonEnabled = false;
			this.DateBox21.FocusDatePart = 1;
			this.DateBox21.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1A94_0 = this.DateBox21;
			location = new global::System.Drawing.Point(827, 310);
			arg_1A94_0.Location = location;
			this.DateBox21.Mask = "0000/00/00";
			this.DateBox21.Name = "DateBox21";
			this.DateBox21.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_1ADD_0 = this.DateBox21;
			size = new global::System.Drawing.Size(100, 25);
			arg_1ADD_0.Size = size;
			this.DateBox21.TabIndex = 24;
			this.DateBox21.TabStop = false;
			this.DateBox21.Text = "1393/05/28";
			this.DateBox21.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.DateBox21.Visible = false;
			this.DateBox21.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.txt_babat_kart.AcceptEnter = true;
			this.txt_babat_kart.AllowEdit = true;
			this.txt_babat_kart.AllowNew = true;
			this.txt_babat_kart.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.txt_babat_kart.FocusColor = true;
			this.txt_babat_kart.Font = new global::System.Drawing.Font("Mitra", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1BB1_0 = this.txt_babat_kart;
			location = new global::System.Drawing.Point(-150, 54);
			arg_1BB1_0.Location = location;
			this.txt_babat_kart.Name = "txt_babat_kart";
			this.txt_babat_kart.Nullable = true;
			this.txt_babat_kart.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_babat_kart.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_1C0A_0 = this.txt_babat_kart;
			size = new global::System.Drawing.Size(176, 36);
			arg_1C0A_0.Size = size;
			this.txt_babat_kart.TabIndex = 3;
			this.txt_babat_kart.Visible = false;
			this.txt_babat_kart.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Label2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1C9F_0 = this.Label2;
			location = new global::System.Drawing.Point(681, 298);
			arg_1C9F_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_1CCA_0 = this.Label2;
			size = new global::System.Drawing.Size(78, 19);
			arg_1CCA_0.Size = size;
			this.Label2.TabIndex = 1;
			this.Label2.Text = "دسته چک";
			this.Label2.Visible = false;
			this.Label6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1D5D_0 = this.Label6;
			location = new global::System.Drawing.Point(27, 63);
			arg_1D5D_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_1D88_0 = this.Label6;
			size = new global::System.Drawing.Size(105, 19);
			arg_1D88_0.Size = size;
			this.Label6.TabIndex = 1;
			this.Label6.Text = "شماره پیگیری";
			this.Label6.Visible = false;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1E1E_0 = this.Label5;
			location = new global::System.Drawing.Point(380, 105);
			arg_1E1E_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_1E49_0 = this.Label5;
			size = new global::System.Drawing.Size(98, 19);
			arg_1E49_0.Size = size;
			this.Label5.TabIndex = 1;
			this.Label5.Text = "حساب بانکی";
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1ED2_0 = this.Label4;
			location = new global::System.Drawing.Point(665, 105);
			arg_1ED2_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1EFD_0 = this.Label4;
			size = new global::System.Drawing.Size(96, 19);
			arg_1EFD_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "کارت به کارت";
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_1F86_0 = this.Label7;
			location = new global::System.Drawing.Point(664, 17);
			arg_1F86_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_1FB1_0 = this.Label7;
			size = new global::System.Drawing.Size(61, 19);
			arg_1FB1_0.Size = size;
			this.Label7.TabIndex = 1;
			this.Label7.Text = "مشتری";
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_203A_0 = this.Label3;
			location = new global::System.Drawing.Point(664, 64);
			arg_203A_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_2065_0 = this.Label3;
			size = new global::System.Drawing.Size(64, 19);
			arg_2065_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "مبلغ نقد";
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_20F1_0 = this.Label1;
			location = new global::System.Drawing.Point(667, 485);
			arg_20F1_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_211C_0 = this.Label1;
			size = new global::System.Drawing.Size(92, 19);
			arg_211C_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "چک مشتری";
			this.Label1.Visible = false;
			this.UiButton1.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.UiButton1.Image = global::FruitBox.My.Resources.Resources.check_print;
			global::Janus.Windows.EditControls.UIButton arg_2194_0 = this.UiButton1;
			size = new global::System.Drawing.Size(32, 32);
			arg_2194_0.ImageSize = size;
			global::System.Windows.Forms.Control arg_21B4_0 = this.UiButton1;
			location = new global::System.Drawing.Point(827, 341);
			arg_21B4_0.Location = location;
			this.UiButton1.Name = "UiButton1";
			this.UiButton1.OfficeColorScheme = global::Janus.Windows.UI.OfficeColorScheme.Custom;
			this.UiButton1.OfficeCustomColor = global::System.Drawing.Color.SteelBlue;
			global::System.Windows.Forms.Control arg_21FD_0 = this.UiButton1;
			size = new global::System.Drawing.Size(97, 41);
			arg_21FD_0.Size = size;
			this.UiButton1.TabIndex = 25;
			this.UiButton1.Text = "چاپ چک";
			this.UiButton1.Visible = false;
			this.UiButton1.VisualStyle = global::Janus.Windows.UI.VisualStyle.Office2010;
			this.txt_tarikhGrid.AcceptEnter = false;
			this.txt_tarikhGrid.AllowEdit = true;
			this.txt_tarikhGrid.BorderStyle = global::Janus.Windows.GridEX.BorderStyle.None;
			this.txt_tarikhGrid.ButtonEnable = false;
			this.txt_tarikhGrid.ButtonEnabled = false;
			this.txt_tarikhGrid.FocusDatePart = 1;
			this.txt_tarikhGrid.Font = new global::System.Drawing.Font("Tahoma", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			global::System.Windows.Forms.Control arg_22C6_0 = this.txt_tarikhGrid;
			location = new global::System.Drawing.Point(827, 310);
			arg_22C6_0.Location = location;
			this.txt_tarikhGrid.Mask = "0000/00/00";
			this.txt_tarikhGrid.Name = "txt_tarikhGrid";
			this.txt_tarikhGrid.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_230F_0 = this.txt_tarikhGrid;
			size = new global::System.Drawing.Size(100, 25);
			arg_230F_0.Size = size;
			this.txt_tarikhGrid.TabIndex = 24;
			this.txt_tarikhGrid.TabStop = false;
			this.txt_tarikhGrid.Text = "1393/05/28";
			this.txt_tarikhGrid.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Far;
			this.txt_tarikhGrid.Visible = false;
			this.txt_tarikhGrid.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			this.Highlighter1.ContainerControl = this.UiGroupBox1;
			this.RibbonStatusBar1.Font = new global::System.Drawing.Font("Tahoma", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.RibbonStatusBar1.LeftPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.LabelCommand1,
				this.lbl_jamcheck,
				this.LabelCommand3,
				this.lbl_jamkol,
				this.LabelCommand5
			});
			global::System.Windows.Forms.Control arg_2404_0 = this.RibbonStatusBar1;
			location = new global::System.Drawing.Point(0, 161);
			arg_2404_0.Location = location;
			this.RibbonStatusBar1.Name = "RibbonStatusBar1";
			this.RibbonStatusBar1.RightPanelCommands.AddRange(new global::Janus.Windows.Ribbon.CommandBase[]
			{
				this.lbl_codem,
				this.LabelCommand7,
				this.lbl_name,
				this.LabelCommand9,
				this.LabelCommand10
			});
			this.RibbonStatusBar1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control arg_2491_0 = this.RibbonStatusBar1;
			size = new global::System.Drawing.Size(771, 23);
			arg_2491_0.Size = size;
			this.RibbonStatusBar1.SuperTipComponent.AutoPopDelay = 2000;
			this.RibbonStatusBar1.SuperTipComponent.ImageList = null;
			this.RibbonStatusBar1.TabIndex = 26;
			this.RibbonStatusBar1.Text = "RibbonStatusBar1";
			this.RibbonStatusBar1.Visible = false;
			this.RibbonStatusBar1.VisualStyle = global::Janus.Windows.Ribbon.VisualStyle.Office2010;
			this.LabelCommand1.Key = "LabelCommand1";
			this.LabelCommand1.Name = "LabelCommand1";
			this.lbl_jamcheck.Key = "LabelCommand2";
			this.lbl_jamcheck.Name = "lbl_jamcheck";
			this.LabelCommand3.Key = "LabelCommand3";
			this.LabelCommand3.Name = "LabelCommand3";
			this.LabelCommand3.Text = "جمع چک ها";
			this.lbl_jamkol.Key = "LabelCommand4";
			this.lbl_jamkol.Name = "lbl_jamkol";
			this.LabelCommand5.Key = "LabelCommand5";
			this.LabelCommand5.Name = "LabelCommand5";
			this.LabelCommand5.Text = "جمع کل پرداختی";
			this.lbl_codem.Key = "LabelCommand1";
			this.lbl_codem.Name = "lbl_codem";
			this.LabelCommand7.Key = "LabelCommand2";
			this.LabelCommand7.Name = "LabelCommand7";
			this.LabelCommand7.Text = "کد مشتری";
			this.lbl_name.Key = "LabelCommand3";
			this.lbl_name.Name = "lbl_name";
			this.LabelCommand9.Key = "LabelCommand4";
			this.LabelCommand9.Name = "LabelCommand9";
			this.LabelCommand9.Text = "نام مشتری";
			this.LabelCommand10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("LabelCommand10.Image");
			this.LabelCommand10.Key = "LabelCommand5";
			this.LabelCommand10.Name = "LabelCommand10";
			this.txt_mablagh.AcceptEnter = false;
			this.txt_mablagh.AllowEdit = true;
			this.txt_mablagh.AllowNew = true;
			this.txt_mablagh.FocusColor = false;
			global::System.Windows.Forms.Control arg_26FB_0 = this.txt_mablagh;
			location = new global::System.Drawing.Point(455, 186);
			arg_26FB_0.Location = location;
			this.txt_mablagh.Name = "txt_mablagh";
			this.txt_mablagh.Nullable = true;
			this.txt_mablagh.NullToolTipText = "این قسمت نمیتواند خالی باشد";
			this.txt_mablagh.ShortcutsEnabled = false;
			global::System.Windows.Forms.Control arg_2751_0 = this.txt_mablagh;
			size = new global::System.Drawing.Size(100, 21);
			arg_2751_0.Size = size;
			this.txt_mablagh.TabIndex = 2;
			this.txt_mablagh.TabStop = false;
			this.txt_mablagh.TextAlignment = global::Janus.Windows.GridEX.TextAlignment.Near;
			this.txt_mablagh.Value = value;
			this.txt_mablagh.VisualStyle = global::Janus.Windows.GridEX.VisualStyle.Office2010;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(771, 184);
			this.ClientSize = size;
			this.Controls.Add(this.RibbonStatusBar1);
			this.Controls.Add(this.UiGroupBox1);
			this.Controls.Add(this.txt_mablagh);
			this.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 178);
			this.KeyPreview = true;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Frm_Daryaft_AzMoshtari";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "دریافت از مشتری";
			((global::System.ComponentModel.ISupportInitialize)this.GridEX1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox1).EndInit();
			this.UiGroupBox1.ResumeLayout(false);
			this.UiGroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.UiGroupBox2).EndInit();
			this.UiGroupBox2.ResumeLayout(false);
			this.UiGroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.GridEX4).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000831 RID: 2097
		private global::System.ComponentModel.IContainer components;
	}
}
